force-app/main/default/objects/Opportunity_Activity__c/Opportunity_Activity__c.object-meta.xml
<CustomObject>
    <label>Opportunity Activity</label>
    <nameField>
        <displayFormat>OA-{yymmdd}-{00000}</displayFormat>
        <label>Opportunity Activity No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Activity__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <label>Canceled</label>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Activity__c/fields/WhatId__c.field-meta.xml
<CustomField>
    <fullName>WhatId__c</fullName>
    <description>Opportunity</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Activity</relationshipLabel>
    <relationshipName>BO_Activity</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/classes/Batch_OpportunityActivityTempDelete_Test.cls
/**
 * @description       : 
 * @author            : hj.lee@dkbmc.com
 * @group             : 
 * @last modified on  : 2021-05-06
 * @last modified by  : hj.lee@dkbmc.com
 * Modifications Log 
 * Ver   Date         Author             Modification
 * 1.0   2021-04-26   hj.lee@dkbmc.com   Initial Version
**/
@isTest
public class Batch_OpportunityActivityTempDelete_Test {
    @TestSetup
    private static void setData() {
        Opportunity oppty = new Opportunity(
            Name = 'Oppty',
            StageName = 'Z01',
            CloseDate = System.today()
        );
        insert oppty;

        Opportunity_Activity__c opptyAct1 = new Opportunity_Activity__c(
            WhatId__c = oppty.Id
            , Status__c = ''
            , CreatedDate = System.today().addDays(-2)
        );
        insert opptyAct1;


        Opportunity_Activity__c opptyAct2 = new Opportunity_Activity__c(
            WhatId__c = oppty.Id
            , Status__c = ''
        );
        insert opptyAct2;

    }

    @isTest
    public static void batch_DeleteDataTest(){

        Test.startTest();
        Batch_OpportunityActivityTempDelete batch = new Batch_OpportunityActivityTempDelete();
        DataBase.executeBatch(batch, 2);
        Test.stopTest();
        
        List<SObject> scopeList = DataBase.query(batch.query);

        System.assertEquals(scopeList.size(), 1);
        System.debug('scopeList::::' + scopeList);
    }

    @isTest
    public static void schedule_test() {
        Test.startTest();
        System.schedule('Batch_OpportunityActivityTempDelete', '0 0 3 * * ? *', new Batch_OpportunityActivityTempDelete());
        Test.stopTest();
    }

}