force-app/main/default/objects/Opportunity_Activity__c/Opportunity_Activity__c.object-meta.xml
<CustomObject>
    <label>Opportunity Activity</label>
    <nameField>
        <displayFormat>OA-{yymmdd}-{00000}</displayFormat>
        <label>Opportunity Activity No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Activity__c/fields/ExtID__c.field-meta.xml
<CustomField>
    <fullName>ExtID__c</fullName>
    <externalId>true</externalId>
    <label>ExtID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Activity__c/fields/TransactionName__c.field-meta.xml
<CustomField>
    <fullName>TransactionName__c</fullName>
    <label>Opportunity Activity Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>XP11</fullName>
                <label>Register BO</label>
            </value>
            <value>
                <fullName>ZP21</fullName>
                <label>Review BO</label>
            </value>
            <value>
                <fullName>ZP32</fullName>
                <label>Request Resources</label>
            </value>
            <value>
                <fullName>XP31</fullName>
                <label>Receive RFP</label>
            </value>
            <value>
                <fullName>ZP31</fullName>
                <label>Request Strategy Committee</label>
            </value>
            <value>
                <fullName>XP32</fullName>
                <label>Strategy Committee Cost Plan Completion</label>
            </value>
            <value>
                <fullName>ZP62</fullName>
                <label>Request Committee Approval</label>
            </value>
            <value>
                <fullName>ZPZ3</fullName>
                <label>Agency Contract Exception</label>
            </value>
            <value>
                <fullName>ZP61</fullName>
                <label>Submit Proposal</label>
            </value>
            <value>
                <fullName>XP41</fullName>
                <label>Presentation</label>
            </value>
            <value>
                <fullName>XP42</fullName>
                <label>Preferred Bidder</label>
            </value>
            <value>
                <fullName>XP43</fullName>
                <label>Customer Approval</label>
            </value>
            <value>
                <fullName>XP44</fullName>
                <label>Negotiation</label>
            </value>
            <value>
                <fullName>XP51</fullName>
                <label>Contract P&amp;L</label>
            </value>
            <value>
                <fullName>XP52</fullName>
                <label>Legal Review</label>
            </value>
            <value>
                <fullName>ZP82</fullName>
                <label>Contract Approval</label>
            </value>
            <value>
                <fullName>XP57</fullName>
                <label>Closing</label>
            </value>
            <value>
                <fullName>ZPZ2</fullName>
                <label>Drop Opportunity</label>
            </value>
            <value>
                <fullName>XPX1</fullName>
                <label>Abort Opportunity</label>
            </value>
            <value>
                <fullName>ZAC1</fullName>
                <label>Hold Opportunity</label>
            </value>
            <value>
                <fullName>ZPZ1</fullName>
                <label>Lost Opportunity</label>
            </value>
            <value>
                <fullName>ZAC4</fullName>
                <label>Unhold Opportunity</label>
            </value>
            <value>
                <fullName>ZPG1</fullName>
                <label>Change Approval Request</label>
            </value>
            <value>
                <fullName>2.2.1.</fullName>
                <label>Credit Assessment</label>
            </value>
            <value>
                <fullName>2.2.2.</fullName>
                <label>Request AP(APS)</label>
            </value>
            <value>
                <fullName>2.3.2.</fullName>
                <label>Bidding LBS</label>
            </value>
            <value>
                <fullName>2.3.3.</fullName>
                <label>Test Shipment</label>
            </value>
            <value>
                <fullName>2.4.5.</fullName>
                <label>Final LBS</label>
            </value>
            <value>
                <fullName>2.5.1.</fullName>
                <label>Receive Contract</label>
            </value>
            <value>
                <fullName>2.5.3.</fullName>
                <label>Rate Change LBS</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Activity__c/fields/WhatId__c.field-meta.xml
<CustomField>
    <fullName>WhatId__c</fullName>
    <description>Opportunity</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Activity</relationshipLabel>
    <relationshipName>BO_Activity</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/classes/MasterLostTypeDataControllerTest.cls
/**
* @description       : This class is a Test coverge for master lost type data table lwc masterLostTypeDataTable
* @author            : rakshit.s@samsung.com
* @group             : 
* @last modified on  : 03-23-2023
* @last modified by  : rakshit.s@samsung.com
* Modifications Log 
* Ver   Date         Author                  Modification
* 1.0   03-23-2023  rakshit.s@samsung.com   Initial Version
**/
@istest
private class MasterLostTypeDataControllerTest {
    static User user;
    @testSetup 
    static void setup(){
        Profile pf = [SELECT Id,name FROM Profile where name='System Administrator'];
        user = new User(Alias = 'Test', Email='Testgroup@Test.com', 
                        EmailEncodingKey='UTF-8', LastName='Test', FirstName='Test', LanguageLocaleKey='en_US', 
                        LocaleSidKey='en_US', ProfileId = pf.Id, TimeZoneSidKey='Asia/Seoul',
                        EvKostl__c='T100-12345',
                        UserName='user0001@samsung.com');
        Insert user;
        Opportunity op = new opportunity();
        
        op.CloseDate = Date.today().addDays(6);
        op.Name = 'sample';
        op.StageName  = 'Z02';
        op.owner = user;
        // op.owner.EvKostl__c = 'T100-12345';
        insert op;
        //system.debug('opportunity inserted-->' + op.owner.EvKostl__c);
        Opportunity op1 = new opportunity();
        
          Opportunity_Activity__c oppAct = new Opportunity_Activity__c(
            WhatId__c = op.id,
            ExtID__c = op.id+'ZPZ1',
            TransactionName__c = 'ZPZ1'
        );
        
        insert oppAct;
    }
    
    @isTest static void testMasterLostTypeData() {
        
        Test.startTest();
        Opportunity opp = [select id from Opportunity limit 1];
         Opportunity_Activity__c oAc = [Select id from Opportunity_Activity__c limit 1];
        MasterLostTypeDataController.getMasterLostType('en-US', true, opp.id,oAc.id);
        MasterLostTypeDataController.getMasterLostType('en-US', false, opp.id,oAc.id);
        
        MasterLostTypeDataController.getMasterLostType('ko', true, opp.id,oAc.id);
        MasterLostTypeDataController.getMasterLostType('ko', false, opp.id,oAc.id);
        
         MasterLostTypeDataController.getMasterLostType('other', true, opp.id,oAc.id);
        
        MasterLostTypeDataController.isLostOrDrop(oAc.id,opp.id);
        Test.stopTest();
        
    }
    
}