force-app/main/default/objects/FunctionSwitch__c/FunctionSwitch__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>특정 기능을 제어 하는 Switch</description>
    <label>FunctionSwitch</label>
</CustomObject>

force-app/main/default/objects/FunctionSwitch__c/fields/OpportunityActivityPanel__c.field-meta.xml
<CustomField>
    <fullName>OpportunityActivityPanel__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Opportunity 상황판 Click 동작 여부, unchecked : 상황판 클릭 불가</description>
    <inlineHelpText>Opportunity 상황판 Click 동작 여부, unchecked : 상황판 클릭 불가</inlineHelpText>
    <label>OpportunityActivityPanel</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MasterActivity__c/MasterActivity__c.object-meta.xml
<CustomObject>
    <label>Master Activity</label>
    <nameField>
        <displayFormat>MA-{000000}</displayFormat>
        <label>Seq. No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Master Activities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/MasterActivity__c/fields/ObjectApiName__c.field-meta.xml
<CustomField>
    <fullName>ObjectApiName__c</fullName>
    <label>Object</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lead</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MasterActivity__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Position</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>1</label>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MasterActivity__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cold</fullName>
            </value>
            <value>
                <fullName>Warm</fullName>
            </value>
            <value>
                <fullName>Hot</fullName>
            </value>
            <value>
                <fullName>Z01</fullName>
                <label>Idendified</label>
            </value>
            <value>
                <fullName>Z02</fullName>
                <label>Validated</label>
            </value>
            <value>
                <fullName>Z03</fullName>
                <label>Qualified</label>
            </value>
            <value>
                <fullName>Z04</fullName>
                <label>Solutioned</label>
            </value>
            <value>
                <fullName>Z05</fullName>
                <label>Won</label>
            </value>
            <value>
                <fullName>Z06</fullName>
                <label>Failed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MasterActivity__c/fields/TransactionName__c.field-meta.xml
<CustomField>
    <fullName>TransactionName__c</fullName>
    <label>Transaction Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>XP11</fullName>
                <label>Register Opportunity</label>
            </value>
            <value>
                <fullName>ZP21</fullName>
                <label>Review Opportunity</label>
            </value>
            <value>
                <fullName>ZP32</fullName>
                <label>Request Resources</label>
            </value>
            <value>
                <fullName>XP31</fullName>
                <label>Receive RFP</label>
            </value>
            <value>
                <fullName>ZP31</fullName>
                <label>Request Strategy Committee</label>
            </value>
            <value>
                <fullName>XP32</fullName>
                <label>Strategy Committee Cost Plan Completion</label>
            </value>
            <value>
                <fullName>ZP62</fullName>
                <label>Request Committee Approval</label>
            </value>
            <value>
                <fullName>ZPZ3</fullName>
                <label>Agency Contract Exception</label>
            </value>
            <value>
                <fullName>ZP61</fullName>
                <label>Submit Proposal</label>
            </value>
            <value>
                <fullName>XP41</fullName>
                <label>Presentation</label>
            </value>
            <value>
                <fullName>XP42</fullName>
                <label>Preferred Bidder</label>
            </value>
            <value>
                <fullName>XP43</fullName>
                <label>Customer Approval</label>
            </value>
            <value>
                <fullName>XP44</fullName>
                <label>Negotiation</label>
            </value>
            <value>
                <fullName>XP51</fullName>
                <label>Contract P&amp;L</label>
            </value>
            <value>
                <fullName>XP52</fullName>
                <label>Legal Review</label>
            </value>
            <value>
                <fullName>ZP82</fullName>
                <label>Contract Approval</label>
            </value>
            <value>
                <fullName>XP57</fullName>
                <label>Closing</label>
            </value>
            <value>
                <fullName>ZPZ2</fullName>
                <label>Drop Opportunity</label>
            </value>
            <value>
                <fullName>XPX1</fullName>
                <label>Abort Opportunity</label>
            </value>
            <value>
                <fullName>ZAC1</fullName>
                <label>Hold Opportunity</label>
            </value>
            <value>
                <fullName>ZPZ1</fullName>
                <label>Lost Opportunity</label>
            </value>
            <value>
                <fullName>ZAC4</fullName>
                <label>Unhold Opportunity</label>
            </value>
            <value>
                <fullName>ZPG1</fullName>
                <label>Change Approval Request</label>
            </value>
            <value>
                <fullName>2.2.1.</fullName>
                <label>Credit Assessment</label>
            </value>
            <value>
                <fullName>2.2.2.</fullName>
                <label>Request AP(APS)</label>
            </value>
            <value>
                <fullName>2.3.2.</fullName>
                <label>Bidding LBS</label>
            </value>
            <value>
                <fullName>2.3.3.</fullName>
                <label>Test Shipment</label>
            </value>
            <value>
                <fullName>2.4.5.</fullName>
                <label>Final LBS</label>
            </value>
            <value>
                <fullName>2.5.1.</fullName>
                <label>Receive Contract</label>
            </value>
            <value>
                <fullName>2.5.3.</fullName>
                <label>Rate Change LBS</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MasterActivity__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Default</fullName>
                <default>true</default>
                <label>Default</label>
            </value>
            <value>
                <fullName>Logistics</fullName>
            </value>
            <value>
                <fullName>HQ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Activity__c/Opportunity_Activity__c.object-meta.xml
<CustomObject>
    <label>Opportunity Activity</label>
    <nameField>
        <displayFormat>OA-{yymmdd}-{00000}</displayFormat>
        <label>Opportunity Activity No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Activity__c/fields/WhatId__c.field-meta.xml
<CustomField>
    <fullName>WhatId__c</fullName>
    <description>Opportunity</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Activity</relationshipLabel>
    <relationshipName>BO_Activity</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/SCPSimulation__c/SCPSimulation__c.object-meta.xml
<CustomObject>
    <label>SCP Simulation information</label>
    <nameField>
        <label>SCP Simulation information Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SCP Simulation information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SCPSimulation__c/fields/BOCode__c.field-meta.xml
<CustomField>
    <fullName>BOCode__c</fullName>
    <label>BO Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SCPSimulation__c/fields/companyCode__c.field-meta.xml
<CustomField>
    <fullName>companyCode__c</fullName>
    <label>Company Code</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SCPSimulation__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>SCP Simulation information</relationshipLabel>
    <relationshipName>SCP_Simulation_information</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SCPSimulation__c/fields/quotStat__c.field-meta.xml
<CustomField>
    <fullName>quotStat__c</fullName>
    <label>Simulation Status</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OpportunityActivityPanelController.cls
/**
 * @description       : Opportunity 상황판 조회
 * @author            : wonjune.oh@partner.samsung.com
 * @group             : 
 * @last modified on  : 2024-03-20
 * @last modified by  : vikrant.ks@samusng.com  
 * Modifications Log 
 * Ver   Date         Author                           Modification
 * 1.0   2020-10-29   wonjune.oh@partner.samsung.com   Initial Version
 * 1.1   2023-10-27   gitesh.s@samsung.com             SCP Quotation Activity color change (MYSALES-339)
 * 1.3   2024-01-30   atul.k1@samusng.com              Task - (IT) Add TXP link Button in BO Activity (MYSALES-421)
 * 1.4   2024-03-20   vikrant.ks@samusng.com           Task - (IT) Add BO Priority Check List Button in BO Activity (MYSALES-468)
**/
public without sharing class OpportunityActivityPanelController{
    
    public static Boolean canClickSwitch = FunctionSwitch__c.getInstance(UserInfo.getUserId()).OpportunityActivityPanel__c; // 상황판 클릭 가능 여부
    
    @AuraEnabled
    public static Map<String, Object> initComponent(String recordId, Boolean isDelTempAct){
        Map<String,List<List<ActivityItem>>> panelMap = new Map<String,List<List<ActivityItem>>>();
        Opportunity oppty = new Opportunity();
        String recordTypeDevName = '';
        Boolean hasEditAccess = [SELECT     RecordId, HasEditAccess  
                                 FROM       UserRecordAccess 
                                 WHERE      UserId = :UserInfo.getUserId() 
                                            AND RecordId = :recordId].HasEditAccess;
        SCPSimulation__c scpList = new SCPSimulation__c();
        Boolean isSubsidiary = false; //V 1.3 MYSALES-421
	    Boolean isSandbox = Utils.getIsSandbox(); // V 1.4 MYSALES-468

        Map<String, Object> resultMap = new Map<String, Object>{
            'panelList'     => panelMap,
            'oppty'         => oppty,
            'recordTypeDevName'    => recordTypeDevName,
            'hasEditAccess' => hasEditAccess,
            'canClickSwitch' => canClickSwitch,
            'isSubsidiary'          => isSubsidiary, // V 1.3 MYSALES-421
	        'isSandbox'          => isSandbox, // V 1.4 MYSALES-468
            // v1.1 - Gitesh Saini (MYSALES-339)
            'scpList'       => scpList
        };

        try{
            // 임시로 저장된 Status가 빈 값인 Activity 삭제
            System.debug('OpportunityActivityPanelController, initComponent recordId ' + recordId);
            System.debug('OpportunityActivityPanelController, initComponent isDelTempAct ' + isDelTempAct);
            if(isDelTempAct) OpportunityActivityHelper.deleteTempOpportunityActivity(recordId);

            // Get Opportunity Info
      //      String opptySOQL = Utils.getQueryAddSelect('Opportunity', 'RecordType.DeveloperName, Account.AccountNumber, cLeadID__r.CreatedDate', ' WHERE  Id = \'' + recordId + '\'', false);
       // V 1.4 Added Collaboration field in the query.
            String opptySOQL = Utils.getQueryAddSelect('Opportunity', 'RecordType.DeveloperName, Account.AccountNumber, cLeadID__r.CreatedDate', ' WHERE  Id = \'' + recordId + '\'', false);
            List<Opportunity> opptyList = System.Database.query(opptySOQL);
            System.debug('### opptyList.size() ' + opptyList.size());
            
            if(opptyList.size() > 0) {
                oppty = opptyList[0];
                recordTypeDevName = oppty.RecordType.DeveloperName;

                List<MasterActivity__c> masterActList = Utils.queryObjectWithoutRichText('MasterActivity__c'
                                                        , 'WHERE ObjectApiName__c	 = \'Opportunity\' AND IsActive__c = true AND Type__c = \'' + recordTypeDevName + '\''
                                                        + ' ORDER BY Stage__c , Order__c'
                                                    );

                panelMap = arrangement(masterActList,recordId);
                isSubsidiary = Utils.isSubsidiary(oppty.CompanyCode__c); // V 1.3 MYSALES-421
            }

            // v1.1 - Gitesh Saini (MYSALES-339)
            List<SCPSimulation__c> scp = [SELECT Id, BOCode__c, quotStat__c, Opportunity__c FROM SCPSimulation__c WHERE Opportunity__c =: recordId ORDER BY LastModifiedDate DESC];
            if(scp.size() > 0){
                scpList = scp[0];
            }

            resultMap = new Map<String, Object>{
                'panelList'     => panelMap,
                'oppty'         => oppty,
                'recordTypeDevName'    => recordTypeDevName,
                'hasEditAccess' => hasEditAccess,
                'canClickSwitch' => canClickSwitch,
                'isSubsidiary'   => isSubsidiary, //V 1.3 MYSALES-421
                'scpList'       => scpList,
                'isSandbox'          => isSandbox // V 1.4 MYSALES-468
            };
            // v1.1 - Gitesh Saini
            
        } catch (Exception e) {
            // "Convert" the exception into an AuraHandledException
            System.debug(System.LoggingLevel.ERROR, e.getLineNumber());
            System.debug(System.LoggingLevel.ERROR, e.getTypeName());
            System.debug(System.LoggingLevel.ERROR, e.getMessage());
            throw new AuraHandledException(e.getMessage());
        }
        return resultMap;
    }

    @AuraEnabled
    public static Map<String,List<List<ActivityItem>>> arrangement(List<MasterActivity__c> masterActList,String recordId){
        List<MasterActivity__c> position1 = new List<MasterActivity__c>();
        List<MasterActivity__c> position2 = new List<MasterActivity__c>();
        Map<String,List<List<ActivityItem>>> result = new Map<String,List<List<ActivityItem>>>();
        
        for(MasterActivity__c masterAct : masterActList){
            if(masterAct.Position__c == '1'){
                position1.add(masterAct);
            }else if(masterAct.Position__c == '2'){
                position2.add(masterAct);
            }
        }
    
        result.put('1',sortList(extract(position1,recordId)));
        result.put('2',sortList(extract(position2,recordId)));
        
        return result;
    }

    @AuraEnabled
    public static List<ActivityItem> extract(List<MasterActivity__c> masterActList, String recordId){
        List<ActivityItem> actItemList = new List<ActivityItem>();
        List<Opportunity_Activity__c> boActList = Utils.queryObjectWithoutRichText('Opportunity_Activity__c'
                                                    , 'WHERE WhatId__c = ' + '\'' + recordId + '\'' 
                                                   + ' ORDER BY TransactionName__c, CreatedDate DESC'
                                                );

        String opptySOQL = Utils.getQueryAddSelect('Opportunity', 'RecordType.DeveloperName', ' WHERE  Id = \'' + recordId + '\'', false);
        List<Opportunity> opptyList = System.Database.query(opptySOQL);

        if(opptyList.size() > 0) {
            Opportunity oppty = opptyList[0];

            Boolean isHQRecordType        = oppty.RecordTypeId == OpportunityActivityHelper.RT_OPPTY_HQ.Id;
            Boolean isLogisticsRecordType = oppty.RecordTypeId == OpportunityActivityHelper.RT_OPPTY_LOGISTICS.Id;
            
            Map<String, String> boActStatusMap = new Map<String, String>();

            String ACT_CODE_DROP_OPPORTUNITY = OpportunityActivityHelper.ACT_CODE_DROP_OPPORTUNITY;
            String ACT_CODE_LOST_OPPORTUNITY = OpportunityActivityHelper.ACT_CODE_LOST_OPPORTUNITY;
            for(MasterActivity__c masterAct : masterActList){
                ActivityItem actItem = new ActivityItem(null, null, null);
                actItem.opptyId = recordId;
                actItem.MasterAct = masterAct;

                for(Opportunity_Activity__c boAct : boActList){
                    boActStatusMap.put(boAct.TransactionName__c, boAct.Status__c);

                    if(actItem.MasterAct.TransactionName__c ==  boAct.TransactionName__c
                        // 중도종결 (Drop/Lost) : Master Activity Code : Drop(ZPZ2) 이며 Oppty Activity 생성시 Lost Type (Lost 'ZPZ1', Drop 'ZPZ2') 에 따라 분기 생성됨
                        || (actItem.MasterAct.TransactionName__c == ACT_CODE_DROP_OPPORTUNITY 
                            && (boAct.TransactionName__c == ACT_CODE_LOST_OPPORTUNITY || boAct.TransactionName__c == ACT_CODE_DROP_OPPORTUNITY)) ) {
                    actItem.boAct = boAct;
                    
                    // Activity Box 노출 Date Setting
                        switch on boAct.Status__c {
                            when 'Not Started' {
                                actItem.DateItem = boAct.DueDate__c;
                            }
                            when 'In Progress' {
                                actItem.DateItem = boAct.StartDate__c;
                            }
                            when 'Completed' {
                                actItem.DateItem = boAct.EndDate__c;
                            }
                            //2022-08-08 수주품의 액티비티 상태 표시 상세화
                            when 'Rejected' {
                                actItem.DateItem = boAct.StartDate__c;
                            }
                            when 'Cancelled' {
                                actItem.DateItem = boAct.StartDate__c;
                            }
                        }
                    break;
                    }
                }
                
                /**
                 * [HQ Record Type] Activity 접근 가능 여부 처리
                 */
                if(isHQRecordType) {
                    actItem.isAccessible = OpportunityActivityHelper.checkAccessHQActivity(oppty, actItem);
                }

                /**
                 * [Logistics Record Type] Activity 접근 가능 여부 처리
                 */
                if(isLogisticsRecordType) {
                    //actItem.isAccessible = OpportunityActivityHelper.checkAccessLogisticsActivity(oppty, actItem);
                    
                    actItem.isAccessible = OpportunityActivityHelper.checkAccessLogisticsActivityV2(oppty, actItem);
                          
                }
                
                actItemList.add(actItem);
            }
        }
        return actItemList;
    }

    public static List<List<ActivityItem>> sortList(List<ActivityItem> actlist){
        String temp='1';
        String order = '';
        List<Map<String, String>> valueCnt = Utils.getPicklistOptionType('Opportunity','StageName');
        List<List<ActivityItem>> sortResult = new List<List<ActivityItem>>();
        List<ActivityItem> sortTemp = new List<ActivityItem>();

        Integer lostStageCount = 3;	// Lost Stage 개수
        Integer cnt = valueCnt.size() - lostStageCount;
        Integer itemIndex = 1;
        for(ActivityItem act : actlist ){ 
            order = act.MasterAct.Stage__c.substring(2);
            act.Index = itemIndex++;

            if(temp != '1' && String.valueOf(Integer.valueOf(temp)+1) !=order && temp !=order){
                List<ActivityItem> fakeTemp = new List<ActivityItem>();
                sortResult.add(fakeTemp);
            }
            if(temp == order){
                sortTemp.add(act);
                
            }else{
                sortResult.add(sortTemp);
                sortTemp = new List<ActivityItem>();
                System.debug(' temp' + temp);
                System.debug(' order' + order);
                temp = order;
                sortTemp.add(act);
            }
        }
        
        if(actlist.size() !=0 ){
            sortResult.add(sortTemp);
            if(Integer.valueOf(order) < cnt){
                List<ActivityItem> fakeTemp = new List<ActivityItem>();
                for(Integer i=Integer.valueOf(temp); i<cnt; i++){
                    sortResult.add(fakeTemp);
                }
            }
        }

        for(List<ActivityItem> act : sortResult ){
            for(ActivityItem act2 : act ){
                System.debug('sortResult : ' + act2.MasterAct.TransactionName__c);
            }
          
        }


        return sortResult;
    }

    public class ActivityItem {
        @AuraEnabled 
        public String opptyId {get; set;}
        @AuraEnabled 
        public MasterActivity__c MasterAct {get; set;}
        @AuraEnabled 
        public Opportunity_Activity__c BoAct {get; set;}
        @AuraEnabled 
        public Date DateItem {get; set;}
        @AuraEnabled 
        public Integer Index {get; set;}
        @AuraEnabled 
        public Boolean isAccessible {set; get;}
         
        public ActivityItem(MasterActivity__c MasterAct, Opportunity_Activity__c BoAct, Date DateItem) {
            this.MasterAct = MasterAct;
            this.BoAct = BoAct;
            this.DateItem = DateItem;
            this.isAccessible = true;
        }
    }
}