force-app/main/default/objects/Biz_Review__c/Biz_Review__c.object-meta.xml
<CustomObject>
    <label>Strategy Committee</label>
    <nameField>
        <displayFormat>SC-{000000}</displayFormat>
        <label>Seq. No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Strategy Committee</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Biz_Review__c/fields/Decision__c.field-meta.xml
<CustomField>
    <fullName>Decision__c</fullName>
    <label>Decision</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Participation</fullName>
            </value>
            <value>
                <fullName>Nonparticipation</fullName>
            </value>
            <value>
                <fullName>Deferral</fullName>
            </value>
            <value>
                <fullName>Conditional Participation</fullName>
                <isActive>false</isActive>
                <label>Conditional Participation</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Biz_Review__c/fields/IsAnswerCount__c.field-meta.xml
<CustomField>
    <fullName>IsAnswerCount__c</fullName>
    <label>Total Number of Answer</label>
    <summaryFilterItems>
        <field>Question__c.IsAnswer__c</field>
        <operation>greaterThan</operation>
        <value>0</value>
    </summaryFilterItems>
    <summaryForeignKey>Question__c.BOBizReview__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Biz_Review__c/fields/IsPMAnswerCount__c.field-meta.xml
<CustomField>
    <fullName>IsPMAnswerCount__c</fullName>
    <label>Total Number of Answered by PM</label>
    <summaryFilterItems>
        <field>Question__c.IsPMAnswer__c</field>
        <operation>greaterThan</operation>
        <value>0</value>
    </summaryFilterItems>
    <summaryForeignKey>Question__c.BOBizReview__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Biz_Review__c/fields/TotalQuestionCount__c.field-meta.xml
<CustomField>
    <fullName>TotalQuestionCount__c</fullName>
    <label>Total Number of Questions</label>
    <summaryForeignKey>Question__c.BOBizReview__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/KnoxApprovalActivityVRBController.cls
/**
 * @description       : 
 * @author            : dongyoung.kim@dkbmc.com
 * @group             : 
 * @last modified on  : 2021-03-03
 * @last modified by  : Junghwa.Kim@dkbmc.com
 * Modifications Log 
 * Ver   Date         Author                    Modification
 * 1.0   2021-02-03   dongyoung.kim@dkbmc.com   Initial Version
**/
public class KnoxApprovalActivityVRBController {
    @AuraEnabled
    public static List<Biz_Review__c> getStrategyInfo(Id recordId){
        List<Biz_Review__c> StrategyInfo = [SELECT id, IsAnswerCount__c, IsPMAnswerCount__c, TotalQuestionCount__c, Decision__c, CreatedById
                                            FROM Biz_Review__c 
                                            WHERE id =: recordId];
        return StrategyInfo;
    }
}