force-app/main/default/objects/Sales_Lead__c/Sales_Lead__c.object-meta.xml
<CustomObject>
    <label>Sales Lead</label>
    <nameField>
        <label>Sales Lead Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Leads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Lead__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Contract Account</description>
    <inlineHelpText>Required Information only for HQ users when creating IT Sales Lead / Required information when converting</inlineHelpText>
    <label>Account(*)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Leads</relationshipLabel>
    <relationshipName>Sales_Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Lead__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>예상금액</description>
    <inlineHelpText>Required Information only for HQ users when creating IT Sales Lead / Required information when converting</inlineHelpText>
    <label>Amount(*)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sales_Lead__c/fields/CloseDate__c.field-meta.xml
<CustomField>
    <fullName>CloseDate__c</fullName>
    <description>예상수주일자</description>
    <label>Close Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Sales_Lead__c/fields/LeadStage__c.field-meta.xml
<CustomField>
    <fullName>LeadStage__c</fullName>
    <description>Lead Stage</description>
    <label>Lead Stage</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cold</fullName>
                <color>#33CCFF</color>
                <label>Cold</label>
            </value>
            <value>
                <fullName>Warm</fullName>
                <color>#FF9900</color>
                <label>Warm</label>
            </value>
            <value>
                <fullName>Hot</fullName>
                <color>#FF0000</color>
                <label>Hot</label>
            </value>
            <value>
                <fullName>Converted</fullName>
                <color>#BBBBBB</color>
                <label>Converted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Lead__c/fields/RevenueEndDate__c.field-meta.xml
<CustomField>
    <fullName>RevenueEndDate__c</fullName>
    <description>(계약) 매출 종료일</description>
    <label>Contract End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Sales_Lead__c/fields/RevenueStartDate__c.field-meta.xml
<CustomField>
    <fullName>RevenueStartDate__c</fullName>
    <description>(계약) 매출 시작일</description>
    <label>Contract Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/CustomLookupControllerNew.cls
/**
 * @author            : divyam.gupta@samsung.com
 * @group             : 
 * @description       : Apex class for VF Page LookupPopup.vfp
 * @last modified on  : 2024-05-10
 * @last modified by  : divyam.gupta@samsung.com
 * Modifications Log 
 * Ver   Date         Author                    Modification
 * 1.0   2024-05-10   divyam.gupta@samsung.com	Initial Version
**/
public with sharing class CustomLookupControllerNew {
    public String query {get; set;}
    public String objname {get; set;}
    public String objnames {get; set;}
    public String objnamevf {get; set;}

    public List<Account> accounts {get; set;} 
    public List<Opportunity> opps{get; set;}
    public List<Sales_Lead__c> salesleads {get; set;}
    public Boolean doneLookup {get; set;}   
     public Boolean doneLookupopp {get; set;}   
    public Boolean doneLookuplead {get; set;}   
    public Boolean errorMessagequery {get; set;}   
    public String listSize {get; set;}   

    // constructor
    public CustomLookupControllerNew() {
    	doneLookup=false;
        query = Apexpages.currentPage().getParameters().get('name');
        objnamevf = Apexpages.currentPage().getParameters().get('objname');
        if(objnamevf == 'Account'){
            objname = System.Label.Account_weeklyReport;
            objnames = System.Label.Accounts_weeklyReport;
        }
        if(objnamevf == 'Opportunity'){
             objname = System.Label.Opportunity_weeklyReport;
            objnames = System.Label.Opportunities_weeklyReport;
        }
         if(objnamevf == 'Sales Lead'){
             objname = System.Label.SalesLead_weeklyReport;
            objnames = System.Label.SalesLeads_weeklyReport;
        }
        //objname = Apexpages.currentPage().getParameters().get('objname');

        runQuery();
    }
    // executes the search
    public PageReference runQuery() {
        if(query != '' && query != null){
            String keyword = '%'+query +'%';
            if(objnamevf !='' && objnamevf == 'Account'){
            List<Account> searchResults=
               /* [FIND :query IN ALL FIELDS RETURNING 
                    Account (id,Name,AccountNumber,Owner.Alias, AccountSource, Active__c, Phone, Type, mLoevm__c)]; */
                [select id,Name,AccountNumber,Owner.Alias, AccountSource, Active__c, Phone, Type, mLoevm__c from Account where Name LIKE: keyword OR AccountNumber LIKE: keyword OR Owner.Alias LIKE: keyword LIMIT 1000];
            accounts=searchResults;
                integer sizelist = searchResults.size();
                if(searchResults.size() >= 1000){
                    system.debug('Coming of if loo more than 1000 records'+searchResults.size());
                    this.listSize = String.valueof(searchResults.size()) + '+';
                   this.doneLookup=true;

                }
                else {
            this.doneLookup=true;
            this.listSize = String.valueof(searchResults.size());
            this.errorMessagequery = false;

                }
        }
            if(objnamevf !='' && objnamevf == 'Opportunity'){
               /*List<List<Opportunity>> searchResults=
                [FIND :query IN ALL FIELDS RETURNING 
                    Opportunity (id,Name, OpportunityCode__c, AccountId, Account.Name, StageName, CloseDate, Owner.Alias)]; */
                List<Opportunity> searchResults =
                [select id,Name, OpportunityCode__c, AccountId, Account.Name, StageName, CloseDate, Owner.Alias from Opportunity where Name LIKE: keyword OR Account.Name LIKE: keyword OR OpportunityCode__c LIKE: keyword OR Owner.Alias LIKE: keyword LIMIT 1000];
           // opps=searchResults[0];
             opps=searchResults;
             integer sizelist = searchResults.size();
                if(searchResults.size() >= 1000){
                this.doneLookupopp=true; 
                this.listSize = String.valueof(searchResults.size()) + '+';


                }
                else {
            this.doneLookup=false;
            this.doneLookupopp=true; 
             this.listSize = String.valueof(searchResults.size());
                }
            }
            if(objnamevf !='' && objnamevf == 'Sales Lead'){
               List<Sales_Lead__c> searchResults=
               /* [FIND :query IN ALL FIELDS RETURNING 
                    Sales_Lead__c (id,Name, AccountId__c,AccountId__r.name,LeadStage__c, Amount__c, CloseDate__c, RevenueStartDate__c, RevenueEndDate__c)];*/
                   [select id,Name, AccountId__c,AccountId__r.name,LeadStage__c, Amount__c, CloseDate__c, RevenueStartDate__c, RevenueEndDate__c from Sales_Lead__c where Name LIKE: keyword OR AccountId__r.name LIKE: keyword LIMIT 1000];
                 salesleads=searchResults;
                integer sizelist = searchResults.size();

                   if(searchResults.size() >= 1000){
                    system.debug('Coming of if loo more than 1000 records'+searchResults.size());
                    this.doneLookuplead=true;
                    this.listSize = String.valueof(searchResults.size()) + '+';


                }
                else {
            this.doneLookuplead=true;
                 this.listSize = String.valueof(searchResults.size());    

                }
            }
        }
        return null;
    }
}