force-app/main/default/objects/Sales_Lead__c/Sales_Lead__c.object-meta.xml
<CustomObject>
    <label>Sales Lead</label>
    <nameField>
        <label>Sales Lead Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Leads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Lead__c/fields/CloseReason__c.field-meta.xml
<CustomField>
    <fullName>CloseReason__c</fullName>
    <description>Sales Lead Close Reason</description>
    <inlineHelpText>Sales Close Reason Registration</inlineHelpText>
    <label>Close Reason</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Lead__c/fields/CustomerContactDate__c.field-meta.xml
<CustomField>
    <fullName>CustomerContactDate__c</fullName>
    <label>Customer Contact Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Sales_Lead__c/fields/LeadChannel__c.field-meta.xml
<CustomField>
    <fullName>LeadChannel__c</fullName>
    <label>Lead Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Direct Registration</fullName>
            </value>
            <value>
                <fullName>Marketing Lead Converted</fullName>
            </value>
            <value>
                <fullName>Demand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Lead__c/fields/LeadStage__c.field-meta.xml
<CustomField>
    <fullName>LeadStage__c</fullName>
    <description>Lead Stage</description>
    <label>Lead Stage</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cold</fullName>
                <color>#33CCFF</color>
                <label>Cold</label>
            </value>
            <value>
                <fullName>Warm</fullName>
                <color>#FF9900</color>
                <label>Warm</label>
            </value>
            <value>
                <fullName>Hot</fullName>
                <color>#FF0000</color>
                <label>Hot</label>
            </value>
            <value>
                <fullName>Converted</fullName>
                <color>#BBBBBB</color>
                <label>Converted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Lead__c/fields/LeadStatus__c.field-meta.xml
<CustomField>
    <fullName>LeadStatus__c</fullName>
    <description>Sales Lead Status</description>
    <inlineHelpText>Sales Lead Status</inlineHelpText>
    <label>Lead Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Process</fullName>
                <default>true</default>
                <label>In Process</label>
            </value>
            <value>
                <fullName>Close</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Lead__c/fields/LeadType__c.field-meta.xml
<CustomField>
    <fullName>LeadType__c</fullName>
    <description>Sales Lead Type</description>
    <inlineHelpText>Sales Lead Type</inlineHelpText>
    <label>Lead Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>LeadChannel__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>Business</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>Technical Support</label>
            </value>
            <value>
                <fullName>09</fullName>
                <label>Others</label>
            </value>
            <value>
                <fullName>31</fullName>
                <label>System Enhancement</label>
            </value>
            <value>
                <fullName>32</fullName>
                <label>New System</label>
            </value>
            <value>
                <fullName>33</fullName>
                <label>Solution/Service</label>
            </value>
            <value>
                <fullName>34</fullName>
                <label>Consulting</label>
            </value>
            <value>
                <fullName>35</fullName>
                <label>Seminar</label>
            </value>
            <value>
                <fullName>36</fullName>
                <label>IT Trend / Research</label>
            </value>
            <value>
                <fullName>37</fullName>
                <label>Benchmarking</label>
            </value>
            <value>
                <fullName>39</fullName>
                <label>Etc</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/IF_DemandCallOutAPIControllerTest.cls
/**
* @description       : Test class to cover functionality of IF_DemandCallOutAPIController Apex class.
* @author            : akash.g@samsung.com
* @group             : 
* @last modified on  : 08-04-2022
* @last modified by  : akash.g@samsung.com
* Modifications Log 
* Ver   Date         Author                    Modification
* 1.0   08-04-2022   akash.g@samsung.com       Initial Version 
**/
@isTest
public class IF_DemandCallOutAPIControllerTest {

    @isTest
    static void restServiceCatchTest() {
        Test.startTest();
       	Sales_Lead__c salesLead = new Sales_Lead__c();
        salesLead.Name = 'Test Lead 1';
        salesLead.LeadChannel__c = 'Demand';
        salesLead.LeadStage__c = 'Cold';
        salesLead.LeadType__c = '32';
        salesLead.LeadStatus__c = 'In Process';
        insert salesLead;
        salesLead.LeadStatus__c = 'Close';
        salesLead.CloseReason__c = 'Close reason';
        salesLead.CustomerContactDate__c =  System.today();
        update saleslead;
        
        Test.stopTest();
    }
    
}