force-app/main/default/objects/BizAttribute__c/BizAttribute__c.object-meta.xml
<CustomObject>
    <label>Biz. Attribute</label>
    <nameField>
        <label>Biz. Attribute Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Biz. Attribute</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/BizAttribute__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <label>Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CostCenter__c/CostCenter__c.object-meta.xml
<CustomObject>
    <label>Cost Center</label>
    <nameField>
        <label>Cost Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cost Center</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CostCenter__c/fields/CostCenter__c.field-meta.xml
<CustomField>
    <fullName>CostCenter__c</fullName>
    <externalId>true</externalId>
    <label>Cost Center</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/EvKostl__c.field-meta.xml
<CustomField>
    <fullName>EvKostl__c</fullName>
    <label>Cost Center</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Service__c/Master_Service__c.object-meta.xml
<CustomObject>
    <label>Master Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Service</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Service__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <externalId>true</externalId>
    <label>Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Master_Service__c/fields/TechAttribute__c.field-meta.xml
<CustomField>
    <fullName>TechAttribute__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Tech. Attribute</description>
    <label>TechAttribute</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Master_Solution__c/Master_Solution__c.object-meta.xml
<CustomObject>
    <label>Master Solution</label>
    <nameField>
        <label>Master Solution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Solution</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Solution__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>서비스</description>
    <label>Service</label>
    <referenceTo>Master_Service__c</referenceTo>
    <relationshipName>Solution</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Organization__c/Organization__c.object-meta.xml
<CustomObject>
    <label>Organization</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organizations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Organization__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <description>거점 코드</description>
    <label>Code</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <displayFormat>SVC-{YYYY}{MM}{00000}</displayFormat>
        <label>Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/BizAttribute__c.field-meta.xml
<CustomField>
    <fullName>BizAttribute__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Biz. Attribute</label>
    <referenceTo>BizAttribute__c</referenceTo>
    <relationshipName>BO_Service_Solution</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Changed__c.field-meta.xml
<CustomField>
    <fullName>Changed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>서비스 변경여부</description>
    <label>Changed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/ItemNumber__c.field-meta.xml
<CustomField>
    <fullName>ItemNumber__c</fullName>
    <label>Item Number</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>BO_Service_Solution</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/SalesDepartment__c.field-meta.xml
<CustomField>
    <fullName>SalesDepartment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Department(IF)</label>
    <referenceTo>CostCenter__c</referenceTo>
    <relationshipLabel>Service (Sales DepartmentC)</relationshipLabel>
    <relationshipName>Service1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/sDeletionFlag__c.field-meta.xml
<CustomField>
    <fullName>sDeletionFlag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>DeletionFlag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/sDeliveryDepartment__c.field-meta.xml
<CustomField>
    <fullName>sDeliveryDepartment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Delivery Department</label>
    <referenceTo>CostCenter__c</referenceTo>
    <relationshipLabel>Services (sDeliveryDepartment)</relationshipLabel>
    <relationshipName>DeliveryDepartment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/SendSAP__c.field-meta.xml
<CustomField>
    <fullName>SendSAP__c</fullName>
    <defaultValue>false</defaultValue>
    <description>SAP전송여부</description>
    <label>SendSAP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service(IF)</label>
    <referenceTo>Master_Service__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>BO_Service_Solution</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/sSalesDepartment__c.field-meta.xml
<CustomField>
    <fullName>sSalesDepartment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Department</label>
    <referenceTo>CostCenter__c</referenceTo>
    <relationshipLabel>Services (sSalesDepartment)</relationshipLabel>
    <relationshipName>SalesDepartment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/sService__c.field-meta.xml
<CustomField>
    <fullName>sService__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>Master_Service__c</referenceTo>
    <relationshipLabel>Services (sService)</relationshipLabel>
    <relationshipName>Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/TechAttribute__c.field-meta.xml
<CustomField>
    <fullName>TechAttribute__c</fullName>
    <defaultValue>false</defaultValue>
    <description>TechAttribute</description>
    <label>TechAttribute</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Solution__c/Solution__c.object-meta.xml
<CustomObject>
    <label>Solution(c)</label>
    <nameField>
        <displayFormat>SOL-{YYYY}{MM}{00000}</displayFormat>
        <label>Solution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Solution(c)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Solution__c/fields/BizAttribute__c.field-meta.xml
<CustomField>
    <fullName>BizAttribute__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Biz. Attribute(IF)</label>
    <referenceTo>BizAttribute__c</referenceTo>
    <relationshipLabel>Solution(c)</relationshipLabel>
    <relationshipName>Solution_c</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Solution__c/fields/Changed__c.field-meta.xml
<CustomField>
    <fullName>Changed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Changed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Solution__c/fields/ItemNumber__c.field-meta.xml
<CustomField>
    <fullName>ItemNumber__c</fullName>
    <formula>Service__r.ItemNumber__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Item Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Solution__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Solution(c)</relationshipLabel>
    <relationshipName>Solution_c</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Solution__c/fields/SalesDepartment__c.field-meta.xml
<CustomField>
    <fullName>SalesDepartment__c</fullName>
    <formula>Service__r.SalesDepartment__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Department</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Solution__c/fields/sBizAttribute__c.field-meta.xml
<CustomField>
    <fullName>sBizAttribute__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Biz. Attribute</label>
    <referenceTo>BizAttribute__c</referenceTo>
    <relationshipLabel>Solution(c) (Biz. Attribute)</relationshipLabel>
    <relationshipName>sBizAttribute</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Solution__c/fields/sBusinessType__c.field-meta.xml
<CustomField>
    <fullName>sBusinessType__c</fullName>
    <label>Business Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Solution__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Solution(c)</relationshipLabel>
    <relationshipName>Solution</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Solution__c/fields/Solution__c.field-meta.xml
<CustomField>
    <fullName>Solution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Solution(IF)</label>
    <referenceTo>Master_Solution__c</referenceTo>
    <relationshipLabel>Solution(c)</relationshipLabel>
    <relationshipName>Solution_c</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Solution__c/fields/sPSType__c.field-meta.xml
<CustomField>
    <fullName>sPSType__c</fullName>
    <label>PSType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Solution__c/fields/sSolution__c.field-meta.xml
<CustomField>
    <fullName>sSolution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Solution</label>
    <referenceTo>Master_Solution__c</referenceTo>
    <relationshipLabel>Solution(c) (sSolution)</relationshipLabel>
    <relationshipName>Solution_c1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Solution__c/fields/sWBSClass__c.field-meta.xml
<CustomField>
    <fullName>sWBSClass__c</fullName>
    <label>WBS Class</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NewTestOpportunity.cls
/**
 * @description       : 
 * @author            : chae_ho.yang@samsung.com
 * @group             : 
 * @last modified on  : 01-03-2024
 * @last modified by  : chae_ho.yang@samsung.com
**/
public with sharing class NewTestOpportunity {

    public User user = [select id, EvKostl__c from user where id =: Userinfo.getUserid()];


    public Boolean condition { get; set; }
    public Opportunity newOpportunity { get; set; }      
    public Service__c srv = new Service__c();
    public Solution__c sol = new Solution__c();
    public Boolean isSandbox = [SELECT IsSandbox FROM Organization LIMIT 1].IsSandbox;
    public RecordType RT_OPPTY_HQ = [SELECT Id, DeveloperName FROM RecordType WHERE SobjectType = 'Opportunity' AND DeveloperName = 'HQ' Limit 1];
    public RecordType RT_OPPTY_LOGI = [SELECT Id, DeveloperName FROM RecordType WHERE SobjectType = 'Opportunity' AND DeveloperName = 'Logistics' Limit 1];
    public Employee__C pm = [select id, name from employee__c where name = '양채호'];
    public Account hyundai = [select id, name from account where AccountNumber = 'A1000259'];
    public Account emro = [select id, name from account where AccountNumber = 'A0034034'];
    public CostCenter__c cc = [select id, name from costcenter__c where costcenter__c =: user.EvKostl__c];
    public Master_Service__c ms = [select id, name from Master_Service__c where name = 'CRM'];
    public Master_Solution__c ms2 = [select id, name from Master_solution__c where name = 'CRM Implementation'];
    public BizAttribute__c bizatt = [select id, name from BizAttribute__c where name = 'SI/NI Implementation'];
    public Organization__c org = [select id, name, Code__c from Organization__c where code__c = 'T714'];
   
    public NewTestOpportunity(ApexPages.StandardSetController controller) {
       newOpportunity = new Opportunity();
    }

    private void createData() {
        newOpportunity.RecordTypeId = RT_OPPTY_HQ.Id;
        newOpportunity.ProposalPM__c = pm.Id;
        newOpportunity.MigData__c = True;
        newOpportunity.StageName = 'Z01';
        newOpportunity.CloseDate = Date.today().addDays(1);
        newOpportunity.AccountId = hyundai.Id;
        newOpportunity.cOriginAcc__c = hyundai.Id;
        newOpportunity.cLeadID__c = NULL;
        newOpportunity.BusinessType2__c = 'Implementation';
        newOpportunity.Amount = 200000000;
        newOpportunity.BiddingMethod__c = 'BID001';
        newOpportunity.CurrencyIsoCode = 'KRW';
        newOpportunity.Reuse__c = 'Y';
        newOpportunity.ReuseReason__c = '기타 재활용';
        newOpportunity.cRevenueStartDate__c = Date.today().addDays(3);
        newOpportunity.cRevenueEndDate__c = Date.today().addDays(7);
        newOpportunity.SalesDepartment__c = cc.Id;
        newOpportunity.cPrimarySalesDepartment__c = cc.Id;
        System.debug(newOpportunity);
    }

    private void createServ() {
        srv.Opportunity__c = newOpportunity.id;
        srv.ItemNumber__c = 10;
        srv.sservice__c = ms.id;
        srv.sSalesDepartment__c = cc.id;
        srv.sDeliveryDepartment__c = cc.id;
        srv.sDeletionFlag__c = false;
        srv.TechAttribute__c = false;
        //srv.Changed__c = true;
        System.debug('service1 : ' + srv);
    }

    private void createSol() {
        sol.Service__c = srv.Id;
        sol.sSolution__c = ms2.Id;
        sol.sBizAttribute__c = bizatt.Id;
        sol.sDeletionFlag__c = false;
        sol.SendSAP__c = false;
        sol.changed__c = false;
        sol.Opportunity__c = newOpportunity.Id;
        //sol.sPSType__c = 'SI1';
        //sol.sBusinessType__c = 'TI';
        //sol.sWBSClass__c = 'SI';
        System.debug('solution1 : ' + sol);
    }

    public PageReference createOpportunityLogi() {
        newOpportunity.RecordTypeId = RT_OPPTY_LOGI.Id;
        newOpportunity.type = '01';
        newOpportunity.MigData__c = True;
        newOpportunity.StageName = 'Z01';
        newOpportunity.CloseDate = Date.today().addDays(3);
        newOpportunity.AccountId = emro.Id;
        newOpportunity.LogisticsBizDevelopmentType__c = '04';
        newOpportunity.cLeadID__c = NULL;
        newOpportunity.BiddingDeadline__c = Date.today().addDays(1);
        newOpportunity.Amount = 200000000;
        newOpportunity.LogisticsServiceType__c = '01';
        newOpportunity.CurrencyIsoCode = 'KRW';
        newOpportunity.LogisticsBizType__c = '01';
        newOpportunity.LBSExceptionType__c = '05';
        newOpportunity.cRevenueStartDate__c = Date.today().addDays(4);
        newOpportunity.cRevenueEndDate__c = Date.today().addDays(7);
        newOpportunity.LogisticsCustomerType__c = 'SECSET';
        newOpportunity.SubIndusrty__c = '06';
        newOpportunity.SalesOrganization__c = org.Id;
        newOpportunity.DeliveryOrganization__c = org.Id;
        System.debug(newOpportunity);
        insert newOpportunity;
        PageReference home = new PageReference('https://sdssfa--qa.sandbox.lightning.force.com/lightning/r/Opportunity/'+newOpportunity.Id+'/view');
        newOpportunity = new Opportunity(); // Reset the form
        home.setRedirect(true);        
        return home;
    }

    public PageReference back() {
        PageReference home = new PageReference('https://sdssfa--qa.sandbox.lightning.force.com/lightning/o/Opportunity/list?filterName=Recent');
        newOpportunity = new Opportunity(); // Reset the form
        home.setRedirect(true);        
        return home;    
    }
    
    public PageReference createOpportunity() {
        createData();
        System.debug('data created');
        try {
            insert newOpportunity;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'Opportunity created successfully!'));
            System.debug('done');
            PageReference home = new PageReference('https://sdssfa--qa.sandbox.lightning.force.com/lightning/r/Opportunity/'+newOpportunity.Id+'/view');
            newOpportunity = new Opportunity(); // Reset the form
            home.setRedirect(true);        
            return home;    
        } catch (Exception ex) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Error Occurred'));
            return null;
        }
    }

    public PageReference createOpportunityServSol() {
        createData();
        System.debug('createdata done');
        try {
            insert newOpportunity;
            createServ();
            System.debug('createserv done');
            insert srv;
            System.debug('serv create done');
            createSol();
            insert sol;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'Opportunity with Service/Solution created successfully!'));
            System.debug('done');
            PageReference home = new PageReference('https://sdssfa--qa.sandbox.lightning.force.com/lightning/r/Opportunity/'+newOpportunity.Id+'/view');
            newOpportunity = new Opportunity(); // Reset the form
            home.setRedirect(true);        
            return home;    
        } catch (Exception ex) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Error Occurred'));
            System.debug('fail' + ex);
            return null;
        }
    }
}