force-app/main/default/objects/BizAttribute__c/BizAttribute__c.object-meta.xml
<CustomObject>
    <label>Biz. Attribute</label>
    <nameField>
        <label>Biz. Attribute Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Biz. Attribute</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/BizAttribute__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <label>Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Business__c/Business__c.object-meta.xml
<CustomObject>
    <label>Business</label>
    <nameField>
        <label>Business Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Business__c/fields/Use__c.field-meta.xml
<CustomField>
    <fullName>Use__c</fullName>
    <defaultValue>false</defaultValue>
    <description>사용여부</description>
    <label>Use</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Business__c/fields/ValidityEndDate__c.field-meta.xml
<CustomField>
    <fullName>ValidityEndDate__c</fullName>
    <description>유효 종료일</description>
    <label>Validity End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Business__c/fields/ValidityStartDate__c.field-meta.xml
<CustomField>
    <fullName>ValidityStartDate__c</fullName>
    <description>유효 시작일</description>
    <label>Validity Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Company__c/Company__c.object-meta.xml
<CustomObject>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Company</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Company__c/fields/CompanyCode__c.field-meta.xml
<CustomField>
    <fullName>CompanyCode__c</fullName>
    <description>회사코드</description>
    <label>Company Code</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CostCenter__c/CostCenter__c.object-meta.xml
<CustomObject>
    <label>Cost Center</label>
    <nameField>
        <label>Cost Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cost Center</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CostCenter__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Company</label>
    <referenceTo>Company__c</referenceTo>
    <relationshipLabel>Cost Center</relationshipLabel>
    <relationshipName>Cost_Center</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CostCenter__c/fields/CompanyCode__c.field-meta.xml
<CustomField>
    <fullName>CompanyCode__c</fullName>
    <label>Company Code</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CostCenter__c/fields/CostCenter__c.field-meta.xml
<CustomField>
    <fullName>CostCenter__c</fullName>
    <externalId>true</externalId>
    <label>Cost Center</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Master_Service__c/Master_Service__c.object-meta.xml
<CustomObject>
    <label>Master Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Service</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Service__c/fields/Business__c.field-meta.xml
<CustomField>
    <fullName>Business__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>사업 대분류</description>
    <label>Business</label>
    <referenceTo>Business__c</referenceTo>
    <relationshipName>Service</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Master_Service__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <externalId>true</externalId>
    <label>Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Master_Service__c/fields/ServiceBizUnit__c.field-meta.xml
<CustomField>
    <fullName>ServiceBizUnit__c</fullName>
    <description>사업부 명</description>
    <label>Service Biz Unit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Service__c/fields/ServiceBizUnitCode__c.field-meta.xml
<CustomField>
    <fullName>ServiceBizUnitCode__c</fullName>
    <description>사업부 코드</description>
    <label>Service Biz Unit Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Service__c/fields/ServiceDepartment__c.field-meta.xml
<CustomField>
    <fullName>ServiceDepartment__c</fullName>
    <description>서비스 팀</description>
    <label>Service Department</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Service__c/fields/ServiceDepartmentCode__c.field-meta.xml
<CustomField>
    <fullName>ServiceDepartmentCode__c</fullName>
    <description>서비스 팀 코드</description>
    <label>Service Department Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Service__c/fields/Use__c.field-meta.xml
<CustomField>
    <fullName>Use__c</fullName>
    <defaultValue>false</defaultValue>
    <description>사용여부</description>
    <label>Use</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Master_Service__c/fields/ValidityEndDate__c.field-meta.xml
<CustomField>
    <fullName>ValidityEndDate__c</fullName>
    <description>유효 종료일</description>
    <label>Validity End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Master_Service__c/fields/ValidityStartDate__c.field-meta.xml
<CustomField>
    <fullName>ValidityStartDate__c</fullName>
    <description>유효 시작일</description>
    <label>Validity Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Master_Solution__c/Master_Solution__c.object-meta.xml
<CustomObject>
    <label>Master Solution</label>
    <nameField>
        <label>Master Solution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Solution</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Solution__c/fields/PLCStatus__c.field-meta.xml
<CustomField>
    <fullName>PLCStatus__c</fullName>
    <description>PLC Status</description>
    <label>PLC Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>N</fullName>
                <label>New</label>
            </value>
            <value>
                <fullName>A</fullName>
                <label>Available for Sales</label>
            </value>
            <value>
                <fullName>D</fullName>
                <label>Discontinued for Sales</label>
            </value>
            <value>
                <fullName>E</fullName>
                <label>End of Sales</label>
            </value>
            <value>
                <fullName>P</fullName>
                <label>Planned</label>
            </value>
            <value>
                <fullName>R</fullName>
                <label>Registered for Sales</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master_Solution__c/fields/PLManagementLevel__c.field-meta.xml
<CustomField>
    <fullName>PLManagementLevel__c</fullName>
    <label>P/L Management Level</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Solution__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Product</description>
    <label>Product</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Master_Solution__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>서비스</description>
    <label>Service</label>
    <referenceTo>Master_Service__c</referenceTo>
    <relationshipName>Solution</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Master_Solution__c/fields/SolutionDepartment__c.field-meta.xml
<CustomField>
    <fullName>SolutionDepartment__c</fullName>
    <description>솔루션 부서 명</description>
    <label>Solution Department</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Solution__c/fields/SolutionDepartmentCode__c.field-meta.xml
<CustomField>
    <fullName>SolutionDepartmentCode__c</fullName>
    <description>솔루션 부서 코드</description>
    <label>Solution Department Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Solution__c/fields/SolutionManageName__c.field-meta.xml
<CustomField>
    <fullName>SolutionManageName__c</fullName>
    <description>솔루션 매니저 이름</description>
    <label>Solution Manage Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Solution__c/fields/SolutionManagerNo__c.field-meta.xml
<CustomField>
    <fullName>SolutionManagerNo__c</fullName>
    <description>솔루션 매니저 사번</description>
    <label>Solution Manager No.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MasterMap__c/MasterMap__c.object-meta.xml
<CustomObject>
    <label>Master Map</label>
    <nameField>
        <displayFormat>MM-{000000}</displayFormat>
        <label>Master Map Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Master Maps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MasterMap__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>L1</fullName>
            </value>
            <value>
                <fullName>L2</fullName>
            </value>
            <value>
                <fullName>L3</fullName>
            </value>
            <value>
                <fullName>Dept</fullName>
            </value>
            <value>
                <fullName>BizAttr</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <displayFormat>SVC-{YYYY}{MM}{00000}</displayFormat>
        <label>Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service(IF)</label>
    <referenceTo>Master_Service__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>BO_Service_Solution</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Solution__c/Solution__c.object-meta.xml
<CustomObject>
    <label>Solution(c)</label>
    <nameField>
        <displayFormat>SOL-{YYYY}{MM}{00000}</displayFormat>
        <label>Solution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Solution(c)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Solution__c/fields/PLCStatus__c.field-meta.xml
<CustomField>
    <fullName>PLCStatus__c</fullName>
    <formula>Text(Solution__r.PLCStatus__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PLC Status(IF)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Solution__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Solution(c)</relationshipLabel>
    <relationshipName>Solution</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Solution__c/fields/Solution__c.field-meta.xml
<CustomField>
    <fullName>Solution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Solution(IF)</label>
    <referenceTo>Master_Solution__c</referenceTo>
    <relationshipLabel>Solution(c)</relationshipLabel>
    <relationshipName>Solution_c</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WBS__c/WBS__c.object-meta.xml
<CustomObject>
    <label>WBS</label>
    <nameField>
        <label>WBS Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WBS</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/WBS__c/fields/Solution__c.field-meta.xml
<CustomField>
    <fullName>Solution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Solution(c)</label>
    <referenceTo>Solution__c</referenceTo>
    <relationshipLabel>Solution(c)</relationshipLabel>
    <relationshipName>Solution</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Batch_BizClassMigController_Test.cls
/**
 * @description       : 
 * @author            : kwangjin.yu@dkbmc.com
 * @group             : 
 * @last modified on  : 01-24-2022
 * @last modified by  : kwangjin.yu@dkbmc.com
 * Modifications Log 
 * Ver   Date         Author                   Modification
 * 1.0   01-21-2022   kwangjin.yu@dkbmc.com   Initial Version
**/
@isTest
public with sharing class Batch_BizClassMigController_Test {
    static List<MasterMap__c> listMasterMap = new List<MasterMap__c>();
    static String strPrefix = 'NoName';
    static Set<Id> setOppId = new Set<Id>();
    static Account acc1 = new Account();
    static Opportunity opp1 = new Opportunity();
    
    static Company__c company = new Company__c();
    static CostCenter__c cCenter = new CostCenter__c();
    
    static Service__c srv = new Service__c();
    static Solution__c sol = new Solution__c();    
    
    
    
    static Master_Service__c MasterService = new Master_Service__c();
    static Master_Solution__c MasterSolution = new Master_Solution__c();
    static Map<String, MasterMap__c> mapMasterMap = new Map<String, MasterMap__c>();
    

    @TestSetup
    static void setData(){
        company.Name = 'test';
        insert company;
        
        cCenter.CostCenter__c = 'T514-70000';
        cCenter.Company__c = company.id;
        insert cCenter;
        
        Business__c biz1 = new Business__c(Name='MSP', Code__c='12000005', Use__c=TRUE ,ValidityEndDate__c=Date.newInstance(4000, 12, 31), ValidityStartDate__c=Date.newInstance(2022, 01, 13));
        insert biz1;
        
        Master_Service__c mSer1 = new Master_Service__c(Name='Cloud App ITO', Code__c='22000008'
                                     , ServiceBizUnitCode__c='T100-10407', ServiceBizUnit__c='클라우드사업부', ServiceDepartmentCode__c='T100-10407'
                                     , ServiceDepartment__c='클라우드사업부', Use__c=TRUE, ValidityEndDate__c=Date.newInstance(4000, 12, 31)
                                     , ValidityStartDate__c=Date.newInstance(2022, 01, 13));
        mSer1.Business__c = biz1.Id;
        insert mSer1;
        
        Master_Solution__c mSol1 = new Master_Solution__c(Name='Mobile App ITO', Code__c='30000026', CompanyCode__c='T100', PLCStatus__c='A', PLManagementLevel__c='L3'
                                      , Product__c=FALSE, SolutionDepartmentCode__c='T100-12014'
                                      , SolutionDepartment__c='전자서비스혁신팀', SolutionManageName__c='오명택 상무', SolutionManagerNo__c='28845', SolutionType__c='10'
                                      , Use__c=TRUE, ValidityEndDate__c=Date.newInstance(4000, 12, 31), ValidityStartDate__c=Date.newInstance(2022, 01, 13));
        mSol1.Service__c = mSer1.Id;
        insert mSol1;
        
        BizAttribute__c mBizAttr = new BizAttribute__c(Name='Service_Usage/Recurring', Code__c='S133');
        insert mBizAttr;
        
        MasterMap__c mMap1 = new MasterMap__c(AsisCode__c='30000026', AsIsName__c='Sol_TEST', TobeCode__c='30000026', ToBeName__c='Sol_TEST',Level__c='L3',RelatedAB__c='equalsAll',TAFlag__c=FALSE);
        insert mMap1;
        
        MasterMap__c mMap2 = new MasterMap__c(AsisCode__c='22000008_30000026', AsIsName__c='Ser_TEST', TobeCode__c='22000008', ToBeName__c='Ser_TEST',Level__c='L2',RelatedAB__c='equalsAll',TAFlag__c=FALSE);
        insert mMap2;
        
        MasterMap__c mMap3 = new MasterMap__c(AsisCode__c='30000026_S133', AsIsName__c='Ser_TEST', TobeCode__c='22000008', ToBeName__c='Ser_TEST',Level__c='BizAttr',RelatedAB__c='merge',TAFlag__c=FALSE);
        insert mMap3;


        MasterMap__c mMap4 = new MasterMap__c(AsisCode__c='22000008_T514-70000', AsIsName__c='Ser_TEST', TobeCode__c=cCenter.Id, ToBeName__c='Ser_TEST',Level__c='Dept',RelatedAB__c='merge',TAFlag__c=FALSE);
        insert mMap4;
        
        
        
        	
        
    }
    
    @isTest
    static void TestCase01(){
        
        acc1 = Utils_TestDataFactory.createAccount('Batch_BizClassMigController_0214');
        acc1.MDGCheck__c = true;
        update acc1;        
        
        opp1.Name = 'testoppty';
        opp1.AccountId = acc1.id;
        opp1.OpportunityCode__c = 'SDS-212109999';
		opp1.ActivityStatus__c = 'XP11';
		opp1.StageName = 'Qualification';
		opp1.CloseDate = Utils.getCurDatetime().date().addDays(1);
        insert opp1;
        
        system.debug('### Batch_BizClassMigController_Test :: TestCase01 :: opp1 = ' + opp1.id);
        
        setOppId.add(opp1.Id);
        
        
        
        
        
        
       // Service__r.Name, Service__r.Code__c, sService__c
       //      , sService__r.Name, sService__r.Code__c, DeliveryDepartmentNmBackup__c, TechAttribute__c, DeliveryDepartment__c, sDeliveryDepartment__c
        Master_Service__c mse1 = [SELECT id, Name FROM Master_Service__c WHERE Code__c='22000008'];
            
        CostCenter__c mCC = [SELECT id, Name, CostCenter__c FROM CostCenter__c WHERE CostCenter__c='T514-70000']; 
        system.debug('### Batch_BizClassMigController_Test :: TestCase01 :: mCC = ' + mCC.CostCenter__c);
            
        system.debug('### Batch_BizClassMigController_Test :: TestCase01 :: mse1 name = ' + mse1.Name);
        srv.Opportunity__c = opp1.id;
        srv.ItemNumber__c = 10;
        srv.Service__c = mse1.id;
        srv.sService__c = mse1.id;
        srv.SalesDepartment__c = mCC.id;
        srv.sSalesDepartment__c = mCC.id;
        srv.DeliveryDepartment__c = mCC.id;
        srv.sDeliveryDepartment__c = mCC.id;
        //srv.TechAttribute__c = false;
        srv.SendSAP__c = true;
        srv.DeletionFlag__c = false;
        insert srv;
        
        
        //Id, Name, Opportunity__c, Service__c, Solution__c, Solution__r.Name, Solution__r.Code__c, sSolution__c, sSolution__r.Name, sSolution__r.Code__c
        //     , SolutionNmBackup__c, sDeletionFlag__c, SendSAP__c, SolutionType__c
        BizAttribute__c bizAttr1 = [SELECT id FROM BizAttribute__c WHERE Code__c='S133'];
        Master_Solution__c mso1 = [SELECT id FROM Master_Solution__c WHERE Code__c='30000026'];
        sol.Opportunity__c = opp1.id;
        sol.Service__c = srv.Id;
        sol.Solution__c = mso1.Id;
        sol.sSolution__c = mso1.Id;
        sol.sDeletionFlag__c = false;
        sol.SendSAP__c = true;
        sol.BizAttributeBackup__c = 'S133';
        sol.BizAttribute__c  = bizAttr1.id;
        insert sol;

        Test.startTest();       
        //Database.executeBatch(new Batch_BizClassMigController(strPrefix, setOppId), 200);
        
        BizClassMigController.executeBatch(opp1.Id,'2020-01-01 00:00:00','2022-10-10 00:00:00',false);
        Test.stopTest();
		
    }
  
    
}