force-app/main/default/objects/BizAttribute__c/BizAttribute__c.object-meta.xml
<CustomObject>
    <label>Biz. Attribute</label>
    <nameField>
        <label>Biz. Attribute Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Biz. Attribute</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/BizAttribute__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>사용 여부</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BizAttribute__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <label>Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/BizAttribute__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>사업 속성 내역</description>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Solution__c/Master_Solution__c.object-meta.xml
<CustomObject>
    <label>Master Solution</label>
    <nameField>
        <label>Master Solution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Solution</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Solution__c/Solution__c.object-meta.xml
<CustomObject>
    <label>Solution(c)</label>
    <nameField>
        <displayFormat>SOL-{YYYY}{MM}{00000}</displayFormat>
        <label>Solution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Solution(c)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Solution__c/fields/BizAttribute__c.field-meta.xml
<CustomField>
    <fullName>BizAttribute__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Biz. Attribute(IF)</label>
    <referenceTo>BizAttribute__c</referenceTo>
    <relationshipLabel>Solution(c)</relationshipLabel>
    <relationshipName>Solution_c</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Solution__c/fields/BusinessType__c.field-meta.xml
<CustomField>
    <fullName>BusinessType__c</fullName>
    <label>Business Type(IF)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Solution__c/fields/Solution__c.field-meta.xml
<CustomField>
    <fullName>Solution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Solution(IF)</label>
    <referenceTo>Master_Solution__c</referenceTo>
    <relationshipLabel>Solution(c)</relationshipLabel>
    <relationshipName>Solution_c</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Solution__c/fields/WBSClass__c.field-meta.xml
<CustomField>
    <fullName>WBSClass__c</fullName>
    <label>WBS Class(IF)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SvcSolBizAttr__c/SvcSolBizAttr__c.object-meta.xml
<CustomObject>
    <label>Service-Solution-Biz. Attribute</label>
    <nameField>
        <label>SvcSolBizAttr Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service-Solution-Biz. Attribute</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SvcSolBizAttr__c/fields/BizAttribute__c.field-meta.xml
<CustomField>
    <fullName>BizAttribute__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Biz. Attribute</label>
    <referenceTo>BizAttribute__c</referenceTo>
    <relationshipLabel>Service-Solution-Biz. Attribute</relationshipLabel>
    <relationshipName>Service_Solution_Biz_Attribute</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SvcSolBizAttr__c/fields/BusinessType__c.field-meta.xml
<CustomField>
    <fullName>BusinessType__c</fullName>
    <description>사업 유</description>
    <label>Business Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TI</fullName>
                <label>Implementation Business</label>
            </value>
            <value>
                <fullName>TS</fullName>
                <label>Service Business</label>
            </value>
            <value>
                <fullName>TD</fullName>
                <label>Sales Business</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SvcSolBizAttr__c/fields/Solution__c.field-meta.xml
<CustomField>
    <fullName>Solution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Solution(c)</label>
    <referenceTo>Master_Solution__c</referenceTo>
    <relationshipLabel>Service-Solution-Biz. Attribute</relationshipLabel>
    <relationshipName>Service_Solution_Biz_Attribute</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SvcSolBizAttr__c/fields/Use__c.field-meta.xml
<CustomField>
    <fullName>Use__c</fullName>
    <defaultValue>false</defaultValue>
    <description>사용 여부</description>
    <label>Use</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SvcSolBizAttr__c/fields/WBSClass__c.field-meta.xml
<CustomField>
    <fullName>WBSClass__c</fullName>
    <description>WBS Class (수익인식기준)</description>
    <label>WBS Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SC</fullName>
            </value>
            <value>
                <fullName>SI</fullName>
            </value>
            <value>
                <fullName>SM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SvcSolBizAttrSendToEccController_Test.cls
/**
 * @description       : 
 * @author            : wonjune.oh@partner.samsung.com
 * @group             : 
 * @last modified on  : 2021-07-12
 * @last modified by  : seonju.jin@dkbmc.com
 * Modifications Log 
 * Ver   Date         Author                           Modification
 * 1.0   2021-01-05   wonjune.oh@partner.samsung.com   Initial Version
**/
@isTest
public with sharing class SvcSolBizAttrSendToEccController_Test {
    static {
        BizAttribute__c BizAttribute = new BizAttribute__c(Code__c ='S144', Description__c='SI/NI Implementation', Active__c=true);

        Master_Solution__c MasterSolution = new Master_Solution__c(Code__c = '30000004');
        
        insert BizAttribute;
        insert MasterSolution;
        
        SvcSolBizAttr__c svcsolBizAttr = new SvcSolBizAttr__c(BusinessType__c= 'TI', WBSClass__c='SI', Use__c = true, BizAttribute__c = BizAttribute.Id, Solution__c= MasterSolution.Id);
        
        insert svcsolBizAttr;
    }
    @isTest static void test_method() {
        Test.startTest();
        Test.setMock( HttpCalloutMock.class, new SvcSolBizAttrSendToEccControllerTestMok(200));

        SvcSolBizAttrSendToEccController.solBizAttrSendToEcc();

		Test.stopTest();
    }

    
    @isTest static void test_method2() {
        Test.startTest();
        Test.setMock( HttpCalloutMock.class, new SvcSolBizAttrSendToEccControllerTestMok(400));

        SvcSolBizAttrSendToEccController.solBizAttrSendToEcc();

		Test.stopTest();
    }

    public class SvcSolBizAttrSendToEccControllerTestMok implements HttpCalloutMock{
        private Integer statusCode = 200;
     
        public SvcSolBizAttrSendToEccControllerTestMok(Integer statusCode) { 
            this.statusCode = statusCode;
        }
    
        public HTTPResponse respond(HTTPRequest request) {
            // Create a fake response
            HttpResponse response = new HttpResponse();
            response.setHeader('Content-Type', 'application/json');
            String body = '';
            if(statusCode == 200){
                body = '{ ' +
                             '   "ES_RTMSG": ' +
                             '   {  ' +
                             '        "TYPE": "S", ' +
                             '        "RTMSG": "Success" ' +
                             '    }, ' +
                             '   "IT_DATA": ' +
                             '   [  ' +
                             '      {  ' +
                             '        "SFDC_CLASS": null, '+
                             '        "ZZORDER_TYPE": "S149", '+
                             '        "ZOPPT_TYPE": null,   '+
                             '        "ZZWBS_CLASS": "SM",  ' +
                             '        "ZZUSEYN": "T",   '+
                             '        "ZZPS_TYPE": "SM4" '+
                             '      }  '+
                             '   ] '+
                             '      ' +
                             ' }';
            }else{
                body = '{ ' +
                '   "ES_RTMSG": ' +
                '   {  ' +
                '        "TYPE": "E", ' +
                '        "RTMSG": "Error" ' +
                '    }, ' +
                '   "IT_DATA":[]}';
            }
            response.setBody(body);
            response.setStatusCode(statusCode);
            return response; 
        }
    }
}