force-app/main/default/objects/BizAttribute__c/BizAttribute__c.object-meta.xml
<CustomObject>
    <label>Biz. Attribute</label>
    <nameField>
        <label>Biz. Attribute Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Biz. Attribute</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/BizAttribute__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>사용 여부</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BizAttribute__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <label>Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Master_Service__c/Master_Service__c.object-meta.xml
<CustomObject>
    <label>Master Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Service</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Service__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <externalId>true</externalId>
    <label>Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Master_Service__c/fields/Use__c.field-meta.xml
<CustomField>
    <fullName>Use__c</fullName>
    <defaultValue>false</defaultValue>
    <description>사용여부</description>
    <label>Use</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Master_Service__c/fields/ValidityEndDate__c.field-meta.xml
<CustomField>
    <fullName>ValidityEndDate__c</fullName>
    <description>유효 종료일</description>
    <label>Validity End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Master_Service__c/fields/ValidityStartDate__c.field-meta.xml
<CustomField>
    <fullName>ValidityStartDate__c</fullName>
    <description>유효 시작일</description>
    <label>Validity Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Master_Solution__c/Master_Solution__c.object-meta.xml
<CustomObject>
    <label>Master Solution</label>
    <nameField>
        <label>Master Solution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Solution</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Solution__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>서비스</description>
    <label>Service</label>
    <referenceTo>Master_Service__c</referenceTo>
    <relationshipName>Solution</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <displayFormat>SVC-{YYYY}{MM}{00000}</displayFormat>
        <label>Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/BizAttribute__c.field-meta.xml
<CustomField>
    <fullName>BizAttribute__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Biz. Attribute</label>
    <referenceTo>BizAttribute__c</referenceTo>
    <relationshipName>BO_Service_Solution</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>BO_Service_Solution</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service(IF)</label>
    <referenceTo>Master_Service__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>BO_Service_Solution</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Solution__c/Solution__c.object-meta.xml
<CustomObject>
    <label>Solution(c)</label>
    <nameField>
        <displayFormat>SOL-{YYYY}{MM}{00000}</displayFormat>
        <label>Solution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Solution(c)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Solution__c/fields/BizAttribute__c.field-meta.xml
<CustomField>
    <fullName>BizAttribute__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Biz. Attribute(IF)</label>
    <referenceTo>BizAttribute__c</referenceTo>
    <relationshipLabel>Solution(c)</relationshipLabel>
    <relationshipName>Solution_c</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Solution__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Solution(c)</relationshipLabel>
    <relationshipName>Solution_c</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Solution__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Solution(c)</relationshipLabel>
    <relationshipName>Solution</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Solution__c/fields/Solution__c.field-meta.xml
<CustomField>
    <fullName>Solution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Solution(IF)</label>
    <referenceTo>Master_Solution__c</referenceTo>
    <relationshipLabel>Solution(c)</relationshipLabel>
    <relationshipName>Solution_c</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SvcSolBizAttr__c/SvcSolBizAttr__c.object-meta.xml
<CustomObject>
    <label>Service-Solution-Biz. Attribute</label>
    <nameField>
        <label>SvcSolBizAttr Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service-Solution-Biz. Attribute</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SvcSolBizAttr__c/fields/BizAttribute__c.field-meta.xml
<CustomField>
    <fullName>BizAttribute__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Biz. Attribute</label>
    <referenceTo>BizAttribute__c</referenceTo>
    <relationshipLabel>Service-Solution-Biz. Attribute</relationshipLabel>
    <relationshipName>Service_Solution_Biz_Attribute</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SvcSolBizAttr__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <formula>Solution__r.Service__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Service</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SvcSolBizAttr__c/fields/Solution__c.field-meta.xml
<CustomField>
    <fullName>Solution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Solution(c)</label>
    <referenceTo>Master_Solution__c</referenceTo>
    <relationshipLabel>Service-Solution-Biz. Attribute</relationshipLabel>
    <relationshipName>Service_Solution_Biz_Attribute</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SvcSolBizAttr__c/fields/Use__c.field-meta.xml
<CustomField>
    <fullName>Use__c</fullName>
    <defaultValue>false</defaultValue>
    <description>사용 여부</description>
    <label>Use</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/OpportunitySolutionItemController_Test.cls
/**
 * @description       : 
 * @author            : seonju.jin@dkbmc.com
 * @group             : 
 * @last modified on  : 2021-10-19
 * @last modified by  : seonju.jin@dkbmc.com
 * Modifications Log 
 * Ver   Date         Author                 Modification
 * 1.0   2020-12-01   seonju.jin@dkbmc.com   Initial Version
**/
@isTest
public class OpportunitySolutionItemController_Test {
    static Master_Solution__c master_solution;
	static Service__c service;
    static Opportunity opport;
    static Opportunity opport2;
    static SvcSolBizAttr__c svcSolAttr;
    static BizAttribute__c bizAttr;
    static Master_Service__c master_service;
    static Solution__c solution;

    static{
         opport = new Opportunity(
            Name = 'Test Oppty',
            CloseDate = System.today(),
            StageName = 'Z01'
		);        
        insert opport;
        
        opport2 = new Opportunity(
            Name = 'Test Oppty2',
            CloseDate = System.today(),
            StageName = 'Z01'
		);        
        insert opport2;

        opport.CollaborationInOut__c = 'IN';
        opport.CollaborationBOId__c = opport2.Id;

        opport2.CollaborationInOut__c = 'OUT';
        opport2.CollaborationBOId__c = opport.Id;

        update opport;
        update opport2;

        master_service = new Master_Service__c(
            Name = 'test',
            Code__c = '12313',
            Use__c = true
        );
        insert master_service;
        
        service = new Service__c(
            //Name = 'testservice',
            Opportunity__c = opport2.Id,
            Service__c = master_service.Id
        );
        insert service;
        
        Date d = System.today();
        Date startDate = d.addDays(-7);
        Date endDate = d.addDays(7);
        master_solution = new Master_Solution__c(
            Name ='Test Solution 1 - 1',
            Code__c = '123',
            Service__c = service.Service__c,
            Use__c = true,
            ValidityEndDate__c = endDate,
            ValidityStartDate__c = startDate
        ); 
        insert master_solution;

        bizAttr = new BizAttribute__c(
            Name = 'testbizattr',
            Code__c = '123123',
            Active__c = true
        );
        insert bizAttr;

        svcSolAttr = new SvcSolBizAttr__c(
            BizAttribute__c = bizAttr.Id,
            Solution__c = master_solution.Id,
            Use__c = true
        );
        insert svcSolAttr;

        solution = new Solution__c(
            Service__c = service.Id,
            Solution__c = master_solution.Id,
            BizAttribute__c = bizAttr.Id
        );
        insert solution;
        
    }
    
    @isTest public static void test_method_01(){
        Test.startTest();
        //OpportunitySolutionItemController.getSolutionOptions(service.Service__c, opport.Id, opport.CollaborationBOId__c, true, true,  OpportunityServiceSolutionMainController.INIT_SERVICE, false);
		OpportunitySolutionItemController.getSolutionOptions(service.Service__c, opport.Id, opport.CollaborationBOId__c, true, true, false);

        
        //List<String> solIdList, String solPSType, Boolean psTypeCheck, String solRecordId
        OpportunitySolutionItemController.getBizAttributeOptions(new List<String>{master_solution.Id}, 'SI', true);
        OpportunitySolutionItemController.getBizAttributeOptions(new List<String>{master_solution.Id}, '', false);
        OpportunitySolutionItemController.getSalesTypeOptions();
        Test.stopTest();
    }
    @isTest public static void test_method_02(){
        Test.startTest();
        //OpportunitySolutionItemController.getSolutionOptions(service.Service__c, opport.Id, '', false, false, OpportunityServiceSolutionMainController.NORMAL_SERVICE, true);
        OpportunitySolutionItemController.getSolutionOptions(service.Service__c, opport.Id, '', false, false, true);
        Test.stopTest();
    }
    @isTest public static void test_method_03(){
        Test.startTest();
        //OpportunitySolutionItemController.getSolutionOptions(service.Service__c, opport.Id, '', false, false, OpportunityServiceSolutionMainController.TECH_SERVICE, true);
        OpportunitySolutionItemController.getSolutionOptions(service.Service__c, opport.Id, '', false, false, true);
        Test.stopTest();
    }
    @isTest public static void test_method_04(){
        Test.startTest();
        //OpportunitySolutionItemController.getSolutionOptions(service.Service__c, opport.Id, '', false, false, OpportunityServiceSolutionMainController.TECH_SERVICE, true);
        OpportunitySolutionItemController.getSolutionduplicterecord(service.id, opport.Id, solution.BizAttribute__c, solution.Solution__c);
        Test.stopTest();
    }

}