force-app/main/default/objects/BizAttribute__c/BizAttribute__c.object-meta.xml
<CustomObject>
    <label>Biz. Attribute</label>
    <nameField>
        <label>Biz. Attribute Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Biz. Attribute</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/BizAttribute__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <label>Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Master_Solution__c/Master_Solution__c.object-meta.xml
<CustomObject>
    <label>Master Solution</label>
    <nameField>
        <label>Master Solution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Solution</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Solution__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>서비스</description>
    <label>Service</label>
    <referenceTo>Master_Service__c</referenceTo>
    <relationshipName>Solution</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Activity__c/Opportunity_Activity__c.object-meta.xml
<CustomObject>
    <label>Opportunity Activity</label>
    <nameField>
        <displayFormat>OA-{yymmdd}-{00000}</displayFormat>
        <label>Opportunity Activity No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Activity__c/fields/DueDate__c.field-meta.xml
<CustomField>
    <fullName>DueDate__c</fullName>
    <description>완료 예정일자</description>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity_Activity__c/fields/ExtID__c.field-meta.xml
<CustomField>
    <fullName>ExtID__c</fullName>
    <externalId>true</externalId>
    <label>ExtID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Activity__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <label>Canceled</label>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Activity__c/fields/TransactionName__c.field-meta.xml
<CustomField>
    <fullName>TransactionName__c</fullName>
    <label>Opportunity Activity Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>XP11</fullName>
                <label>Register BO</label>
            </value>
            <value>
                <fullName>ZP21</fullName>
                <label>Review BO</label>
            </value>
            <value>
                <fullName>ZP32</fullName>
                <label>Request Resources</label>
            </value>
            <value>
                <fullName>XP31</fullName>
                <label>Receive RFP</label>
            </value>
            <value>
                <fullName>ZP31</fullName>
                <label>Request Strategy Committee</label>
            </value>
            <value>
                <fullName>XP32</fullName>
                <label>Strategy Committee Cost Plan Completion</label>
            </value>
            <value>
                <fullName>ZP62</fullName>
                <label>Request Committee Approval</label>
            </value>
            <value>
                <fullName>ZPZ3</fullName>
                <label>Agency Contract Exception</label>
            </value>
            <value>
                <fullName>ZP61</fullName>
                <label>Submit Proposal</label>
            </value>
            <value>
                <fullName>XP41</fullName>
                <label>Presentation</label>
            </value>
            <value>
                <fullName>XP42</fullName>
                <label>Preferred Bidder</label>
            </value>
            <value>
                <fullName>XP43</fullName>
                <label>Customer Approval</label>
            </value>
            <value>
                <fullName>XP44</fullName>
                <label>Negotiation</label>
            </value>
            <value>
                <fullName>XP51</fullName>
                <label>Contract P&amp;L</label>
            </value>
            <value>
                <fullName>XP52</fullName>
                <label>Legal Review</label>
            </value>
            <value>
                <fullName>ZP82</fullName>
                <label>Contract Approval</label>
            </value>
            <value>
                <fullName>XP57</fullName>
                <label>Closing</label>
            </value>
            <value>
                <fullName>ZPZ2</fullName>
                <label>Drop Opportunity</label>
            </value>
            <value>
                <fullName>XPX1</fullName>
                <label>Abort Opportunity</label>
            </value>
            <value>
                <fullName>ZAC1</fullName>
                <label>Hold Opportunity</label>
            </value>
            <value>
                <fullName>ZPZ1</fullName>
                <label>Lost Opportunity</label>
            </value>
            <value>
                <fullName>ZAC4</fullName>
                <label>Unhold Opportunity</label>
            </value>
            <value>
                <fullName>ZPG1</fullName>
                <label>Change Approval Request</label>
            </value>
            <value>
                <fullName>2.2.1.</fullName>
                <label>Credit Assessment</label>
            </value>
            <value>
                <fullName>2.2.2.</fullName>
                <label>Request AP(APS)</label>
            </value>
            <value>
                <fullName>2.3.2.</fullName>
                <label>Bidding LBS</label>
            </value>
            <value>
                <fullName>2.3.3.</fullName>
                <label>Test Shipment</label>
            </value>
            <value>
                <fullName>2.4.5.</fullName>
                <label>Final LBS</label>
            </value>
            <value>
                <fullName>2.5.1.</fullName>
                <label>Receive Contract</label>
            </value>
            <value>
                <fullName>2.5.3.</fullName>
                <label>Rate Change LBS</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Activity__c/fields/WhatId__c.field-meta.xml
<CustomField>
    <fullName>WhatId__c</fullName>
    <description>Opportunity</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Activity</relationshipLabel>
    <relationshipName>BO_Activity</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <displayFormat>SVC-{YYYY}{MM}{00000}</displayFormat>
        <label>Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/BizAttribute__c.field-meta.xml
<CustomField>
    <fullName>BizAttribute__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Biz. Attribute</label>
    <referenceTo>BizAttribute__c</referenceTo>
    <relationshipName>BO_Service_Solution</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/BusinessType__c.field-meta.xml
<CustomField>
    <fullName>BusinessType__c</fullName>
    <label>Business Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/DeletionFlag__c.field-meta.xml
<CustomField>
    <fullName>DeletionFlag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Deletion Flag(IF)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/ItemNumber__c.field-meta.xml
<CustomField>
    <fullName>ItemNumber__c</fullName>
    <label>Item Number</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service(IF)</label>
    <referenceTo>Master_Service__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>BO_Service_Solution</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/WBSClass__c.field-meta.xml
<CustomField>
    <fullName>WBSClass__c</fullName>
    <label>WBS Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Solution__c/Solution__c.object-meta.xml
<CustomObject>
    <label>Solution(c)</label>
    <nameField>
        <displayFormat>SOL-{YYYY}{MM}{00000}</displayFormat>
        <label>Solution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Solution(c)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Solution__c/fields/BizAttribute__c.field-meta.xml
<CustomField>
    <fullName>BizAttribute__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Biz. Attribute(IF)</label>
    <referenceTo>BizAttribute__c</referenceTo>
    <relationshipLabel>Solution(c)</relationshipLabel>
    <relationshipName>Solution_c</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Solution__c/fields/BusinessType__c.field-meta.xml
<CustomField>
    <fullName>BusinessType__c</fullName>
    <label>Business Type(IF)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Solution__c/fields/DeletionFlag__c.field-meta.xml
<CustomField>
    <fullName>DeletionFlag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Deletion Flag(IF)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Solution__c/fields/ItemNumber__c.field-meta.xml
<CustomField>
    <fullName>ItemNumber__c</fullName>
    <formula>Service__r.ItemNumber__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Item Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Solution__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Solution(c)</relationshipLabel>
    <relationshipName>Solution</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Solution__c/fields/Solution__c.field-meta.xml
<CustomField>
    <fullName>Solution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Solution(IF)</label>
    <referenceTo>Master_Solution__c</referenceTo>
    <relationshipLabel>Solution(c)</relationshipLabel>
    <relationshipName>Solution_c</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Solution__c/fields/WBSClass__c.field-meta.xml
<CustomField>
    <fullName>WBSClass__c</fullName>
    <label>WBS Class(IF)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Solution__c/fields/WBSCode__c.field-meta.xml
<CustomField>
    <fullName>WBSCode__c</fullName>
    <label>WBS Code</label>
    <length>24</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WBS__c/WBS__c.object-meta.xml
<CustomObject>
    <label>WBS</label>
    <nameField>
        <label>WBS Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WBS</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/WBS__c/fields/DeletionFlag__c.field-meta.xml
<CustomField>
    <fullName>DeletionFlag__c</fullName>
    <label>Deletion Flag</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WBS__c/fields/ItemNumber__c.field-meta.xml
<CustomField>
    <fullName>ItemNumber__c</fullName>
    <description>솔루션의 Item Number</description>
    <label>Item Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WBS__c/fields/Solution__c.field-meta.xml
<CustomField>
    <fullName>Solution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Solution(c)</label>
    <referenceTo>Solution__c</referenceTo>
    <relationshipLabel>Solution(c)</relationshipLabel>
    <relationshipName>Solution</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WBS__c/fields/WBSClass__c.field-meta.xml
<CustomField>
    <fullName>WBSClass__c</fullName>
    <description>WBSClass</description>
    <formula>LEFT(Name, 2)</formula>
    <label>WBS Class</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Batch_IF040_Automation.cls
global class Batch_IF040_Automation implements DataBase.stateful, DataBase.Batchable<SObject>, DataBase.AllowsCallouts, Schedulable {
	private final String INTERFACE_ID = 'IF-040-Automation';
	private final String APEX_CLASS = 'Batch_IF040_Automation';
	private final String METHOD_NAME = 'Batch';
	//private static Map<String,String> oppId = new Map<String,String>();
	Map<Opportunity, Opportunity_Activity__c> oppId;
	List<Id> lstId;
	List<String> lstOppCode;
	Map<String, List<Solution__c>> solActiveList;

	public Date BATCH_CONDITION = null; // 배치 처리 조건

	private static final Boolean DEBUG_FLAG = false;

	private static String guId = IF_Util.generateGuid();

	public Batch_IF040_Automation() {
		oppId = new Map<Opportunity, Opportunity_Activity__c>();
		solActiveList = new Map<String, List<Solution__c>>();
		lstId = new List<Id>();
		lstOppCode = new List<String>();
	}

	public DataBase.QueryLocator start(DataBase.BatchableContext BC) {
		IF_Log ifStartLog = new IF_Log();
		IF_Log.BatchLog batchStartLog;
		List<String> startErrorMsgList = new List<String>();

		ifStartLog.addLog('#################### ' + INTERFACE_ID +' | ' + APEX_CLASS + ' | ' + METHOD_NAME + '(Start:' + BC.getJobId() + ') 시작' + ' ####################');

		String queryString;
		Database.QueryLocator returnScope;

		// 기본 쿼리 검색
		try {
			if (BATCH_CONDITION == null)
				BATCH_CONDITION = Date.today().addDays(-3); // 현재일의 기준 3일 전 데이터 처리

			queryString =
				'SELECT Id' +
				',Name' +
				',OpportunityCode__c ' +
				'FROM   MigOppCode__c ' +
				'WHERE  SystemModstamp  = Today ' +
				'AND    Send_Check__c  = false ' +
				'AND    InterfaceId__c = \'IF-040\' ';

			returnScope = DataBase.getQueryLocator(queryString);
			System.debug('returnScope MigOpp ' + returnScope);

			ifStartLog.addLog('#################### ' + INTERFACE_ID + ' | ' + APEX_CLASS + ' | ' + METHOD_NAME + '(Start:' + BC.getJobId() + ') 종료' + ' ####################');

			batchStartLog = new IF_Log.BatchLog(INTERFACE_ID, guId, APEX_CLASS, 'Start', '', 0);

			ifStartLog.createLog(batchStartLog);
		} catch (Exception e) {
			batchStartLog = new IF_Log.BatchLog(INTERFACE_ID, guId, APEX_CLASS, 'Start', '', 0, 0, e);
			startErrorMsgList.add('Batch exception : ' + e.getMessage());

			ifStartLog.addLog('#################### ' + INTERFACE_ID + ' | ' + APEX_CLASS + ' | ' + METHOD_NAME + '(Start:' + BC.getJobId() + ') 종료' + ' ####################' );

			ifStartLog.createLog(batchStartLog);
		}
		return returnScope;
	}

	public void execute(DataBase.BatchableContext BC, List<MigOppCode__c> scopeList) {
		IF_Log ifExcuteLog = new IF_Log();
		IF_Log.BatchLog batchExcuteLog;
		List<String> excuteErrorMsgList = new List<String>();
		Opportunity_Activity__c opptyAct = new Opportunity_Activity__c();
		
		Opportunity opp = [
			SELECT
				Id,
				CompanyCode__c,
				BusinessType__c,
				Opportunity_Review_VRB_Type_Confirm__c,
				CollaborationBOId__c,
				CollaborationBOId__r.BusinessType__c,
				Collaboration__c
			FROM Opportunity
			WHERE Id = :scopeList[0].Name
		];

		opptyAct = [
			SELECT
				Id,
				Name,
				Status__c,
				StartDate__c,
				DueDate__c,
				EndDate__c,
				ExtId__c,
				WhatId__c,
				WhatId__r.OpportunityCode__c,
				TransactionName__c,
				WhatId__r.CompanyCode__c,
				WhatId__r.GroupInternal__c
			FROM Opportunity_Activity__c
			WHERE WhatId__c = :scopeList[0].Name AND TransactionName__c = :OpportunityActivityHelper.ACT_CODE_REVIEW_BO
			ORDER BY CreatedDate DESC
			LIMIT 1
		];
												  
		Map<String, Object> resultMap = new Map<String, Object>();
		System.debug('Ani scopeList[0].Name ' + scopeList[0].Name);
		resultMap = IF_040_Automation.Project_WBS(scopeList[0].Name);
		System.debug('returnScope MigOpp result ' + resultMap.get('MSG'));
		String compCode = opp.CompanyCode__c;
		//System.debug('returnScope MigOpp Company Code '+ resultMap.get('Company Code'));

		List<MigOppCode__c> migOppList = new List<MigOppCode__c>();
		try {
			if (resultMap.get('MSG') == 'S' || Test.isRunningTest()) {
				migOppList = [
					SELECT Id, Name, OpportunityCode__c, Send_Check__c
					FROM MigOppCode__c
					WHERE InterfaceId__c = 'IF-040' AND Name = :scopeList[0].Name
				];

				for (MigOppCode__c migOpp : migOppList) {
					migOpp.Send_Check__c = true;
				}
				oppId.put(opp, opptyAct);
				// solActiveList.put(migOppList[0].Name , lSolList);
				lstId.add(migOppList[0].Name);
				lstOppCode.add(migOppList[0].OpportunityCode__c);
				update migOppList;
			}

			batchExcuteLog = new IF_Log.BatchLog(INTERFACE_ID, guId, APEX_CLASS, 'Execute', '', 0);
			// 로그 남기기
			ifExcuteLog.addLog('#################### ' + INTERFACE_ID + ' | ' + APEX_CLASS + ' | ' + METHOD_NAME + '(Excute:' + BC.getJobId() + ') 종료' + migOppList[0].OpportunityCode__c + ', Result -' + resultMap.get('MSG'));

			ifExcutelog.createLog(batchExcuteLog);
		} catch (Exception e) {
			ifExcuteLog.addLog('Exception : ' + e.getStackTraceString());
			excuteErrorMsgList.add('Exception : ' + e.getMessage());

			batchExcuteLog = new IF_Log.BatchLog(INTERFACE_ID, guId, APEX_CLASS, 'Excute', '', 0, 0, e);

			ifExcuteLog.addLog('#################### ' + INTERFACE_ID + ' | ' + APEX_CLASS + ' | ' + METHOD_NAME + '(Excute:' + BC.getJobId() + ') 종료' + ' ####################');

			ifExcutelog.createLog(batchExcuteLog);
		}
		
	}

	public void finish(DataBase.BatchableContext BC) {
		System.debug('Update 040 oppId' + oppId);
		System.debug('Update 040 solActiveList' + solActiveList);
		System.debug('Update 040 lstId' + lstId);
		List<Solution__c> lSol = new List<Solution__c>();
		List<Solution__c> lSolList = new List<Solution__c>();
		List<Opportunity> lstOpp = new List<Opportunity>();
		Map<Id, List<Solution__c>> mapSol = new Map<Id, List<Solution__c>>();
		lSol = [
			SELECT
				Id,
				Name,
				ItemNumber__c,
				WBSCode__c,
				Service__r.Service__r.Code__c,
				Solution__r.Code__c,
				BizAttribute__r.Code__c,
				WBSClass__c,
				DeletionFlag__c,
				BusinessType__c,
				Service__r.TechAttribute__c,
				Opportunity__c
			FROM Solution__c
			WHERE Opportunity__c IN :lstId AND SendSAP__c = TRUE
		];
		for (Solution__c sol : lSol) {
			if (!mapSol.containsKey(sol.Opportunity__c)) {
				mapSol.put(sol.Opportunity__c, new List<Solution__c>{ sol });
			} else {
				mapSol.get(sol.Opportunity__c).add(sol);
			}
		}
		System.debug('mapSol Ani' + mapSol);

		for (Id oppId : mapSol.keySet()) {
			String bizType = 'TS';
			Opportunity opp = new Opportunity();
			opp.Id = oppId;
			for (Solution__c obj : mapSol.get(oppId)) {
				if (obj.BusinessType__c == 'TI') {
					bizType = 'TI';
					break;
				} else if (obj.BusinessType__c == 'TD') {
					bizType = 'TD';
				}
			}
			opp.BusinessType__c = bizType;
			lstOpp.add(opp);
		}

		System.debug('lstOpp Ani' + lstOpp);

		if (lstOpp.Size() > 0) {
			Database.Update(lstOpp, false);
		}

		IF_040_Automation.upsertOpportunityActivity(oppId, 'Completed');
		
		IF_Log ifFinishLog = new IF_Log();
		IF_Log.BatchLog batchFinishLog;
		List<String> finishErrorMsgList = new List<String>();

		batchFinishLog = new IF_Log.BatchLog(INTERFACE_ID, guId, APEX_CLASS, 'Finish', '', 0);

		ifFinishLog.addLog('#################### ' + INTERFACE_ID + ' | ' + APEX_CLASS + ' | ' + METHOD_NAME + '(Finish:' + BC.getJobId() + ') ' + ' Opportunity BO Code List - ' + lstOppCode);

		ifFinishLog.createLog(batchFinishLog);
	}

	// 스케줄 호출
	public void execute(SchedulableContext SC) {
		DataBase.executeBatch(new Batch_IF040_Automation(), 1);
	}
}