force-app/main/default/objects/BizAttribute__c/BizAttribute__c.object-meta.xml
<CustomObject>
    <label>Biz. Attribute</label>
    <nameField>
        <label>Biz. Attribute Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Biz. Attribute</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/BizAttribute__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <label>Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Company__c/Company__c.object-meta.xml
<CustomObject>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Company</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Company__c/fields/CompanyCode__c.field-meta.xml
<CustomField>
    <fullName>CompanyCode__c</fullName>
    <description>회사코드</description>
    <label>Company Code</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Company__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AE</fullName>
                <label>United Arab Emirates</label>
            </value>
            <value>
                <fullName>AR</fullName>
                <label>Argentina</label>
            </value>
            <value>
                <fullName>AT</fullName>
                <label>Austria</label>
            </value>
            <value>
                <fullName>AU</fullName>
                <label>Australia</label>
            </value>
            <value>
                <fullName>AW</fullName>
                <label>Aruba</label>
            </value>
            <value>
                <fullName>AZ</fullName>
                <label>Azerbaijan</label>
            </value>
            <value>
                <fullName>BD</fullName>
                <label>Bangladesh</label>
            </value>
            <value>
                <fullName>BE</fullName>
                <label>Belgium</label>
            </value>
            <value>
                <fullName>BG</fullName>
                <label>Bulgaria</label>
            </value>
            <value>
                <fullName>BO</fullName>
                <label>Bolivia</label>
            </value>
            <value>
                <fullName>BR</fullName>
                <label>Brazil</label>
            </value>
            <value>
                <fullName>BY</fullName>
                <label>Belarus</label>
            </value>
            <value>
                <fullName>CA</fullName>
                <label>Canada</label>
            </value>
            <value>
                <fullName>CH</fullName>
                <label>Switzerland</label>
            </value>
            <value>
                <fullName>CL</fullName>
                <label>Chile</label>
            </value>
            <value>
                <fullName>CN</fullName>
                <label>China</label>
            </value>
            <value>
                <fullName>CO</fullName>
                <label>Colombia</label>
            </value>
            <value>
                <fullName>CR</fullName>
                <label>Costa Rica</label>
            </value>
            <value>
                <fullName>CS</fullName>
                <label>Serbia and Montenegro</label>
            </value>
            <value>
                <fullName>CW</fullName>
                <label>Curaçao</label>
            </value>
            <value>
                <fullName>CY</fullName>
                <label>Cyprus</label>
            </value>
            <value>
                <fullName>CZ</fullName>
                <label>Czech Republic</label>
            </value>
            <value>
                <fullName>DE</fullName>
                <label>Germany</label>
            </value>
            <value>
                <fullName>DK</fullName>
                <label>Denmark</label>
            </value>
            <value>
                <fullName>DM</fullName>
                <label>Dominica</label>
            </value>
            <value>
                <fullName>DO</fullName>
                <label>Dominican Republic</label>
            </value>
            <value>
                <fullName>DZ</fullName>
                <label>Algeria</label>
            </value>
            <value>
                <fullName>EC</fullName>
                <label>Ecuador</label>
            </value>
            <value>
                <fullName>EG</fullName>
                <label>Egypt</label>
            </value>
            <value>
                <fullName>ES</fullName>
                <label>Spain</label>
            </value>
            <value>
                <fullName>AI</fullName>
                <label>Anguilla</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Company__c/fields/EPCompanyCode__c.field-meta.xml
<CustomField>
    <fullName>EPCompanyCode__c</fullName>
    <description>인사 시스템 회사번호</description>
    <label>EP Company Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CostCenter__c/CostCenter__c.object-meta.xml
<CustomObject>
    <label>Cost Center</label>
    <nameField>
        <label>Cost Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cost Center</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CostCenter__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Company</label>
    <referenceTo>Company__c</referenceTo>
    <relationshipLabel>Cost Center</relationshipLabel>
    <relationshipName>Cost_Center</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CostCenter__c/fields/CompanyCode__c.field-meta.xml
<CustomField>
    <fullName>CompanyCode__c</fullName>
    <label>Company Code</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CostCenter__c/fields/CostCenter__c.field-meta.xml
<CustomField>
    <fullName>CostCenter__c</fullName>
    <externalId>true</externalId>
    <label>Cost Center</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/EvEmpNO__c.field-meta.xml
<CustomField>
    <fullName>EvEmpNO__c</fullName>
    <label>Employee Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/EvMailAddr__c.field-meta.xml
<CustomField>
    <fullName>EvMailAddr__c</fullName>
    <label>Email</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/EvUniqID__c.field-meta.xml
<CustomField>
    <fullName>EvUniqID__c</fullName>
    <externalId>true</externalId>
    <label>EP ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Service__c/Master_Service__c.object-meta.xml
<CustomObject>
    <label>Master Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Service</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Service__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <externalId>true</externalId>
    <label>Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <displayFormat>SVC-{YYYY}{MM}{00000}</displayFormat>
        <label>Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>BO_Service_Solution</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Solution__c/Solution__c.object-meta.xml
<CustomObject>
    <label>Solution(c)</label>
    <nameField>
        <displayFormat>SOL-{YYYY}{MM}{00000}</displayFormat>
        <label>Solution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Solution(c)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Solution__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Solution(c)</relationshipLabel>
    <relationshipName>Solution_c</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TriggerSwitch__c/TriggerSwitch__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>TriggerSwitch</label>
</CustomObject>

force-app/main/default/objects/TriggerSwitch__c/fields/All__c.field-meta.xml
<CustomField>
    <fullName>All__c</fullName>
    <defaultValue>true</defaultValue>
    <label>All</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerSwitch__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Event</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerSwitch__c/fields/Migration__c.field-meta.xml
<CustomField>
    <fullName>Migration__c</fullName>
    <defaultValue>false</defaultValue>
    <description>해당 필드가 체크되어있는 경우 마이그 로직을 실행하지않음</description>
    <label>Migration</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerSwitch__c/fields/OpportunityActivity__c.field-meta.xml
<CustomField>
    <fullName>OpportunityActivity__c</fullName>
    <defaultValue>true</defaultValue>
    <label>OpportunityActivity</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerSwitch__c/fields/OpportunityBizLvSetting__c.field-meta.xml
<CustomField>
    <fullName>OpportunityBizLvSetting__c</fullName>
    <defaultValue>true</defaultValue>
    <label>OpportunityBizLvSetting</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerSwitch__c/fields/OpportunityCodeSetting__c.field-meta.xml
<CustomField>
    <fullName>OpportunityCodeSetting__c</fullName>
    <defaultValue>true</defaultValue>
    <label>OpportunityCodeSetting</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerSwitch__c/fields/OpportunityDeleteSetting__c.field-meta.xml
<CustomField>
    <fullName>OpportunityDeleteSetting__c</fullName>
    <defaultValue>true</defaultValue>
    <label>OpportunityDeleteSetting</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerSwitch__c/fields/OpportunityLogisticsValidation__c.field-meta.xml
<CustomField>
    <fullName>OpportunityLogisticsValidation__c</fullName>
    <defaultValue>true</defaultValue>
    <description>레코드 타입 Logistics 유효성 트리거</description>
    <label>OpportunityLogisticsValidation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerSwitch__c/fields/OpportunitySendToSAP__c.field-meta.xml
<CustomField>
    <fullName>OpportunitySendToSAP__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Opportunity 작성/수정/삭제 시 SAP 정보 전송 여부</description>
    <inlineHelpText>Opportunity 작성/수정/삭제 시 SAP 정보 전송 여부</inlineHelpText>
    <label>OpportunitySendToSAP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerSwitch__c/fields/RevenueScheduleOpportunity__c.field-meta.xml
<CustomField>
    <fullName>RevenueScheduleOpportunity__c</fullName>
    <defaultValue>false</defaultValue>
    <label>RevenueScheduleOpportunity</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerSwitch__c/fields/WeeklyReportSend__c.field-meta.xml
<CustomField>
    <fullName>WeeklyReportSend__c</fullName>
    <defaultValue>true</defaultValue>
    <label>WeeklyReportSend</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Batch_MigrationForTA_Test.cls
@isTest
public class Batch_MigrationForTA_Test {
    @TestSetup
    static void setup(){
        // [S] Custom Setting
        TriggerSwitch__c ts = new TriggerSwitch__c(
            All__c                              = true,
            Event__c                            = true,
            Migration__c                        = true,
            Opportunity__c                      = true,
            OpportunityActivity__c              = true,
            OpportunityBizLvSetting__c          = true,
            OpportunityCodeSetting__c           = true,
            OpportunityDeleteSetting__c         = false,
            OpportunityLogisticsValidation__c   = false,
            OpportunitySendToSAP__c             = false,
            RevenueScheduleOpportunity__c       = false,
            WeeklyReportSend__c                 = false
        );
        insert ts;
        // [E] Custom Setting

        // [S] User Insert
        List<User> userList = new List<User>();
        
        Profile profile_Admin = [SELECT id FROM Profile WHERE name = 'System Administrator' OR name = '시스템 관리자'];
        User user_Admin = new User(
            Alias                   = 'Admin', 
            Email                   = 'admin@samsung.com', 
            EmailEncodingKey        = 'UTF-8', 
            LastName                = 'Admin', 
            LanguageLocaleKey       = 'en_US', 
            LocaleSidKey            = 'ko_KR', 
            ProfileId               = profile_Admin.Id, 
            TimeZoneSidKey          = 'Asia/Seoul', 
            UserName                = 'admin@samsung.com.test', 
            EmployeeNumber          = '111111', 
            FederationIdentifier    = 'admin111111'
        );
        userList.add(user_Admin);

        Profile profile_SalesRep = [SELECT Id FROM Profile WHERE Name = 'Sales Rep.(HQ)'];
        User user_salesRep1 = new User(
            Alias                   = 'sr1', 
            Email                   = 'sr1@samsung.com', 
            EmailEncodingKey        = 'UTF-8', 
            LastName                = 'sr1', 
            LanguageLocaleKey       = 'en_US', 
            LocaleSidKey            = 'ko_KR', 
            ProfileId               = profile_SalesRep.Id, 
            TimeZoneSidKey          = 'Asia/Seoul', 
            UserName                = 'sr1@samsung.com.test', 
            EmployeeNumber          = '222222', 
            FederationIdentifier    = 'sales222222'
        );
        userList.add(user_salesRep1);

        User user_salesRep2 = new User(
            Alias                   = 'sr2', 
            Email                   = 'sr2@samsung.com', 
            EmailEncodingKey        = 'UTF-8', 
            LastName                = 'sr2', 
            LanguageLocaleKey       = 'en_US', 
            LocaleSidKey            = 'ko_KR', 
            ProfileId               = profile_SalesRep.Id, 
            TimeZoneSidKey          = 'Asia/Seoul', 
            UserName                = 'sr2@samsung.com.test', 
            EmployeeNumber          = '222222', 
            FederationIdentifier    = 'sales222222'
        );
        userList.add(user_salesRep2);

        insert userList;
        // [E] User Insert

        // [S] Employee Insert
        Employee__c emp_Admin = new Employee__c(
            Name            = 'Admin',
            EvMailAddr__c   = 'admin@samsung.com',
            EvUniqID__c     = 'admin111111',            
            EvEmpNO__c      = '111111'
        );
        insert emp_Admin;
        // [E] Employee Insert

        // [S] Company Insert
        List<Company__c> compList = new List<Company__c>();

        Company__c comp_asis1 = new Company__c (
            Name              = 'SDSLA', 
            CompanyCode__c    = 'T801', 
            EPCompanyCode__c  = 'C6L', 
            Country__c        = 'BR'
        );
        compList.add(comp_asis1);

        Company__c comp_tobe1 = new Company__c (
            Name              = 'SDSLA_SL', 
            CompanyCode__c    = 'T815', 
            EPCompanyCode__c  = 'C6L', 
            Country__c        = 'BR'
        );
        compList.add(comp_tobe1);

        insert compList;
        // [E] Company Insert

        // [S] Cost Center Insert
        List<CostCenter__c> ccList = new List<CostCenter__c>();

        CostCenter__c costCenter_asis1 = new CostCenter__c(
            Name            = '[CLSD]Solution Deli', 
            CostCenter__c   = 'T801-10070',
            Company__c      =  comp_asis1.Id,
            CompanyCode__c  = 'T801'
        );
        ccList.add(costCenter_asis1);

        CostCenter__c costCenter_tobe1 = new CostCenter__c(
            Name            = 'Pricing Group',
            CostCenter__c   = 'T815-10040',
            Company__c      =  comp_tobe1.Id,
            CompanyCode__c  = 'T815'
        );
        ccList.add(costCenter_tobe1);

        CostCenter__c costCenter_tobe2 = new CostCenter__c(
            Name            = 'Support Team', 
            CostCenter__c   = 'T815-10041',
            Company__c      =  comp_tobe1.Id,
            CompanyCode__c  = 'T815'
        );
        ccList.add(costCenter_tobe2);

        insert ccList;
        // [E] Cost Center Insert
            
        // [S] Account Insert
        Account account = new Account(
            Name            = 'Test Account',
            AccountNumber   = '123123',
            MDGCheck__c     = true
        );
        insert account;
        // [E] Account Insert

        // [S] Opportunity Insert
        Date today = System.today();
        Date revenueStartDate = today.addDays(1);
        Date revenueEndDate = today.addDays(10);
        Opportunity oppty = new Opportunity(
            Name                        = 'Test Oppty',
            CloseDate                   = System.today(),
            StageName                   = 'Z01',
            SalesDepartment__c          = costCenter_asis1.Id,
            cPrimarySalesDepartment__c  = costCenter_asis1.Id,
            OpportunityCode__c          = 'SDS-20000010',
            cOriginAcc__c               = account.Id,
            ProposalPM__c               = emp_Admin.Id,
            BusinessLevel__c            = 'C',
            cRevenueStartDate__c        = revenueStartDate,
            cRevenueEndDate__c          = revenueEndDate,
            BiddingMethod__c            = 'BID001',
            Amount                      = 11000
        );
        insert oppty;
        // [E] Opportunity Insert

        // [S] Master Service Insert
        Master_Service__c master_service = new Master_Service__c(
            Name        = 'AI',
            Code__c     = '22000003'
        );
        insert master_service;
        // [E] Master Service Insert

        // [S] Master Solution Insert
        Master_Solution__c master_solution = new Master_Solution__c(
            Name                = 'Test Master Solution',
            Code__c             = '32000069',
            SolutionType__c     = '30'
        );
        insert master_solution;
        // [E] Master Solution Insert

        // [S] Biz Attribute Insert
        BizAttribute__c bizAttr = new BizAttribute__c (
            Name        = 'Technical Support', 
            Active__c   = true, 
            Code__c     = 'S149'
        );
        insert bizAttr;
        // [E] Biz Attribute Insert

        // [S] Service Insert
        Service__c service = new Service__c(
            Opportunity__c          = oppty.Id,
            Service__c = master_service.Id,
            SendSAP__c = True
        );

        insert service;
        // [E] Service Insert

        // [S] Solution Insert
        Solution__c solution = new Solution__c(
            Opportunity__c          = oppty.Id,
            Service__c              = service.Id,
            Solution__c             = master_solution.Id,
            sSolution__c            = master_solution.Id
        );
        insert solution;
        // [E] Solution Insert
        
        // [S] WBS Insert
        WBS__c wbs = new WBS__c(
            OpportunityID__c = oppty.Id,
            Solution__c = solution.Id,
            Name = '12345678912345678',
            ItemNumber__c = '10',
            ServiceCode__c = '22000003'
        );
        insert wbs;
        // [E] WBS Insert
    }
    
    @isTest
    static void testBatch() {
        Test.startTest();
        Database.executeBatch(new Batch_MigrationForTA(), 100);
        Test.stopTest();
    }
}