force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/EvMailAddr__c.field-meta.xml
<CustomField>
    <fullName>EvMailAddr__c</fullName>
    <label>Email</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/EvUniqID__c.field-meta.xml
<CustomField>
    <fullName>EvUniqID__c</fullName>
    <externalId>true</externalId>
    <label>EP ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KnoxEmail__c/KnoxEmail__c.object-meta.xml
<CustomObject>
    <label>Knox Email</label>
    <nameField>
        <label>Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>KnoxEmail</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KnoxEmail__c/fields/BccAddress__c.field-meta.xml
<CustomField>
    <fullName>BccAddress__c</fullName>
    <label>Bcc Address</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/KnoxEmail__c/fields/CcAddress__c.field-meta.xml
<CustomField>
    <fullName>CcAddress__c</fullName>
    <label>Cc Address</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/KnoxEmail__c/fields/MailId__c.field-meta.xml
<CustomField>
    <fullName>MailId__c</fullName>
    <label>Mail Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KnoxEmail__c/fields/ToAddress__c.field-meta.xml
<CustomField>
    <fullName>ToAddress__c</fullName>
    <label>To Address</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/KnoxEmailCancelController_Test.cls
/**
 * @description       : 
 * @author            : soohong0.kim@partner.samsung.com
 * @group             : 
 * @last modified on  : 01-21-2021
 * @last modified by  : soohong0.kim@partner.samsung.com
 * Modifications Log 
 * Ver   Date         Author                             Modification
 * 1.0   01-21-2021   soohong0.kim@partner.samsung.com   Initial Version
**/

@isTest
public class KnoxEmailCancelController_Test {

    @TestSetup
    static void setData(){
        KnoxEmail__c email = new KnoxEmail__c();
        email.ToAddress__c = 'test@test.com';
        email.CcAddress__c = 'test@test.com';
        email.BccAddress__c = 'test@test.com';
        email.MailId__c = 'test';
        insert email;

        Employee__c emp1 = Utils_TestDataFactory.createEmployee('TestEmp1', 'EPID1');

        User salesRepHqUser1 = Utils_TestDataFactory.createUserFull(
                Utils_TestDataFactory.getProfile('Sales Rep.(HQ)')
                , emp1.EvMailAddr__c
                , emp1.EvUniqID__c);
    }

    private static testMethod void KnoxEmailCancelController_Test() {

        Test.startTest();
        Test.setMock( HttpCalloutMock.class, new IF_Callout_TestMock());
        User salesRepHqUser1 = [select id, FederationIdentifier from User where FederationIdentifier = 'EPID1' limit 1];
        
        System.runAs(salesRepHqUser1) {
            Map<String, Object> paramMap = new Map<String,Object>();
            KnoxEmail__c obj = [select id, ToAddress__c, CcAddress__c, BccAddress__c, MailId__c from KnoxEmail__c where MailId__c = 'test' limit 1];
            paramMap.put('KnoxEmail__c',obj);

            KnoxEmailCancelController.cancelKnoxEmail(JSON.serialize(paramMap));        
        }
        
    
        Test.stopTest();
    }


}