force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Retirement status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>B</fullName>
                <label>재직</label>
            </value>
            <value>
                <fullName>V</fullName>
                <label>휴직</label>
            </value>
            <value>
                <fullName>R</fullName>
                <label>퇴사</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Batch_Employee_Deletion_Test.cls
/**
* @description       : Test Class for Batch_Employee_Deletion
* @author            : waris.m@samsung.com
* @group             : 
* @last modified on  : 2024-03-07
* @last modified by  : waris.m@samsung.com 
* Modifications Log 
* Ver   Date         Author                      Modification
* 1.0   2024-03-07   waris.m@samsung.com          MYSALES-455
**/
@isTest
public class Batch_Employee_Deletion_Test {
    @isTest
    static void batchTest()
    {
      Employee__c emp1= new Employee__c();
      emp1.Name='Test Employee1';
      emp1.Status__c='R';
      insert emp1;
      Test.startTest();
      Batch_Employee_Deletion batch1= new Batch_Employee_Deletion();
      Id batchID = Database.executeBatch(batch1);
      Test.stopTest();
      
    }
}