force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/MSP_Project__c/MSP_Project__c.object-meta.xml
<CustomObject>
    <label>SCP Project</label>
    <nameField>
        <label>Project ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SCP Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MSP_Project__c/fields/Contract_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Start_Date__c</fullName>
    <formula>SCP_Account_ID__r.Contract_Start_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contract Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/MSP_Project__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <formula>HYPERLINK( SCP_Account_ID__r.Customer__r.Id , SCP_Account_ID__r.Customer__r.Name , &quot;_self&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MSP_Project__c/fields/Estimated_Monthly_Fee_Won__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Monthly_Fee_Won__c</fullName>
    <label>Estimated Monthly Fee</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/MSP_Project__c/fields/Incentive__c.field-meta.xml
<CustomField>
    <fullName>Incentive__c</fullName>
    <formula>TEXT( SCP_Account_ID__r.Incentive__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Incentive</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MSP_Project__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <formula>HYPERLINK( SCP_Account_ID__r.Partner__r.Id , SCP_Account_ID__r.Partner__r.Name , &quot;_self&quot; )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Partner</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MSP_Project__c/fields/Partner_AM__c.field-meta.xml
<CustomField>
    <fullName>Partner_AM__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Partner AM</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipName>MSP_Projects</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MSP_Project__c/fields/Partner_PM__c.field-meta.xml
<CustomField>
    <fullName>Partner_PM__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Partner PM</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipName>MSP_Projects1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MSP_Project__c/fields/SCP_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>SCP_Account_ID__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>SCP Account ID</label>
    <referenceTo>SCP_Account__c</referenceTo>
    <relationshipName>MSP_Projects</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MSP_Project__c/fields/SDS_AM__c.field-meta.xml
<CustomField>
    <fullName>SDS_AM__c</fullName>
    <formula>HYPERLINK( SCP_Account_ID__r.SDS_AM__c , SCP_Account_ID__r.SDS_AM__r.EvHName__c , &quot;_self&quot; )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SDS AM</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MSP_Project__c/fields/SDS_PDM__c.field-meta.xml
<CustomField>
    <fullName>SDS_PDM__c</fullName>
    <formula>HYPERLINK( SCP_Account_ID__r.SDS_PDM__c , SCP_Account_ID__r.SDS_PDM__r.EvHName__c , &quot;_self&quot; )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SDS PDM</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SCP_Account__c/SCP_Account__c.object-meta.xml
<CustomObject>
    <label>SCP Account</label>
    <nameField>
        <label>SCP Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SCP Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SCP_Account__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Customer</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>MDG check must equal true</errorMessage>
        <filterItems>
            <field>Account.MDGCheck__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SCP Accounts</relationshipLabel>
    <relationshipName>SCP_Accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SCP_Account__c/fields/Incentive__c.field-meta.xml
<CustomField>
    <fullName>Incentive__c</fullName>
    <label>Incentive</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SCP_Account__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SCP Accounts (Partner)</relationshipLabel>
    <relationshipName>SCP_Accounts1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SCP_Account__c/fields/SCP_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>SCP_Account_ID__c</fullName>
    <label>SCP Account ID</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SCP_Account__c/fields/SDS_AM__c.field-meta.xml
<CustomField>
    <fullName>SDS_AM__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>SDS AM</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>SCP Accounts</relationshipLabel>
    <relationshipName>SCP_Accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SCP_Account__c/fields/SDS_PDM__c.field-meta.xml
<CustomField>
    <fullName>SDS_PDM__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>SDS PDM</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>SCP Accounts (SDS PDM)</relationshipLabel>
    <relationshipName>SCP_Accounts1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SCP_Account__c/fields/WBS_Code__c.field-meta.xml
<CustomField>
    <fullName>WBS_Code__c</fullName>
    <label>WBS Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CustomRelatedListController_Test.cls
/**
 * @description       : Test Class for CustomRelatedListController
 * @author            : gitesh.s@samsung.com
 * @group             : 
 * @last modified on  : 20-12-2022
 * @last modified by  : gitesh.s@smsung.com
 * Modifications Log 
 * Ver   Date         Author                 Modification
 * 1.0   20-12-2022   gitesh.s@samsung.com   Initial Version
**/
@isTest
private class CustomRelatedListController_Test {
    static SCP_Account__c SCP_Acc;
    static MSP_Project__c MSP_Proj;
    static Account acc;
    static Employee__c emp;

    static {
        acc = new Account(Name = 'Test Account', MDGCheck__c = true);
        insert acc;
        acc.IsPartner = true;
        update acc;
        emp = new Employee__c(Name = 'Test Employee');
        insert emp;
        Date currentDate = System.today();
        Date nextDate = currentDate.addDays(1);
        SCP_Acc = new SCP_Account__c(SCP_Account_ID__c = 'ACCOUNT-12345', Name = 'Test Name',
                                    Customer__c = acc.Id, Contract_Start_Date__c = currentDate,
                                    WBS_Code__c = '1234', Partner__c = acc.Id,
                                    SDS_AM__c = emp.Id, SDS_PDM__c = emp.Id,  Incentive__c = 'Y');
        insert SCP_Acc;
        MSP_Proj = new MSP_Project__C(SCP_Account_ID__c = SCP_Acc.Id,
                                     Name = 'PROJECT-1234', Project_Name__c = 'Test Project Name',
                                     Estimated_Monthly_Fee_Won__c = 100, Partner_AM__c = emp.Id,
                                     Partner_PM__c = emp.Id);
        insert MSP_Proj;
    }
    
    @isTest
    static void getObjectName_Test() {
        Test.startTest();
        CustomRelatedListController.getObjectName(SCP_Acc.Id);
        Test.stopTest();
    }

    @isTest
    static void getCurrentRecord_Test() {
        Test.startTest();
        CustomRelatedListController.getCurrentRecord(SCP_Acc.Id);
        Test.stopTest();
    }

    @isTest
    static void getRelatedRecords_Test() {
        Test.startTest();
        CustomRelatedListController.getRelatedRecords(SCP_Acc.Id);
        Test.stopTest();
    }

    @isTest
    static void getMSPRecord_Test() {
        Test.startTest();
        CustomRelatedListController.getMSPRecord(MSP_Proj.Id);
        Test.stopTest();
    }

    @isTest
    static void deleteMSPRecord_Test() {
        Test.startTest();
        CustomRelatedListController.deleteMSPRecord(MSP_Proj.Id);
        Test.stopTest();
    }

    @isTest
    static void checkApprovalStatus_Test() {
        Test.startTest();
        CustomRelatedListController.checkApprovalStatus(SCP_Acc.Id);
        Test.stopTest();
    }

    @isTest
    static void getProfileInfo_Test() {
        Test.startTest();
        CustomRelatedListController.getProfileInfo();
        Test.stopTest();
    }
}