force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SCP_Account__c/SCP_Account__c.object-meta.xml
<CustomObject>
    <label>SCP Account</label>
    <nameField>
        <label>SCP Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SCP Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SCP_Account__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Customer</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>MDG check must equal true</errorMessage>
        <filterItems>
            <field>Account.MDGCheck__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SCP Accounts</relationshipLabel>
    <relationshipName>SCP_Accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SCP_Account__c/fields/Incentive__c.field-meta.xml
<CustomField>
    <fullName>Incentive__c</fullName>
    <label>Incentive</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SCP_Account__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SCP Accounts (Partner)</relationshipLabel>
    <relationshipName>SCP_Accounts1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SCP_Account__c/fields/SCP_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>SCP_Account_ID__c</fullName>
    <label>SCP Account ID</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SCP_Account__c/fields/SDS_AM__c.field-meta.xml
<CustomField>
    <fullName>SDS_AM__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>SDS AM</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>SCP Accounts</relationshipLabel>
    <relationshipName>SCP_Accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SCP_Account__c/fields/SDS_PDM__c.field-meta.xml
<CustomField>
    <fullName>SDS_PDM__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>SDS PDM</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>SCP Accounts (SDS PDM)</relationshipLabel>
    <relationshipName>SCP_Accounts1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SCP_Account__c/fields/WBS_Code__c.field-meta.xml
<CustomField>
    <fullName>WBS_Code__c</fullName>
    <label>WBS Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SCPAccountSharing_Test.cls
/**
 * @description       : 
 * @author            : gitesh.s@samsung.com
 * @group             : 
 * @last modified on  : 20-01-2023
 * @last modified by  : gitesh.s@samsung.com
 * Modifications Log 
 * Ver   Date         Author                  Modification
 * 1.0   20-01-2023   gitesh.s@samsung.com    Initial Version
**/
@isTest
private class SCPAccountSharing_Test {

    static User user;
    static SCP_Account__c scpAcc;
    static Contact con;
    static Employee__c emp;
    static Account acc;
    static SCP_Account__Share partnerShare;
    static {
        acc = new Account(Name = 'Test', MDGCheck__c = true);
        insert acc;
        acc.IsPartner = true;
        update acc;

        con = new Contact(LastName='Test', FirstName='User', AccountId = acc.Id);
        insert con;

        Profile profile = [SELECT Id FROM Profile WHERE Name = 'Partner Community Manager'];

        user = new User(LastName = 'User', Email = 'user0001@samsung.com', Username = 'user0001@samsung.com',
                        Alias = 'test', ProfileId = profile.Id, TimeZoneSidKey = 'Asia/Seoul',
                        LocaleSidKey = 'en_US', EmailEncodingKey = 'UTF-8', LanguageLocaleKey = 'en_US', ContactId = con.Id);
        insert user;

        emp = new Employee__c(Name = 'Test Employee');
        insert emp;

        Date currentDate = System.today();
        Date nextDate = currentDate.addDays(1);

        scpAcc = new SCP_Account__c(SCP_Account_ID__c = 'ACCOUNT-12345', Name = 'Test Name',
                                    Customer__c = acc.Id, Contract_Start_Date__c = currentDate,
                                    WBS_Code__c = '1234', Partner__c = acc.Id,
                                    SDS_AM__c = emp.Id, SDS_PDM__c = emp.Id, Incentive__c = 'Y');
        insert scpAcc;
        
        partnerShare = new SCP_Account__Share(ParentId = scpAcc.Id, UserOrGroupId = user.Id, AccessLevel = 'read');
        insert partnerShare;
    }
    
    @isTest
    public static void sharingTestMethod() {
        Test.startTest();
        List<SCP_Account__Share> accountShare = [SELECT Id, UserOrGroupId, AccessLevel, RowCause FROM SCP_Account__Share WHERE ParentId =: partnerShare.ParentId AND UserOrGroupId =: partnerShare.UserOrGroupId];
        Test.stopTest();
    }
}