force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/EvMailAddr__c.field-meta.xml
<CustomField>
    <fullName>EvMailAddr__c</fullName>
    <label>Email</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/EvUniqID__c.field-meta.xml
<CustomField>
    <fullName>EvUniqID__c</fullName>
    <externalId>true</externalId>
    <label>EP ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Knox_Id__c.field-meta.xml
<CustomField>
    <fullName>Knox_Id__c</fullName>
    <label>Knox_Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Lead__c/Sales_Lead__c.object-meta.xml
<CustomObject>
    <label>Sales Lead</label>
    <nameField>
        <label>Sales Lead Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Leads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Lead__c/fields/CustomerContactDate__c.field-meta.xml
<CustomField>
    <fullName>CustomerContactDate__c</fullName>
    <label>Customer Contact Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Sales_Lead__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lead ID</description>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipName>BO_Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Lead__c/fields/LeadChannel__c.field-meta.xml
<CustomField>
    <fullName>LeadChannel__c</fullName>
    <label>Lead Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Direct Registration</fullName>
            </value>
            <value>
                <fullName>Marketing Lead Converted</fullName>
            </value>
            <value>
                <fullName>Demand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Lead__c/fields/LeadDescription__c.field-meta.xml
<CustomField>
    <fullName>LeadDescription__c</fullName>
    <description>Marketing Lead&apos;s Description</description>
    <label>Marketing Lead Description</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Sales_Lead__c/fields/LeadStage__c.field-meta.xml
<CustomField>
    <fullName>LeadStage__c</fullName>
    <description>Lead Stage</description>
    <label>Lead Stage</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cold</fullName>
                <color>#33CCFF</color>
                <label>Cold</label>
            </value>
            <value>
                <fullName>Warm</fullName>
                <color>#FF9900</color>
                <label>Warm</label>
            </value>
            <value>
                <fullName>Hot</fullName>
                <color>#FF0000</color>
                <label>Hot</label>
            </value>
            <value>
                <fullName>Converted</fullName>
                <color>#BBBBBB</color>
                <label>Converted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Lead__c/fields/PersonalInfoAgreement__c.field-meta.xml
<CustomField>
    <fullName>PersonalInfoAgreement__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Personal Info. Agreement</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sales_Lead__c/fields/PersonalInfoAgreementExpireDate__c.field-meta.xml
<CustomField>
    <fullName>PersonalInfoAgreementExpireDate__c</fullName>
    <label>Personal Info. Agreement Expire Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Sales_Lead__c/fields/Sales_Alert_Date__c.field-meta.xml
<CustomField>
    <fullName>Sales_Alert_Date__c</fullName>
    <label>Sales Alert Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Sales_Lead__c/recordTypes/Logistics.recordType-meta.xml
<RecordType>
    <fullName>Logistics</fullName>
    <active>true</active>
    <label>Logistics</label>
</RecordType>

force-app/main/default/classes/Batch_SalesLeadEmail_Test.cls
/**
 * @description       : 
 * @author            : yeongju.baek@dkbmc.com
 * @group             : 
 * @last modified on  : 12-02-2021
 * @last modified by  : zenith21c@test.com
 * Modifications Log 
 * Ver   Date         Author                   Modification
 * 1.0   07-29-2021   yeongju.baek@dkbmc.com   Initial Version
 * 1.1   11-31-2022   anish.jain@partner.samsung.com  Coverage for DeptHead Notification.
**/
@isTest
public class Batch_SalesLeadEmail_Test {
    static Lead l1;
    static Lead l2;
    static User sander;
    static Employee__c sanderEmp;
    static User owner;
    static Employee__c ownerEmp;
    static Datetime deadline = Datetime.now().addDays(-2);
    static Profile pf = [SELECT Id FROM Profile WHERE Name = 'System Administrator' OR Name = '시스템 관리자' LIMIT 1];
    static String recordTypeId = String.valueOf([SELECT Id FROM RecordType WHERE DeveloperName = 'Logistics' AND SobjectType = 'Opportunity' LIMIT 1].Id);
    static Sales_Lead__c sl1;
    static Sales_Lead__c sl2;
    static Sales_Lead__c sl3;

    static {
        
        l1 = new Lead(LastName = 'TestLead', 
                      //PersonalInfoAgreementExpireDate__c = Date.today(), 
                      PersonalInfoAgreement__c = true, 
                      Company='TestCompany');
        insert l1;

        l2 = new Lead(LastName = 'TestLead', 
                      //PersonalInfoAgreementExpireDate__c = Date.today(), 
                      PersonalInfoAgreement__c = true, 
                      Company='TestCompany');
        insert l2;

        

        owner = new User(
            Alias = 'testUser',
            Email='SysAdminTestuser@dkbmc.com',
            EmailEncodingKey='UTF-8',
            LastName='Testing',
            LanguageLocaleKey='en_US',
            LocaleSidKey='en_US',
            EmployeeNumber='k123456789',
            TimeZoneSidKey='Asia/Seoul',
            UserName='SysAdminTestuser@samsung.com',
            ProfileId = pf.Id,
            FederationIdentifier = 'k123456789'
        );
        insert owner;

        ownerEmp = new Employee__c(
            Name = 'testUser',
            EvMailAddr__c = 'SysAdminTestuser@samsung.com',
            EvUniqID__c = 'k123456789',
            Knox_Id__c = 'knoxId5'
        );
        insert ownerEmp;

        List<Sales_Lead__c> salesLeadList = new List<Sales_Lead__c>();
        sl1 = new Sales_Lead__c(
            Name = 'TestSalesLead1',
            OwnerId = owner.Id,
            LeadDescription__c = 'TEstDescription\n TEstDescription',
            CreatedDate = Datetime.now().addDays(-3),
            Sales_Alert_Date__c = null,
            CustomerContactDate__c = null,
            Lead__c = l1.Id ,
            LeadStage__c = 'Warm',
            LeadChannel__c= 'Marketing Lead Converted' //Added by Anish - v 1.1
        );
        salesLeadList.add(sl1); 

       sl2 = new Sales_Lead__c(
            Name = 'TestSalesLead2',
            OwnerId = owner.Id,
            LeadDescription__c = 'TEstDescription',
            CreatedDate = Datetime.now().addDays(-2),
            Sales_Alert_Date__c = deadline,
            CustomerContactDate__c = null,
            Lead__c = l2.Id,
            LeadStage__c = 'Warm',
            LeadChannel__c= 'Marketing Lead Converted' //Added by Anish - v 1.1
        );
        salesLeadList.add(sl2); 

       sl3 = new Sales_Lead__c(
            Name = 'TestSalesLead3',
            OwnerId = owner.Id,
            LeadDescription__c = 'TEstDescription',
            CreatedDate = deadline,
            Sales_Alert_Date__c = null,
            CustomerContactDate__c = null,
            Lead__c = null,
            LeadStage__c = 'Warm'
        );
        salesLeadList.add(sl3);
        insert salesLeadList;

        
    }
    @isTest
    public static void Test_Batch_SalesLeadEmail(){
        Test.startTest();
        DataBase.executeBatch( new Batch_SalesLeadEmail(), 10);
        Test.stopTest();
    }
    @isTest
    public static void Test_Batch_SalesLeadEmail2(){
        Test.startTest();
        DataBase.executeBatch( new Batch_SalesLeadEmail(new Set<Id>{sl1.Id}), 10);
        Test.stopTest();
    }

    @isTest
    public static void Test_Shcedule(){
        Test.startTest();
        System.schedule('Test','0 0 4 * * ? *', new Batch_SalesLeadEmail());
        Test.stopTest();
    }

    @isTest
    public static void Test_Batch_SalesLeadEmail3(){
        Test.startTest();
        Set<Id> testIdSet = new Set<Id>();
        testIdSet.add('a0P1s000001s5R5EAI');
        Batch_SalesLeadEmail b = new Batch_SalesLeadEmail(testIdSet);
        Id ttt = Database.executeBatch(b, 1);
        Test.stopTest();
    }
}