force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/EvEmpNO__c.field-meta.xml
<CustomField>
    <fullName>EvEmpNO__c</fullName>
    <label>Employee Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/EvSapBukrs__c.field-meta.xml
<CustomField>
    <fullName>EvSapBukrs__c</fullName>
    <label>Company Code</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Knox_Server_Location__c.field-meta.xml
<CustomField>
    <fullName>Knox_Server_Location__c</fullName>
    <label>Knox Server Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>KR</fullName>
                <default>true</default>
                <label>KR</label>
            </value>
            <value>
                <fullName>GB</fullName>
            </value>
            <value>
                <fullName>US</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Retirement status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>B</fullName>
                <label>재직</label>
            </value>
            <value>
                <fullName>V</fullName>
                <label>휴직</label>
            </value>
            <value>
                <fullName>R</fullName>
                <label>퇴사</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KnoxApproval__c/KnoxApproval__c.object-meta.xml
<CustomObject>
    <label>Knox Approval</label>
    <nameField>
        <label>Knox Approval Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Knox Approval</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KnoxApproval__c/fields/MISID__c.field-meta.xml
<CustomField>
    <fullName>MISID__c</fullName>
    <description>Interface : ExternalKey 옵션 지정</description>
    <externalId>true</externalId>
    <label>MISID</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KnoxApproval__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Knox Approval</relationshipLabel>
    <relationshipName>Knox_Approval</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KnoxApproval__c/fields/OpportunityActivity__c.field-meta.xml
<CustomField>
    <fullName>OpportunityActivity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Activity</label>
    <referenceTo>Opportunity_Activity__c</referenceTo>
    <relationshipLabel>Knox Approval</relationshipLabel>
    <relationshipName>KnoxApproval</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KnoxApproval__c/fields/syncFlag__c.field-meta.xml
<CustomField>
    <fullName>syncFlag__c</fullName>
    <defaultValue>&quot;N&quot;</defaultValue>
    <label>syncFlag</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KnoxApprover__c/KnoxApprover__c.object-meta.xml
<CustomObject>
    <label>Knox Approver</label>
    <nameField>
        <label>Knox Approver Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Knox Approver</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/KnoxApprover__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Knox Approver</relationshipLabel>
    <relationshipName>Knox_Approver</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KnoxApprover__c/fields/KnoxApproval__c.field-meta.xml
<CustomField>
    <fullName>KnoxApproval__c</fullName>
    <label>Knox Approval</label>
    <referenceTo>KnoxApproval__c</referenceTo>
    <relationshipLabel>Knox Approver</relationshipLabel>
    <relationshipName>Knox_Approver</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/KnoxApprover__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <label>미결</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>결재</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>반려</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>전결</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>자동결재</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>자동반려</label>
            </value>
            <value>
                <fullName>-1</fullName>
                <isActive>false</isActive>
                <label>-1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Activity__c/Opportunity_Activity__c.object-meta.xml
<CustomObject>
    <label>Opportunity Activity</label>
    <nameField>
        <displayFormat>OA-{yymmdd}-{00000}</displayFormat>
        <label>Opportunity Activity No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Activity__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <label>Canceled</label>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Activity__c/fields/TransactionName__c.field-meta.xml
<CustomField>
    <fullName>TransactionName__c</fullName>
    <label>Opportunity Activity Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>XP11</fullName>
                <label>Register BO</label>
            </value>
            <value>
                <fullName>ZP21</fullName>
                <label>Review BO</label>
            </value>
            <value>
                <fullName>ZP32</fullName>
                <label>Request Resources</label>
            </value>
            <value>
                <fullName>XP31</fullName>
                <label>Receive RFP</label>
            </value>
            <value>
                <fullName>ZP31</fullName>
                <label>Request Strategy Committee</label>
            </value>
            <value>
                <fullName>XP32</fullName>
                <label>Strategy Committee Cost Plan Completion</label>
            </value>
            <value>
                <fullName>ZP62</fullName>
                <label>Request Committee Approval</label>
            </value>
            <value>
                <fullName>ZPZ3</fullName>
                <label>Agency Contract Exception</label>
            </value>
            <value>
                <fullName>ZP61</fullName>
                <label>Submit Proposal</label>
            </value>
            <value>
                <fullName>XP41</fullName>
                <label>Presentation</label>
            </value>
            <value>
                <fullName>XP42</fullName>
                <label>Preferred Bidder</label>
            </value>
            <value>
                <fullName>XP43</fullName>
                <label>Customer Approval</label>
            </value>
            <value>
                <fullName>XP44</fullName>
                <label>Negotiation</label>
            </value>
            <value>
                <fullName>XP51</fullName>
                <label>Contract P&amp;L</label>
            </value>
            <value>
                <fullName>XP52</fullName>
                <label>Legal Review</label>
            </value>
            <value>
                <fullName>ZP82</fullName>
                <label>Contract Approval</label>
            </value>
            <value>
                <fullName>XP57</fullName>
                <label>Closing</label>
            </value>
            <value>
                <fullName>ZPZ2</fullName>
                <label>Drop Opportunity</label>
            </value>
            <value>
                <fullName>XPX1</fullName>
                <label>Abort Opportunity</label>
            </value>
            <value>
                <fullName>ZAC1</fullName>
                <label>Hold Opportunity</label>
            </value>
            <value>
                <fullName>ZPZ1</fullName>
                <label>Lost Opportunity</label>
            </value>
            <value>
                <fullName>ZAC4</fullName>
                <label>Unhold Opportunity</label>
            </value>
            <value>
                <fullName>ZPG1</fullName>
                <label>Change Approval Request</label>
            </value>
            <value>
                <fullName>2.2.1.</fullName>
                <label>Credit Assessment</label>
            </value>
            <value>
                <fullName>2.2.2.</fullName>
                <label>Request AP(APS)</label>
            </value>
            <value>
                <fullName>2.3.2.</fullName>
                <label>Bidding LBS</label>
            </value>
            <value>
                <fullName>2.3.3.</fullName>
                <label>Test Shipment</label>
            </value>
            <value>
                <fullName>2.4.5.</fullName>
                <label>Final LBS</label>
            </value>
            <value>
                <fullName>2.5.1.</fullName>
                <label>Receive Contract</label>
            </value>
            <value>
                <fullName>2.5.3.</fullName>
                <label>Rate Change LBS</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Activity__c/fields/WhatId__c.field-meta.xml
<CustomField>
    <fullName>WhatId__c</fullName>
    <description>Opportunity</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Activity</relationshipLabel>
    <relationshipName>BO_Activity</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/classes/IF_KnoxApprovalSubmitController_Test.cls
/**
 * @description       : 
 * @author            : soohong0.kim@partner.samsung.com
 * @group             : 
 * @last modified on  : 2021-05-21
 * @last modified by  : soohong0.kim@partner.samsung.com
 * Modifications Log 
 * Ver   Date         Author                             Modification
 * 1.0   01-07-2021   soohong0.kim@partner.samsung.com   Initial Version
**/
@isTest
public class IF_KnoxApprovalSubmitController_Test {

    private static testMethod void IF_KnoxApprovalSubmitControllerTest() {

        Test.startTest();
        Test.setMock( HttpCalloutMock.class, new IF_Callout_TestMock());

        Employee__c emp = Utils_TestDataFactory.createEmployee('TestEmp', 'EPID');
        emp.EvEmpNO__c     = '16241';
        emp.EvSapBukrs__c  = 'T100';
        emp.Knox_Server_Location__c = 'KR';
        update emp;

        Opportunity oppty = new Opportunity(
			Name = 'Test Opportunity', 
            StageName = 'Z01',
            Type = 'New Business',
            LeadSource = 'Other',
			CloseDate = System.today()
		);
        insert oppty;

        Opportunity_Activity__c opptyAct_requestResource = new Opportunity_Activity__c(
            Status__c = 'Not Started',
            WhatId__c = oppty.id,
            TransactionName__c = OpportunityActivityHelper.ACT_CODE_REQUEST_RESOURCES
        );
        insert opptyAct_requestResource;        

        KnoxApproval__c approval = new KnoxApproval__c();
        approval.Status__c = '2';
        approval.MISID__c = 'SDSSFDC2020121710344116081688819';
        approval.syncFlag__c = 'N';
        approval.Opportunity__c = oppty.Id;
        approval.OpportunityActivity__c = opptyAct_requestResource.Id;
        insert approval;
        
        KnoxApprover__c approver = new KnoxApprover__c();
        approver.KnoxApproval__c = approval.id;
        approver.ApproverType__c = '0';
        approver.Employee__c     = emp.Id;
        insert approver;

        IF_KnoxApprovalSubmitController.InputClass input = new IF_KnoxApprovalSubmitController.InputClass();

        input.contents      = 'test';
        input.contentsType  = 'test';
        input.docSecuType   = 'test';
        input.notifyOption  = 'test';
        input.urgYn         = 'Y';
        input.sbmDt         = 'test';
        input.timeZone      = 'test';
        input.docMngSaveCode= 'test';
        input.subject       = 'test';
        input.sbmLang       = 'test';
        input.importantYn   = 'Y';
        input.apInfId       = approval.MISID__c;
        
        List<IF_KnoxApprovalSubmitController.Aplns> aplnsList = new List<IF_KnoxApprovalSubmitController.Aplns>();
        aplnsList.add(new IF_KnoxApprovalSubmitController.Aplns('test','test','test','test','test','test','test','test','test','test'));
        input.aplns = aplnsList;

        List<IF_KnoxApprovalSubmitController.Attachments> attachList = new List<IF_KnoxApprovalSubmitController.Attachments>();
        attachList.add(new IF_KnoxApprovalSubmitController.Attachments('test','test','test'));
        input.attachments = attachList;
      
        Test.stopTest();


        Map<String, Object> returnMap = IF_KnoxApprovalSubmitController.approvalSubmit(input);
        Integer statusCode   = Util_String.nvlInt( returnMap.get( 'StatusCode'));
        System.assertEquals( statusCode, 200);        
    }
}