force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/EvCompany__c.field-meta.xml
<CustomField>
    <fullName>EvCompany__c</fullName>
    <label>EP Company</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/EvDept__c.field-meta.xml
<CustomField>
    <fullName>EvDept__c</fullName>
    <label>Department Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/EvSapEmpNO__c.field-meta.xml
<CustomField>
    <fullName>EvSapEmpNO__c</fullName>
    <label>SAP Employee Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/EvStatus__c.field-meta.xml
<CustomField>
    <fullName>EvStatus__c</fullName>
    <description>1    Active
2    Retiree/pensioner
3    Early retiree
4    Interns
5    Terminated
6    Inactive Employees
7    Temp/Seasonal
8    Expatriate
9    External employee
B    Non-holders (PS)
C    Holders (PS)</description>
    <label>Status</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/EvUniqID__c.field-meta.xml
<CustomField>
    <fullName>EvUniqID__c</fullName>
    <externalId>true</externalId>
    <label>EP ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MDGAccountNewControllerTest.cls
/**
 * @description       : 
 * @author            : jiiiiii.park@partner.samsung.com.sds.dev
 * @group             : 
 * @last modified on  : 2022-05-24
 * @last modified by  : younghoon.kim@dkbmc.com
 * Modifications Log 
 * Ver   Date         Author                                     Modification
 * 1.0   2020-12-01   jiiiiii.park@partner.samsung.com.sds.dev   Initial Version
**/
@isTest
public class MDGAccountNewControllerTest {
    static Account acc;
    static User user;
    static Employee__c emp;

    static{
        Profile p = [SELECT Id FROM Profile WHERE Name = 'System Administrator' OR Name = '시스템 관리자'];
        user = new User(
            Alias = 'standt1', 
            Email='user0001@samsung.com', 
            EmailEncodingKey='UTF-8', 
            LastName='Testing', 
            LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', 
            ProfileId = p.Id, 
            TimeZoneSidKey='Asia/Seoul',
            UserName='user0001@samsung.com', 
            EmployeeNumber='1234');
        insert user;

        Employee__c emp = new Employee__c(
            Name = 'Test',
            EvCompany__c = 'C60',
            EvDept__c = 'C60AJ760',
            EvUniqId__c = 'M200810085139C603253',
            EvSapEmpNO__c = '36549',
            EvStatus__c = '1'
        );
        insert emp;

        acc = new Account(
            Name = 'accTest',
            mCountry__c = 'KR',
            BillingCountry = 'Korea, Republic of',
            BillingStreet = 'Test',
            BillingState = 'Seoul',
            BillingCity = 'Test',
            BillingPostalCode = '00000',
            mBizTypeL1Code__c = 'L100',
            mBizTypeL2Code__c = 'L101',
            CorporateNumber__c = '0000000000',
            mDomesticForeign__c = '10',
            mCEOName__c = 'TestCEO',
            OwnerId = user.Id
        );
        insert acc;
    }
    
    @isTest static void test_method_one() { //처음 저장
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new IF_Callout_TestMock());
        MDGAccountNewController.getAccountInfo(acc.Id);
		Test.stopTest();
    }
    
    @isTest static void test_method_two() {//사업자번호 10자리 x
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new IF_Callout_TestMock());
        acc.CorporateNumber__c = '123';
        update acc;
        MDGAccountNewController.getAccountInfo(acc.Id);
		Test.stopTest();
    }

    @isTest static void test_method_three() {
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new IF_Callout_TestMock());
        MDGAccountNewController.AccountTendencySync();
		Test.stopTest();
    }
}