force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/EvMailAddr__c.field-meta.xml
<CustomField>
    <fullName>EvMailAddr__c</fullName>
    <label>Email</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/EvUniqID__c.field-meta.xml
<CustomField>
    <fullName>EvUniqID__c</fullName>
    <externalId>true</externalId>
    <label>EP ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Retirement status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>B</fullName>
                <label>재직</label>
            </value>
            <value>
                <fullName>V</fullName>
                <label>휴직</label>
            </value>
            <value>
                <fullName>R</fullName>
                <label>퇴사</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KnoxApproval__c/KnoxApproval__c.object-meta.xml
<CustomObject>
    <label>Knox Approval</label>
    <nameField>
        <label>Knox Approval Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Knox Approval</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KnoxApproval__c/fields/CompanyCode__c.field-meta.xml
<CustomField>
    <fullName>CompanyCode__c</fullName>
    <label>Company Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KnoxApproval__c/fields/MISID__c.field-meta.xml
<CustomField>
    <fullName>MISID__c</fullName>
    <description>Interface : ExternalKey 옵션 지정</description>
    <externalId>true</externalId>
    <label>MISID</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KnoxApproval__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Knox Approval</relationshipLabel>
    <relationshipName>Knox_Approval</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KnoxApproval__c/fields/OpportunityActivity__c.field-meta.xml
<CustomField>
    <fullName>OpportunityActivity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Activity</label>
    <referenceTo>Opportunity_Activity__c</referenceTo>
    <relationshipLabel>Knox Approval</relationshipLabel>
    <relationshipName>KnoxApproval</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KnoxApproval__c/fields/RequestBusinessLevel__c.field-meta.xml
<CustomField>
    <fullName>RequestBusinessLevel__c</fullName>
    <label>Request Business Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business_Level</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/KnoxApproval__c/fields/syncFlag__c.field-meta.xml
<CustomField>
    <fullName>syncFlag__c</fullName>
    <defaultValue>&quot;N&quot;</defaultValue>
    <label>syncFlag</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Activity__c/Opportunity_Activity__c.object-meta.xml
<CustomObject>
    <label>Opportunity Activity</label>
    <nameField>
        <displayFormat>OA-{yymmdd}-{00000}</displayFormat>
        <label>Opportunity Activity No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Activity__c/fields/LostType__c.field-meta.xml
<CustomField>
    <fullName>LostType__c</fullName>
    <label>Lost Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Z06</fullName>
                <label>Lost</label>
            </value>
            <value>
                <fullName>Z07</fullName>
                <label>Drop</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Activity__c/fields/OpportunityStage__c.field-meta.xml
<CustomField>
    <fullName>OpportunityStage__c</fullName>
    <formula>TEXT(WhatId__r.StageName)</formula>
    <label>Opportunity Stage</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Activity__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <label>Canceled</label>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Activity__c/fields/TransactionName__c.field-meta.xml
<CustomField>
    <fullName>TransactionName__c</fullName>
    <label>Opportunity Activity Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>XP11</fullName>
                <label>Register BO</label>
            </value>
            <value>
                <fullName>ZP21</fullName>
                <label>Review BO</label>
            </value>
            <value>
                <fullName>ZP32</fullName>
                <label>Request Resources</label>
            </value>
            <value>
                <fullName>XP31</fullName>
                <label>Receive RFP</label>
            </value>
            <value>
                <fullName>ZP31</fullName>
                <label>Request Strategy Committee</label>
            </value>
            <value>
                <fullName>XP32</fullName>
                <label>Strategy Committee Cost Plan Completion</label>
            </value>
            <value>
                <fullName>ZP62</fullName>
                <label>Request Committee Approval</label>
            </value>
            <value>
                <fullName>ZPZ3</fullName>
                <label>Agency Contract Exception</label>
            </value>
            <value>
                <fullName>ZP61</fullName>
                <label>Submit Proposal</label>
            </value>
            <value>
                <fullName>XP41</fullName>
                <label>Presentation</label>
            </value>
            <value>
                <fullName>XP42</fullName>
                <label>Preferred Bidder</label>
            </value>
            <value>
                <fullName>XP43</fullName>
                <label>Customer Approval</label>
            </value>
            <value>
                <fullName>XP44</fullName>
                <label>Negotiation</label>
            </value>
            <value>
                <fullName>XP51</fullName>
                <label>Contract P&amp;L</label>
            </value>
            <value>
                <fullName>XP52</fullName>
                <label>Legal Review</label>
            </value>
            <value>
                <fullName>ZP82</fullName>
                <label>Contract Approval</label>
            </value>
            <value>
                <fullName>XP57</fullName>
                <label>Closing</label>
            </value>
            <value>
                <fullName>ZPZ2</fullName>
                <label>Drop Opportunity</label>
            </value>
            <value>
                <fullName>XPX1</fullName>
                <label>Abort Opportunity</label>
            </value>
            <value>
                <fullName>ZAC1</fullName>
                <label>Hold Opportunity</label>
            </value>
            <value>
                <fullName>ZPZ1</fullName>
                <label>Lost Opportunity</label>
            </value>
            <value>
                <fullName>ZAC4</fullName>
                <label>Unhold Opportunity</label>
            </value>
            <value>
                <fullName>ZPG1</fullName>
                <label>Change Approval Request</label>
            </value>
            <value>
                <fullName>2.2.1.</fullName>
                <label>Credit Assessment</label>
            </value>
            <value>
                <fullName>2.2.2.</fullName>
                <label>Request AP(APS)</label>
            </value>
            <value>
                <fullName>2.3.2.</fullName>
                <label>Bidding LBS</label>
            </value>
            <value>
                <fullName>2.3.3.</fullName>
                <label>Test Shipment</label>
            </value>
            <value>
                <fullName>2.4.5.</fullName>
                <label>Final LBS</label>
            </value>
            <value>
                <fullName>2.5.1.</fullName>
                <label>Receive Contract</label>
            </value>
            <value>
                <fullName>2.5.3.</fullName>
                <label>Rate Change LBS</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Activity__c/fields/WhatId__c.field-meta.xml
<CustomField>
    <fullName>WhatId__c</fullName>
    <description>Opportunity</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Activity</relationshipLabel>
    <relationshipName>BO_Activity</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/RevenueScheduleOpportunity__c/RevenueScheduleOpportunity__c.object-meta.xml
<CustomObject>
    <label>Opportunity Revenue Schedule</label>
    <nameField>
        <displayFormat>RS{0000000000}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Revenue Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TriggerSwitch__c/TriggerSwitch__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>TriggerSwitch</label>
</CustomObject>

force-app/main/default/objects/TriggerSwitch__c/fields/All__c.field-meta.xml
<CustomField>
    <fullName>All__c</fullName>
    <defaultValue>true</defaultValue>
    <label>All</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerSwitch__c/fields/CollaboApproval__c.field-meta.xml
<CustomField>
    <fullName>CollaboApproval__c</fullName>
    <defaultValue>false</defaultValue>
    <description>협업 사업기회의 Knox Approval 처리 여부(True인 경우 처리)</description>
    <label>CollaboApproval</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerSwitch__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Event</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerSwitch__c/fields/FakeTest__c.field-meta.xml
<CustomField>
    <fullName>FakeTest__c</fullName>
    <defaultValue>false</defaultValue>
    <label>FakeTest</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerSwitch__c/fields/Migration__c.field-meta.xml
<CustomField>
    <fullName>Migration__c</fullName>
    <defaultValue>false</defaultValue>
    <description>해당 필드가 체크되어있는 경우 마이그 로직을 실행하지않음</description>
    <label>Migration</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerSwitch__c/fields/OpportunityActivity__c.field-meta.xml
<CustomField>
    <fullName>OpportunityActivity__c</fullName>
    <defaultValue>true</defaultValue>
    <label>OpportunityActivity</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerSwitch__c/fields/OpportunityBizLvSetting__c.field-meta.xml
<CustomField>
    <fullName>OpportunityBizLvSetting__c</fullName>
    <defaultValue>true</defaultValue>
    <label>OpportunityBizLvSetting</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerSwitch__c/fields/OpportunityCodeSetting__c.field-meta.xml
<CustomField>
    <fullName>OpportunityCodeSetting__c</fullName>
    <defaultValue>true</defaultValue>
    <label>OpportunityCodeSetting</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerSwitch__c/fields/OpportunityDeleteSetting__c.field-meta.xml
<CustomField>
    <fullName>OpportunityDeleteSetting__c</fullName>
    <defaultValue>true</defaultValue>
    <label>OpportunityDeleteSetting</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerSwitch__c/fields/OpportunityLogisticsValidation__c.field-meta.xml
<CustomField>
    <fullName>OpportunityLogisticsValidation__c</fullName>
    <defaultValue>true</defaultValue>
    <description>레코드 타입 Logistics 유효성 트리거</description>
    <label>OpportunityLogisticsValidation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerSwitch__c/fields/OpportunitySendToSAP__c.field-meta.xml
<CustomField>
    <fullName>OpportunitySendToSAP__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Opportunity 작성/수정/삭제 시 SAP 정보 전송 여부</description>
    <inlineHelpText>Opportunity 작성/수정/삭제 시 SAP 정보 전송 여부</inlineHelpText>
    <label>OpportunitySendToSAP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerSwitch__c/fields/RevenueScheduleOpportunity__c.field-meta.xml
<CustomField>
    <fullName>RevenueScheduleOpportunity__c</fullName>
    <defaultValue>false</defaultValue>
    <label>RevenueScheduleOpportunity</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerSwitch__c/fields/WeeklyReportSend__c.field-meta.xml
<CustomField>
    <fullName>WeeklyReportSend__c</fullName>
    <defaultValue>true</defaultValue>
    <label>WeeklyReportSend</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/KnoxApprovalTrigger_Test2.cls
/**
 * @author            : younghoon.kim@dkbmc.com
 * @group             : 
 * @description       : 
 * @last modified on  : 2023-11-06
 * @last modified by  : divyam.gupta@samsung.com
 *  1.1   2023-11-06   divyam.gupta@samsung.com  Mysales-343 Put If-Logs inside knox approval of drop /lost functionality.

**/
@isTest(SeeAllData = true)
public class KnoxApprovalTrigger_Test2 {
    static Opportunity oppty;
    static Opportunity_Activity__c opptyAct_ZP82;
    static Opportunity_Activity__c opptyAct_ZPZ1;
    static Opportunity_Activity__c opptyAct_ZPZ2;
    static Opportunity_Activity__c opptyAct_ZPZ3;
    static Opportunity_Activity__c opptyAct_ZPG1;
    static KnoxApproval__c knoxApp1;
    static KnoxApproval__c knoxApp2;
    static KnoxApproval__c preKnoxApp;
    //START V 1.1 Divyam 
     static KnoxApproval__c knoxApp3;
     static User testuser;
    static Employee__c emp1;
    static Employee__c migEmp;
    // END V 1.1

    static {
        TriggerSwitch__c ts = [SELECT Id, Name, SetupOwnerId, SetupOwner.Name, All__c, Event__c, Opportunity__c, OpportunityActivity__c, OpportunityCodeSetting__c, 
                                      OpportunityBizLvSetting__c, OpportunityDeleteSetting__c, OpportunityLogisticsValidation__c, OpportunitySendToSAP__c, 
                                      RevenueScheduleOpportunity__c, CollaboApproval__c, Migration__c, WeeklyReportSend__c, FakeTest__c
                                 FROM TriggerSwitch__c 
                                WHERE SetupOwner.Name = 'SAMSUNG SDS'];
        ts.CollaboApproval__c = false;
        ts.FakeTest__c = true;
        update ts;
        //START V 1.1
           migEmp  = Utils_TestDataFactory.createEmployee('migEmp', 'migEmp');

        testuser = Utils_TestDataFactory.createUserFull(Utils_TestDataFactory.getProfile('System Administrator')
                                                        , migEmp.EvMailAddr__c
                                                        , migEmp.EvUniqID__c);
        
        // Mig User Switch insert (SetupOwnerId 에 특정 프로필 또는 User 셋팅하여 Test 제어)
        TriggerSwitch__c trSwitch_migUser = new TriggerSwitch__c(
            Opportunity__c = false,
            SetupOwnerId = testuser.Id
        );        
        insert trSwitch_migUser;
       // END V 1.1
        knoxApp2 = [SELECT Id, Name, Opportunity__c, Opportunity__r.StageName, Opportunity__r.Amount, OpportunityActivity__c, OpportunityActivity__r.TransactionName__c 
                      FROM KnoxApproval__c 
                     WHERE Opportunity__r.StageName = 'Z05' 
                       AND Opportunity__r.Amount = 0 
                       AND OpportunityActivity__r.TransactionName__c = 'ZP82' 
                     LIMIT 1];

        opptyAct_ZP82 = [SELECT Id, Name, WhatId__c, WhatId__r.Name, WhatId__r.CompanyCode__c, WhatId__r.OpportunityCode__c, WhatId__r.CollaborationBOId__c, TransactionName__c, Status__c 
                           FROM Opportunity_Activity__c 
                          WHERE OpportunityStage__c = 'Z05' 
                            AND TransactionName__c = :OpportunityActivityHelper.ACT_CODE_CONTRACT_APPROVAL
                          LIMIT 1];

                          /*
        opptyAct_ZPZ1 = [SELECT Id, Name, WhatId__c, WhatId__r.Name, WhatId__r.CompanyCode__c, WhatId__r.OpportunityCode__c, WhatId__r.CollaborationBOId__c, TransactionName__c, Status__c 
                           FROM Opportunity_Activity__c 
                          WHERE TransactionName__c = :OpportunityActivityHelper.ACT_CODE_LOST_OPPORTUNITY
                            AND LostType__c IN ('Z06', 'Z07')
                          LIMIT 1];
                          */

        opptyAct_ZPZ1 = [SELECT Id, Name, WhatId__c, WhatId__r.Name, WhatId__r.CompanyCode__c, WhatId__r.OpportunityCode__c, WhatId__r.CollaborationBOId__c, TransactionName__c, Status__c 
                           FROM Opportunity_Activity__c
                          WHERE Id = :knoxApp2.OpportunityActivity__c];

        opptyAct_ZPZ2 = [SELECT Id, Name, WhatId__c, WhatId__r.Name, WhatId__r.CompanyCode__c, WhatId__r.OpportunityCode__c, WhatId__r.CollaborationBOId__c, TransactionName__c, Status__c 
                           FROM Opportunity_Activity__c 
                          WHERE TransactionName__c = :OpportunityActivityHelper.ACT_CODE_DROP_OPPORTUNITY
                          LIMIT 1];
        opptyAct_ZPZ3 = [SELECT Id, Name, WhatId__c, WhatId__r.Name, WhatId__r.CompanyCode__c, WhatId__r.OpportunityCode__c, WhatId__r.CollaborationBOId__c, TransactionName__c, Status__c 
                           FROM Opportunity_Activity__c 
                          WHERE TransactionName__c = :OpportunityActivityHelper.ACT_CODE_AGENCY_CONTRACT_EXCEPTION
                          LIMIT 1];

        opptyAct_ZPG1 = [SELECT Id, Name, WhatId__c, WhatId__r.Name, WhatId__r.CompanyCode__c, WhatId__r.OpportunityCode__c, WhatId__r.CollaborationBOId__c, TransactionName__c, Status__c 
                           FROM Opportunity_Activity__c 
                          WHERE TransactionName__c = :OpportunityActivityHelper.ACT_CODE_CHANGE_APPROVAL_REQUEST
                          LIMIT 1];
                          

        oppty = [SELECT Id, Name 
                   FROM Opportunity 
                  WHERE Id = :opptyAct_ZP82.WhatId__c];

        preKnoxApp = new KnoxApproval__c(
            Opportunity__c = oppty.Id,
            OpportunityActivity__c = opptyAct_ZP82.Id,
            Status__c = KnoxApprovalHelper.KNOX_APPROVAL_STATUS_COMPLETED,
            RequestBusinessLevel__c = 'S',
            MISID__c = 'SDSSFDC2021000000000000000000001'
        );
        insert preKnoxApp;
    }

    @isTest 
    static void test_method_1() {
        Test.startTest();

        Test.setMock(HttpCalloutMock.class, new IF_Callout_TestMock(200));

        knoxApp1 = new KnoxApproval__c(
            Opportunity__c = oppty.Id,
            OpportunityActivity__c = opptyAct_ZP82.Id,
            Status__c = KnoxApprovalHelper.KNOX_APPROVAL_STATUS_IN_PROGRESS,
            RequestBusinessLevel__c = 'S'
        );
        insert knoxApp1;

        knoxApp1.Status__c = KnoxApprovalHelper.KNOX_APPROVAL_STATUS_COMPLETED;
        update knoxApp1;

        Test.stopTest();
    }

    @isTest 
    static void test_method_2() {
        Test.startTest();

        Test.setMock(HttpCalloutMock.class, new IF_Callout_TestMock(200));

        knoxApp1 = new KnoxApproval__c(
            Opportunity__c = oppty.Id,
            OpportunityActivity__c = opptyAct_ZPZ1.Id,
            Status__c = KnoxApprovalHelper.KNOX_APPROVAL_STATUS_IN_PROGRESS,
            RequestBusinessLevel__c = 'S',
            syncFlag__c = 'N'
        );
        insert knoxApp1;

        Test.stopTest();
    }
	/*
    @isTest 
    static void test_method_3() {
        Test.startTest();

        Test.setMock(HttpCalloutMock.class, new IF_Callout_TestMock(200));

        knoxApp1 = new KnoxApproval__c(
            Opportunity__c = oppty.Id,
            OpportunityActivity__c = opptyAct_ZPZ2.Id,
            Status__c = KnoxApprovalHelper.KNOX_APPROVAL_STATUS_IN_PROGRESS,
            RequestBusinessLevel__c = 'S'
        );
        insert knoxApp1;

        knoxApp1.Status__c = KnoxApprovalHelper.KNOX_APPROVAL_STATUS_COMPLETED;
        update knoxApp1;

        Test.stopTest();
    }
	*/

    @isTest 
    static void test_method_4() {
        Test.startTest();

        Test.setMock(HttpCalloutMock.class, new IF_Callout_TestMock(200));

        knoxApp1 = new KnoxApproval__c(
            Opportunity__c = oppty.Id,
            OpportunityActivity__c = opptyAct_ZPZ3.Id,
            Status__c = KnoxApprovalHelper.KNOX_APPROVAL_STATUS_IN_PROGRESS,
            RequestBusinessLevel__c = 'S'
        );
        insert knoxApp1;

        //knoxApp1.Status__c = KnoxApprovalHelper.KNOX_APPROVAL_STATUS_COMPLETED;
        //update knoxApp1;

        Test.stopTest();
    }

    @isTest 
    static void test_method_5() {
        Test.startTest();

        Test.setMock(HttpCalloutMock.class, new IF_Callout_TestMock(200));

        knoxApp1 = new KnoxApproval__c(
            Opportunity__c = oppty.Id,
            OpportunityActivity__c = opptyAct_ZPG1.Id,
            Status__c = KnoxApprovalHelper.KNOX_APPROVAL_STATUS_IN_PROGRESS,
            RequestBusinessLevel__c = 'S'
        );
        insert knoxApp1;

        Test.stopTest();
    }
   // START V 1.1 Divyam    
     @isTest 
     static void test_method_6() {
        Test.startTest();

        Test.setMock(HttpCalloutMock.class, new IF_Callout_TestMock(200));
         system.runAs(testuser){
             opptyAct_ZPZ2.LostType__c = 'Z07';
             update opptyAct_ZPZ2;
        knoxApp3 = new KnoxApproval__c(
            Opportunity__c = oppty.Id,
            OpportunityActivity__c = opptyAct_ZPZ2.Id,
            Status__c = KnoxApprovalHelper.KNOX_APPROVAL_STATUS_IN_PROGRESS,
            RequestBusinessLevel__c = 'S',
            syncFlag__c = 'N'
        );
        insert knoxApp3;
        knoxApp3.Status__c = KnoxApprovalHelper.KNOX_APPROVAL_STATUS_AFTER_CONFIRMED;
         knoxApp3.syncFlag__c = 'S';
      
        update knoxApp3;
         }

        Test.stopTest();
    }
    // END V 1.1 
 
    
}