force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/EvUniqID__c.field-meta.xml
<CustomField>
    <fullName>EvUniqID__c</fullName>
    <externalId>true</externalId>
    <label>EP ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Knox_Server_Location__c.field-meta.xml
<CustomField>
    <fullName>Knox_Server_Location__c</fullName>
    <label>Knox Server Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>KR</fullName>
                <default>true</default>
                <label>KR</label>
            </value>
            <value>
                <fullName>GB</fullName>
            </value>
            <value>
                <fullName>US</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KnoxApproval__c/KnoxApproval__c.object-meta.xml
<CustomObject>
    <label>Knox Approval</label>
    <nameField>
        <label>Knox Approval Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Knox Approval</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KnoxApproval__c/fields/MISID__c.field-meta.xml
<CustomField>
    <fullName>MISID__c</fullName>
    <description>Interface : ExternalKey 옵션 지정</description>
    <externalId>true</externalId>
    <label>MISID</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KnoxApproval__c/fields/OriginKnoxApproval__c.field-meta.xml
<CustomField>
    <fullName>OriginKnoxApproval__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>협업 법인 Original 결재</description>
    <inlineHelpText>협업 법인 Original 결재</inlineHelpText>
    <label>Origin Knox Approval</label>
    <referenceTo>KnoxApproval__c</referenceTo>
    <relationshipLabel>Knox Approval</relationshipLabel>
    <relationshipName>KnoxApproval</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KnoxApprover__c/KnoxApprover__c.object-meta.xml
<CustomObject>
    <label>Knox Approver</label>
    <nameField>
        <label>Knox Approver Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Knox Approver</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/KnoxApprover__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Knox Approver</relationshipLabel>
    <relationshipName>Knox_Approver</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KnoxApprover__c/fields/EvUniqID__c.field-meta.xml
<CustomField>
    <fullName>EvUniqID__c</fullName>
    <label>EP ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KnoxApprover__c/fields/KnoxApproval__c.field-meta.xml
<CustomField>
    <fullName>KnoxApproval__c</fullName>
    <label>Knox Approval</label>
    <referenceTo>KnoxApproval__c</referenceTo>
    <relationshipLabel>Knox Approver</relationshipLabel>
    <relationshipName>Knox_Approver</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/IF_KnoxApprovalCancelController.cls
/**
 * @description       : 
 * @author            : soohong0.kim@partner.samsung.com
 * @group             : 
 * @last modified on  : 2021-05-21
 * @last modified by  : soohong0.kim@partner.samsung.com
 * Modifications Log 
 * Ver   Date         Author                             Modification
 * 1.0   2020-11-11   soohong0.kim@partner.samsung.com   Initial Version
 * 1.1   2021-03-04   soohong0.kim@partner.samsung.com   IF_Log 수정(기존 DML 제거, Return 객체에 put)
**/

public class IF_KnoxApprovalCancelController {
    private static final String INTERFACE_ID = 'IF-078';
    private static final String APEX_CLASS   = 'IF_KnoxApprovalCancelController';
    private static final String METHOD_NAME  = 'approvalCancel';

    @AuraEnabled
    public static Map<String,Object> approvalCancel(InputClass input){
        String guId = IF_Util.generateGuid();
        IF_Callout call = new IF_Callout(INTERFACE_ID);
        IF_Log log = new IF_Log();
        IF_Log.InterfaceLog ifLog;
        Map<String,Object> resMap = new Map<String,Object>();
        Map<String,Object> returnMap = new Map<String,Object>();
        try{

            // 기안자 확인
            List<KnoxApprover__c> knoxAprList = [

                SELECT  Id, Employee__c, Employee__r.EvUniqID__c, Employee__r.Knox_Server_Location__c
                FROM    KnoxApprover__c 
                WHERE   KnoxApproval__r.MISID__c = :input.apInfId
                AND     ApproverType__c  = '0'
                LIMIT   1
            ];

            if( knoxAprList.size() > 0){

                input.serverlocation = knoxAprList.get( 0).Employee__r.Knox_Server_Location__c;
            }            


            String jsonBody = JSON.serialize(input);
            resMap = call.httpCallout(jsonBody, '');
            system.debug('request : '+resMap.get('Request'));
            system.debug('response : '+resMap.get('Response'));

            HttpResponse res = (HttpResponse)resMap.get('HttpResponse');
            returnMap.put('StatusCode',res.getStatusCode());
            returnMap.put('IF_MSG',String.valueOf(resMap.get('IF_MSG')));
            returnMap.putAll((Map<String,Object>) JSON.deserializeUntyped(res.getBody()));
            
            
            system.debug('returnMap : '+returnMap);

            ifLog = new IF_Log.InterfaceLog(INTERFACE_ID, guId, APEX_CLASS, METHOD_NAME, String.valueOf(resMap.get('Request')), String.valueOf(resMap.get('Response')));
        
        }catch(Exception e){
            ifLog = new IF_Log.InterfaceLog(INTERFACE_ID, guId, APEX_CLASS, METHOD_NAME, String.valueOf(resMap.get('Request')), String.valueOf(resMap.get('Response')),e);
        }
        returnMap.put('INTERFACE_LOG',ifLog);
        return returnMap;
    }
 
    public class InputClass{
        @AuraEnabled
        public String apInfId;
        @AuraEnabled
        public String opinion;
        @AuraEnabled
        public String serverlocation;
    }
}