force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/EvMailAddr__c.field-meta.xml
<CustomField>
    <fullName>EvMailAddr__c</fullName>
    <label>Email</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/EvSdeptNM__c.field-meta.xml
<CustomField>
    <fullName>EvSdeptNM__c</fullName>
    <label>Department Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/EvUniqID__c.field-meta.xml
<CustomField>
    <fullName>EvUniqID__c</fullName>
    <externalId>true</externalId>
    <label>EP ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Retirement status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>B</fullName>
                <label>재직</label>
            </value>
            <value>
                <fullName>V</fullName>
                <label>휴직</label>
            </value>
            <value>
                <fullName>R</fullName>
                <label>퇴사</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KnoxApproval__c/KnoxApproval__c.object-meta.xml
<CustomObject>
    <label>Knox Approval</label>
    <nameField>
        <label>Knox Approval Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Knox Approval</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KnoxApproval__c/fields/MISID__c.field-meta.xml
<CustomField>
    <fullName>MISID__c</fullName>
    <description>Interface : ExternalKey 옵션 지정</description>
    <externalId>true</externalId>
    <label>MISID</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KnoxApproval__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Knox Approval</relationshipLabel>
    <relationshipName>Knox_Approval</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KnoxApproval__c/fields/OpportunityActivity__c.field-meta.xml
<CustomField>
    <fullName>OpportunityActivity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Activity</label>
    <referenceTo>Opportunity_Activity__c</referenceTo>
    <relationshipLabel>Knox Approval</relationshipLabel>
    <relationshipName>KnoxApproval</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KnoxApproval__c/fields/OriginKnoxApproval__c.field-meta.xml
<CustomField>
    <fullName>OriginKnoxApproval__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>협업 법인 Original 결재</description>
    <inlineHelpText>협업 법인 Original 결재</inlineHelpText>
    <label>Origin Knox Approval</label>
    <referenceTo>KnoxApproval__c</referenceTo>
    <relationshipLabel>Knox Approval</relationshipLabel>
    <relationshipName>KnoxApproval</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KnoxApproval__c/fields/syncFlag__c.field-meta.xml
<CustomField>
    <fullName>syncFlag__c</fullName>
    <defaultValue>&quot;N&quot;</defaultValue>
    <label>syncFlag</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KnoxApprover__c/KnoxApprover__c.object-meta.xml
<CustomObject>
    <label>Knox Approver</label>
    <nameField>
        <label>Knox Approver Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Knox Approver</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/KnoxApprover__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Knox Approver</relationshipLabel>
    <relationshipName>Knox_Approver</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KnoxApprover__c/fields/EvSdeptNM__c.field-meta.xml
<CustomField>
    <fullName>EvSdeptNM__c</fullName>
    <label>Department</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KnoxApprover__c/fields/EvUniqID__c.field-meta.xml
<CustomField>
    <fullName>EvUniqID__c</fullName>
    <label>EP ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KnoxApprover__c/fields/KnoxApproval__c.field-meta.xml
<CustomField>
    <fullName>KnoxApproval__c</fullName>
    <label>Knox Approval</label>
    <referenceTo>KnoxApproval__c</referenceTo>
    <relationshipLabel>Knox Approver</relationshipLabel>
    <relationshipName>Knox_Approver</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/KnoxApprover__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <label>미결</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>결재</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>반려</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>전결</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>자동결재</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>자동반려</label>
            </value>
            <value>
                <fullName>-1</fullName>
                <isActive>false</isActive>
                <label>-1</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Activity__c/Opportunity_Activity__c.object-meta.xml
<CustomObject>
    <label>Opportunity Activity</label>
    <nameField>
        <displayFormat>OA-{yymmdd}-{00000}</displayFormat>
        <label>Opportunity Activity No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Activity__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>설명</description>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity_Activity__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <label>Canceled</label>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Activity__c/fields/TransactionName__c.field-meta.xml
<CustomField>
    <fullName>TransactionName__c</fullName>
    <label>Opportunity Activity Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>XP11</fullName>
                <label>Register BO</label>
            </value>
            <value>
                <fullName>ZP21</fullName>
                <label>Review BO</label>
            </value>
            <value>
                <fullName>ZP32</fullName>
                <label>Request Resources</label>
            </value>
            <value>
                <fullName>XP31</fullName>
                <label>Receive RFP</label>
            </value>
            <value>
                <fullName>ZP31</fullName>
                <label>Request Strategy Committee</label>
            </value>
            <value>
                <fullName>XP32</fullName>
                <label>Strategy Committee Cost Plan Completion</label>
            </value>
            <value>
                <fullName>ZP62</fullName>
                <label>Request Committee Approval</label>
            </value>
            <value>
                <fullName>ZPZ3</fullName>
                <label>Agency Contract Exception</label>
            </value>
            <value>
                <fullName>ZP61</fullName>
                <label>Submit Proposal</label>
            </value>
            <value>
                <fullName>XP41</fullName>
                <label>Presentation</label>
            </value>
            <value>
                <fullName>XP42</fullName>
                <label>Preferred Bidder</label>
            </value>
            <value>
                <fullName>XP43</fullName>
                <label>Customer Approval</label>
            </value>
            <value>
                <fullName>XP44</fullName>
                <label>Negotiation</label>
            </value>
            <value>
                <fullName>XP51</fullName>
                <label>Contract P&amp;L</label>
            </value>
            <value>
                <fullName>XP52</fullName>
                <label>Legal Review</label>
            </value>
            <value>
                <fullName>ZP82</fullName>
                <label>Contract Approval</label>
            </value>
            <value>
                <fullName>XP57</fullName>
                <label>Closing</label>
            </value>
            <value>
                <fullName>ZPZ2</fullName>
                <label>Drop Opportunity</label>
            </value>
            <value>
                <fullName>XPX1</fullName>
                <label>Abort Opportunity</label>
            </value>
            <value>
                <fullName>ZAC1</fullName>
                <label>Hold Opportunity</label>
            </value>
            <value>
                <fullName>ZPZ1</fullName>
                <label>Lost Opportunity</label>
            </value>
            <value>
                <fullName>ZAC4</fullName>
                <label>Unhold Opportunity</label>
            </value>
            <value>
                <fullName>ZPG1</fullName>
                <label>Change Approval Request</label>
            </value>
            <value>
                <fullName>2.2.1.</fullName>
                <label>Credit Assessment</label>
            </value>
            <value>
                <fullName>2.2.2.</fullName>
                <label>Request AP(APS)</label>
            </value>
            <value>
                <fullName>2.3.2.</fullName>
                <label>Bidding LBS</label>
            </value>
            <value>
                <fullName>2.3.3.</fullName>
                <label>Test Shipment</label>
            </value>
            <value>
                <fullName>2.4.5.</fullName>
                <label>Final LBS</label>
            </value>
            <value>
                <fullName>2.5.1.</fullName>
                <label>Receive Contract</label>
            </value>
            <value>
                <fullName>2.5.3.</fullName>
                <label>Rate Change LBS</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Activity__c/fields/WhatId__c.field-meta.xml
<CustomField>
    <fullName>WhatId__c</fullName>
    <description>Opportunity</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Activity</relationshipLabel>
    <relationshipName>BO_Activity</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>Opportunity</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Project</relationshipLabel>
    <relationshipName>BO_Project</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/ProjectCode__c.field-meta.xml
<CustomField>
    <fullName>ProjectCode__c</fullName>
    <externalId>true</externalId>
    <label>Project Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SendActCompleteEmail_Test.cls
/**
 * @description       : 
 * @author            : seonju.jin@dkbmc.com
 * @group             : 
 * @last modified on  : 2022-02-17
 * @last modified by  : seonju.jin@dkbmc.com
**/
@isTest
public class SendActCompleteEmail_Test {
    @TestSetup
    static void setData(){

        Opportunity oppty = new Opportunity(
			Name = 'Test Opportunity', 
            StageName = 'Z01',
            Type = 'New Business',
            LeadSource = 'Other',
			CloseDate = System.today()
		);
        insert oppty;

        // *******************************************
        // OppoActivity 
        // **************************************************************

        // Request Resource
        Opportunity_Activity__c opptyAct_requestResource = new Opportunity_Activity__c(
            Status__c = 'Not Started',
            WhatId__c = oppty.id,
            TransactionName__c = OpportunityActivityHelper.ACT_CODE_REQUEST_RESOURCES
        );
        insert opptyAct_requestResource;


        Project__c project = new Project__c(
            Opportunity__c =  oppty.Id,
            Name = 'Test2',
            Description__c = 'Test2',
            ProjectCode__c = 'testProject002'
        );
        insert project;

        KnoxApproval__c approval = new KnoxApproval__c();
        approval.Status__c = '1';
        approval.MISID__c = 'SDSSFDC2020121710344116081688819';
        approval.syncFlag__c = 'N';
        approval.Opportunity__c = oppty.Id;
        approval.OpportunityActivity__c = opptyAct_requestResource.Id;
        insert approval;
        
        /**
         * Knox Approver
         */
        Employee__c emp1 = Utils_TestDataFactory.createEmployee('TestEmp1', 'EPID1');
        KnoxApprover__c knoxApprover1 = new KnoxApprover__c(
            KnoxApproval__c = approval.Id,
            Index__c = 0,
            Name = 'test1',
            ApproverType__c = '0',
            EvSdeptNM__c = '개발',
            EvMailAddr__c = emp1.EvMailAddr__c,
            Employee__c = emp1.Id,
            EvUniqID__c = emp1.EvUniqID__c,
            IsChangeLine__c = true,
            IsEditText__c = true,
            IsArbitraryDecision__c = true
        );
        insert knoxApprover1;
        
        
        KnoxApproval__c approval2 = new KnoxApproval__c(
            Name = 'approval2',
        	Status__c = '1',
        	MISID__c = 'SDSSFDC2020121710344116081688820',
        	syncFlag__c = 'Y',
        	Opportunity__c = oppty.Id,
        	OpportunityActivity__c = opptyAct_requestResource.Id
        );
        insert approval2;

        KnoxApproval__c approval_copy = approval.clone(false, true, false);
        approval_copy.id = null;
        approval_copy.OriginKnoxApproval__c = approval.Id;
        insert approval_copy;

        KnoxApproval__c approval_copy2 = approval2.clone(false, true, false);
        approval_copy2.id = null;
        approval_copy2.syncFlag__c = 'Y';
        approval_copy2.OriginKnoxApproval__c = approval2.Id;
        insert approval_copy2;

        KnoxApproval__c approval3 = new KnoxApproval__c(
            Name = 'approval3',
        	Status__c = '1',
        	MISID__c = 'SDSSFDC2020121710344116081688821',
        	syncFlag__c = 'Y',
        	Opportunity__c = oppty.Id,
        	OpportunityActivity__c = opptyAct_requestResource.Id
        );
        insert approval3;
    }
    
    @IsTest
    static void testmethod_01(){
        Test.startTest();
        List<KnoxApproval__c> objList = [SELECT Id FROM KnoxApproval__c];
        Set<Id> knoxApprovalIdSet = new Set<Id>();
        for(KnoxApproval__c obj : objList){
            KnoxApprovalIdSet.add(obj.Id);
        }
        SendActCompleteEmail.sendKnoxMail(KnoxApprovalIdSet);
        Test.stopTest();
        
    }
}