force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Partnership_Info__c/Partnership_Info__c.object-meta.xml
<CustomObject>
    <description>MSP Accout 하위의 파트너십 현황 정보</description>
    <label>Partnership Info</label>
    <nameField>
        <displayFormat>PI-{0000}</displayFormat>
        <label>Partnership Info Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partnership Infos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Partnership_Info__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>고객사</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partnership Infos</relationshipLabel>
    <relationshipName>Partnership_Infos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partnership_Info__c/fields/Contract_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Start_Date__c</fullName>
    <description>계약 시작일(Date)</description>
    <label>Contract Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Partnership_Info__c/fields/SDS_PDM__c.field-meta.xml
<CustomField>
    <fullName>SDS_PDM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>SDS PDM(Employee__c)</description>
    <label>SDS PDM</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Partnership Infos</relationshipLabel>
    <relationshipName>Partnership_Infos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SCP_Account__c/SCP_Account__c.object-meta.xml
<CustomObject>
    <label>SCP Account</label>
    <nameField>
        <label>SCP Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SCP Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SCP_Account__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Customer</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>MDG check must equal true</errorMessage>
        <filterItems>
            <field>Account.MDGCheck__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SCP Accounts</relationshipLabel>
    <relationshipName>SCP_Accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SCP_Account__c/fields/Incentive__c.field-meta.xml
<CustomField>
    <fullName>Incentive__c</fullName>
    <label>Incentive</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SCP_Account__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SCP Accounts (Partner)</relationshipLabel>
    <relationshipName>SCP_Accounts1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SCP_Account__c/fields/SDS_AM__c.field-meta.xml
<CustomField>
    <fullName>SDS_AM__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>SDS AM</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>SCP Accounts</relationshipLabel>
    <relationshipName>SCP_Accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SCP_Account__c/fields/SDS_PDM__c.field-meta.xml
<CustomField>
    <fullName>SDS_PDM__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>SDS PDM</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>SCP Accounts (SDS PDM)</relationshipLabel>
    <relationshipName>SCP_Accounts1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CustomCreateRecordController.cls
/**
 * @description       : Create Custom Record (For SCP Account and MSP Project)
 * @author            : gitesh.s@samsung.com
 * @group             : 
 * @last modified on  : 18-11-2022
 * @last modified by  : gitesh.s@smsung.com
 * Modifications Log 
 * Ver   Date         Author                 Modification
 * 1.0   18-11-2022   gitesh.s@samsung.com   Initial Version
**/
public class CustomCreateRecordController {
    @AuraEnabled
    public static Id getPartnershipInfo(Id recordId) {
        return [SELECT Id, Name FROM Employee__c WHERE Id IN (
                SELECT SDS_PDM__c FROM Partnership_Info__c WHERE Account__c =: recordId)].Id;
    }

    @AuraEnabled
    public static List<SCP_Account__c> getSCPAccountInfo(Id recordId) {
        return [SELECT Id, Name, Customer__c, Partner__c, Contract_Start_Date__c, Incentive__c, SDS_AM__c, SDS_PDM__c FROM SCP_Account__c WHERE Id =: recordId];
    }

    @AuraEnabled
    public static Boolean getPartnerAccount(Id recordId) {
        return [SELECT Id, IsPartner FROM Account WHERE Id =: recordId].IsPartner;
    }

    @AuraEnabled
    public static Boolean checkApprovalStatus(Id recordId) {
        return Approval.isLocked(recordId);
    }

    @AuraEnabled
    public static Profile getProfileInfo() {
        String profileId = UserInfo.getProfileId();
        Profile profile = [SELECT Id, Name FROM Profile WHERE Id =:profileId];
        return profile;
    }
}