force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/EvMailAddr__c.field-meta.xml
<CustomField>
    <fullName>EvMailAddr__c</fullName>
    <label>Email</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/EvUniqID__c.field-meta.xml
<CustomField>
    <fullName>EvUniqID__c</fullName>
    <externalId>true</externalId>
    <label>EP ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/KnoxApprovalTrigger_Test3.cls
/**
 * @author            : younghoon.kim@dkbmc.com
 * @group             : 
 * @description       : 
 * @last modified on  : 2022-01-03
 * @last modified by  : younghoon.kim@dkbmc.com
**/
@isTest
public class KnoxApprovalTrigger_Test3 {
    @TestSetup
    static void setData(){
        Employee__c emp_1 = Utils_TestDataFactory.createEmployee('TestEmp1', 'EPID1');
        User user_1 = Utils_TestDataFactory.createUserFull(Utils_TestDataFactory.getProfile('Sales Rep.(HQ)'), emp_1.EvMailAddr__c, emp_1.EvUniqID__c);
    }

    private static testMethod void test01() {
        Test.startTest();
        Test.stopTest();
    }
}