force-app/main/default/objects/WeeklyReport__c/WeeklyReport__c.object-meta.xml
<CustomObject>
    <label>Weekly Report</label>
    <nameField>
        <label>Reporting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Weekly Report</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/WeeklyReport__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Weekly Report</relationshipLabel>
    <relationshipName>AccountWeeklyReports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WeeklyReport__c/fields/CheckedforIssue__c.field-meta.xml
<CustomField>
    <fullName>CheckedforIssue__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Checked for Issue</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/WeeklyReport__c/fields/ComplianceGuide__c.field-meta.xml
<CustomField>
    <fullName>ComplianceGuide__c</fullName>
    <defaultValue>&quot;경쟁사, 발주처 로부터 비공식적으로 취득한 정보의 사용 또는 경쟁사와 정보를 교환하는 행위는&quot; 
&amp; BR() &amp;
&quot;영업비밀 침해, 담합 등 compliance 위반에 해당될 수 있으므로 유의하시기 바랍니다.&quot;
&amp; BR() &amp;
&quot;※ 교환 금지 정보&quot;
&amp; BR() &amp;
&quot; ① 원가 정보, ② 판매량/출고량/재고, ③ 상품ㆍ용역 거래조건 및 대금ㆍ대가 지급 조건&quot;
&amp; BR() &amp; BR() &amp;
&quot;Please note that the use of information obtained unofficially from competitors and clients or the exchange information with competitors may constitute a violation of laws and regulations such as infringement of trade secrets or illegal cartel.&quot;
&amp; BR() &amp;
&quot;※ Not allowed to exchange&quot;
&amp; BR() &amp;
&quot;  ① Cost of goods and services,  ② Sales/Forwarding volume, inventory, ③ Terms of transaction of payment and consideration&quot;</defaultValue>
    <label>Compliance Guide</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/WeeklyReport__c/fields/Contents__c.field-meta.xml
<CustomField>
    <fullName>Contents__c</fullName>
    <label>Contents</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/WeeklyReport__c/fields/Critical__c.field-meta.xml
<CustomField>
    <fullName>Critical__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Critical</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/WeeklyReport__c/fields/DisplayOrder__c.field-meta.xml
<CustomField>
    <fullName>DisplayOrder__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Display Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WeeklyReport__c/fields/Flag__c.field-meta.xml
<CustomField>
    <fullName>Flag__c</fullName>
    <label>Flag</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>I</fullName>
                <default>true</default>
                <label>Insert</label>
            </value>
            <value>
                <fullName>U</fullName>
                <label>Update</label>
            </value>
            <value>
                <fullName>D</fullName>
                <label>Delete</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WeeklyReport__c/fields/Issue_Description_Check__c.field-meta.xml
<CustomField>
    <fullName>Issue_Description_Check__c</fullName>
    <label>New Editor</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/WeeklyReport__c/fields/IssueDescription__c.field-meta.xml
<CustomField>
    <fullName>IssueDescription__c</fullName>
    <label>Issue Description</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/WeeklyReport__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Weekly Report</relationshipLabel>
    <relationshipName>Weekly_Report</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WeeklyReport__c/fields/ReportingDate__c.field-meta.xml
<CustomField>
    <fullName>ReportingDate__c</fullName>
    <label>Reporting Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/WeeklyReport__c/fields/SalesLead__c.field-meta.xml
<CustomField>
    <fullName>SalesLead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Lead</label>
    <referenceTo>Sales_Lead__c</referenceTo>
    <relationshipLabel>Weekly Report</relationshipLabel>
    <relationshipName>Weekly_Report</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/newWeeklyReportVFController.cls
/**
 * @author            : aditya.r2@samsung.com
 * @group             : 
 * @description       : Apex class for VF Page newWeeklyReportVF.vfp
 * @last modified on  : 2024-03-26
 * @last modified by  : aditya.r2@samsung.com
 * Modifications Log 
 * Ver   Date         Author                    Modification
 * 1.0   2024-03-26   aditya.r2@samsung.com		Initial Version
**/
public class newWeeklyReportVFController {

    public Id recordId { get; set; }
    public String issueDescriptionCheck {get; set;}
    public WeeklyReport__c wr { get; set; }
     public static Boolean isSandbox = Utils.getIsSandbox();

    public newWeeklyReportVFController(ApexPages.StandardController std){
        
    }
    
    public static void deleteImage(String deleteSrc) {
        List<String> src = deleteSrc.split(' ');
        List<String>  cvIdList = new List<String>(); 
        for(String s : src){
        	cvIdList.add(s.split('/')[7]);
        }
        List<ContentVersion> cvList = [SELECT Id,ContentDocumentId FROM ContentVersion WHERE ID IN :cvIdList]; 
        Set<Id> deleteIdList = new Set<Id>(); 
        for(ContentVersion cv : cvList){
        	deleteIdList.add(cv.ContentDocumentId); 
        }
        List<ContentDocument> cdList = [SELECT ID FROM ContentDocument WHERE ID IN :deleteIdList]; 
        DELETE cdList; 
    }
    
    public static void CreateImgPublicLink(String uploadedImgSrc){

        System.debug('########### uploadedImgSrc ##############'); 
        System.debug(uploadedImgSrc); 
        if(uploadedImgSrc == null || uploadedImgSrc == '') return; 
        List<Id> src = uploadedImgSrc.split(' ');
        Set<Id> cvSet = new Set<Id>(); 
        List<ContentDistribution> cdList = new List<ContentDistribution>(); 
        for(Id s : src) cvSet.add(s); 
        Map<Id,ContentVersion> cvMap = new Map<Id,ContentVersion>([SELECT ID,Title FROM ContentVersion WHERE ID in :cvSet]); 

       for(Id s : src){
           ContentVersion cv 		= cvMap.get(s); 
           ContentDistribution cd = new ContentDistribution(); 
           cd.ContentVersionId 	= cv.Id; 
           cd.Name             	= cv.Title; 
           cd.PreferencesNotifyOnVisit = false; 
           cdList.add(cd);
       }
        
        if(cdList.size()>0) Insert cdList; 
    }
    
    public pageReference doSave(){
        try{
            System.debug('******************* CafeNote Editor doSave Start****************'); 
            
            String issueDesc = Apexpages.currentPage().getParameters().get('issueDescription');
			String deleteSrc   = Apexpages.currentPage().getParameters().get('deleteSrc');
            String uploadedImgSrcList   = Apexpages.currentPage().getParameters().get('uploadedImgSrcList');
            String ReportingName = Apexpages.currentPage().getParameters().get('ReportingName');
			Date ReportingDate   = Date.valueOf(Apexpages.currentPage().getParameters().get('ReportingDate'));
            String Critical   = Apexpages.currentPage().getParameters().get('Critical');
            String Account = Apexpages.currentPage().getParameters().get('Account');
			String Opportunity   = Apexpages.currentPage().getParameters().get('Opportunity');
            String SalesLead   = Apexpages.currentPage().getParameters().get('SalesLead');
            String IssueReport = Apexpages.currentPage().getParameters().get('IssueReport');
			//String Flag   = Apexpages.currentPage().getParameters().get('Flag');
            String ComplianceGuide   = Apexpages.currentPage().getParameters().get('ComplianceGuide');
            system.debug('ComplianceGuide val:'+ComplianceGuide);
            String ReportContent   = Apexpages.currentPage().getParameters().get('ReportContent');
            system.debug('parameters value : '+ ReportContent);
           // String IssueDescription1 = Apexpages.currentPage().getParameters().get('IssueDescription1');
			//system.debug('parameters value : '+ IssueDescription1);
            //String DisplayOrder   = Apexpages.currentPage().getParameters().get('DisplayOrder');
            //system.debug('DoSave name: ' + ReportingName + 'date: ' + ReportingDate + 'critical: ' + Critical + 'Account: ' + Account + 'Opp ' + Opportunity + 'SalesLead: ' + SalesLead + 'IssueReport: ' + IssueReport + 'Flag: ' + Flag);
               String oldimgurl = 'img src="/sfc/servlet.shepherd/version/download/';
             String newimgurl;
            if(isSandbox) {
             newimgurl = 'img src="https://sdssfa--qa.sandbox.my.salesforce.com/sfc/servlet.shepherd/version/download/';
            }
            else {
               newimgurl =  'img src="https://sdssfa.lightning.force.com/sfc/servlet.shepherd/version/download/';
            }
            String imgsrc;
            if(issueDesc.contains(oldimgurl)){
            imgsrc = issueDesc.replace(oldimgurl,newimgurl);
            }
            else {
                imgsrc = issueDesc;
            }
//            String encodedContent = EncodingUtil.urlEncode(issueDesc, 'UTF-8');
            String encodedContent = EncodingUtil.urlEncode(imgsrc, 'UTF-8');
            Integer stringCount = encodedContent.length(); 
            
            Schema.DescribeFieldResult fieldResult = WeeklyReport__c.Issue_Description_Check__c.getDescribe();
            Integer lengthOfField = fieldResult.getLength(); 
               System.debug('stringCount : ' +stringCount ); 
             
            /*if(stringCount > lengthOfField){
                System.debug('stringCount : ' +stringCount ); 
                System.debug('lengthOfField : ' +lengthOfField ); 
                System.debug('size초과');
                
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,lengthOfField+'자 Size 초과입니다. 현재('+stringCount+'자)'));                    
                return null;
            }*/
            
            System.debug('Delete List : ' + DeleteSrc);
            if(deleteSrc.length()>0) deleteImage(deleteSrc); 
            
            createImgPublicLink(uploadedImgSrcList); 
            system.debug('Present1');
            WeeklyReport__c newWR = new WeeklyReport__c();
        	system.debug('Present2');
            newWR.name = ReportingName;
            system.debug('Present3');
            newWR.ReportingDate__c = ReportingDate;
            system.debug('Present4');
            newWR.Critical__c = Boolean.valueOf(Critical);
            system.debug('Present5');
            if(Account != null && Account != '' && Account != ' ') newWR.Account__c = Account;
            system.debug('Present6');
            if(Opportunity != null && Opportunity != '' && Opportunity != ' ') newWR.Opportunity__c = Opportunity;
            system.debug('Present7');
            if(SalesLead != null && SalesLead != '' && SalesLead != ' ') newWR.SalesLead__c = SalesLead;
            system.debug('Present8');
            newWR.CheckedforIssue__c = Boolean.valueOf(IssueReport);
            system.debug('Present9');
            //newWR.Flag__c = Flag;
            system.debug('Present10');
            //if(encodedContent != null) newWR.Issue_Description_Check__c = encodedContent;
           // if(issueDesc != null) newWR.Issue_Description_Check__c = issueDesc;
             if(issueDesc != null) newWR.Issue_Description_Check__c = imgsrc;

            if(ComplianceGuide != null) newWR.ComplianceGuide__c = ComplianceGuide;
            if(ReportContent != null) newWR.Contents__c = ReportContent;
          //  if(IssueDescription1 != null) newWR.IssueDescription__c = IssueDescription1;
            //if(DisplayOrder != null) newWR.DisplayOrder__c = decimal.valueOf(DisplayOrder);
            system.debug('Before insert Apex Class '+ newWR);
        	//insert newWR;
             Database.SaveResult lsr = Database.insert(newWR,false); 
                       PageReference redirectUrl;

            system.debug('After insert Apex Class '+ newWR.Id);
             if(lsr.isSuccess()){
                            if(isSandbox){
               redirectUrl = new PageReference('https://sdssfa--qa.sandbox.my.salesforce.com/' + newWR.Id);
            }
            else {
            redirectUrl = new PageReference('https://sdssfa.lightning.force.com/' + newWR.Id);
            }
            redirectUrl.setRedirect(true);
		
                    }
                    else{
                        for(Database.Error err : lsr.getErrors()){
                            if(String.valueOF(err).contains('Issue Description: data value too large'))
                                Apexpages.addMessage(new Apexpages.Message(ApexPages.Severity.ERROR, System.Label.CharacterLimitError));
                            else
                                Apexpages.addMessage(new Apexpages.Message(ApexPages.Severity.ERROR, '' + err));
                                
                            return null;
                        }
                    }
           
           /* PageReference redirectUrl;
             if(isSandbox){
            redirectUrl = new PageReference('https://sdssfa--qa.sandbox.my.salesforce.com/' + newWR.Id);
             }
            else {
              redirectUrl = new PageReference('https://sdssfa.lightning.force.com/' + newWR.Id);

            }
            redirectUrl.setRedirect(true);*/
			return redirectUrl;
        }
        catch(Exception e){
            Apexpages.addMessage(new Apexpages.Message(ApexPages.Severity.ERROR, 'Error Saving record: '+e.getMessage()));
        }
        System.debug('*************** do Save End *******************');
        return null;
    }
}