force-app/main/default/objects/Master_Service__c/Master_Service__c.object-meta.xml
<CustomObject>
    <label>Master Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Service</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Solution__c/Master_Solution__c.object-meta.xml
<CustomObject>
    <label>Master Solution</label>
    <nameField>
        <label>Master Solution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Solution</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Solution__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>서비스</description>
    <label>Service</label>
    <referenceTo>Master_Service__c</referenceTo>
    <relationshipName>Solution</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Master_Solution__c/fields/SolutionType__c.field-meta.xml
<CustomField>
    <fullName>SolutionType__c</fullName>
    <label>Solution Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>10</fullName>
                <label>Professional Service</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>H/W</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>S/W</label>
            </value>
            <value>
                <fullName>40</fullName>
                <label>Infra</label>
            </value>
            <value>
                <fullName>50</fullName>
                <label>BPO</label>
            </value>
            <value>
                <fullName>60</fullName>
                <label>SaaS</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/DeletionFlag__c.field-meta.xml
<CustomField>
    <fullName>DeletionFlag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Deletion Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>Opportunity</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Project</relationshipLabel>
    <relationshipName>BO_Project</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/ProjectCode__c.field-meta.xml
<CustomField>
    <fullName>ProjectCode__c</fullName>
    <externalId>true</externalId>
    <label>Project Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <displayFormat>SVC-{YYYY}{MM}{00000}</displayFormat>
        <label>Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/DeletionFlag__c.field-meta.xml
<CustomField>
    <fullName>DeletionFlag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Deletion Flag(IF)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/ItemNumber__c.field-meta.xml
<CustomField>
    <fullName>ItemNumber__c</fullName>
    <label>Item Number</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>BO_Service_Solution</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/SendSAP__c.field-meta.xml
<CustomField>
    <fullName>SendSAP__c</fullName>
    <defaultValue>false</defaultValue>
    <description>SAP전송여부</description>
    <label>SendSAP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service(IF)</label>
    <referenceTo>Master_Service__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>BO_Service_Solution</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Service_Code__c.field-meta.xml
<CustomField>
    <fullName>Service_Code__c</fullName>
    <formula>Service__r.Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Service Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Solution__c/Solution__c.object-meta.xml
<CustomObject>
    <label>Solution(c)</label>
    <nameField>
        <displayFormat>SOL-{YYYY}{MM}{00000}</displayFormat>
        <label>Solution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Solution(c)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Solution__c/fields/DeletionFlag__c.field-meta.xml
<CustomField>
    <fullName>DeletionFlag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Deletion Flag(IF)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Solution__c/fields/ItemNumber__c.field-meta.xml
<CustomField>
    <fullName>ItemNumber__c</fullName>
    <formula>Service__r.ItemNumber__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Item Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Solution__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Solution(c)</relationshipLabel>
    <relationshipName>Solution_c</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Solution__c/fields/ProjectCode__c.field-meta.xml
<CustomField>
    <fullName>ProjectCode__c</fullName>
    <label>Project Code</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Solution__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Solution(c)</relationshipLabel>
    <relationshipName>Solution</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Solution__c/fields/Solution__c.field-meta.xml
<CustomField>
    <fullName>Solution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Solution(IF)</label>
    <referenceTo>Master_Solution__c</referenceTo>
    <relationshipLabel>Solution(c)</relationshipLabel>
    <relationshipName>Solution_c</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Solution__c/fields/Solution_Code__c.field-meta.xml
<CustomField>
    <fullName>Solution_Code__c</fullName>
    <formula>Solution__r.Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Solution Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Solution__c/fields/SolutionType__c.field-meta.xml
<CustomField>
    <fullName>SolutionType__c</fullName>
    <formula>Text(Solution__r.SolutionType__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Solution Type(IF)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TA_Mig_Target__c/TA_Mig_Target__c.object-meta.xml
<CustomObject>
    <label>TA Mig Target</label>
    <nameField>
        <displayFormat>TMT-{YY}{MM}{00000}</displayFormat>
        <label>TA Mig Target Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TA Mig Target</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TA_Mig_Target__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>TA Mig Target</relationshipLabel>
    <relationshipName>TA_Mig_Target</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TA_Mig_Target__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>TA Mig Target</relationshipLabel>
    <relationshipName>TA_Mig_Target</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TA_Mig_Target__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>TA Mig Target</relationshipLabel>
    <relationshipName>TA_Mig_Target</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TA_Mig_Target__c/fields/Solution__c.field-meta.xml
<CustomField>
    <fullName>Solution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Solution(c)</label>
    <referenceTo>Solution__c</referenceTo>
    <relationshipLabel>TA Mig Target</relationshipLabel>
    <relationshipName>TA_Mig_Target</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TA_Mig_Target__c/fields/WBS__c.field-meta.xml
<CustomField>
    <fullName>WBS__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>WBS</label>
    <referenceTo>WBS__c</referenceTo>
    <relationshipLabel>TA Mig Target</relationshipLabel>
    <relationshipName>TA_Mig_Target</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WBS__c/WBS__c.object-meta.xml
<CustomObject>
    <label>WBS</label>
    <nameField>
        <label>WBS Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WBS</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/WBS__c/fields/DeletionFlag__c.field-meta.xml
<CustomField>
    <fullName>DeletionFlag__c</fullName>
    <label>Deletion Flag</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WBS__c/fields/ItemNumber__c.field-meta.xml
<CustomField>
    <fullName>ItemNumber__c</fullName>
    <description>솔루션의 Item Number</description>
    <label>Item Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WBS__c/fields/ItemNumberInt__c.field-meta.xml
<CustomField>
    <fullName>ItemNumberInt__c</fullName>
    <description>ItemNumber String to Number value</description>
    <formula>VALUE(ItemNumber__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ItemNumberInt</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WBS__c/fields/OpportunityID__c.field-meta.xml
<CustomField>
    <fullName>OpportunityID__c</fullName>
    <label>Opportunity ID</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>WBS</relationshipLabel>
    <relationshipName>WBS</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/WBS__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>WBS</relationshipLabel>
    <relationshipName>WBS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WBS__c/fields/ProjectCode__c.field-meta.xml
<CustomField>
    <fullName>ProjectCode__c</fullName>
    <label>Project Code</label>
    <length>24</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WBS__c/fields/ServiceCode__c.field-meta.xml
<CustomField>
    <fullName>ServiceCode__c</fullName>
    <label>Service Code</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WBS__c/fields/Solution__c.field-meta.xml
<CustomField>
    <fullName>Solution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Solution(c)</label>
    <referenceTo>Solution__c</referenceTo>
    <relationshipLabel>Solution(c)</relationshipLabel>
    <relationshipName>Solution</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WBS__c/fields/SolutionCode__c.field-meta.xml
<CustomField>
    <fullName>SolutionCode__c</fullName>
    <label>Solution Code</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WBS__c/fields/WBSLevel__c.field-meta.xml
<CustomField>
    <fullName>WBSLevel__c</fullName>
    <description>WBS Level</description>
    <formula>IF(LEN(SUBSTITUTE(Name,&apos;-&apos;,&apos;&apos;)) == 13
			, &apos;1&apos;
			, IF(LEN(SUBSTITUTE(Name,&apos;-&apos;,&apos;&apos;)) == 15 , &apos;2&apos;, &apos;3&apos;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>WBSLevel</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Batch_MigrationForTA.cls
/**
 * @author            : younghoon.kim@dkbmc.com
 * @group             : 
 * @description       : 
 * @last modified on  : 2021-11-29
 * @last modified by  : younghoon.kim@dkbmc.com
**/
global class Batch_MigrationForTA implements DataBase.Batchable<SObject>, DataBase.stateful{
    // ↓ 배치 실행코드
    // Database.executeBatch(new Batch_MigrationForTA(), 100);

    // ↓ 데이터 추출용 쿼리
    // SELECT Id, Opportunity__c, Opportunity__r.CompanyCode__c, Opportunity__r.OpportunityCode__c, Service__c, Service__r.Service__r.Name, Service__r.Service_Code__c, Service__r.ItemNumber__c, Solution__c, Solution__r.Solution__r.Name, Solution__r.Solution_Code__c, Solution__r.SolutionType__c, Project__c, Project__r.Name, Project__r.ProjectCode__c, WBS__c, WBS__r.Name FROM TA_Mig_Target__c 
    
    private Set<String> opptyIdSet = new Set<String>();
    
    global Batch_MigrationForTA(){  
        
    }

    global DataBase.QueryLocator start(DataBase.BatchableContext BC){
        String query_Select = 'SELECT';
        String query_Fields = ' Id, Name, Service_Code__c, Opportunity__c';
        String query_From   = ' FROM Service__c';
        String query_Where   = ' WHERE Service_Code__c IN (\'22000003\', \'22000004\', \'22000006\', \'22000007\', \'20000030\') ';
        query_Where += ' AND SendSAP__c = true';
		query_Where += ' AND DeletionFlag__c = false';
        String query_Order = ' ORDER BY Opportunity__c';
        
        return DataBase.getQueryLocator(query_Select + query_Fields + query_From + query_Where + query_Order);
    }
    
    global void execute(DataBase.BatchableContext BC, List<Service__c> scope){
        List<TA_Mig_Target__c> tmtList = new List<TA_Mig_Target__c>();
        Set<String> opptyIdSet = new Set<String>();

        for(Service__c svc : scope){
            opptyIdSet.add(svc.Opportunity__c);
        }

        List<Solution__c> solList = [SELECT Id, Name, Opportunity__c, Opportunity__r.OpportunityCode__c, Service__c
                                       FROM Solution__c 
                                      WHERE Opportunity__c =: opptyIdSet
                                        AND SendSAP__c = true
                                        AND DeletionFlag__c = false];

        if(solList.size() > 0){
            for(Solution__c sol : solList){
                TA_Mig_Target__c tmt = new TA_Mig_Target__c();
                tmt.Opportunity__c = sol.Opportunity__c;
                tmt.Service__c = sol.Service__c;
                tmt.Solution__c = sol.Id;
                
                tmtList.add(tmt);
            }
        }
                                        
        if(tmtList.size() > 0) insert tmtList;
    }
    
    global void finish(DataBase.BatchableContext BC){
        
    }
    
    /*
    global DataBase.QueryLocator start(DataBase.BatchableContext BC){
        String query_Select = 'SELECT ';
        String query_Fields = ' Id, Name, OpportunityID__r.CompanyCode__c, OpportunityID__r.OpportunityCode__c, Solution__r.Service__c, ServiceCode__c, ItemNumberInt__c, Solution__c, SolutionCode__c, ProjectCode__c, Project__r.ProjectCode__c, WBSLevel__c ';
        String query_From   = ' FROM WBS__c';
        String query_Where   = ' WHERE ServiceCode__c IN (\'22000003\', \'22000004\', \'22000006\', \'22000007\', \'20000030\') ';
        query_Where += ' AND WBSLevel__c = \'3\'  ';
		query_Where += ' AND ItemNumberInt__c != 0 ';
        // query_Where += ' AND Solution__r.Service__r.SendSAP__c = true ';
        // query_Where += ' AND Solution__r.Service__r.DeletionFlag__c = false ';
        String query_Order = ' ORDER BY OpportunityID__r.OpportunityCode__c, ServiceCode__c, ItemNumberInt__c ';
        
        return DataBase.getQueryLocator(query_Select + query_Fields + query_From + query_Where + query_Order);
    }
    
    global void execute(DataBase.BatchableContext BC, List<WBS__C> scope){
        if(scope.size() > 0){
            Map<String, TA_Mig_Target__c> tmtMap = new Map<String, TA_Mig_Target__c>();
            
            for(WBS__C wbs : scope){
                // if(!(wbs.OpportunityID__r.OpportunityCode__c).contains('SDZ')){
                    if(tmtMap.get(wbs.Name) == null){
                        TA_Mig_Target__c tmt = new TA_Mig_Target__c();
                        tmt.Opportunity__c = wbs.OpportunityID__c;
                        tmt.Service__c = wbs.Solution__r.Service__c;
                        tmt.Solution__c = wbs.Solution__c;
                        tmt.Project__c = wbs.Project__c;
                        tmt.WBS__c = wbs.Id;
                            
                        tmtMap.put(wbs.Name, tmt);
                    }
                // }
            }
            if(tmtMap.size() > 0) insert tmtMap.values();
        }
    }
    
    global void finish(DataBase.BatchableContext BC){
        
    }
    */
}