force-app/main/default/objects/Master_Service__c/Master_Service__c.object-meta.xml
<CustomObject>
    <label>Master Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Service</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Service__c/fields/TechAttribute__c.field-meta.xml
<CustomField>
    <fullName>TechAttribute__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Tech. Attribute</description>
    <label>TechAttribute</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Master_Service__c/fields/Use__c.field-meta.xml
<CustomField>
    <fullName>Use__c</fullName>
    <defaultValue>false</defaultValue>
    <description>사용여부</description>
    <label>Use</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Master_Service__c/fields/ValidityEndDate__c.field-meta.xml
<CustomField>
    <fullName>ValidityEndDate__c</fullName>
    <description>유효 종료일</description>
    <label>Validity End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Master_Service__c/fields/ValidityStartDate__c.field-meta.xml
<CustomField>
    <fullName>ValidityStartDate__c</fullName>
    <description>유효 시작일</description>
    <label>Validity Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Master_Solution__c/Master_Solution__c.object-meta.xml
<CustomObject>
    <label>Master Solution</label>
    <nameField>
        <label>Master Solution Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Solution</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Solution__c/fields/PLCStatus__c.field-meta.xml
<CustomField>
    <fullName>PLCStatus__c</fullName>
    <description>PLC Status</description>
    <label>PLC Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>N</fullName>
                <label>New</label>
            </value>
            <value>
                <fullName>A</fullName>
                <label>Available for Sales</label>
            </value>
            <value>
                <fullName>D</fullName>
                <label>Discontinued for Sales</label>
            </value>
            <value>
                <fullName>E</fullName>
                <label>End of Sales</label>
            </value>
            <value>
                <fullName>P</fullName>
                <label>Planned</label>
            </value>
            <value>
                <fullName>R</fullName>
                <label>Registered for Sales</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master_Solution__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>서비스</description>
    <label>Service</label>
    <referenceTo>Master_Service__c</referenceTo>
    <relationshipName>Solution</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Master_Solution__c/fields/SolutionType__c.field-meta.xml
<CustomField>
    <fullName>SolutionType__c</fullName>
    <label>Solution Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>10</fullName>
                <label>Professional Service</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>H/W</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>S/W</label>
            </value>
            <value>
                <fullName>40</fullName>
                <label>Infra</label>
            </value>
            <value>
                <fullName>50</fullName>
                <label>BPO</label>
            </value>
            <value>
                <fullName>60</fullName>
                <label>SaaS</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <displayFormat>SVC-{YYYY}{MM}{00000}</displayFormat>
        <label>Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/BizAttribute__c.field-meta.xml
<CustomField>
    <fullName>BizAttribute__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Biz. Attribute</label>
    <referenceTo>BizAttribute__c</referenceTo>
    <relationshipName>BO_Service_Solution</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/BusinessType__c.field-meta.xml
<CustomField>
    <fullName>BusinessType__c</fullName>
    <label>Business Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/ItemNumber__c.field-meta.xml
<CustomField>
    <fullName>ItemNumber__c</fullName>
    <label>Item Number</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>BO_Service_Solution</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/SendSAP__c.field-meta.xml
<CustomField>
    <fullName>SendSAP__c</fullName>
    <defaultValue>false</defaultValue>
    <description>SAP전송여부</description>
    <label>SendSAP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service(IF)</label>
    <referenceTo>Master_Service__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>BO_Service_Solution</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/TechAttribute__c.field-meta.xml
<CustomField>
    <fullName>TechAttribute__c</fullName>
    <defaultValue>false</defaultValue>
    <description>TechAttribute</description>
    <label>TechAttribute</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Service__c/fields/WBSClass__c.field-meta.xml
<CustomField>
    <fullName>WBSClass__c</fullName>
    <label>WBS Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Solution__c/Solution__c.object-meta.xml
<CustomObject>
    <label>Solution(c)</label>
    <nameField>
        <displayFormat>SOL-{YYYY}{MM}{00000}</displayFormat>
        <label>Solution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Solution(c)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Solution__c/fields/BizAttribute__c.field-meta.xml
<CustomField>
    <fullName>BizAttribute__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Biz. Attribute(IF)</label>
    <referenceTo>BizAttribute__c</referenceTo>
    <relationshipLabel>Solution(c)</relationshipLabel>
    <relationshipName>Solution_c</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Solution__c/fields/ItemNumber__c.field-meta.xml
<CustomField>
    <fullName>ItemNumber__c</fullName>
    <formula>Service__r.ItemNumber__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Item Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Solution__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Solution(c)</relationshipLabel>
    <relationshipName>Solution_c</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Solution__c/fields/PLCStatus__c.field-meta.xml
<CustomField>
    <fullName>PLCStatus__c</fullName>
    <formula>Text(Solution__r.PLCStatus__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PLC Status(IF)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Solution__c/fields/PSType__c.field-meta.xml
<CustomField>
    <fullName>PSType__c</fullName>
    <label>PSType(IF)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Solution__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Solution(c)</relationshipLabel>
    <relationshipName>Solution</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Solution__c/fields/Solution__c.field-meta.xml
<CustomField>
    <fullName>Solution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Solution(IF)</label>
    <referenceTo>Master_Solution__c</referenceTo>
    <relationshipLabel>Solution(c)</relationshipLabel>
    <relationshipName>Solution_c</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Solution__c/fields/SolutionType__c.field-meta.xml
<CustomField>
    <fullName>SolutionType__c</fullName>
    <formula>Text(Solution__r.SolutionType__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Solution Type(IF)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Solution__c/fields/sSolution__c.field-meta.xml
<CustomField>
    <fullName>sSolution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Solution</label>
    <referenceTo>Master_Solution__c</referenceTo>
    <relationshipLabel>Solution(c) (sSolution)</relationshipLabel>
    <relationshipName>Solution_c1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Solution__c/fields/WBSClass__c.field-meta.xml
<CustomField>
    <fullName>WBSClass__c</fullName>
    <label>WBS Class(IF)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SvcSolBizAttr__c/SvcSolBizAttr__c.object-meta.xml
<CustomObject>
    <label>Service-Solution-Biz. Attribute</label>
    <nameField>
        <label>SvcSolBizAttr Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service-Solution-Biz. Attribute</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/SvcSolBizAttr__c/fields/BizAttribute__c.field-meta.xml
<CustomField>
    <fullName>BizAttribute__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Biz. Attribute</label>
    <referenceTo>BizAttribute__c</referenceTo>
    <relationshipLabel>Service-Solution-Biz. Attribute</relationshipLabel>
    <relationshipName>Service_Solution_Biz_Attribute</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SvcSolBizAttr__c/fields/PSType__c.field-meta.xml
<CustomField>
    <fullName>PSType__c</fullName>
    <label>PS Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SvcSolBizAttr__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <formula>Solution__r.Service__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Service</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SvcSolBizAttr__c/fields/Solution__c.field-meta.xml
<CustomField>
    <fullName>Solution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Solution(c)</label>
    <referenceTo>Master_Solution__c</referenceTo>
    <relationshipLabel>Service-Solution-Biz. Attribute</relationshipLabel>
    <relationshipName>Service_Solution_Biz_Attribute</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SvcSolBizAttr__c/fields/Use__c.field-meta.xml
<CustomField>
    <fullName>Use__c</fullName>
    <defaultValue>false</defaultValue>
    <description>사용 여부</description>
    <label>Use</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SvcSolBizAttr__c/fields/WBSClass__c.field-meta.xml
<CustomField>
    <fullName>WBSClass__c</fullName>
    <description>WBS Class (수익인식기준)</description>
    <label>WBS Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SC</fullName>
            </value>
            <value>
                <fullName>SI</fullName>
            </value>
            <value>
                <fullName>SM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WBS__c/WBS__c.object-meta.xml
<CustomObject>
    <label>WBS</label>
    <nameField>
        <label>WBS Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WBS</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/WBS__c/fields/ItemNumber__c.field-meta.xml
<CustomField>
    <fullName>ItemNumber__c</fullName>
    <description>솔루션의 Item Number</description>
    <label>Item Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WBS__c/fields/Solution__c.field-meta.xml
<CustomField>
    <fullName>Solution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Solution(c)</label>
    <referenceTo>Solution__c</referenceTo>
    <relationshipLabel>Solution(c)</relationshipLabel>
    <relationshipName>Solution</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WBS__c/fields/WBSClass__c.field-meta.xml
<CustomField>
    <fullName>WBSClass__c</fullName>
    <description>WBSClass</description>
    <formula>LEFT(Name, 2)</formula>
    <label>WBS Class</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OpportunitySolutionItemController.cls
/**
 * @description       : 
 * @author            : seonju.jin@dkbmc.com
 * @group             : 
 * @last modified on  : 2022-02-07
 * @last modified by  : seonju.jin@dkbmc.com
 * Modifications Log 
 * Ver   Date         Author                 Modification
 * 1.0   2020-11-19   seonju.jin@dkbmc.com   Initial Version
 * 1.1   2023-08-02   divyam.gupta@samsung.com  Mysales-267 Add validation logic for changing solution
**/
public without sharing class OpportunitySolutionItemController {
    
    @AuraEnabled
    public static List<Options> getSolutionOptions(String serviceId, String boId, String collaboBoId, Boolean isHQ, Boolean isCollaboration, Boolean getAllTA){
        List<Options> loptions = new List<Options>();
        Set<Options> setOptions = new set<Options>();
        List<Master_Solution__c> masterSolList;
        /**
         * companyCode가 본사이고 법인과 협업인 경우
         * 법인이 선택한 솔루션 pickvalue만 나와야한다.
         */
        List<Map<String,String>> lmap = Utils.getPicklistOptionType('Master_Solution__c', 'SolutionType__c');
        List<Map<String,String>> PLCMap = Utils.getPicklistOptionType('Master_Solution__c', 'PLCStatus__c');
        Set<Id> solIdSet = new Set<Id>();

        Date today = System.today();
        String queryStr= 'SELECT Id, Name, SolutionType__c, toLabel(PLCStatus__c), Service__c FROM Master_Solution__c WHERE Use__c = true AND (ValidityStartDate__c  < :today AND ValidityEndDate__c  > :today)';
        if(isHQ && isCollaboration){
            Set<Id> boIdSet = new Set<Id>();
            boIdSet.add(boId);
            boIdSet.add(collaboBoId);

            List<Solution__c> lsolution = [SELECT Id, Solution__c, sSolution__c FROM Solution__c 
                                            WHERE Service__r.Opportunity__c =: boIdSet ORDER BY Solution__r.Name];
            
            for(Solution__c sol : lsolution){
                solIdSet.add(sol.Solution__c);
                solIdSet.add(sol.sSolution__c);
            }
        }

        if(solIdSet.size() > 0) queryStr += ' AND Id IN :solIdSet';
        if(getAllTA){
            queryStr += ' AND Service__r.TechAttribute__c = true';
        } else{
            queryStr += ' AND Service__c = :serviceId';
        }
        
        System.debug('queryStr:' + queryStr);
        masterSolList = Database.query(queryStr);
        Set<String> solutionNameSet = new Set<String>();
        for(Master_Solution__c masterSol : masterSolList){
            
            Options opts = new Options();
            opts.Id = masterSol.Id;
            opts.Name = masterSol.Name;
            opts.Code = masterSol.SolutionType__c;
            opts.parentId = masterSol.Service__c;
            String codeNm = '';
            
            for(Map<String,String> map1 : lmap){
                if(map1.get('value') == masterSol.SolutionType__c){
                    codeNm = map1.get('label');
                    break;
                } 
            }
            Map<String,String> otherCodeMap = new Map<String,String>();
            otherCodeMap.put('PLCStatus',masterSol.PLCStatus__c );

            opts.CodeNm = codeNm;
            opts.otherCode = otherCodeMap;

            if(solutionNameSet.contains(opts.Name)) continue;   //중복옵션 continue
            
            solutionNameSet.add(opts.Name);
            loptions.add(opts);
        }

        return loptions;
    }

    @AuraEnabled
    public static Boolean professionalServiceCheck(Id opptyId, Integer itemNumber){
        System.debug('opptyId:' + opptyId);
        System.debug('itemNumber:' + itemNumber);
        List<Solution__c> solList = [SELECT Id, Name FROM Solution__c WHERE Opportunity__c =:opptyId and SendSAP__c = true AND ItemNumber__c =:itemNumber AND Solution__r.SolutionType__c = '10'];
        return (solList.size() == 0) ? true : false;
    }
    
    /** 
    * @description 솔루션과 관련된 BizAttribute 리스트 조회
    * @author seonju.jin@dkbmc.com | 2021-09-09 
    * @param List<String> solIdList     솔루션 룩업 Id List
    * @param Boolean solChangeCheck        화면에서 솔루션 변경시에만 체크
    * @return Map<String, List<Options>> 
    **/
    @AuraEnabled
    public static Map<String,Object> getBizAttributeOptions(List<String> solIdList, String solPSType, Boolean solChangeCheck){
        System.debug(solIdList);
        Set<String> solIdSet = new Set<String>();
        for(String s : solIdList){solIdSet.add(s);}
        Map<String,List<Options>> returnOpts = new Map<String,List<Options>>();
        
        Boolean returnMsg = true;
        Map<String,Object> returnMap = new Map<String,Object>{
            'OPTIONS' => new List<Options>(),
            'MESSAGE' => true                   //변경할 솔루션 하위 bizAttirbute 리스트에 동일한 PSType이 존재하지 않으면 false
        };

        System.debug('solPSType:' + solPSType);

        List<SvcSolBizAttr__c> objList = [SELECT Id, Solution__c, Solution__r.PLCStatus__c, BizAttribute__c, WBSClass__c, PSType__c, toLabel(BusinessType__c) FROM SvcSolBizAttr__c WHERE Solution__c IN :solIdSet AND Use__c = true];

        List<String> a = new List<String>();
        for(SvcSolBizAttr__c o : objList) a.add(String.valueOf(o.BizAttribute__c));

        List<BizAttribute__c> lattr = [SELECT Id, Name , Code__c
                                           FROM BizAttribute__c 
                                          WHERE Id IN : a AND Active__c = true ORDER BY Name];

        Boolean samePsType = false;
        for(SvcSolBizAttr__c solbiz : objList){
            List<Options> optionList = new List<Options>();
            for(BizAttribute__c attr: lattr){
                if(solbiz.BizAttribute__c == attr.Id){
                    Options opt = new Options();
                    opt.Id = attr.Id;
                    opt.Name = attr.Name;
                    opt.Code = attr.Code__c;

                    String wbsClass = (solbiz.WBSClass__c == null) ? '' : solbiz.WBSClass__c;
                    String psType = (solbiz.PSType__c == null) ? '' : solbiz.PSType__c;
                    String bizType = (solbiz.BusinessType__c == null) ? '' : solbiz.BusinessType__c;
                    String plcStatus = (solbiz.Solution__r.PLCStatus__c == null) ? '' : solbiz.Solution__r.PLCStatus__c;

                    //2021.09.09
                    if(solChangeCheck && !samePsType){
                        samePsType = (solPSType == psType) ? true : false;
                    }

                    Map<String,String> otherCodeMap = new Map<String,String>();
                    otherCodeMap.put('WBSClass', wbsClass);
                    otherCodeMap.put('PSType', psType);
                    otherCodeMap.put('BizType', bizType);
                    opt.otherCode = otherCodeMap;
                    optionList = (returnOpts.get(solbiz.Solution__c) == null) ? new List<Options>() : returnOpts.get(solbiz.Solution__c);
                    optionList.add(opt);
                    returnOpts.put(solbiz.Solution__c , optionList);
                }
            }
        }
        returnMsg = (solChangeCheck) ? samePsType : true;

        returnMap.put('OPTIONS',returnOpts);
        returnMap.put('MESSAGE',returnMsg);
        return returnMap;
    }

    @AuraEnabled
    public static List<Options> getSalesTypeOptions(){
        Schema.DescribeFieldResult salesTypeFieldResult = Solution__c.SalesType__c.getDescribe();
        List<Schema.PicklistEntry> salesTypeList = salesTypeFieldResult.getPicklistValues();
        List<Options> options = new List<Options>();
        for (Schema.PicklistEntry salesType: salesTypeList) {
            Options opt = new Options();
            opt.Id = salesType.getValue();
            opt.Name = salesType.getLabel();
            options.add(opt);
        }
        options.sort();
        return options;
    }
    //START V 1.1
 @AuraEnabled
    public static String getSolutionduplicterecord(String serviceId,String boId,String attributeid,String solutiontype){
        List<Solution__c> sollist = [select id,Name from Solution__c where Opportunity__c=:boId AND sSolution__c=:solutiontype AND Service__c =:serviceId AND sBizAttribute__c=:attributeid AND DeletionFlag__c = false];
        String returnval;
        if(sollist.size() > 0){
            returnval = 'DupliSolrecord';
        }
        else {
            returnval = 'NotDupliSolrecord';
        }
        
        
        return returnval;
    }
    //END V 1.1
    public class Options implements Comparable {
        @AuraEnabled
        public String Id {get;set;}
        @AuraEnabled
        public String Name {get;set;}
        @AuraEnabled
        public String Code {get;set;}
        @AuraEnabled
        public String CodeNm {get;set;}
        @AuraEnabled
        public String parentId {get;set;}   //master service record id
        @AuraEnabled
        public Boolean migCheck {get;set;}
        @AuraEnabled
        public Map<String,String> otherCode {get;set;}

        public Integer compareTo(Object compareTo) {
            Options compareToOpt = (Options)compareTo;
            if (Name == compareToOpt.Name) return 0;
            if (Name > compareToOpt.Name) return 1;
            return -1;
        }
    }
}