force-app/main/default/objects/Company__c/Company__c.object-meta.xml
<CustomObject>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Company</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Company__c/fields/CompanyCode__c.field-meta.xml
<CustomField>
    <fullName>CompanyCode__c</fullName>
    <description>회사코드</description>
    <label>Company Code</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Company__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AE</fullName>
                <label>United Arab Emirates</label>
            </value>
            <value>
                <fullName>AR</fullName>
                <label>Argentina</label>
            </value>
            <value>
                <fullName>AT</fullName>
                <label>Austria</label>
            </value>
            <value>
                <fullName>AU</fullName>
                <label>Australia</label>
            </value>
            <value>
                <fullName>AW</fullName>
                <label>Aruba</label>
            </value>
            <value>
                <fullName>AZ</fullName>
                <label>Azerbaijan</label>
            </value>
            <value>
                <fullName>BD</fullName>
                <label>Bangladesh</label>
            </value>
            <value>
                <fullName>BE</fullName>
                <label>Belgium</label>
            </value>
            <value>
                <fullName>BG</fullName>
                <label>Bulgaria</label>
            </value>
            <value>
                <fullName>BO</fullName>
                <label>Bolivia</label>
            </value>
            <value>
                <fullName>BR</fullName>
                <label>Brazil</label>
            </value>
            <value>
                <fullName>BY</fullName>
                <label>Belarus</label>
            </value>
            <value>
                <fullName>CA</fullName>
                <label>Canada</label>
            </value>
            <value>
                <fullName>CH</fullName>
                <label>Switzerland</label>
            </value>
            <value>
                <fullName>CL</fullName>
                <label>Chile</label>
            </value>
            <value>
                <fullName>CN</fullName>
                <label>China</label>
            </value>
            <value>
                <fullName>CO</fullName>
                <label>Colombia</label>
            </value>
            <value>
                <fullName>CR</fullName>
                <label>Costa Rica</label>
            </value>
            <value>
                <fullName>CS</fullName>
                <label>Serbia and Montenegro</label>
            </value>
            <value>
                <fullName>CW</fullName>
                <label>Curaçao</label>
            </value>
            <value>
                <fullName>CY</fullName>
                <label>Cyprus</label>
            </value>
            <value>
                <fullName>CZ</fullName>
                <label>Czech Republic</label>
            </value>
            <value>
                <fullName>DE</fullName>
                <label>Germany</label>
            </value>
            <value>
                <fullName>DK</fullName>
                <label>Denmark</label>
            </value>
            <value>
                <fullName>DM</fullName>
                <label>Dominica</label>
            </value>
            <value>
                <fullName>DO</fullName>
                <label>Dominican Republic</label>
            </value>
            <value>
                <fullName>DZ</fullName>
                <label>Algeria</label>
            </value>
            <value>
                <fullName>EC</fullName>
                <label>Ecuador</label>
            </value>
            <value>
                <fullName>EG</fullName>
                <label>Egypt</label>
            </value>
            <value>
                <fullName>ES</fullName>
                <label>Spain</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Company__c/fields/EPCompanyCode__c.field-meta.xml
<CustomField>
    <fullName>EPCompanyCode__c</fullName>
    <description>인사 시스템 회사번호</description>
    <label>EP Company Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CostCenter__c/CostCenter__c.object-meta.xml
<CustomObject>
    <label>Cost Center</label>
    <nameField>
        <label>Cost Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cost Center</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CostCenter__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Company</label>
    <referenceTo>Company__c</referenceTo>
    <relationshipLabel>Cost Center</relationshipLabel>
    <relationshipName>Cost_Center</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CostCenter__c/fields/CompanyCode__c.field-meta.xml
<CustomField>
    <fullName>CompanyCode__c</fullName>
    <label>Company Code</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CostCenter__c/fields/CostCenter__c.field-meta.xml
<CustomField>
    <fullName>CostCenter__c</fullName>
    <externalId>true</externalId>
    <label>Cost Center</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CostCenter__c/fields/CostCenterName__c.field-meta.xml
<CustomField>
    <fullName>CostCenterName__c</fullName>
    <label>Cost Center Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CostCenter__c/fields/Node1__c.field-meta.xml
<CustomField>
    <fullName>Node1__c</fullName>
    <label>NODE1</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CostCenter__c/fields/Node2__c.field-meta.xml
<CustomField>
    <fullName>Node2__c</fullName>
    <label>NODE2</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CostCenter__c/fields/Node3__c.field-meta.xml
<CustomField>
    <fullName>Node3__c</fullName>
    <label>NODE3</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CostCenter__c/fields/Node4__c.field-meta.xml
<CustomField>
    <fullName>Node4__c</fullName>
    <label>NODE4</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CostCenter__c/fields/Node5__c.field-meta.xml
<CustomField>
    <fullName>Node5__c</fullName>
    <label>NODE5</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CostCenter__c/fields/Text2__c.field-meta.xml
<CustomField>
    <fullName>Text2__c</fullName>
    <label>TEXT2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CostCenter__c/fields/ZZCheck__c.field-meta.xml
<CustomField>
    <fullName>ZZCheck__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ZZCheck</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Organization__c/Organization__c.object-meta.xml
<CustomObject>
    <label>Organization</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organizations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Organization__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Company</label>
    <referenceTo>Company__c</referenceTo>
    <relationshipName>Branch</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TXPmanpower__c/TXPmanpower__c.object-meta.xml
<CustomObject>
    <label>TXP information</label>
    <nameField>
        <label>TXP manpower input information Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TXP information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TXPmanpower__c/fields/companycode__c.field-meta.xml
<CustomField>
    <fullName>companycode__c</fullName>
    <label>Company code</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TXPmanpower__c/fields/E_Projectcode__c.field-meta.xml
<CustomField>
    <fullName>E_Projectcode__c</fullName>
    <label>Execute PM Projectcode</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TXPmanpower__c/fields/ExecutionPMEdDt__c.field-meta.xml
<CustomField>
    <fullName>ExecutionPMEdDt__c</fullName>
    <label>Execute PM EndDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TXPmanpower__c/fields/ExecutionPMNo__c.field-meta.xml
<CustomField>
    <fullName>ExecutionPMNo__c</fullName>
    <label>Execute PM Employee No</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TXPmanpower__c/fields/ExecutionPMPlan__c.field-meta.xml
<CustomField>
    <fullName>ExecutionPMPlan__c</fullName>
    <label>ExecutionPM Plan Y/N</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TXPmanpower__c/fields/ExecutionPMStatus__c.field-meta.xml
<CustomField>
    <fullName>ExecutionPMStatus__c</fullName>
    <label>Execute PM Status</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TXPmanpower__c/fields/ExecutionPMStDt__c.field-meta.xml
<CustomField>
    <fullName>ExecutionPMStDt__c</fullName>
    <label>Execute PM StartDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TXPmanpower__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>TXP_manpower_input_information</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TXPmanpower__c/fields/P_Projectcode__c.field-meta.xml
<CustomField>
    <fullName>P_Projectcode__c</fullName>
    <label>Proposal PM Projectcode</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TXPmanpower__c/fields/ProposalPMEdDt__c.field-meta.xml
<CustomField>
    <fullName>ProposalPMEdDt__c</fullName>
    <label>Proposal PM EndDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TXPmanpower__c/fields/ProposalPMNo__c.field-meta.xml
<CustomField>
    <fullName>ProposalPMNo__c</fullName>
    <label>Proposal PM Employee No</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TXPmanpower__c/fields/ProposalPMPlan__c.field-meta.xml
<CustomField>
    <fullName>ProposalPMPlan__c</fullName>
    <label>ProposalPM Plan Y/N</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TXPmanpower__c/fields/ProposalPMStatus__c.field-meta.xml
<CustomField>
    <fullName>ProposalPMStatus__c</fullName>
    <label>Proposal PM Status</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TXPmanpower__c/fields/ProposalPMStDt__c.field-meta.xml
<CustomField>
    <fullName>ProposalPMStDt__c</fullName>
    <label>Proposal PM StartDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/Batch_SendTXPManpowerInfo_Test.cls
/**
* @description       : Test Class of Batch_SendTXPManpowerInfo(IF-184)
* @author            : vikrant.ks@samsung.com
* @group             : 
* @last modified on  : 2023-12-05
* @last modified by  : vikrant.ks@samsung.com 
* Modifications Log 
* Ver   Date         Author                   Modification
* 1.0   2023-12-05   vikrant.ks@samsung.com   Initial Version(MySales 374) 
**/
@isTest(SeeAllData=false)
public class Batch_SendTXPManpowerInfo_Test {
    @TestSetup
    static void setData(){
    	Id rdType = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('MDG').getRecordTypeId();
        Account acc = new Account (
        Name = 'Test1234',AccountNumber='A2999999',RecordTypeId = rdType, MDGCheck__c = true, mLoevm__c = false);
        insert acc;
        Organization__c org = new Organization__c();
        insert org;
        RecordType RT_OPPTY_HQ   = [SELECT Id FROM RecordType WHERE SobjectType = 'Opportunity' AND DeveloperName = 'HQ' Limit 1];
        
        Company__c insertCompany = new Company__c (
            Name                = 'T100 - Name'
            , CompanyCode__c    = 'T100'
            , EPCompanyCode__c  = 'EP1'
            , CurrencyIsoCode   = 'KRW'
            , Country__c        = 'Korea, Republic of'
        );
        insert insertCompany;
		System.debug('Company: '+insertCompany);
        
        CostCenter__c insertCostCenter = new CostCenter__c(
                    Name                = '기술전략팀(T100-11331)'
                    , CurrencyIsoCode   = 'KRW'
                    , CompanyCode__c    = 'T100'
                    , CostCenterName__c = '기술전략팀'
                    , CostCenter__c     = 'T100-11331'
                    , Node1__c          = 'T100'
                    , Node2__c          = 'T100SB'
                    , Node3__c          = 'T100SB1'
                    , Node4__c          = 'T100SB13'
                    , Node5__c          = 'T100SB131'
            		, ZZCheck__c        = true
            		, Text2__c      = '클라우드서비스사업부'
                    , Company__c        = insertCompany.Id
                );
        insert insertCostCenter;     
        System.debug('CostCenter: '+insertCostCenter);
        
        Opportunity Opportunity1 = new Opportunity(
            Name = 'MySales',
            CurrencyIsoCode='EUR',
            OpportunityCode__c='SDS-22001260',
            StageName= 'Z03',
            CspMspType__c = 'CSP',
            Amount = 78,
            AccountId = acc.id,
            SalesOrganization__c = org.id,
            DeliveryOrganization__c = org.id,
            CloseDate = System.today().addDays(5),
            OpportunityStatus__c='E0003',
            CMBizType__c='CSP_SCP',
            RecordTypeId = RT_OPPTY_HQ.Id,
            SalesDepartment__c= insertCostCenter.Id 
            );
        
         insert Opportunity1;
        
        TXPmanpower__c txpTemp      = new TXPmanpower__c();
        txpTemp.Opportunity__c      = Opportunity1.Id;
        txpTemp.BOCode__c           = Opportunity1.OpportunityCode__c;
        txpTemp.companycode__c      = 'T100';
        txpTemp.ProposalPMNo__c     = '12345';
        txpTemp.ProposalPMStatus__c = 'ASSGNREQ';
        txpTemp.ProposalPMStDt__c   = Date.valueOf('2023-1-8');
        txpTemp.ProposalPMEdDt__c   = Date.valueOf('2023-12-31');
        txpTemp.ExecutionPMNo__c    = '12345';
        txpTemp.ExecutionPMStatus__c= 'ASSGNEND';
        txpTemp.ExecutionPMStDt__c  = Date.valueOf('2023-10-1');
        txpTemp.ExecutionPMEdDt__c  = Date.valueOf('2024-2-3');
        txpTemp.ProposalPMPlan__c   = 'Y';
        txpTemp.ExecutionPMPlan__c  = 'Y';
        txpTemp.P_Projectcode__c    = '09643';
        txpTemp.E_Projectcode__c    = '123567';
        
        upsert txpTemp;
        System.debug('txpTemp'+txpTemp);
    }
    @isTest
    public static void TXPManpowerInputInfoTest_1(){
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new IF_Callout_TestMock(200));
        
        String oppID = [Select Id from Opportunity Limit 1].Id;
        Set<String> BoList = new Set<String>{oppID};
            
		Batch_SendTXPManpowerInfo Batch_SendTXPInfo = new Batch_SendTXPManpowerInfo();
        Batch_SendTXPInfo.BoIdList = BoList;
		DataBase.executeBatch(Batch_SendTXPInfo, 200); 
        
        Test.stopTest();
    }
}