force-app/main/default/objects/Company__c/Company__c.object-meta.xml
<CustomObject>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Company</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Company__c/fields/CompanyCode__c.field-meta.xml
<CustomField>
    <fullName>CompanyCode__c</fullName>
    <description>회사코드</description>
    <label>Company Code</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CostCenter__c/CostCenter__c.object-meta.xml
<CustomObject>
    <label>Cost Center</label>
    <nameField>
        <label>Cost Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cost Center</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CostCenter__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Company</label>
    <referenceTo>Company__c</referenceTo>
    <relationshipLabel>Cost Center</relationshipLabel>
    <relationshipName>Cost_Center</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CostCenter__c/fields/CompanyCode__c.field-meta.xml
<CustomField>
    <fullName>CompanyCode__c</fullName>
    <label>Company Code</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CostCenter__c/fields/CostCenter__c.field-meta.xml
<CustomField>
    <fullName>CostCenter__c</fullName>
    <externalId>true</externalId>
    <label>Cost Center</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CostCenter__c/fields/CostCenterName__c.field-meta.xml
<CustomField>
    <fullName>CostCenterName__c</fullName>
    <label>Cost Center Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CostCenter__c/fields/Node1__c.field-meta.xml
<CustomField>
    <fullName>Node1__c</fullName>
    <label>NODE1</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CostCenter__c/fields/Node2__c.field-meta.xml
<CustomField>
    <fullName>Node2__c</fullName>
    <label>NODE2</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CostCenter__c/fields/Node3__c.field-meta.xml
<CustomField>
    <fullName>Node3__c</fullName>
    <label>NODE3</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CostCenter__c/fields/Node4__c.field-meta.xml
<CustomField>
    <fullName>Node4__c</fullName>
    <label>NODE4</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CostCenter__c/fields/Node5__c.field-meta.xml
<CustomField>
    <fullName>Node5__c</fullName>
    <label>NODE5</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CostCenter__c/fields/Text2__c.field-meta.xml
<CustomField>
    <fullName>Text2__c</fullName>
    <label>TEXT2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CostCenter__c/fields/ZZCheck__c.field-meta.xml
<CustomField>
    <fullName>ZZCheck__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ZZCheck</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Delivery_Probabiliy__c/Delivery_Probabiliy__c.object-meta.xml
<CustomObject>
    <label>Opportunity Delivery probability</label>
    <nameField>
        <label>Delivery Probability</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Delivery probability</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Probabiliy__c/fields/Companycode__c.field-meta.xml
<CustomField>
    <fullName>Companycode__c</fullName>
    <label>Companycode</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Delivery_Probabiliy__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Delivery probability</relationshipLabel>
    <relationshipName>Opportunity_Delivery_probability</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RevenueScheduleOpportunity__c/RevenueScheduleOpportunity__c.object-meta.xml
<CustomObject>
    <label>Opportunity Revenue Schedule</label>
    <nameField>
        <displayFormat>RS{0000000000}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Revenue Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RevenueScheduleOpportunity__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <label>Parent</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Revenue Schedules</relationshipLabel>
    <relationshipName>OpportunityRevenueSchedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/RevenueScheduleOpportunity__c/fields/Period__c.field-meta.xml
<CustomField>
    <fullName>Period__c</fullName>
    <label>Period</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RevenueScheduleOpportunity__c/fields/Revenue__c.field-meta.xml
<CustomField>
    <fullName>Revenue__c</fullName>
    <label>Revenue</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/OppRevenueSchTriggerHandler_Test.cls
/**
 * @description       : 
 * @author            : d.ashish@samsung.com
 * @group             : 
 * @last modified on  : 2024-02-22
 * @last modified by  : d.ashish@samsung.com
 * Modifications Log 
 * Ver   Date         Author                    Modification
 * 1.0   2024-02-22   d.ashish@samsung.com          Initial Version
 **/

@isTest
public class OppRevenueSchTriggerHandler_Test {
    @isTest
    public static void testRevenueSchTrigger(){
        
        Date tDate = Date.today();
        RecordType RT_OPPTY_HQ = [SELECT Id, DeveloperName FROM RecordType WHERE SobjectType = 'Opportunity' AND DeveloperName = 'HQ' Limit 1];
        Account acc = new Account( 
            Name = 'Test Account',
            MDGCheck__c = true
        );
        insert acc;
        Company__c cmp = new Company__c(
                Name = 'comp',
                CompanyCode__c = 'T100'
            );
            insert cmp;
            
        CostCenter__c costCenterHQ = new CostCenter__c(
            Name                = '기술전략팀(T100-11331)'
            , CurrencyIsoCode   = 'KRW'
            , CompanyCode__c    = 'T100'
            , CostCenterName__c = '기술전략팀'
            , CostCenter__c     = 'T100-11331'
            , Node1__c          = 'T100'
            , Node2__c          = System.Label.RevenueScheduleNote2//'T100S4'//'T100SB'
            , Node3__c          = 'T100SB1'
            , Node4__c          = 'T100SB13'
            , Node5__c          = 'T100SB131'            
            , ZZCheck__c        = true
            , Text2__c			= '솔루션사업부'//'클라우드서비스사업부'
            , Company__c = cmp.Id
        );
        insert costCenterHQ;
        
        Opportunity opptyHQ1 = new Opportunity(
            Name = 'Test Opportunity',
            RecordTypeId = RT_OPPTY_HQ.Id,
            CurrencyIsoCode = 'KRW',
            Amount = 10000,
            cRevenueStartDate__c = tDate,
            cRevenueEndDate__c = tDate.addMonths(1),
            CspMspType__c = 'CSP', 
            OtherCSP__c = 'CSP1',
            MSP_Amount__c = 200,
            StageName = 'Z01',
            cPrimarySalesDepartment__c = costCenterHQ.Id,
            SalesDepartment__c = costCenterHQ.Id,
            CloseDate = Date.today(),
            AccountId = acc.Id,
            cOriginAcc__c = acc.Id,
            cLeadID__c = NULL
        );
        insert opptyHQ1;
        
           Delivery_Probabiliy__c del = new Delivery_Probabiliy__c(name = 'test', Opportunity__c = opptyHQ1.Id);
        insert del;
     
        List<RevenueScheduleOpportunity__c> oppRS = new List<RevenueScheduleOpportunity__c>();
        RevenueScheduleOpportunity__c ora = new RevenueScheduleOpportunity__c(
        	Parent__c = opptyHQ1.Id,
            ScheduleDate__c = opptyHQ1.cRevenueStartDate__c,
            Revenue__c = 10,
            Period__c = '2'
        );
        oppRS.add(ora);
        RevenueScheduleOpportunity__c ora1 = new RevenueScheduleOpportunity__c(
        	Parent__c = opptyHQ1.Id,
            ScheduleDate__c = opptyHQ1.cRevenueStartDate__c,
            Revenue__c = 10,
            Period__c = '2'
        );
        oppRS.add(ora1);
        insert oppRS;
        
        update oppRS;
    }
}