force-app/main/default/objects/Company__c/Company__c.object-meta.xml
<CustomObject>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Company</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CostCenter__c/CostCenter__c.object-meta.xml
<CustomObject>
    <label>Cost Center</label>
    <nameField>
        <label>Cost Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cost Center</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CostCenter__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Company</label>
    <referenceTo>Company__c</referenceTo>
    <relationshipLabel>Cost Center</relationshipLabel>
    <relationshipName>Cost_Center</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CostCenter__c/fields/CostCenter__c.field-meta.xml
<CustomField>
    <fullName>CostCenter__c</fullName>
    <externalId>true</externalId>
    <label>Cost Center</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CostCenter__c/fields/CostCenterName__c.field-meta.xml
<CustomField>
    <fullName>CostCenterName__c</fullName>
    <label>Cost Center Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Lead__c/Sales_Lead__c.object-meta.xml
<CustomObject>
    <label>Sales Lead</label>
    <nameField>
        <label>Sales Lead Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Leads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Lead__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>예상금액</description>
    <inlineHelpText>Required Information only for HQ users when creating IT Sales Lead / Required information when converting</inlineHelpText>
    <label>Amount(*)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sales_Lead__c/fields/Authority__c.field-meta.xml
<CustomField>
    <fullName>Authority__c</fullName>
    <defaultValue>false</defaultValue>
    <description>권한</description>
    <inlineHelpText>Whether the customer in charge has obtained the right to perform the business (change the stage to Hot when satisfying two or more BANTs)</inlineHelpText>
    <label>Authority</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sales_Lead__c/fields/Budget__c.field-meta.xml
<CustomField>
    <fullName>Budget__c</fullName>
    <defaultValue>false</defaultValue>
    <description>예산확보 여부</description>
    <inlineHelpText>Whether to have a customer budget (change the stage to Hot when satisfying two or more BANTs)</inlineHelpText>
    <label>Budget</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sales_Lead__c/fields/CampaignId__c.field-meta.xml
<CustomField>
    <fullName>CampaignId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>캠페인</description>
    <label>Campaign ID</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipName>BO_Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Lead__c/fields/CloseDate__c.field-meta.xml
<CustomField>
    <fullName>CloseDate__c</fullName>
    <description>예상수주일자</description>
    <label>Close Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Sales_Lead__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <description>고객사 명</description>
    <label>Company</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Lead__c/fields/LeadChannel__c.field-meta.xml
<CustomField>
    <fullName>LeadChannel__c</fullName>
    <label>Lead Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Direct Registration</fullName>
            </value>
            <value>
                <fullName>Marketing Lead Converted</fullName>
            </value>
            <value>
                <fullName>Demand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Lead__c/fields/LeadStage__c.field-meta.xml
<CustomField>
    <fullName>LeadStage__c</fullName>
    <description>Lead Stage</description>
    <label>Lead Stage</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cold</fullName>
                <color>#33CCFF</color>
                <label>Cold</label>
            </value>
            <value>
                <fullName>Warm</fullName>
                <color>#FF9900</color>
                <label>Warm</label>
            </value>
            <value>
                <fullName>Hot</fullName>
                <color>#FF0000</color>
                <label>Hot</label>
            </value>
            <value>
                <fullName>Converted</fullName>
                <color>#BBBBBB</color>
                <label>Converted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Lead__c/fields/LeadStatus__c.field-meta.xml
<CustomField>
    <fullName>LeadStatus__c</fullName>
    <description>Sales Lead Status</description>
    <inlineHelpText>Sales Lead Status</inlineHelpText>
    <label>Lead Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Process</fullName>
                <default>true</default>
                <label>In Process</label>
            </value>
            <value>
                <fullName>Close</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Lead__c/fields/RevenueEndDate__c.field-meta.xml
<CustomField>
    <fullName>RevenueEndDate__c</fullName>
    <description>(계약) 매출 종료일</description>
    <label>Contract End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Sales_Lead__c/fields/RevenueStartDate__c.field-meta.xml
<CustomField>
    <fullName>RevenueStartDate__c</fullName>
    <description>(계약) 매출 시작일</description>
    <label>Contract Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Sales_Lead__c/fields/SalesDepartment__c.field-meta.xml
<CustomField>
    <fullName>SalesDepartment__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Required Information only for HQ users when creating IT Sales Lead / Required information when converting</inlineHelpText>
    <label>Sales Dept. 3(*)</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR (2 AND 3 AND 4)</booleanFilter>
        <errorMessage>Closed departments cannot be selected.</errorMessage>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>Custom System Administrator, System Administrator</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>notEqual</operation>
            <value>Custom System Administrator, System Administrator</value>
        </filterItems>
        <filterItems>
            <field>CostCenter__c.Closed__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$User.CompanyCode__c</field>
            <operation>equals</operation>
            <valueField>CostCenter__c.CompanyCode__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CostCenter__c</referenceTo>
    <relationshipLabel>Sales Leads</relationshipLabel>
    <relationshipName>Sales_Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Lead_Team__c/Sales_Lead_Team__c.object-meta.xml
<CustomObject>
    <label>Sales Lead Team</label>
    <nameField>
        <displayFormat>SLT-{00000}</displayFormat>
        <label>Sales Lead Team No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Lead Team</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Lead_Team__c/fields/AccessLevel__c.field-meta.xml
<CustomField>
    <fullName>AccessLevel__c</fullName>
    <label>Access Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Read</fullName>
            </value>
            <value>
                <fullName>Edit</fullName>
                <label>Read/Write</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Lead_Team__c/fields/Sales_Lead__c.field-meta.xml
<CustomField>
    <fullName>Sales_Lead__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Sales Lead</label>
    <referenceTo>Sales_Lead__c</referenceTo>
    <relationshipLabel>Sales Lead Team</relationshipLabel>
    <relationshipName>Sales_Lead_Team</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Lead_Team__c/fields/SalesLead_TeamMember__c.field-meta.xml
<CustomField>
    <fullName>SalesLead_TeamMember__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Lead Team Member</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sales_Lead_Team</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Lead_Team__c/fields/Team_Role__c.field-meta.xml
<CustomField>
    <fullName>Team_Role__c</fullName>
    <label>Team Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Proposal PM</fullName>
            </value>
            <value>
                <fullName>Sales Rep</fullName>
            </value>
            <value>
                <fullName>Sales Manager</fullName>
            </value>
            <value>
                <fullName>Account Manager</fullName>
            </value>
            <value>
                <fullName>Channel Manager</fullName>
            </value>
            <value>
                <fullName>Executive Sponsor</fullName>
            </value>
            <value>
                <fullName>Lead Qualifier</fullName>
            </value>
            <value>
                <fullName>Pre-Sales Consultant</fullName>
            </value>
            <value>
                <fullName>Strategy Committee Officer</fullName>
            </value>
            <value>
                <fullName>Strategy Committee Member</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ManualSharingController_Test.cls
/**
 * @description       : 
 * @author            : hj.lee@dkbmc.com
 * @group             : 
 * @last modified on  : 2024-02-06
 * @last modified by  : vikrant.ks@samsung.com
 * Modifications Log 
 * Ver   Date         Author             		Modification
 * 1.0   2020-11-16   hj.lee@dkbmc.com   		Initial Version
 * 1.1   2024-02-06   vikrant.ks@samsung.com    Increased code coverage.(MySales-389)
**/
@isTest
public class ManualSharingController_Test {
    static Macro macro;
    Static Account acc;
    static User user1;
    static UserRole ur;
    static UserRole urole;
    static Group gr;
    
    //V1.1 Start
	static User member1;
    static User member2;
    static Campaign campaign1;
    static CostCenter__c costCenter;
    static Sales_Lead__c sl;
    static Sales_Lead_Team__c slt;
    //V1.1 End
    
    static{
        
        System.runAs(new User(Id=UserInfo.getUserId())){
            urole = new UserRole();
            urole.Name = 'New Role';
            insert urole;
        }
        gr = [SELECT Id FROM Group WHERE RelatedId = :urole.Id][0];


        acc = new Account();
        acc.Name = 'TestAccount';

        insert acc; 

        macro = new Macro();
        macro.Name = 'test';
        insert macro;
        
        Profile pf = [SELECT Id FROM Profile WHERE Name = 'System Administrator' OR Name = '시스템 관리자'];
        
         user1 = new User(
            Alias = 'TestUser'
            , Email='SysAdminTestuser@dkbmc.com'
            , EmailEncodingKey='UTF-8'
            , LastName='TestUser'
            , LanguageLocaleKey='en_US'
            , LocaleSidKey='en_US'
            , EmployeeNumber='AC100000'
            , TimeZoneSidKey='Asia/Seoul'
            , UserName='SysAdminTestuser@samsung.com'
            , ProfileId = pf.Id
        );
                                
        insert user1;
        

    }

    @isTest
    static void initCompTest() {        
        Map<String, Object> insertdata = new Map<String, Object>();

        insertdata.put('ParentId', macro.Id);
        insertdata.put('UserOrGroupId', user1.Id);
        insertdata.put('AccessLevel', 'Edit');
        insertdata.put('RowCause', 'Manual');

        Id insertId = ManualSharingController.insertData(macro.Id, JSON.serialize(insertdata));
        MacroShare ms = [SELECT Id, ParentId, UserOrGroupId, AccessLevel, RowCause FROM MacroShare WHERE UserOrGroupId = :user1.Id];
        System.assertEquals(ms.ParentId, macro.Id);
        System.assertEquals(ms.AccessLevel, 'Edit');

        insertdata = new Map<String, Object>();

        insertdata.put('ParentId', macro.Id);
        insertdata.put('UserOrGroupId', gr.Id);
        insertdata.put('AccessLevel', 'Read');
        insertdata.put('RowCause', 'Manual');

        ManualSharingController.insertData(macro.Id, JSON.serialize(insertdata));
        
        Map<String,Object> sharingList = ManualSharingController.getSharingData(macro.Id);

        List<Map<String,Object>> sResult = ManualSharingController.getSearchData('TestUser', 'User','');
        List<Map<String,Object>> rResult = ManualSharingController.getSearchData('New Role', 'Role','');
        List<Map<String,Object>> uResult = ManualSharingController.getSearchData('Test','PublicGroup','');//V1.1

        System.assertEquals(user1.LastName, sResult[0].get('Name'));
        System.assertEquals(urole.Name, rResult[0].get('Name'));

        Map<String, Object> updatedata = new Map<String, Object>();

        updatedata.put('Id', insertId);
        updatedata.put('AccessLevel', 'Read');

        ManualSharingController.updateData(macro.Id, JSON.serialize(updatedata));

        MacroShare ums = [SELECT Id, ParentId, UserOrGroupId, AccessLevel, RowCause FROM MacroShare WHERE UserOrGroupId = :user1.Id];
        System.assertEquals(ums.AccessLevel, 'Read');

        Boolean isAvailability = ManualSharingController.init(macro.Id);
        System.assertEquals(true, isAvailability);     

        ManualSharingController.deleteData(macro.Id, insertId);

        List<MacroShare> dms = [SELECT Id, ParentId, UserOrGroupId, AccessLevel, RowCause FROM MacroShare WHERE UserOrGroupId = :user1.Id];
        System.assertEquals(dms.size() , 0);
    }
    //V1.1 Start
    @isTest
    static void SalesLeadTest() {        
        Test.startTest();
        
        Profile p = [SELECT Id FROM Profile WHERE Name = 'System Administrator' OR Name = '시스템 관리자'];

        member1 = new User(Alias = 'member1', Email='member1@samsung.com', 
                     EmailEncodingKey='UTF-8', LastName='member1', LanguageLocaleKey='en_US', 
                     LocaleSidKey='en_US', ProfileId = p.Id, TimeZoneSidKey='Asia/Seoul', 
                     UserName='member1@samsung.com');

        insert member1;
        
        campaign1 = new Campaign(Name = 'test1');
        insert campaign1;
        
        costCenter = new CostCenter__c(CostCenterName__c = 'Test1', Name ='Test1');
        insert costCenter;
        sl = new Sales_Lead__c(
            Name = 'TestSalesLead', 
            LeadStatus__c = 'In Process',
            CampaignId__c = campaign1.Id,
            Company__c = 'Company__c',
            Email__c = 'tse@sdfjo.com.vop',
            LeadChannel__c='Demand',
            LeadStage__c = 'Hot',
            Amount__c = 5000, 
            CloseDate__c = Date.today().addDays(1),  
            RevenueEndDate__c = Date.today().addDays(3), 
            RevenueStartDate__c = Date.today().addDays(2),
            Budget__c = true,
            Authority__c = true,
            SalesDepartment__c = costCenter.Id
        );
		insert sl;

        Sales_Lead_Team__c slt = new Sales_Lead_Team__c(
            SalesLead_TeamMember__c = member1.Id, 
            AccessLevel__c = 'Read',
            Sales_Lead__c = sl.Id,
            Team_Role__c = 'Sales Rep'
        );
        
        insert slt;
        Sales_Lead__Share sLeadShare = new Sales_Lead__Share();
        sLeadShare.ParentId      = sl.Id;
        sLeadShare.UserOrGroupId = member1.Id; 
        sLeadShare.AccessLevel   = 'Read'; 
        sLeadShare.RowCause      = 'Manual';
        insert sLeadShare;
        
        Map<String, Object> updatedata = new Map<String, Object>();

        updatedata.put('Id', sLeadShare.Id);
        updatedata.put('AccessLevel','Edit');
		
        ManualSharingController.updateData(sl.Id, JSON.serialize(updatedata));
        //ManualSharingController.deleteData(sl.Id, sLeadShare.Id);
        slt.Id = null;
        sLeadShare.Id = null;
        //insert slt;
        insert sLeadShare;
        ManualSharingController.deleteDatas(sl.Id);
        Test.stopTest();
    }
    //V1.1 End
}