force-app/main/default/objects/Company__c/Company__c.object-meta.xml
<CustomObject>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Company</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Company__c/fields/CompanyCode__c.field-meta.xml
<CustomField>
    <fullName>CompanyCode__c</fullName>
    <description>회사코드</description>
    <label>Company Code</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Company__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AE</fullName>
                <label>United Arab Emirates</label>
            </value>
            <value>
                <fullName>AR</fullName>
                <label>Argentina</label>
            </value>
            <value>
                <fullName>AT</fullName>
                <label>Austria</label>
            </value>
            <value>
                <fullName>AU</fullName>
                <label>Australia</label>
            </value>
            <value>
                <fullName>AW</fullName>
                <label>Aruba</label>
            </value>
            <value>
                <fullName>AZ</fullName>
                <label>Azerbaijan</label>
            </value>
            <value>
                <fullName>BD</fullName>
                <label>Bangladesh</label>
            </value>
            <value>
                <fullName>BE</fullName>
                <label>Belgium</label>
            </value>
            <value>
                <fullName>BG</fullName>
                <label>Bulgaria</label>
            </value>
            <value>
                <fullName>BO</fullName>
                <label>Bolivia</label>
            </value>
            <value>
                <fullName>BR</fullName>
                <label>Brazil</label>
            </value>
            <value>
                <fullName>BY</fullName>
                <label>Belarus</label>
            </value>
            <value>
                <fullName>CA</fullName>
                <label>Canada</label>
            </value>
            <value>
                <fullName>CH</fullName>
                <label>Switzerland</label>
            </value>
            <value>
                <fullName>CL</fullName>
                <label>Chile</label>
            </value>
            <value>
                <fullName>CN</fullName>
                <label>China</label>
            </value>
            <value>
                <fullName>CO</fullName>
                <label>Colombia</label>
            </value>
            <value>
                <fullName>CR</fullName>
                <label>Costa Rica</label>
            </value>
            <value>
                <fullName>CS</fullName>
                <label>Serbia and Montenegro</label>
            </value>
            <value>
                <fullName>CW</fullName>
                <label>Curaçao</label>
            </value>
            <value>
                <fullName>CY</fullName>
                <label>Cyprus</label>
            </value>
            <value>
                <fullName>CZ</fullName>
                <label>Czech Republic</label>
            </value>
            <value>
                <fullName>DE</fullName>
                <label>Germany</label>
            </value>
            <value>
                <fullName>DK</fullName>
                <label>Denmark</label>
            </value>
            <value>
                <fullName>DM</fullName>
                <label>Dominica</label>
            </value>
            <value>
                <fullName>DO</fullName>
                <label>Dominican Republic</label>
            </value>
            <value>
                <fullName>DZ</fullName>
                <label>Algeria</label>
            </value>
            <value>
                <fullName>EC</fullName>
                <label>Ecuador</label>
            </value>
            <value>
                <fullName>EG</fullName>
                <label>Egypt</label>
            </value>
            <value>
                <fullName>ES</fullName>
                <label>Spain</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Company__c/fields/EPCompanyCode__c.field-meta.xml
<CustomField>
    <fullName>EPCompanyCode__c</fullName>
    <description>인사 시스템 회사번호</description>
    <label>EP Company Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CostCenter__c/CostCenter__c.object-meta.xml
<CustomObject>
    <label>Cost Center</label>
    <nameField>
        <label>Cost Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cost Center</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CostCenter__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Company</label>
    <referenceTo>Company__c</referenceTo>
    <relationshipLabel>Cost Center</relationshipLabel>
    <relationshipName>Cost_Center</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CostCenter__c/fields/CompanyCode__c.field-meta.xml
<CustomField>
    <fullName>CompanyCode__c</fullName>
    <label>Company Code</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CostCenter__c/fields/CostCenter__c.field-meta.xml
<CustomField>
    <fullName>CostCenter__c</fullName>
    <externalId>true</externalId>
    <label>Cost Center</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CostCenter__c/fields/CostCenterName__c.field-meta.xml
<CustomField>
    <fullName>CostCenterName__c</fullName>
    <label>Cost Center Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CostCenter__c/fields/Node1__c.field-meta.xml
<CustomField>
    <fullName>Node1__c</fullName>
    <label>NODE1</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CostCenter__c/fields/Node2__c.field-meta.xml
<CustomField>
    <fullName>Node2__c</fullName>
    <label>NODE2</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CostCenter__c/fields/Node3__c.field-meta.xml
<CustomField>
    <fullName>Node3__c</fullName>
    <label>NODE3</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CostCenter__c/fields/Node4__c.field-meta.xml
<CustomField>
    <fullName>Node4__c</fullName>
    <label>NODE4</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CostCenter__c/fields/Node5__c.field-meta.xml
<CustomField>
    <fullName>Node5__c</fullName>
    <label>NODE5</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CostCenter__c/fields/Text2__c.field-meta.xml
<CustomField>
    <fullName>Text2__c</fullName>
    <label>TEXT2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CostCenter__c/fields/ZZCheck__c.field-meta.xml
<CustomField>
    <fullName>ZZCheck__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ZZCheck</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OpportunityAmt__c/OpportunityAmt__c.object-meta.xml
<CustomObject>
    <label>Opportunity Amount</label>
    <nameField>
        <label>Opportunity Amount</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Amount</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OpportunityAmt__c/fields/Closedate__c.field-meta.xml
<CustomField>
    <fullName>Closedate__c</fullName>
    <label>Closedate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OpportunityAmt__c/fields/Companycode__c.field-meta.xml
<CustomField>
    <fullName>Companycode__c</fullName>
    <label>CompanyCode</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityAmt__c/fields/CurrencyLoc__c.field-meta.xml
<CustomField>
    <fullName>CurrencyLoc__c</fullName>
    <label>Currency_Loc</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityAmt__c/fields/DiffAmt__c.field-meta.xml
<CustomField>
    <fullName>DiffAmt__c</fullName>
    <label>DiffAmt</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityAmt__c/fields/DiffAmtLoc__c.field-meta.xml
<CustomField>
    <fullName>DiffAmtLoc__c</fullName>
    <label>DiffAmt_Loc</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityAmt__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Amount</relationshipLabel>
    <relationshipName>Opportunity_Amount</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityAmt__c/fields/Opportunitycode__c.field-meta.xml
<CustomField>
    <fullName>Opportunitycode__c</fullName>
    <label>OpportunityCode</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityAmt__c/fields/Rateyn__c.field-meta.xml
<CustomField>
    <fullName>Rateyn__c</fullName>
    <label>Rate_yn</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityAmt__c/fields/TotalAmt__c.field-meta.xml
<CustomField>
    <fullName>TotalAmt__c</fullName>
    <label>TotalAmt</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityAmt__c/fields/TotalAmtLoc__c.field-meta.xml
<CustomField>
    <fullName>TotalAmtLoc__c</fullName>
    <label>TotalAmt_Loc</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityAmt__c/fields/Version__c.field-meta.xml
<CustomField>
    <fullName>Version__c</fullName>
    <label>Version</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Organization__c/Organization__c.object-meta.xml
<CustomObject>
    <label>Organization</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organizations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Organization__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Company</label>
    <referenceTo>Company__c</referenceTo>
    <relationshipName>Branch</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Batch_IF185ExchangeRateController_Test.cls
/**
 * @description       : Test Class of Batch_IF185ExchangeRateController
 * @author            : vikrant.ks@samsung.com
 * @group             : 
 * @last modified on  : 2023-10-10
 * @last modified by  : vikrant.ks@samsung.com 
 * Modifications Log 
 * Ver   Date         Author                   Modification
 * 1.0   2023-10-10   vikrant.ks@samsung.com   Initial Version(MySales 317)
**/
@isTest
public class Batch_IF185ExchangeRateController_Test{
    @TestSetup
    static void setData(){
    	Id rdType = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('MDG').getRecordTypeId();
        Account acc = new Account (
        Name = 'Test1234',AccountNumber='A2999999',RecordTypeId = rdType, MDGCheck__c = true, mLoevm__c = false);
        insert acc;
        Organization__c org = new Organization__c();
        insert org;
        RecordType RT_OPPTY_HQ   = [SELECT Id FROM RecordType WHERE SobjectType = 'Opportunity' AND DeveloperName = 'HQ' Limit 1];
        
        Company__c insertCompany = new Company__c (
            Name                = 'T100 - Name'
            , CompanyCode__c    = 'T100'
            , EPCompanyCode__c  = 'EP1'
            , CurrencyIsoCode   = 'KRW'
            , Country__c        = 'Korea, Republic of'
        );
        insert insertCompany;
		System.debug('Company: '+insertCompany);
        
        CostCenter__c insertCostCenter = new CostCenter__c(
                    Name                = '기술전략팀(T100-11331)'
                    , CurrencyIsoCode   = 'KRW'
                    , CompanyCode__c    = 'T100'
                    , CostCenterName__c = '기술전략팀'
                    , CostCenter__c     = 'T100-11331'
                    , Node1__c          = 'T100'
                    , Node2__c          = 'T100SB'
                    , Node3__c          = 'T100SB1'
                    , Node4__c          = 'T100SB13'
                    , Node5__c          = 'T100SB131'
            		, ZZCheck__c        = true
            		, Text2__c      = '클라우드서비스사업부'
                    , Company__c        = insertCompany.Id
                );
        insert insertCostCenter;     
        System.debug('CostCenter: '+insertCostCenter);
        
        Opportunity Opportunity1 = new Opportunity(
            Name = 'MySales',
            CurrencyIsoCode='EUR',
            OpportunityCode__c='SDS-22001260',
            StageName= 'Z03',
            CspMspType__c = 'CSP',
            Amount = 78,
            AccountId = acc.id,
            SalesOrganization__c = org.id,
            DeliveryOrganization__c = org.id,
            CloseDate = System.today().addDays(5),
            OpportunityStatus__c='E0003',
            CMBizType__c='CSP_SCP',
            RecordTypeId = RT_OPPTY_HQ.Id,
            SalesDepartment__c= insertCostCenter.Id 
            );
        
        insert Opportunity1;
        
        OpportunityAmt__c oppAmt = new OpportunityAmt__c();
        oppAmt.OpportunityCode__c = 'SDS-22001260';
        oppAmt.CompanyCode__c = 'T100';
        oppAmt.Version__c = 'S001';
        oppAmt.Closedate__c = Date.today();
        oppAmt.TotalAmt__c = 1000000;
        oppAmt.Currency__c = 'INR';
        oppAmt.DiffAmt__c = 1000000;
        oppAmt.TotalAmtLoc__c = 1000000;
        oppAmt.CurrencyLoc__c = 'KRW';
        oppAmt.DiffAmtLoc__c = 1000000;
        oppAmt.Rateyn__c = 'N';
        oppAmt.Opportunity__c = Opportunity1.Id;
        
        insert oppAmt;
    }
    @isTest
    public static void Test_Batch_IF185ExchangeRateController(){
        Test.startTest();
        DataBase.executeBatch(new Batch_IF185ExchangeRateController());
        Test.stopTest();
    } 
}