force-app/main/default/objects/Company__c/Company__c.object-meta.xml
<CustomObject>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Company</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Company__c/fields/CompanyCode__c.field-meta.xml
<CustomField>
    <fullName>CompanyCode__c</fullName>
    <description>회사코드</description>
    <label>Company Code</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Company__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AE</fullName>
                <label>United Arab Emirates</label>
            </value>
            <value>
                <fullName>AR</fullName>
                <label>Argentina</label>
            </value>
            <value>
                <fullName>AT</fullName>
                <label>Austria</label>
            </value>
            <value>
                <fullName>AU</fullName>
                <label>Australia</label>
            </value>
            <value>
                <fullName>AW</fullName>
                <label>Aruba</label>
            </value>
            <value>
                <fullName>AZ</fullName>
                <label>Azerbaijan</label>
            </value>
            <value>
                <fullName>BD</fullName>
                <label>Bangladesh</label>
            </value>
            <value>
                <fullName>BE</fullName>
                <label>Belgium</label>
            </value>
            <value>
                <fullName>BG</fullName>
                <label>Bulgaria</label>
            </value>
            <value>
                <fullName>BO</fullName>
                <label>Bolivia</label>
            </value>
            <value>
                <fullName>BR</fullName>
                <label>Brazil</label>
            </value>
            <value>
                <fullName>BY</fullName>
                <label>Belarus</label>
            </value>
            <value>
                <fullName>CA</fullName>
                <label>Canada</label>
            </value>
            <value>
                <fullName>CH</fullName>
                <label>Switzerland</label>
            </value>
            <value>
                <fullName>CL</fullName>
                <label>Chile</label>
            </value>
            <value>
                <fullName>CN</fullName>
                <label>China</label>
            </value>
            <value>
                <fullName>CO</fullName>
                <label>Colombia</label>
            </value>
            <value>
                <fullName>CR</fullName>
                <label>Costa Rica</label>
            </value>
            <value>
                <fullName>CS</fullName>
                <label>Serbia and Montenegro</label>
            </value>
            <value>
                <fullName>CW</fullName>
                <label>Curaçao</label>
            </value>
            <value>
                <fullName>CY</fullName>
                <label>Cyprus</label>
            </value>
            <value>
                <fullName>CZ</fullName>
                <label>Czech Republic</label>
            </value>
            <value>
                <fullName>DE</fullName>
                <label>Germany</label>
            </value>
            <value>
                <fullName>DK</fullName>
                <label>Denmark</label>
            </value>
            <value>
                <fullName>DM</fullName>
                <label>Dominica</label>
            </value>
            <value>
                <fullName>DO</fullName>
                <label>Dominican Republic</label>
            </value>
            <value>
                <fullName>DZ</fullName>
                <label>Algeria</label>
            </value>
            <value>
                <fullName>EC</fullName>
                <label>Ecuador</label>
            </value>
            <value>
                <fullName>EG</fullName>
                <label>Egypt</label>
            </value>
            <value>
                <fullName>ES</fullName>
                <label>Spain</label>
            </value>
            <value>
                <fullName>KR</fullName>
                <label>South Korea</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Company__c/fields/EPCompanyCode__c.field-meta.xml
<CustomField>
    <fullName>EPCompanyCode__c</fullName>
    <description>인사 시스템 회사번호</description>
    <label>EP Company Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CostCenter__c/CostCenter__c.object-meta.xml
<CustomObject>
    <label>Cost Center</label>
    <nameField>
        <label>Cost Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cost Center</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CostCenter__c/fields/Bkzer__c.field-meta.xml
<CustomField>
    <fullName>Bkzer__c</fullName>
    <defaultValue>false</defaultValue>
    <description>실제수익 전기에 대한 잠금지시자</description>
    <label>BKZER</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CostCenter__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Company</label>
    <referenceTo>Company__c</referenceTo>
    <relationshipLabel>Cost Center</relationshipLabel>
    <relationshipName>Cost_Center</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CostCenter__c/fields/CompanyCode__c.field-meta.xml
<CustomField>
    <fullName>CompanyCode__c</fullName>
    <label>Company Code</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CostCenter__c/fields/CostCenter__c.field-meta.xml
<CustomField>
    <fullName>CostCenter__c</fullName>
    <externalId>true</externalId>
    <label>Cost Center</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CostCenter__c/fields/CostCenterName__c.field-meta.xml
<CustomField>
    <fullName>CostCenterName__c</fullName>
    <label>Cost Center Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CostCenter__c/fields/Node1__c.field-meta.xml
<CustomField>
    <fullName>Node1__c</fullName>
    <label>NODE1</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CostCenter__c/fields/Node2__c.field-meta.xml
<CustomField>
    <fullName>Node2__c</fullName>
    <label>NODE2</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CostCenter__c/fields/Node3__c.field-meta.xml
<CustomField>
    <fullName>Node3__c</fullName>
    <label>NODE3</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CostCenter__c/fields/Node4__c.field-meta.xml
<CustomField>
    <fullName>Node4__c</fullName>
    <label>NODE4</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CostCenter__c/fields/Node5__c.field-meta.xml
<CustomField>
    <fullName>Node5__c</fullName>
    <label>NODE5</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Department__c/Department__c.object-meta.xml
<CustomObject>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Department</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Department__c/fields/Abtel__c.field-meta.xml
<CustomField>
    <fullName>Abtel__c</fullName>
    <description>부서</description>
    <label>ABTEI</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Department__c/fields/Bkzer__c.field-meta.xml
<CustomField>
    <fullName>Bkzer__c</fullName>
    <description>실제수익 전기에 대한 잠금지시자</description>
    <label>BKZER</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Department__c/fields/Bukrs__c.field-meta.xml
<CustomField>
    <fullName>Bukrs__c</fullName>
    <description>Company Code</description>
    <label>BUKRS</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Department__c/fields/Datab__c.field-meta.xml
<CustomField>
    <fullName>Datab__c</fullName>
    <description>효력 시작일</description>
    <label>DATAB</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Department__c/fields/DatabI__c.field-meta.xml
<CustomField>
    <fullName>DatabI__c</fullName>
    <description>효력 종료일</description>
    <label>DATBI</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Department__c/fields/EKText__c.field-meta.xml
<CustomField>
    <fullName>EKText__c</fullName>
    <description>일반이름(E)</description>
    <label>EKTEXT</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Department__c/fields/Kostl__c.field-meta.xml
<CustomField>
    <fullName>Kostl__c</fullName>
    <description>코스트 센터</description>
    <label>KOSTL</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/IF_EccProjectBasicInfoController_Test.cls
/**
 * @description       : 
 * @author            : raeganja@partner.samsung.com
 * @group             : 
 * @last modified on  : 2021-02-15
 * @last modified by  : raeganja@partner.samsung.com
 * Modifications Log 
 * Ver   Date         Author                         Modification
 * 1.0   2021-02-05   raeganja@partner.samsung.com   Initial Version
**/
@isTest
public class IF_EccProjectBasicInfoController_Test {
    public IF_EccProjectBasicInfoController_Test() {

    }

    static Account acc;
    static Opportunity oppty;
    static final String REQUEST_DATA = 	'0061s000005QCXuAAO';

    @TestSetup
    static void makeData(){
        RecordType RT_OPPTY_HQ        = [SELECT Id FROM RecordType WHERE SobjectType = 'Opportunity' AND DeveloperName = 'HQ' Limit 1];

        Company__c insertCompany = new Company__c (
            Name                = 'C60 - Name'
            , CompanyCode__c    = 'C60'
            , EPCompanyCode__c  = 'EP1'
            , CurrencyIsoCode   = 'KRW'
            , Country__c        = 'KR'
        );
        Insert insertCompany;

        CostCenter__c insertCostCenter = new CostCenter__c(
            Name                = '기술전략팀(T100-11331)'
            , CurrencyIsoCode   = 'KRW'
            , CompanyCode__c    = 'C60'
            , CostCenterName__c = '기술전략팀'
            , CostCenter__c     = 'C60-11331'
            , Node1__c          = 'C60'
            , Node2__c          = 'C60SB'
            , Node3__c          = 'C60SB1'
            , Node4__c          = 'C60SB13'
            , Node5__c          = 'C60SB131'
            , Company__c        = insertCompany.Id
        );
        Insert insertCostCenter;

        Department__c insertDepartment = new Department__c(
            Name                = '기술기획팀'
            , CurrencyIsoCode   = 'KRW'
            , Abtel__c          = 'C60AI562'
            , Bkzer__c          = 'X'
            , Bukrs__c          = 'C60'
            , Datab__c          = System.today()
            , DatabI__c         = Date.valueOf('4000-12-31')
            , EKText__c         = '기술기획팀'
            , Kostl__c          = 'C60-11331'
        );
        Insert insertDepartment;

        Opportunity hqOppty = new Opportunity(
            Name                    = 'testOpp1'
            , RecordTypeId          = RT_OPPTY_HQ.Id
            , CloseDate             = System.today()
            , StageName             = 'Z01'
            , SalesDepartment__c    = insertCostCenter.Id
            , Amount                = 1000000
            , CurrencyIsoCode       = 'KRW'
            , OpportunityCode__c    = 'SDS-15016921'
            , MigData__c            = false
        );
        Insert hqOppty;
    }

    @isTest
    static void testCallout() {
        Test.startTest();
        
        Test.setMock(HttpCalloutMock.class, new IF_Callout_TestMock(200));

        Opportunity oppty = [Select Id From Opportunity where OpportunityCode__c = 'SDS-15016921' limit 1];
        Map<String, Object> result = IF_EccProjectBasicInfoController.getProjectBasicInfo(oppty.Id);
        System.assertEquals(result.get('StatusCode'), 200);

        HttpResponse resp = (HttpResponse)result.get('HttpResponse');
        Map<String,Object> returnMap = (Map<String,Object>) JSON.deserializeUntyped(resp.getBody());

        System.assertEquals(String.valueOf(returnMap.get('EV_RTNST')), 'S');

        Test.stopTest();
    }

    @isTest
    static void testCallout400() {
        Test.startTest();
        
        Test.setMock(HttpCalloutMock.class, new IF_Callout_TestMock(400));
        Opportunity oppty = [Select Id From Opportunity where OpportunityCode__c = 'SDS-15016921' limit 1];
        Map<String, Object> result = IF_EccProjectBasicInfoController.getProjectBasicInfo(oppty.Id);
        System.assertEquals(result.get('StatusCode'), 400);

        Test.stopTest();
    }

    @isTest
    static void testCalloutError() {
        Test.startTest();

        Map<String, Object> result = IF_EccProjectBasicInfoController.getProjectBasicInfo('Error');

        Test.stopTest();
    }
}