force-app/main/default/objects/Company__c/Company__c.object-meta.xml
<CustomObject>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Company</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Lead__c/Sales_Lead__c.object-meta.xml
<CustomObject>
    <label>Sales Lead</label>
    <nameField>
        <label>Sales Lead Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Leads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Lead__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>예상금액</description>
    <inlineHelpText>Required Information only for HQ users when creating IT Sales Lead / Required information when converting</inlineHelpText>
    <label>Amount(*)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sales_Lead__c/fields/Authority__c.field-meta.xml
<CustomField>
    <fullName>Authority__c</fullName>
    <defaultValue>false</defaultValue>
    <description>권한</description>
    <inlineHelpText>Whether the customer in charge has obtained the right to perform the business (change the stage to Hot when satisfying two or more BANTs)</inlineHelpText>
    <label>Authority</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sales_Lead__c/fields/Budget__c.field-meta.xml
<CustomField>
    <fullName>Budget__c</fullName>
    <defaultValue>false</defaultValue>
    <description>예산확보 여부</description>
    <inlineHelpText>Whether to have a customer budget (change the stage to Hot when satisfying two or more BANTs)</inlineHelpText>
    <label>Budget</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sales_Lead__c/fields/CloseDate__c.field-meta.xml
<CustomField>
    <fullName>CloseDate__c</fullName>
    <description>예상수주일자</description>
    <label>Close Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Sales_Lead__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <description>고객사 명</description>
    <label>Company</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Lead__c/fields/LeadChannel__c.field-meta.xml
<CustomField>
    <fullName>LeadChannel__c</fullName>
    <label>Lead Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Direct Registration</fullName>
            </value>
            <value>
                <fullName>Marketing Lead Converted</fullName>
            </value>
            <value>
                <fullName>Demand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Lead__c/fields/LeadStage__c.field-meta.xml
<CustomField>
    <fullName>LeadStage__c</fullName>
    <description>Lead Stage</description>
    <label>Lead Stage</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cold</fullName>
                <color>#33CCFF</color>
                <label>Cold</label>
            </value>
            <value>
                <fullName>Warm</fullName>
                <color>#FF9900</color>
                <label>Warm</label>
            </value>
            <value>
                <fullName>Hot</fullName>
                <color>#FF0000</color>
                <label>Hot</label>
            </value>
            <value>
                <fullName>Converted</fullName>
                <color>#BBBBBB</color>
                <label>Converted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Lead__c/fields/RevenueEndDate__c.field-meta.xml
<CustomField>
    <fullName>RevenueEndDate__c</fullName>
    <description>(계약) 매출 종료일</description>
    <label>Contract End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Sales_Lead__c/fields/RevenueStartDate__c.field-meta.xml
<CustomField>
    <fullName>RevenueStartDate__c</fullName>
    <description>(계약) 매출 시작일</description>
    <label>Contract Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Sales_Lead_Team__c/Sales_Lead_Team__c.object-meta.xml
<CustomObject>
    <label>Sales Lead Team</label>
    <nameField>
        <displayFormat>SLT-{00000}</displayFormat>
        <label>Sales Lead Team No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Lead Team</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Lead_Team__c/fields/AccessLevel__c.field-meta.xml
<CustomField>
    <fullName>AccessLevel__c</fullName>
    <label>Access Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Read</fullName>
            </value>
            <value>
                <fullName>Edit</fullName>
                <label>Read/Write</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Lead_Team__c/fields/Sales_Lead__c.field-meta.xml
<CustomField>
    <fullName>Sales_Lead__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Sales Lead</label>
    <referenceTo>Sales_Lead__c</referenceTo>
    <relationshipLabel>Sales Lead Team</relationshipLabel>
    <relationshipName>Sales_Lead_Team</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Lead_Team__c/fields/SalesLead_TeamMember__c.field-meta.xml
<CustomField>
    <fullName>SalesLead_TeamMember__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Lead Team Member</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sales_Lead_Team</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Lead_Team__c/fields/Team_Role__c.field-meta.xml
<CustomField>
    <fullName>Team_Role__c</fullName>
    <label>Team Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Proposal PM</fullName>
            </value>
            <value>
                <fullName>Sales Rep</fullName>
            </value>
            <value>
                <fullName>Sales Manager</fullName>
            </value>
            <value>
                <fullName>Account Manager</fullName>
            </value>
            <value>
                <fullName>Channel Manager</fullName>
            </value>
            <value>
                <fullName>Executive Sponsor</fullName>
            </value>
            <value>
                <fullName>Lead Qualifier</fullName>
            </value>
            <value>
                <fullName>Pre-Sales Consultant</fullName>
            </value>
            <value>
                <fullName>Strategy Committee Officer</fullName>
            </value>
            <value>
                <fullName>Strategy Committee Member</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AddSalesTeamMemberCmpController_Test.cls
/**
* @author            : vikrant.ks@samsung.com
* @group             : 
* @description       : 
* @last modified on  : 2024-01-18
* @last modified by  : vikrant.ks@samsung.com
* Modifications Log 
* Ver   Date         Author                    Modification
* 1.0   2024-01-18   vikrant.ks@samsung.com    Initial Version
**/
@isTest
private class AddSalesTeamMemberCmpController_Test {
    static User owner;
    static User member1;
    static User member2;
    static Sales_Lead__c sl;
    static Sales_Lead_Team__c slt;

    static{
        Profile p = [SELECT Id FROM Profile WHERE Name = 'System Administrator' OR Name = '시스템 관리자'];

        list<User> userList = new list<User>();

        owner = new User(Alias = 'owner', Email='owner@samsung.com', 
                     EmailEncodingKey='UTF-8', LastName='owner', LanguageLocaleKey='en_US', 
                     LocaleSidKey='en_US', ProfileId = p.Id, TimeZoneSidKey='Asia/Seoul', 
                     UserName='owner@samsung.com');
        userList.add(owner);

        member1 = new User(Alias = 'member1', Email='member1@samsung.com', 
                     EmailEncodingKey='UTF-8', LastName='member1', LanguageLocaleKey='en_US', 
                     LocaleSidKey='en_US', ProfileId = p.Id, TimeZoneSidKey='Asia/Seoul', 
                     UserName='member1@samsung.com');
        userList.add(member1);

        member2 = new User(Alias = 'member2', Email='member2@samsung.com', 
                     EmailEncodingKey='UTF-8', LastName='member2', LanguageLocaleKey='en_US', 
                     LocaleSidKey='en_US', ProfileId = p.Id, TimeZoneSidKey='Asia/Seoul', 
                     UserName='member2@samsung.com');
        userList.add(member2);

        insert userList;
        sl = new Sales_Lead__c(
            Name = 'TestSalesLead', 
            Company__c = 'Company__c',
            Email__c = 'tse@sdfjo.com.vop',
            LeadChannel__c='Demand',
            LeadStage__c = 'Hot',
            Amount__c = 5000, 
            CloseDate__c = Date.today().addDays(1),  
            RevenueEndDate__c = Date.today().addDays(3), 
            RevenueStartDate__c = Date.today().addDays(2),
            Budget__c = true,
            Authority__c = true
        );
		insert sl;

        Sales_Lead_Team__c slt = new Sales_Lead_Team__c(
            SalesLead_TeamMember__c = member1.Id, 
            AccessLevel__c = 'Read',
            Sales_Lead__c = sl.Id,
            Team_Role__c = 'Sales Rep'
        );

        insert slt;
    }

 
    @isTest static void test_method_1() {
        Test.startTest();
        AddSalesTeamMemberCmpController.customUser customUser = new AddSalesTeamMemberCmpController.customUser();
        customUser.Id = member1.Id;
        customUser.Name = member1.Name;

        AddSalesTeamMemberCmpController.sltm sltm = new AddSalesTeamMemberCmpController.sltm();
        sltm.User = customUser;
        sltm.AccessLevel = 'Edit';

        List<AddSalesTeamMemberCmpController.sltm> sltmList = new List<AddSalesTeamMemberCmpController.sltm>();
        sltmList.add(sltm);
        AddSalesTeamMemberCmpController.save(JSON.serialize(sltmList),sl.Id);
        AddSalesTeamMemberCmpController.CheckOwner(sl.Id);
		Test.stopTest();
	}
    
    @isTest static void test_method_2() {
        Test.startTest();
        AddSalesTeamMemberCmpController.customUser customUser = new AddSalesTeamMemberCmpController.customUser();
        customUser.Id = member2.Id;
        customUser.Name = member2.Name;

        AddSalesTeamMemberCmpController.sltm sltm = new AddSalesTeamMemberCmpController.sltm();
        sltm.User = customUser;
        sltm.AccessLevel = 'Read';

        List<AddSalesTeamMemberCmpController.sltm> sltmList = new List<AddSalesTeamMemberCmpController.sltm>();
        sltmList.add(sltm);
        AddSalesTeamMemberCmpController.save(JSON.serialize(sltmList),sl.Id);
        System.runAs(member2){
            AddSalesTeamMemberCmpController.save(JSON.serialize(sltmList),sl.Id);
        	AddSalesTeamMemberCmpController.CheckOwner(sl.Id);
        }
		Test.stopTest();
	}
    @isTest static void test_method_3() {
        Test.startTest();
        AddSalesTeamMemberCmpController.customUser customUser = new AddSalesTeamMemberCmpController.customUser();
        customUser.Id = member1.Id;
        customUser.Name = member1.Name;

        AddSalesTeamMemberCmpController.sltm sltm = new AddSalesTeamMemberCmpController.sltm();
        sltm.User = customUser;
        sltm.AccessLevel = 'Read';

        List<AddSalesTeamMemberCmpController.sltm> sltmList = new List<AddSalesTeamMemberCmpController.sltm>();
        sltmList.add(sltm);
        AddSalesTeamMemberCmpController.save(JSON.serialize(sltmList),sl.Id);
		Test.stopTest();
	}
    @isTest static void test_method_4() {
        Test.startTest();
        AddSalesTeamMemberCmpController.customUser customUser = new AddSalesTeamMemberCmpController.customUser();
        customUser.Id = sl.Id;
        customUser.Name = member1.Name;

        AddSalesTeamMemberCmpController.sltm sltm = new AddSalesTeamMemberCmpController.sltm();
        sltm.User = customUser;
        sltm.AccessLevel = 'Write';

        List<AddSalesTeamMemberCmpController.sltm> sltmList = new List<AddSalesTeamMemberCmpController.sltm>();
        sltmList.add(sltm);
        try{
        	AddSalesTeamMemberCmpController.save(JSON.serialize(sltmList),sl.Id);
        }catch(Exception e){
            System.debug('Error: '+e.getMessage());
        }
		Test.stopTest();
	}
}