force-app/main/default/objects/Company__c/Company__c.object-meta.xml
<CustomObject>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Company</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Company__c/fields/CompanyCode__c.field-meta.xml
<CustomField>
    <fullName>CompanyCode__c</fullName>
    <description>회사코드</description>
    <label>Company Code</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Company__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AE</fullName>
                <label>United Arab Emirates</label>
            </value>
            <value>
                <fullName>AR</fullName>
                <label>Argentina</label>
            </value>
            <value>
                <fullName>AT</fullName>
                <label>Austria</label>
            </value>
            <value>
                <fullName>AU</fullName>
                <label>Australia</label>
            </value>
            <value>
                <fullName>AW</fullName>
                <label>Aruba</label>
            </value>
            <value>
                <fullName>AZ</fullName>
                <label>Azerbaijan</label>
            </value>
            <value>
                <fullName>BD</fullName>
                <label>Bangladesh</label>
            </value>
            <value>
                <fullName>BE</fullName>
                <label>Belgium</label>
            </value>
            <value>
                <fullName>BG</fullName>
                <label>Bulgaria</label>
            </value>
            <value>
                <fullName>BO</fullName>
                <label>Bolivia</label>
            </value>
            <value>
                <fullName>BR</fullName>
                <label>Brazil</label>
            </value>
            <value>
                <fullName>BY</fullName>
                <label>Belarus</label>
            </value>
            <value>
                <fullName>CA</fullName>
                <label>Canada</label>
            </value>
            <value>
                <fullName>CH</fullName>
                <label>Switzerland</label>
            </value>
            <value>
                <fullName>CL</fullName>
                <label>Chile</label>
            </value>
            <value>
                <fullName>CN</fullName>
                <label>China</label>
            </value>
            <value>
                <fullName>CO</fullName>
                <label>Colombia</label>
            </value>
            <value>
                <fullName>CR</fullName>
                <label>Costa Rica</label>
            </value>
            <value>
                <fullName>CS</fullName>
                <label>Serbia and Montenegro</label>
            </value>
            <value>
                <fullName>CW</fullName>
                <label>Curaçao</label>
            </value>
            <value>
                <fullName>CY</fullName>
                <label>Cyprus</label>
            </value>
            <value>
                <fullName>CZ</fullName>
                <label>Czech Republic</label>
            </value>
            <value>
                <fullName>DE</fullName>
                <label>Germany</label>
            </value>
            <value>
                <fullName>DK</fullName>
                <label>Denmark</label>
            </value>
            <value>
                <fullName>DM</fullName>
                <label>Dominica</label>
            </value>
            <value>
                <fullName>DO</fullName>
                <label>Dominican Republic</label>
            </value>
            <value>
                <fullName>DZ</fullName>
                <label>Algeria</label>
            </value>
            <value>
                <fullName>EC</fullName>
                <label>Ecuador</label>
            </value>
            <value>
                <fullName>EG</fullName>
                <label>Egypt</label>
            </value>
            <value>
                <fullName>ES</fullName>
                <label>Spain</label>
            </value>
            <value>
                <fullName>KR</fullName>
                <label>South Korea</label>
            </value>
            <value>
                <fullName>SG</fullName>
                <label>Singapore</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Company__c/fields/EPCompanyCode__c.field-meta.xml
<CustomField>
    <fullName>EPCompanyCode__c</fullName>
    <description>인사 시스템 회사번호</description>
    <label>EP Company Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CostCenter__c/CostCenter__c.object-meta.xml
<CustomObject>
    <label>Cost Center</label>
    <nameField>
        <label>Cost Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cost Center</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CostCenter__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Company</label>
    <referenceTo>Company__c</referenceTo>
    <relationshipLabel>Cost Center</relationshipLabel>
    <relationshipName>Cost_Center</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CostCenter__c/fields/CompanyCode__c.field-meta.xml
<CustomField>
    <fullName>CompanyCode__c</fullName>
    <label>Company Code</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CostCenter__c/fields/CostCenter__c.field-meta.xml
<CustomField>
    <fullName>CostCenter__c</fullName>
    <externalId>true</externalId>
    <label>Cost Center</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/EvMailAddr__c.field-meta.xml
<CustomField>
    <fullName>EvMailAddr__c</fullName>
    <label>Email</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/EvUniqID__c.field-meta.xml
<CustomField>
    <fullName>EvUniqID__c</fullName>
    <externalId>true</externalId>
    <label>EP ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Activity__c/Opportunity_Activity__c.object-meta.xml
<CustomObject>
    <label>Opportunity Activity</label>
    <nameField>
        <displayFormat>OA-{yymmdd}-{00000}</displayFormat>
        <label>Opportunity Activity No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RevenueScheduleOpportunity__c/RevenueScheduleOpportunity__c.object-meta.xml
<CustomObject>
    <label>Opportunity Revenue Schedule</label>
    <nameField>
        <displayFormat>RS{0000000000}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Revenue Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TriggerSwitch__c/TriggerSwitch__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>TriggerSwitch</label>
</CustomObject>

force-app/main/default/objects/TriggerSwitch__c/fields/All__c.field-meta.xml
<CustomField>
    <fullName>All__c</fullName>
    <defaultValue>true</defaultValue>
    <label>All</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerSwitch__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Event</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerSwitch__c/fields/Migration__c.field-meta.xml
<CustomField>
    <fullName>Migration__c</fullName>
    <defaultValue>false</defaultValue>
    <description>해당 필드가 체크되어있는 경우 마이그 로직을 실행하지않음</description>
    <label>Migration</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerSwitch__c/fields/OpportunityActivity__c.field-meta.xml
<CustomField>
    <fullName>OpportunityActivity__c</fullName>
    <defaultValue>true</defaultValue>
    <label>OpportunityActivity</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerSwitch__c/fields/OpportunityBizLvSetting__c.field-meta.xml
<CustomField>
    <fullName>OpportunityBizLvSetting__c</fullName>
    <defaultValue>true</defaultValue>
    <label>OpportunityBizLvSetting</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerSwitch__c/fields/OpportunityCodeSetting__c.field-meta.xml
<CustomField>
    <fullName>OpportunityCodeSetting__c</fullName>
    <defaultValue>true</defaultValue>
    <label>OpportunityCodeSetting</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerSwitch__c/fields/OpportunityDeleteSetting__c.field-meta.xml
<CustomField>
    <fullName>OpportunityDeleteSetting__c</fullName>
    <defaultValue>true</defaultValue>
    <label>OpportunityDeleteSetting</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerSwitch__c/fields/OpportunityLogisticsValidation__c.field-meta.xml
<CustomField>
    <fullName>OpportunityLogisticsValidation__c</fullName>
    <defaultValue>true</defaultValue>
    <description>레코드 타입 Logistics 유효성 트리거</description>
    <label>OpportunityLogisticsValidation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerSwitch__c/fields/OpportunitySendToSAP__c.field-meta.xml
<CustomField>
    <fullName>OpportunitySendToSAP__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Opportunity 작성/수정/삭제 시 SAP 정보 전송 여부</description>
    <inlineHelpText>Opportunity 작성/수정/삭제 시 SAP 정보 전송 여부</inlineHelpText>
    <label>OpportunitySendToSAP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerSwitch__c/fields/RevenueScheduleOpportunity__c.field-meta.xml
<CustomField>
    <fullName>RevenueScheduleOpportunity__c</fullName>
    <defaultValue>false</defaultValue>
    <label>RevenueScheduleOpportunity</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerSwitch__c/fields/WeeklyReportSend__c.field-meta.xml
<CustomField>
    <fullName>WeeklyReportSend__c</fullName>
    <defaultValue>true</defaultValue>
    <label>WeeklyReportSend</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ChangeAccountOppOwnerControllertest.cls
/**
* @description       : ChangeAccountOppOwnerController Test
* @author            : Divyam.gupta@samsung.com
* @group             : 
* @last modified on  : 2022-09-06
* @last modified by  : Divyam.gupta@samsung.com
* Modifications Log 
* Ver   Date         Author                 Modification
* 1.0   2022-09-06   Divyam.gupta@samsung.com   Initial Version
**/
@isTest
public class ChangeAccountOppOwnerControllertest {
       static User u;
    
       static RecordType rcdType_Acc_MDG;
       static RecordType rcdType_Oppty_HQ;
       static User user_sysAdmin;
        static User user_sysAdmin1;
       static Account acc_1;
      static Company__c comp_SDS;
      static Company__c comp_SDSAP;
    static CostCenter__c cc_1;
    static CostCenter__c cc_2;
    static Opportunity oppty_HQ_1_HQ;
    static Opportunity oppty_HQ_1_1_HQ;
    static Opportunity oppty_HQ_2_Corp;
     static Opportunity oppty_HQ_2_HQ;
    static Opportunity_Activity__c opptyAct_Corp_1;
    static Opportunity_Activity__c opptyAct_HQ_2;
    static Opportunity_Activity__c opptyAct_HQ_3;
    static Employee__c emp_0;
     static Employee__c emp_1;


       static {
        TriggerSwitch__c ts = new TriggerSwitch__c(
            // Event__c = true,
            // OpportunityCodeSetting__c = true,
            // OpportunityBizLvSetting__c = true,
            // OpportunityDeleteSetting__c = true,
            // OpportunityLogisticsValidation__c = true,
            // OpportunitySendToSAP__c = true,
            // RevenueScheduleOpportunity__c = false,
            // Migration__c = false,
            // WeeklyReportSend__c = true,
            All__c = true,
            Opportunity__c = true,
            OpportunityActivity__c = true
        );
        insert ts;

        rcdType_Acc_MDG = [SELECT Id FROM RecordType WHERE SobjectType = 'Account' AND DeveloperName = 'MDG' Limit 1];
        rcdType_Oppty_HQ = [SELECT Id FROM RecordType WHERE SobjectType = 'Opportunity' AND DeveloperName = 'HQ' Limit 1];
          emp_0 = Utils_TestDataFactory.createEmployee('TestEmp0', 'EPID0');
          emp_1 = Utils_TestDataFactory.createEmployee('TestEmp1', 'EPID1');

     
          user_sysAdmin = Utils_TestDataFactory.createUserFull(
                            Utils_TestDataFactory.getProfile('System Administrator')
                            , emp_0.EvMailAddr__c
                            , emp_0.EvUniqID__c
                        );
           user_sysAdmin1 = Utils_TestDataFactory.createUserFull(
                            Utils_TestDataFactory.getProfile('System Administrator')
                            , emp_1.EvMailAddr__c
                            , emp_1.EvUniqID__c
                        );
            acc_1 = new Account(
            Name = 'Test Account 1',
            RecordTypeId = rcdType_Acc_MDG.Id,
            MDGCheck__c = true,
            AccountNumber = 'A2100002'
        );
        insert acc_1;
                    
        List<Company__c> compList = new List<Company__c>();
        comp_SDS = new Company__c(
            Name = 'Samsung SDS',
            CompanyCode__c = 'T100',
            Country__c = 'KR',
            EPCompanyCode__c = 'C60'
        );
        compList.add(comp_SDS);

        comp_SDSAP = new Company__c(
            Name = 'SDSAP',
            CompanyCode__c = 'T501',
            Country__c = 'SG',
            EPCompanyCode__c = 'C6S'
        );
        compList.add(comp_SDSAP);
           
          List<CostCenter__c> ccList = new List<CostCenter__c>();
        cc_1 = new CostCenter__c(
            Name = 'Test Cost Center 1', 
            Company__c = comp_SDS.Id, 
            CompanyCode__c = 'T100', 
            CostCenter__c = 'T100-12345'
        );
        ccList.add(cc_1);

        cc_2 = new CostCenter__c(
            Name = 'Test Cost Center 1', 
            Company__c = comp_SDSAP.Id, 
            CompanyCode__c = 'T501', 
            CostCenter__c = 'T501-12345'
        );
        ccList.add(cc_2);

        insert ccList;
           
         
        List<Opportunity> insert_OpptyList = new List<Opportunity>();
        oppty_HQ_1_HQ = new Opportunity(
            Name = 'Test Opportunity 1 HQ',
            RecordTypeId = rcdType_Oppty_HQ.Id,
            CurrencyIsoCode = 'USD', 
            Amount = 5000000, 
            CloseDate = Date.today(), 
            StageName = 'Z01',
            BusinessType__c = 'TI',
            AccountId = acc_1.Id, 
            cOriginAcc__c = acc_1.Id, 
            SalesDepartment__c = cc_1.Id,
             OpportunityCode__c = 'SDS-21999999'

            
        );
          insert_OpptyList.add(oppty_HQ_1_HQ);
           
            oppty_HQ_2_Corp = new Opportunity(
            Name = 'Test Opportunity 2 Collabo',
            RecordTypeId = rcdType_Oppty_HQ.Id,
            CurrencyIsoCode = 'USD', 
            Amount = 5000000, 
            CloseDate = Date.today(), 
            StageName = 'Z01', 
            BusinessType__c = 'TI',
            AccountId = acc_1.Id, 
            cOriginAcc__c = acc_1.Id, 
            SalesDepartment__c = cc_2.Id,
            OpportunityCode__c = 'SDS-21999990'
        );
        insert_OpptyList.add(oppty_HQ_2_Corp);
           
             oppty_HQ_2_HQ = new Opportunity(
            Name = 'Test Opportunity 2 Collabo',
            RecordTypeId = rcdType_Oppty_HQ.Id,
            CurrencyIsoCode = 'USD', 
            Amount = 5000000, 
            CloseDate = Date.today(), 
            StageName = 'Z01', 
            AccountId = acc_1.Id, 
            cOriginAcc__c = acc_1.Id, 
            SalesDepartment__c = cc_1.Id,
            OpportunityCode__c = 'SDS-21999990'
        );   
        insert_OpptyList.add(oppty_HQ_2_HQ);
         insert insert_OpptyList;
       }
           @isTest
           public static void getopportunitytest(){
               System.runAs(user_sysAdmin){
                   Test.startTest();
                   ChangeAccountOppOwnerController.getOppInfo(oppty_HQ_1_HQ.OpportunityCode__c);
                   ChangeAccountOppOwnerController.getOppInfo(oppty_HQ_2_HQ.OpportunityCode__c);
                   ChangeAccountOppOwnerController.getOppInfo('');
                   Test.stopTest();
                   
               }
           }

    
             @isTest
           public static void getAccounttest(){
               System.runAs(user_sysAdmin){
                   Test.startTest();
                   ChangeAccountOppOwnerController.getAccInfo(acc_1.AccountNumber);
                   ChangeAccountOppOwnerController.getAccInfo('');
                   ChangeAccountOppOwnerController.getAccInfo('A1224455');                                           
                   Test.stopTest();
                                                              }
               }
                                                              

    
            @isTest
           public static void updagteAccounttest(){
               System.runAs(user_sysAdmin){
                   Test.startTest();
                   ChangeAccountOppOwnerController.updateAcc('A2100002',user_sysAdmin1.Id);

                   Test.stopTest();
                   
               }
           }
    
            @isTest
           public static void updagteOpptest(){
               System.runAs(user_sysAdmin){
                   Test.startTest();
                   ChangeAccountOppOwnerController.updateOpp(oppty_HQ_1_HQ.OpportunityCode__c,user_sysAdmin1.Id,oppty_HQ_1_HQ.CompanyCode__c);
                   Test.stopTest();
                   
               }
           }
               
           }