force-app/main/default/objects/Delivery_Probabiliy__c/Delivery_Probabiliy__c.object-meta.xml
<CustomObject>
    <label>Opportunity Delivery probability</label>
    <nameField>
        <label>Delivery Probability</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Delivery probability</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Probabiliy__c/fields/DeliveryActivity__c.field-meta.xml
<CustomField>
    <fullName>DeliveryActivity__c</fullName>
    <label>DeliveryActivity</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Delivery_Probabiliy__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Delivery probability</relationshipLabel>
    <relationshipName>Opportunity_Delivery_probability</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/DeliveryProbabilityCmpController.cls
/**
 * @description       : 
 * @author            : vikrant.ks@samsung.com
 * @group             : 
 * @last modified on  : 02-26-2024
 * @last modified by  : vikrant.ks@samsung.com
 * Modifications Log 
 * Ver   Date         Author            			   Modification
 * 1.0   02-26-2024   vikrant.ks@samsung.com           Initial Version (MYSALES-447)
**/
public class DeliveryProbabilityCmpController{
    @AuraEnabled    
    public static String DeliveryProbabilityList(String oppId){
        
        List<Delivery_Probabiliy__c> DP = [Select DeliveryActivity__c from Delivery_Probabiliy__c where Opportunity__c = :oppId Limit 1];
        if(DP.size()>0){
        	return DP[0].DeliveryActivity__c;
        }
        return '';
    }
}