force-app/main/default/objects/ProfitLoss__c/ProfitLoss__c.object-meta.xml
<CustomObject>
    <label>ProfitLoss</label>
    <nameField>
        <displayFormat>PL-{YYYY}{MM}{000000}</displayFormat>
        <label>ProfitLoss No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ProfitLoss</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/ProfitLoss__c/fields/BACode__c.field-meta.xml
<CustomField>
    <fullName>BACode__c</fullName>
    <label>BA Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProfitLoss__c/fields/BALANCE_FLAG__c.field-meta.xml
<CustomField>
    <fullName>BALANCE_FLAG__c</fullName>
    <label>BALANCE_FLAG</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProfitLoss__c/fields/BAName__c.field-meta.xml
<CustomField>
    <fullName>BAName__c</fullName>
    <label>BA Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProfitLoss__c/fields/BizType1__c.field-meta.xml
<CustomField>
    <fullName>BizType1__c</fullName>
    <label>Biz Type1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProfitLoss__c/fields/BizType2__c.field-meta.xml
<CustomField>
    <fullName>BizType2__c</fullName>
    <label>Biz Type2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProfitLoss__c/fields/BizYear__c.field-meta.xml
<CustomField>
    <fullName>BizYear__c</fullName>
    <label>Biz Year</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProfitLoss__c/fields/Contract01__c.field-meta.xml
<CustomField>
    <fullName>Contract01__c</fullName>
    <description>01월 수주</description>
    <label>Contract01</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProfitLoss__c/fields/Contract02__c.field-meta.xml
<CustomField>
    <fullName>Contract02__c</fullName>
    <description>02월 수주</description>
    <label>Contract02</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProfitLoss__c/fields/Contract03__c.field-meta.xml
<CustomField>
    <fullName>Contract03__c</fullName>
    <description>03월 수주</description>
    <label>Contract03</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProfitLoss__c/fields/Contract04__c.field-meta.xml
<CustomField>
    <fullName>Contract04__c</fullName>
    <description>04월 수주</description>
    <label>Contract04</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProfitLoss__c/fields/Contract05__c.field-meta.xml
<CustomField>
    <fullName>Contract05__c</fullName>
    <description>05월 수주</description>
    <label>Contract05</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProfitLoss__c/fields/Contract06__c.field-meta.xml
<CustomField>
    <fullName>Contract06__c</fullName>
    <description>06월 수주</description>
    <label>Contract06</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProfitLoss__c/fields/Contract07__c.field-meta.xml
<CustomField>
    <fullName>Contract07__c</fullName>
    <description>07월 수주</description>
    <label>Contract07</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProfitLoss__c/fields/Contract08__c.field-meta.xml
<CustomField>
    <fullName>Contract08__c</fullName>
    <description>08월 수주</description>
    <label>Contract08</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProfitLoss__c/fields/Contract09__c.field-meta.xml
<CustomField>
    <fullName>Contract09__c</fullName>
    <description>09월 수주</description>
    <label>Contract09</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProfitLoss__c/fields/Contract10__c.field-meta.xml
<CustomField>
    <fullName>Contract10__c</fullName>
    <description>10월 수주</description>
    <label>Contract10</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProfitLoss__c/fields/Contract11__c.field-meta.xml
<CustomField>
    <fullName>Contract11__c</fullName>
    <description>11월 수주</description>
    <label>Contract11</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProfitLoss__c/fields/Contract12__c.field-meta.xml
<CustomField>
    <fullName>Contract12__c</fullName>
    <description>12월 수주</description>
    <label>Contract12</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProfitLoss__c/fields/DeliveryDeptL1__c.field-meta.xml
<CustomField>
    <fullName>DeliveryDeptL1__c</fullName>
    <label>Delivery Dept L1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProfitLoss__c/fields/DeliveryDeptL2__c.field-meta.xml
<CustomField>
    <fullName>DeliveryDeptL2__c</fullName>
    <label>Delivery Dept L2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProfitLoss__c/fields/DeliveryDeptL3__c.field-meta.xml
<CustomField>
    <fullName>DeliveryDeptL3__c</fullName>
    <label>Delivery Dept L3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProfitLoss__c/fields/DeliveryDeptL4__c.field-meta.xml
<CustomField>
    <fullName>DeliveryDeptL4__c</fullName>
    <label>Delivery Dept L4</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProfitLoss__c/fields/DeliveryDeptL5__c.field-meta.xml
<CustomField>
    <fullName>DeliveryDeptL5__c</fullName>
    <label>Delivery Dept L5</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProfitLoss__c/fields/DeliveryDeptName__c.field-meta.xml
<CustomField>
    <fullName>DeliveryDeptName__c</fullName>
    <label>Delivery Dept Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProfitLoss__c/fields/GroupInOut__c.field-meta.xml
<CustomField>
    <fullName>GroupInOut__c</fullName>
    <label>Group InOut</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProfitLoss__c/fields/LocalInternational__c.field-meta.xml
<CustomField>
    <fullName>LocalInternational__c</fullName>
    <label>Local International</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProfitLoss__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProfitLoss__c/fields/OpportunityName__c.field-meta.xml
<CustomField>
    <fullName>OpportunityName__c</fullName>
    <label>Opportunity Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProfitLoss__c/fields/OriginAccount__c.field-meta.xml
<CustomField>
    <fullName>OriginAccount__c</fullName>
    <label>Origin Account</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProfitLoss__c/fields/REAL_FLAG2__c.field-meta.xml
<CustomField>
    <fullName>REAL_FLAG2__c</fullName>
    <label>REAL_FLAG2</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProfitLoss__c/fields/RegionCode__c.field-meta.xml
<CustomField>
    <fullName>RegionCode__c</fullName>
    <label>Region Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProfitLoss__c/fields/RegionName__c.field-meta.xml
<CustomField>
    <fullName>RegionName__c</fullName>
    <label>Region Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProfitLoss__c/fields/Revenue01__c.field-meta.xml
<CustomField>
    <fullName>Revenue01__c</fullName>
    <description>01월 매출</description>
    <label>Revenue01</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProfitLoss__c/fields/Revenue02__c.field-meta.xml
<CustomField>
    <fullName>Revenue02__c</fullName>
    <description>02월 매출</description>
    <label>Revenue02</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProfitLoss__c/fields/Revenue03__c.field-meta.xml
<CustomField>
    <fullName>Revenue03__c</fullName>
    <description>03월 매출</description>
    <label>Revenue03</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProfitLoss__c/fields/Revenue04__c.field-meta.xml
<CustomField>
    <fullName>Revenue04__c</fullName>
    <description>04월 매출</description>
    <label>Revenue04</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProfitLoss__c/fields/Revenue05__c.field-meta.xml
<CustomField>
    <fullName>Revenue05__c</fullName>
    <description>05월 매출</description>
    <label>Revenue05</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProfitLoss__c/fields/Revenue06__c.field-meta.xml
<CustomField>
    <fullName>Revenue06__c</fullName>
    <description>06월 매출</description>
    <label>Revenue06</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProfitLoss__c/fields/Revenue07__c.field-meta.xml
<CustomField>
    <fullName>Revenue07__c</fullName>
    <description>07월 매출</description>
    <label>Revenue07</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProfitLoss__c/fields/Revenue08__c.field-meta.xml
<CustomField>
    <fullName>Revenue08__c</fullName>
    <description>08월 매출</description>
    <label>Revenue08</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProfitLoss__c/fields/Revenue09__c.field-meta.xml
<CustomField>
    <fullName>Revenue09__c</fullName>
    <description>09월 매출</description>
    <label>Revenue09</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProfitLoss__c/fields/SalesDeptL1__c.field-meta.xml
<CustomField>
    <fullName>SalesDeptL1__c</fullName>
    <label>Sales Dept L1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProfitLoss__c/fields/SalesDeptL2__c.field-meta.xml
<CustomField>
    <fullName>SalesDeptL2__c</fullName>
    <label>Sales Dept L2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProfitLoss__c/fields/SalesDeptL3__c.field-meta.xml
<CustomField>
    <fullName>SalesDeptL3__c</fullName>
    <label>Sales Dept L3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProfitLoss__c/fields/SalesDeptL4__c.field-meta.xml
<CustomField>
    <fullName>SalesDeptL4__c</fullName>
    <label>Sales Dept L4</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProfitLoss__c/fields/SalesDeptL5__c.field-meta.xml
<CustomField>
    <fullName>SalesDeptL5__c</fullName>
    <label>Sales Dept L5</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProfitLoss__c/fields/SalesDeptNameL1__c.field-meta.xml
<CustomField>
    <fullName>SalesDeptNameL1__c</fullName>
    <label>Sales Dept Name L1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProfitLoss__c/fields/SalesDeptNameL2__c.field-meta.xml
<CustomField>
    <fullName>SalesDeptNameL2__c</fullName>
    <label>Sales Dept Name L2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProfitLoss__c/fields/SalesDeptNameL3__c.field-meta.xml
<CustomField>
    <fullName>SalesDeptNameL3__c</fullName>
    <label>Sales Dept Name L3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProfitLoss__c/fields/SalesDeptNameL4__c.field-meta.xml
<CustomField>
    <fullName>SalesDeptNameL4__c</fullName>
    <label>Sales Dept Name L4</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProfitLoss__c/fields/SalesDeptNameL5__c.field-meta.xml
<CustomField>
    <fullName>SalesDeptNameL5__c</fullName>
    <label>Sales Dept Name L5</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProfitLoss__c/fields/ServiceName__c.field-meta.xml
<CustomField>
    <fullName>ServiceName__c</fullName>
    <label>Service Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProfitLoss__c/fields/SolutionCode__c.field-meta.xml
<CustomField>
    <fullName>SolutionCode__c</fullName>
    <label>Solution Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProfitLoss__c/fields/SolutionName__c.field-meta.xml
<CustomField>
    <fullName>SolutionName__c</fullName>
    <label>Solution Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProfitLoss__c/fields/StndCustCode__c.field-meta.xml
<CustomField>
    <fullName>StndCustCode__c</fullName>
    <label>Standard Cust Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProfitLoss__c/fields/StndCustName__c.field-meta.xml
<CustomField>
    <fullName>StndCustName__c</fullName>
    <label>Standard Cust Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProfitLoss__c/fields/Version__c.field-meta.xml
<CustomField>
    <fullName>Version__c</fullName>
    <label>Version</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>Opportunity</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Project</relationshipLabel>
    <relationshipName>BO_Project</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/IF_LegGetProfitLossController.cls
/**
 * @description       : 
 * @author            : raeganja@partner.samsung.com
 * @group             : 
 * @last modified on  : 2021-04-12
 * @last modified by  : raeganja@partner.samsung.com
 * Modifications Log 
 * Ver   Date         Author                         Modification
 * 1.0   2021-01-15   raeganja@partner.samsung.com   Initial Version
**/
@RestResource( UrlMapping='/IF031/*')
global class IF_LegGetProfitLossController implements Schedulable{
    private static final String INTERFACE_ID = 'IF-031';
    private static final String APEX_CLASS   = 'IF_LegGetProfitLossController';
    private static final String METHOD_NAME  = 'getProfitLoss';

    @HttpPost
    global static OutputHeader receiveProfitLoss(){
        // 로그 정보
        String              guId      = IF_Util.generateGuid();
        OutputHeader        outHeader = new OutputHeader();
        IF_Log              log       = new IF_Log();
        IF_Log.InterfaceLog infLog    = null;

        // RequestBody 데이터 확인
        RestRequest req = RestContext.request;
        Blob    reqBody = req.requestBody;
        RestResponse rep= RestContext.response;
        rep.addHeader('Content-Type', 'application/json');

        try{
            outHeader.EV_RESULT      = IF_Util.RESULT_STATUS_SUCCESS;
            outHeader.EV_MESG        = IF_Util.RESULT_MESSAGE_SUCCESS;

            // 데이터 존재 하는지 여부 확인
            Map<String,Object> bodyMap =( Map<String, Object>) JSON.deserializeUntyped( reqBody.toString());
            if( bodyMap == null){

                outHeader.EV_RESULT = IF_Util.RESULT_MESSAGE_ERROR;
                outHeader.EV_MESG   = 'No Data';

                infLog = new IF_Log.InterfaceLog( INTERFACE_ID, guId, APEX_CLASS, METHOD_NAME, reqBody.toString(), JSON.serialize(outHeader));
                log.createLog( infLog);
                return outHeader;
            }

            List<Object>        dataList       = (List<Object>)bodyMap.get('IT_DATA');
            List<ProfitLoss__c> profitLossList = new List<ProfitLoss__c>();
            String bizYear  = '';//사업년도;
            String version  = '';//버전;
            String realFlag2= '';//실매출 구분(수주부서 L2);

            for(Object obj : dataList) {
                Map<String,Object> objMap = (Map<String,Object>) obj;

                //Upsert 정보 매핑
            
                bizYear   = Util_String.nvlStr(objMap.get('BizYear'));//사업년도;
                version   = Util_String.nvlStr(objMap.get('Version'));//버전;
                realFlag2 = Util_String.nvlStr(objMap.get('REAL_FLAG2'));//실매출 구분(수주부서 L2);

                if(String.isNotBlank(bizYear) && String.isNotBlank(version) && String.isNotBlank(realFlag2)){
                    ProfitLoss__c profitLoss = new ProfitLoss__c();

                    profitLoss.BizYear__c               = bizYear;//사업년도;
                    profitLoss.Version__c               = version;//버전
                    profitLoss.REAL_FLAG2__c            = realFlag2;//실매출 구분(수주부서 L2)
                    profitLoss.CompanyCode__c           = Util_String.nvlStr(objMap.get('CompanyCode'));//법인코드
                    profitLoss.CompanyName__c           = Util_String.nvlStr(objMap.get('CompanyName'));//법인명
                    profitLoss.BACode__c                = Util_String.nvlStr(objMap.get('BACode'));//Business Area
                    profitLoss.BAName__c                = Util_String.nvlStr(objMap.get('BAName'));//Business Area Name
                    profitLoss.BALANCE_FLAG__c          = Util_String.nvlStr(objMap.get('BALANCE_FLAG'));//차감구분
                    profitLoss.Opportunity__c           = Util_String.nvlStr(objMap.get('Opportunity'));//사업기회코드
                    profitLoss.OpportunityName__c       = Util_String.nvlStr(objMap.get('OpportunityName'));//사업기회명
                    profitLoss.Project__c               = Util_String.nvlStr(objMap.get('Project'));//프로젝트코드
                    profitLoss.ProjectName__c           = Util_String.nvlStr(objMap.get('ProjectName'));//프로젝트명
                    profitLoss.RegionCode__c            = Util_String.nvlStr(objMap.get('RegionCode'));//권역
                    profitLoss.RegionName__c            = Util_String.nvlStr(objMap.get('RegionName'));//권역명
                    profitLoss.SalesDeptL1__c           = Util_String.nvlStr(objMap.get('SalesDeptL1'));//수주부서코드 L1
                    profitLoss.SalesDeptNameL1__c       = Util_String.nvlStr(objMap.get('SalesDeptNameL1'));//수주부서명 L1
                    profitLoss.SalesDeptL2__c           = Util_String.nvlStr(objMap.get('SalesDeptL2'));//수주부서코드 L2
                    profitLoss.SalesDeptNameL2__c       = Util_String.nvlStr(objMap.get('SalesDeptNameL2'));//수주부서명 L2
                    profitLoss.SalesDeptL3__c           = Util_String.nvlStr(objMap.get('SalesDeptL3'));//수주부서코드 L3
                    profitLoss.SalesDeptNameL3__c       = Util_String.nvlStr(objMap.get('SalesDeptNameL3'));//수주부서명 L3
                    profitLoss.SalesDeptL4__c           = Util_String.nvlStr(objMap.get('SalesDeptL4'));//수주부서코드 L4
                    profitLoss.SalesDeptNameL4__c       = Util_String.nvlStr(objMap.get('SalesDeptNameL4'));//수주부서명 L4
                    profitLoss.SalesDeptL5__c           = Util_String.nvlStr(objMap.get('SalesDeptL5'));//수주부서코드 L5
                    profitLoss.SalesDeptNameL5__c       = Util_String.nvlStr(objMap.get('SalesDeptNameL5'));//수주부서명 L5
                    profitLoss.DeliveryDeptL1__c        = Util_String.nvlStr(objMap.get('DeliveryDeptL1'));//개발부서코드 L1
                    profitLoss.DeliveryDeptL2__c        = Util_String.nvlStr(objMap.get('DeliveryDeptL2'));//개발부서코드 L2
                    profitLoss.DeliveryDeptL3__c        = Util_String.nvlStr(objMap.get('DeliveryDeptL3'));//개발부서코드 L3
                    profitLoss.DeliveryDeptL4__c        = Util_String.nvlStr(objMap.get('DeliveryDeptL4'));//개발부서코드 L4
                    profitLoss.DeliveryDeptL5__c        = Util_String.nvlStr(objMap.get('DeliveryDeptL5'));//개발부서코드 L5
                    profitLoss.DeliveryDeptName__c      = Util_String.nvlStr(objMap.get('DeliveryDeptName'));//개발부서명
                    profitLoss.BizType1__c              = Util_String.nvlStr(objMap.get('BizType1'));//사업유형3
                    profitLoss.BizType2__c              = Util_String.nvlStr(objMap.get('BizType2'));//사업유형3
                    profitLoss.ServiceCode__c           = Util_String.nvlStr(objMap.get('ServiceCode'));//서비스코드
                    profitLoss.ServiceName__c           = Util_String.nvlStr(objMap.get('ServiceName'));//서비스명
                    profitLoss.SolutionCode__c          = Util_String.nvlStr(objMap.get('SolutionCode'));//솔루션코드
                    profitLoss.SolutionName__c          = Util_String.nvlStr(objMap.get('SolutionName'));//솔루션명
                    profitLoss.OriginAccount__c         = Util_String.nvlStr(objMap.get('OriginAccount'));//원청고객코드
                    profitLoss.AccountName__c           = Util_String.nvlStr(objMap.get('AccountName'));//원천고객명
                    profitLoss.StndCustCode__c          = Util_String.nvlStr(objMap.get('StndCustCode'));//표준고객코드
                    profitLoss.StndCustName__c          = Util_String.nvlStr(objMap.get('StndCustName'));//표준고객명
                    profitLoss.GroupInOut__c            = Util_String.nvlStr(objMap.get('GroupInOut'));//그룹내외 구분 (10:대내, 20:대외)
                    profitLoss.LocalInternational__c    = Util_String.nvlStr(objMap.get('LocalInternational'));//국내외 구분 (10:국내, 20:해외)
                    profitLoss.CurrencyIsoCode          = Util_String.nvlStr(objMap.get('CurrencyIsoCode'));//화폐코드
                    profitLoss.Contract01__c            = Util_String.nvlDec(objMap.get('Contract01'));//수주금액01
                    profitLoss.Contract02__c            = Util_String.nvlDec(objMap.get('Contract02'));//수주금액02
                    profitLoss.Contract03__c            = Util_String.nvlDec(objMap.get('Contract03'));//수주금액03
                    profitLoss.Contract04__c            = Util_String.nvlDec(objMap.get('Contract04'));//수주금액04
                    profitLoss.Contract05__c            = Util_String.nvlDec(objMap.get('Contract05'));//수주금액05
                    profitLoss.Contract06__c            = Util_String.nvlDec(objMap.get('Contract06'));//수주금액06
                    profitLoss.Contract07__c            = Util_String.nvlDec(objMap.get('Contract07'));//수주금액07
                    profitLoss.Contract08__c            = Util_String.nvlDec(objMap.get('Contract08'));//수주금액08
                    profitLoss.Contract09__c            = Util_String.nvlDec(objMap.get('Contract09'));//수주금액09
                    profitLoss.Contract10__c            = Util_String.nvlDec(objMap.get('Contract10'));//수주금액10
                    profitLoss.Contract11__c            = Util_String.nvlDec(objMap.get('Contract11'));//수주금액11
                    profitLoss.Contract12__c            = Util_String.nvlDec(objMap.get('Contract12'));//수주금액12
                    profitLoss.Revenue01__c             = Util_String.nvlDec(objMap.get('Revenue01'));//매출금액01
                    profitLoss.Revenue02__c             = Util_String.nvlDec(objMap.get('Revenue02'));//매출금액02
                    profitLoss.Revenue03__c             = Util_String.nvlDec(objMap.get('Revenue03'));//매출금액03
                    profitLoss.Revenue04__c             = Util_String.nvlDec(objMap.get('Revenue04'));//매출금액04
                    profitLoss.Revenue05__c             = Util_String.nvlDec(objMap.get('Revenue05'));//매출금액05
                    profitLoss.Revenue06__c             = Util_String.nvlDec(objMap.get('Revenue06'));//매출금액06
                    profitLoss.Revenue07__c             = Util_String.nvlDec(objMap.get('Revenue07'));//매출금액07
                    profitLoss.Revenue08__c             = Util_String.nvlDec(objMap.get('Revenue08'));//매출금액08
                    profitLoss.Revenue09__c             = Util_String.nvlDec(objMap.get('Revenue09'));//매출금액09
                    profitLoss.Revenue10__c             = Util_String.nvlDec(objMap.get('Revenue10'));//매출금액10
                    profitLoss.Revenue11__c             = Util_String.nvlDec(objMap.get('Revenue11'));//매출금액11
                    profitLoss.Revenue12__c             = Util_String.nvlDec(objMap.get('Revenue12'));//매출금액12
                    profitLoss.Profit01__c              = Util_String.nvlDec(objMap.get('Profit01'));//영업이익01
                    profitLoss.Profit02__c              = Util_String.nvlDec(objMap.get('Profit02'));//영업이익02
                    profitLoss.Profit03__c              = Util_String.nvlDec(objMap.get('Profit03'));//영업이익03
                    profitLoss.Profit04__c              = Util_String.nvlDec(objMap.get('Profit04'));//영업이익04
                    profitLoss.Profit05__c              = Util_String.nvlDec(objMap.get('Profit05'));//영업이익05
                    profitLoss.Profit06__c              = Util_String.nvlDec(objMap.get('Profit06'));//영업이익06
                    profitLoss.Profit07__c              = Util_String.nvlDec(objMap.get('Profit07'));//영업이익07
                    profitLoss.Profit08__c              = Util_String.nvlDec(objMap.get('Profit08'));//영업이익08
                    profitLoss.Profit09__c              = Util_String.nvlDec(objMap.get('Profit09'));//영업이익09
                    profitLoss.Profit10__c              = Util_String.nvlDec(objMap.get('Profit10'));//영업이익10
                    profitLoss.Profit11__c              = Util_String.nvlDec(objMap.get('Profit11'));//영업이익11
                    profitLoss.Profit12__c              = Util_String.nvlDec(objMap.get('Profit12'));//영업이익12

                    //Upsert 를 위한 Key값
                    //profitLoss.ExternalId__c            = bizYear + '_' + version +'_'+ realFlag2;
                    profitLossList.add(profitLoss);
                }
            }
            
            insert profitLossList;
            outHeader.TOTAL_COUNT = profitLossList.size();

            // 로그 객체 생성
            infLog = new IF_Log.InterfaceLog( INTERFACE_ID, guId, APEX_CLASS, METHOD_NAME, reqBody.toString(), JSON.serialize(outHeader));
        } catch(Exception e){

            outHeader.EV_RESULT      = IF_Util.RESULT_STATUS_SUCCESS;
            outHeader.EV_MESG        = IF_Util.RESULT_MESSAGE_SUCCESS;
            infLog = new IF_Log.InterfaceLog( INTERFACE_ID, guId, APEX_CLASS, METHOD_NAME, reqBody.toString(), JSON.serialize(outHeader),e);
        }
        log.createLog( infLog);
        return outHeader;
    }

    // Callout 처리
    // @Future( Callout=true)
    global static void getProfitLoss(String bizYear, String version){
        // 로그 변수
        String      guId = IF_Util.generateGuid();
        IF_Callout  call = new IF_Callout( INTERFACE_ID);
        IF_Log      log  = new IF_Log();
        IF_Log.InterfaceLog ifLog;

        // 검색할 사업년도, 버전 -> json 변환
        Map<String,String> reqMap = new Map<String,String>();
        reqMap.put('BizYear' , bizYear);
        reqMap.put('Version' , version);
        String jsonBody = JSON.serialize(reqMap);

        try{

            // callout
            Map<String, Object> rtnMap = call.httpCallout(jsonBody, '');
            String statusCode = rtnMap.get( 'StatusCode') + '';
            ifLog = new IF_Log.InterfaceLog(INTERFACE_ID, guId, APEX_CLASS, METHOD_NAME, jsonBody, 'Async(' + statusCode + ')');
        }catch( Exception e){

            ifLog = new IF_Log.InterfaceLog(INTERFACE_ID, guId, APEX_CLASS, METHOD_NAME, jsonBody, 'Async',e);
        }
        log.createLog( ifLog);
    }

    global void execute( SchedulableContext SC){

        Date toDt = Date.today();
        String bizYear = toDt.year()+'';
        String version = '';

        getProfitLoss ( bizYear, version);
    }

    // 전달 값: JitterBit
    global class OutputHeader{

        @AuraEnabled
        public Integer TOTAL_COUNT = 0; // 전체 데이터 건수
        @AuraEnabled
        public String EV_RESULT = ''; // 처리 결과
        @AuraEnabled
        public String EV_MESG = ''; // 처리 메세지
        @AuraEnabled
        public List<OutputClass> DATA; // 데이터 포멧
    }

    public class OutputClass{ }
}