force-app/main/default/objects/MDGAccount__c/MDGAccount__c.object-meta.xml
<CustomObject>
    <label>MDG Account</label>
    <nameField>
        <label>Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MDG Account</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/MDGAccount__c/fields/BP_HEADER__c.field-meta.xml
<CustomField>
    <fullName>BP_HEADER__c</fullName>
    <label>BP_HEADER</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/CITY1__c.field-meta.xml
<CustomField>
    <fullName>CITY1__c</fullName>
    <label>CITY1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/CITY2__c.field-meta.xml
<CustomField>
    <fullName>CITY2__c</fullName>
    <label>CITY2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/COUNTRY__c.field-meta.xml
<CustomField>
    <fullName>COUNTRY__c</fullName>
    <label>COUNTRY</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/MDG_INFO__c.field-meta.xml
<CustomField>
    <fullName>MDG_INFO__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MDG_INFO</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/NAME1__c.field-meta.xml
<CustomField>
    <fullName>NAME1__c</fullName>
    <label>NAME1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/NAME2__c.field-meta.xml
<CustomField>
    <fullName>NAME2__c</fullName>
    <label>NAME2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/POST_CODE1__c.field-meta.xml
<CustomField>
    <fullName>POST_CODE1__c</fullName>
    <label>POST_CODE1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/REGION__c.field-meta.xml
<CustomField>
    <fullName>REGION__c</fullName>
    <label>REGION</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/TEL_NUMBER__c.field-meta.xml
<CustomField>
    <fullName>TEL_NUMBER__c</fullName>
    <label>TEL_NUMBER</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>dummy object에 account 와 account sales area 데이터를 구분하기 위한 필드, A : Account, S : Account Sales Area</description>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MDG_AccountInfoUpdate_Test.cls
/**
 * @description       : 
 * @author            : anish.jain@partner.samsung.com
 * @group             : 
 * @last modified on  : 12-26-2022
 * @last modified by  : anish.jain@partner.samsung.com
 * Modifications Log 
 * Ver   Date         Author                   Modification
 * 1.0   12-26-2022   anish.jain@partner.samsung.com   Initial Version
**/

@isTest
public class MDG_AccountInfoUpdate_Test {
    
    static MDGAccount__c md1;
    static{
          List<MDGAccount__c> MDGList = new List<MDGAccount__c>();
          md1 = new MDGAccount__c(
            Name= 'TestMDG',
            BP_HEADER__c = 'A2040734',
            CITY1__c = 'CNSZH',
            CITY2__c = 'CNSZP',
            STREET__c = null,
            POST_CODE1__c= null,
            COUNTRY__c = 'Korea' ,
            REGION__c = 'Seoul',
            NAME1__c= 'Marketing Lead Converted',
            NAME2__c= 'CO,LTD',
            TEL_NUMBER__c = '1234567865',
            MDG_INFO__c = FALSE,
            Type__c = 'A'
        );
        MDGList.add(md1);
        insert MDGList;
    }
    
        @isTest
        public static void Test_Batch_MDGInfo(){
        Test.startTest();
        DataBase.executeBatch( new MDG_AccountInfoUpdate(), 10);
        Test.stopTest();
    }
    
        @isTest
        public static void Test_Shcedule(){
        Test.startTest();
        System.schedule('Test','0 0 4 * * ? *', new MDG_AccountInfoUpdate());
        Test.stopTest();
    }

}