force-app/main/default/objects/MDGAccount__c/MDGAccount__c.object-meta.xml
<CustomObject>
    <label>MDG Account</label>
    <nameField>
        <label>Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MDG Account</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/MDGAccount__c/fields/ANTLF__c.field-meta.xml
<CustomField>
    <fullName>ANTLF__c</fullName>
    <label>ANTLF</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/AWAHR__c.field-meta.xml
<CustomField>
    <fullName>AWAHR__c</fullName>
    <label>AWAHR</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/BP_HEADER__c.field-meta.xml
<CustomField>
    <fullName>BP_HEADER__c</fullName>
    <label>BP_HEADER</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/IsBatch__c.field-meta.xml
<CustomField>
    <fullName>IsBatch__c</fullName>
    <label>IsBatch</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/LPRIO__c.field-meta.xml
<CustomField>
    <fullName>LPRIO__c</fullName>
    <label>LPRIO</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/NAME1__c.field-meta.xml
<CustomField>
    <fullName>NAME1__c</fullName>
    <label>NAME1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>dummy object에 account 와 account sales area 데이터를 구분하기 위한 필드, A : Account, S : Account Sales Area</description>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Batch_AccountMdgController_Test.cls
/**
 * @description       : 
 * @author            : soohong0.kim@partner.samsung.com
 * @group             : 
 * @last modified on  : 02-19-2021
 * @last modified by  : soohong0.kim@partner.samsung.com
 * Modifications Log 
 * Ver   Date         Author                             Modification
 * 1.0   01-12-2021   soohong0.kim@partner.samsung.com   Initial Version
**/


//Batch_AccountController, Batch_AccountSalesAreaController 의 Test Class
@isTest
public class Batch_AccountMdgController_Test {
    @TestSetup
    static void setData(){

        MDGAccount__c mAcc = new MDGAccount__c();
        mAcc.Type__c = 'A';
        mAcc.BP_HEADER__c = 'test';
        mAcc.isBatch__c = 'N';
        mAcc.NAME1__c = 'test';
        mAcc.ExternalId__c = 'test1';
        insert mAcc;

        MDGAccount__c sales = new MDGAccount__c();
        sales.Type__c = 'S';
        sales.BP_HEADER__c = 'test';
        sales.AWAHR__c = '1';
        sales.ANTLF__c = '1';
        sales.LPRIO__c = '1';
        sales.isBatch__c = 'N';
        sales.ExternalId__c = 'test2';
        insert sales;
    }
    private static testMethod void test01() {
        Test.startTest();
        Database.executeBatch(new Batch_AccountController());
        Test.stopTest();
    }
}