force-app/main/default/objects/MDGAccount__c/MDGAccount__c.object-meta.xml
<CustomObject>
    <label>MDG Account</label>
    <nameField>
        <label>Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MDG Account</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/MDGAccount__c/fields/ANTLF__c.field-meta.xml
<CustomField>
    <fullName>ANTLF__c</fullName>
    <label>ANTLF</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/AUFSD__c.field-meta.xml
<CustomField>
    <fullName>AUFSD__c</fullName>
    <label>AUFSD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/AWAHR__c.field-meta.xml
<CustomField>
    <fullName>AWAHR__c</fullName>
    <label>AWAHR</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/BP_HEADER__c.field-meta.xml
<CustomField>
    <fullName>BP_HEADER__c</fullName>
    <label>BP_HEADER</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/BZIRK__c.field-meta.xml
<CustomField>
    <fullName>BZIRK__c</fullName>
    <label>BZIRK</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/CITY1__c.field-meta.xml
<CustomField>
    <fullName>CITY1__c</fullName>
    <label>CITY1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/CITY2__c.field-meta.xml
<CustomField>
    <fullName>CITY2__c</fullName>
    <label>CITY2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/COUNTRY__c.field-meta.xml
<CustomField>
    <fullName>COUNTRY__c</fullName>
    <label>COUNTRY</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/FAKSD__c.field-meta.xml
<CustomField>
    <fullName>FAKSD__c</fullName>
    <label>FAKSD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/FAX_NUMBER__c.field-meta.xml
<CustomField>
    <fullName>FAX_NUMBER__c</fullName>
    <label>FAX_NUMBER</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/INCO1__c.field-meta.xml
<CustomField>
    <fullName>INCO1__c</fullName>
    <label>INCO1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/INCO2__c.field-meta.xml
<CustomField>
    <fullName>INCO2__c</fullName>
    <label>INCO2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/IsBatch__c.field-meta.xml
<CustomField>
    <fullName>IsBatch__c</fullName>
    <label>IsBatch</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/KALKS__c.field-meta.xml
<CustomField>
    <fullName>KALKS__c</fullName>
    <label>KALKS</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/KDGRP__c.field-meta.xml
<CustomField>
    <fullName>KDGRP__c</fullName>
    <label>KDGRP</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/KONDA__c.field-meta.xml
<CustomField>
    <fullName>KONDA__c</fullName>
    <label>KONDA</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/KTGRD__c.field-meta.xml
<CustomField>
    <fullName>KTGRD__c</fullName>
    <label>KTGRD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/KUNNR__c.field-meta.xml
<CustomField>
    <fullName>KUNNR__c</fullName>
    <label>KUNNR</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/KURST__c.field-meta.xml
<CustomField>
    <fullName>KURST__c</fullName>
    <label>KURST</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/KZAZU__c.field-meta.xml
<CustomField>
    <fullName>KZAZU__c</fullName>
    <label>KZAZU</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/LAND1__c.field-meta.xml
<CustomField>
    <fullName>LAND1__c</fullName>
    <label>LAND1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/LIFSD__c.field-meta.xml
<CustomField>
    <fullName>LIFSD__c</fullName>
    <label>LIFSD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/LOEVM__c.field-meta.xml
<CustomField>
    <fullName>LOEVM__c</fullName>
    <label>LOEVM</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/LPRIO__c.field-meta.xml
<CustomField>
    <fullName>LPRIO__c</fullName>
    <label>LPRIO</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/mLOEVM__c.field-meta.xml
<CustomField>
    <fullName>mLOEVM__c</fullName>
    <label>mLOEVM</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/NAME1__c.field-meta.xml
<CustomField>
    <fullName>NAME1__c</fullName>
    <label>NAME1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/NAME2__c.field-meta.xml
<CustomField>
    <fullName>NAME2__c</fullName>
    <label>NAME2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/PLTYP__c.field-meta.xml
<CustomField>
    <fullName>PLTYP__c</fullName>
    <label>PLTYP</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/POST_CODE1__c.field-meta.xml
<CustomField>
    <fullName>POST_CODE1__c</fullName>
    <label>POST_CODE1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/REGION__c.field-meta.xml
<CustomField>
    <fullName>REGION__c</fullName>
    <label>REGION</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/SPART__c.field-meta.xml
<CustomField>
    <fullName>SPART__c</fullName>
    <label>SPART</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/STCD1__c.field-meta.xml
<CustomField>
    <fullName>STCD1__c</fullName>
    <label>STCD1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/STCD2__c.field-meta.xml
<CustomField>
    <fullName>STCD2__c</fullName>
    <label>STCD2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/STCD3__c.field-meta.xml
<CustomField>
    <fullName>STCD3__c</fullName>
    <label>STCD3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/STCD4__c.field-meta.xml
<CustomField>
    <fullName>STCD4__c</fullName>
    <label>STCD4</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/TEL_NUMBER__c.field-meta.xml
<CustomField>
    <fullName>TEL_NUMBER__c</fullName>
    <label>TEL_NUMBER</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>dummy object에 account 와 account sales area 데이터를 구분하기 위한 필드, A : Account, S : Account Sales Area</description>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/URI_ADDR__c.field-meta.xml
<CustomField>
    <fullName>URI_ADDR__c</fullName>
    <label>URI_ADDR</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/VKBUR__c.field-meta.xml
<CustomField>
    <fullName>VKBUR__c</fullName>
    <label>VKBUR</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/VKORG__c.field-meta.xml
<CustomField>
    <fullName>VKORG__c</fullName>
    <label>VKORG</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/VSBED__c.field-meta.xml
<CustomField>
    <fullName>VSBED__c</fullName>
    <label>VSBED</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/VTWEG__c.field-meta.xml
<CustomField>
    <fullName>VTWEG__c</fullName>
    <label>VTWEG</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/WAERS__c.field-meta.xml
<CustomField>
    <fullName>WAERS__c</fullName>
    <label>WAERS</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/ZTERM__c.field-meta.xml
<CustomField>
    <fullName>ZTERM__c</fullName>
    <label>ZTERM</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/ZZJ_1KFRE__c.field-meta.xml
<CustomField>
    <fullName>ZZJ_1KFRE__c</fullName>
    <label>ZZJ_1KFRE</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/ZZKDGRP_C__c.field-meta.xml
<CustomField>
    <fullName>ZZKDGRP_C__c</fullName>
    <label>ZZKDGRP_C</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/ZZNSTKUNL1__c.field-meta.xml
<CustomField>
    <fullName>ZZNSTKUNL1__c</fullName>
    <label>ZZNSTKUNL1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/ZZNSTKUNL1_T__c.field-meta.xml
<CustomField>
    <fullName>ZZNSTKUNL1_T__c</fullName>
    <label>ZZNSTKUNL1_T</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/ZZNSTKUNL2__c.field-meta.xml
<CustomField>
    <fullName>ZZNSTKUNL2__c</fullName>
    <label>ZZNSTKUNL2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/ZZNSTKUNL2_T__c.field-meta.xml
<CustomField>
    <fullName>ZZNSTKUNL2_T__c</fullName>
    <label>ZZNSTKUNL2_T</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/ZZNSTKUNL3__c.field-meta.xml
<CustomField>
    <fullName>ZZNSTKUNL3__c</fullName>
    <label>ZZNSTKUNL3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/ZZNSTKUNL3_T__c.field-meta.xml
<CustomField>
    <fullName>ZZNSTKUNL3_T__c</fullName>
    <label>ZZNSTKUNL3_T</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/ZZSHIPPER__c.field-meta.xml
<CustomField>
    <fullName>ZZSHIPPER__c</fullName>
    <label>ZZSHIPPER</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/ZZTOBUSL1__c.field-meta.xml
<CustomField>
    <fullName>ZZTOBUSL1__c</fullName>
    <label>ZZTOBUSL1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/ZZTOBUSL1_EN__c.field-meta.xml
<CustomField>
    <fullName>ZZTOBUSL1_EN__c</fullName>
    <label>ZZTOBUSL1_EN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/ZZTOBUSL1_KO__c.field-meta.xml
<CustomField>
    <fullName>ZZTOBUSL1_KO__c</fullName>
    <label>ZZTOBUSL1_KO</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/ZZTOBUSL2__c.field-meta.xml
<CustomField>
    <fullName>ZZTOBUSL2__c</fullName>
    <label>ZZTOBUSL2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/ZZTOBUSL2_EN__c.field-meta.xml
<CustomField>
    <fullName>ZZTOBUSL2_EN__c</fullName>
    <label>ZZTOBUSL2_EN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/ZZTOBUSL2_KO__c.field-meta.xml
<CustomField>
    <fullName>ZZTOBUSL2_KO__c</fullName>
    <label>ZZTOBUSL2_KO</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MdgAccountController_Test.cls
/**
 * @description       : 
 * @author            : soohong0.kim@partner.samsung.com
 * @group             : 
 * @last modified on  : 03-19-2021
 * @last modified by  : soohong0.kim@partner.samsung.com
 * Modifications Log 
 * Ver   Date         Author                             Modification
 * 1.0   01-12-2021   soohong0.kim@partner.samsung.com   Initial Version
**/
@isTest
public class MdgAccountController_Test {
    
    @TestSetup
    static void setData(){
       
        MDGAccount__c mAcc = new MDGAccount__c();
        mAcc.Type__c = 'A';
        mAcc.BP_HEADER__c = 'test';
        mAcc.isBatch__c = 'N';
        mAcc.NAME1__c = 'test';
        mAcc.ExternalId__c = 'test1';
        insert mAcc;

        MDGAccount__c sales = new MDGAccount__c();
        sales.Type__c = 'S';
        sales.BP_HEADER__c = 'test';
        sales.AWAHR__c = '1';
        sales.ANTLF__c = '1';
        sales.LPRIO__c = '1';
        sales.isBatch__c = 'N';
        sales.ExternalId__c = 'test2';
        insert sales;
    }
    private static testMethod void test01() {
        Test.startTest();
        List<MdgAccount__c> accList = [Select Id, Name, ANTLF__c, AUFSD__c, AWAHR__c, BP_HEADER__c, BZIRK__c, CITY1__c, CITY2__c, COUNTRY__c, FAKSD__c, FAX_NUMBER__c, INCO1__c, INCO2__c, KALKS__c, KDGRP__c, KONDA__c, KTGRD__c, KUNNR__c, KURST__c, KZAZU__c, LAND1__c, LIFSD__c, LOEVM__c, LPRIO__c, NAME1__c, NAME2__c, PLTYP__c, POST_CODE1__c, REGION__c, SPART__c, STCD1__c, STCD2__c, STCD3__c, STCD4__c, STREET__c, TEL_NUMBER__c, URI_ADDR__c, VKBUR__c, VKORG__c, VSBED__c, VTWEG__c, WAERS__c, ZTERM__c, ZZJ_1KFRE__c, ZZKDGRP_C__c, ZZNSTKUNL1_T__c, ZZNSTKUNL1__c, ZZNSTKUNL2_T__c, ZZNSTKUNL2__c, ZZNSTKUNL3_T__c, ZZNSTKUNL3__c, ZZSHIPPER__c, ZZTOBUSL1_EN__c, ZZTOBUSL1_KO__c, ZZTOBUSL2_EN__c, ZZTOBUSL2_KO__c, mLOEVM__c, ExternalId__c, Type__c, ZZTOBUSL1__c, ZZTOBUSL2__c, isBatch__c  From MdgAccount__c Where Type__c = 'A'];
        List<MdgAccount__c> salesList = [Select Id, Name, ANTLF__c, AUFSD__c, AWAHR__c, BP_HEADER__c, BZIRK__c, CITY1__c, CITY2__c, COUNTRY__c, FAKSD__c, FAX_NUMBER__c, INCO1__c, INCO2__c, KALKS__c, KDGRP__c, KONDA__c, KTGRD__c, KUNNR__c, KURST__c, KZAZU__c, LAND1__c, LIFSD__c, LOEVM__c, LPRIO__c, NAME1__c, NAME2__c, PLTYP__c, POST_CODE1__c, REGION__c, SPART__c, STCD1__c, STCD2__c, STCD3__c, STCD4__c, STREET__c, TEL_NUMBER__c, URI_ADDR__c, VKBUR__c, VKORG__c, VSBED__c, VTWEG__c, WAERS__c, ZTERM__c, ZZJ_1KFRE__c, ZZKDGRP_C__c, ZZNSTKUNL1_T__c, ZZNSTKUNL1__c, ZZNSTKUNL2_T__c, ZZNSTKUNL2__c, ZZNSTKUNL3_T__c, ZZNSTKUNL3__c, ZZSHIPPER__c, ZZTOBUSL1_EN__c, ZZTOBUSL1_KO__c, ZZTOBUSL2_EN__c, ZZTOBUSL2_KO__c, mLOEVM__c, ExternalId__c, Type__c, ZZTOBUSL1__c, ZZTOBUSL2__c, isBatch__c  From MdgAccount__c Where Type__c = 'S'];
        MdgAccountController.updateAccountByMdg(accList,null);
        MdgAccountController.updateSalesAreaByMdg(salesList);

        Test.stopTest();
    }
}