force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <displayFormat>SVC-{YYYY}{MM}{00000}</displayFormat>
        <label>Service Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service(IF)</label>
    <referenceTo>Master_Service__c</referenceTo>
    <relationshipLabel>Services</relationshipLabel>
    <relationshipName>BO_Service_Solution</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Solution__c/Solution__c.object-meta.xml
<CustomObject>
    <label>Solution(c)</label>
    <nameField>
        <displayFormat>SOL-{YYYY}{MM}{00000}</displayFormat>
        <label>Solution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Solution(c)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Solution__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <label>Service</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Solution(c)</relationshipLabel>
    <relationshipName>Solution</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Solution__c/fields/Solution__c.field-meta.xml
<CustomField>
    <fullName>Solution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Solution(IF)</label>
    <referenceTo>Master_Solution__c</referenceTo>
    <relationshipLabel>Solution(c)</relationshipLabel>
    <relationshipName>Solution_c</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ossDataWrapper.cls
public class ossDataWrapper {
    public Opportunity rowOpp;
    public Map<String, ServiceWrap> Services;
    
    public class ServiceWrap {
        public String ServiceCode; //String 으로 따로 처리하는 이유. 코드값이 존재하지 않아 ##Manual## 처리 해야 함.
        public String sServiceCode; //String 으로 따로 처리하는 이유. 코드값이 존재하지 않아 ##Manual## 처리 해야 함.
        
        public String MasterServiceName; 
        public String MastersServiceName; 
        
        //public String DlvDeptCostCenter; 
        //public String sDlvDeptCostCenter; 
        //public String DlvDeptName; 	
        //public String sDlvDeptName; 
        
        public Service__c Service;
        public Map<String, SolutionWrap> Solutions;
    }
    
    public class SolutionWrap { 
        public String SolutionCode; //String 으로 따로 처리하는 이유. 코드값이 존재하지 않아 ##Manual## 처리 해야 함.
        public String sSolutionCode; //String 으로 따로 처리하는 이유. 코드값이 존재하지 않아 ##Manual## 처리 해야 함.
        
        public String MasterSolutionName; 
        public String MastersSolutionName; 
        
        public Solution__c Solution;
    }
}