force-app/main/default/objects/MasterActivityLogisticsAttribute__c/MasterActivityLogisticsAttribute__c.object-meta.xml
<CustomObject>
    <label>Master Activity Logistics Attribute</label>
    <nameField>
        <displayFormat>MAA-{00000}</displayFormat>
        <label>Master Activity Attribute Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Master Activity Logistics Attributes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MasterActivityLogisticsAttribute__c/fields/Attribute__c.field-meta.xml
<CustomField>
    <fullName>Attribute__c</fullName>
    <label>Attribute</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accessible</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MasterActivityLogisticsAttribute__c/fields/TransactionName__c.field-meta.xml
<CustomField>
    <fullName>TransactionName__c</fullName>
    <formula>TEXT(MasterActivity__r.TransactionName__c)</formula>
    <label>TransactionName</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MasterActivityLogisticsAttribute__c/recordTypes/Condition.recordType-meta.xml
<RecordType>
    <fullName>Condition</fullName>
    <active>true</active>
    <label>Condition</label>
</RecordType>

force-app/main/default/classes/MasterActivityLogisticsAttributeHelper.cls
public class MasterActivityLogisticsAttributeHelper {
    private String OriginObject;
    private List<Criteria> Criterias;
    private String Logic;
    private String Output;
    
    private class Criteria { 
        private String No;
        private String OriginField;
        private String Operator;
        private String AttributeField;
    }
    
    
    public Static String dynamicSOQL(String jsonFilterCriteria, sObject rowObject, String Attribute, String TransactionName){
        String SOQL = 'SELECT Id, {Output} FROM MasterActivityLogisticsAttribute__c WHERE RecordType.DeveloperName = \'Condition\' AND Attribute__c = \'{Attribute}\' AND TransactionName__c = \'{TransactionName}\' AND {Logic} ';
        MasterActivityLogisticsAttributeHelper rowCriteria = (MasterActivityLogisticsAttributeHelper) System.JSON.deserialize(jsonFilterCriteria, MasterActivityLogisticsAttributeHelper.class);
                
        String sObjcet = rowCriteria.OriginObject;        
        String Output = rowCriteria.Output;
        
		Map<String, String> mapCondition = new Map<String, String>();      
        for(Criteria row : rowCriteria.Criterias){           
            String strCondition = '';
            
            //TODO : Operator Case는 확장 되어야 함.            
            switch on row.Operator.toLowercase() {
                when 'includes' {	
                    strCondition = row.AttributeField + ' INCLUDES (\'' + rowObject.get(row.OriginField) + '\')';
                }
                when '=' {	
                    strCondition = row.AttributeField + ' = \'' + rowObject.get(row.OriginField) + '\'';
                }
                when else {
                    // TODO : 에러 발생 시키기.
                }
            }
            mapCondition.put(row.No, strCondition);            
        }
        
        //SOQL 조건절 Generate
        String Logic = rowCriteria.Logic;
        for(String key : mapCondition.keySet()){
            Logic = Logic.replace('{'+key+'}', mapCondition.get(key));
        }
        
        SOQL = SOQL.replace('{Output}', rowCriteria.Output).replace('{sObject}', rowCriteria.OriginObject).replace('{Logic}', Logic).replace('{Attribute}', Attribute).replace('{TransactionName}', TransactionName);
        
        
        system.debug('### MasterActivityAttribute :: dynamicSOQL :: SOQL = ' + SOQL);
        
        return SOQL;
    }
}