force-app/main/default/objects/IF_Log__c/IF_Log__c.object-meta.xml
<CustomObject>
    <description>Interface 처리 Log를 기록</description>
    <label>IF_Log</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0000000}</displayFormat>
        <label>IF_Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IF_Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IF_Log__c/fields/LogType__c.field-meta.xml
<CustomField>
    <fullName>LogType__c</fullName>
    <description>Log Type은 Interface를 구분하는 것으로 Callout, Batch, WebService로 구분</description>
    <inlineHelpText>Log Type은 Interface를 구분하는 것으로 Callout, Batch, WebService로 구분</inlineHelpText>
    <label>LogType</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Batch_InterfaceLogDeleteController_Test.cls
/**
 * @description       : 
 * @author            : ghkil@partner.samsung.com
 * @group             : 
 * @last modified on  : 2021-02-18
 * @last modified by  : ghkil@partner.samsung.com
 * Modifications Log 
 * Ver   Date         Author                      Modification
 * 1.0   2021-02-18   ghkil@partner.samsung.com   Initial Version
**/
@isTest
public class Batch_InterfaceLogDeleteController_Test {
    
    // Batch_InterfaceLogDeleteController 테스트 클래스
    // INTERFACE_ID = 'IF-000';
    // APEX_CLASS   = 'Batch_InterfaceLogDeleteController';
    // METHOD_NAME  = 'Batch'; 

    public Batch_InterfaceLogDeleteController_Test() {    }

    @TestSetup
    static void makeData(){
        IF_Log__c insertLog = new IF_Log__c(
            LogType__c = 'Interface'
            , InterfaceId__c = 'IF-000'
        );

        Insert insertLog;
    }    
    
    @isTest
    static void testBatch1() {
        Test.startTest();

        Batch_InterfaceLogDeleteController batch = new Batch_InterfaceLogDeleteController();
        // batch.BATCH_CONDITION = date.valueOf('2020-11-04T00:00:00Z');
        batch.BATCH_CONDITION = date.valueOf(system.today().addDays(1));
        Id batchJobId = Database.executeBatch(batch, 2000);

        Test.stopTest();
    }

    @isTest
    static void testBatch2() {
        Test.startTest();

        Id batchJobId = Database.executeBatch(new Batch_InterfaceLogDeleteController(), 2000);

        Test.stopTest();
    }    
}