force-app/main/default/objects/UserActive_Logs__c/UserActive_Logs__c.object-meta.xml
<CustomObject>
    <label>UserActive Logs</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>UserActive Logs Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UserActive Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UserActive_Logs__c/fields/ChangedById__c.field-meta.xml
<CustomField>
    <fullName>ChangedById__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ChangedById</label>
    <referenceTo>User</referenceTo>
    <relationshipName>UserActive_Logs2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UserActive_Logs__c/fields/ChangedDate__c.field-meta.xml
<CustomField>
    <fullName>ChangedDate__c</fullName>
    <label>ChangedDate</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/UserActive_Logs__c/fields/CompanyCode__c.field-meta.xml
<CustomField>
    <fullName>CompanyCode__c</fullName>
    <label>CompanyCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UserActive_Logs__c/fields/UserCreatedById__c.field-meta.xml
<CustomField>
    <fullName>UserCreatedById__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>UserCreatedById</label>
    <referenceTo>User</referenceTo>
    <relationshipName>UserActive_Logs1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UserActive_Logs__c/fields/UserCreatedDate__c.field-meta.xml
<CustomField>
    <fullName>UserCreatedDate__c</fullName>
    <label>UserCreatedDate</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/UserActive_Logs__c/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>UserId</label>
    <referenceTo>User</referenceTo>
    <relationshipName>UserActive_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UserInfo_Change_Logs__c/UserInfo_Change_Logs__c.object-meta.xml
<CustomObject>
    <label>UserInfo_Change_Logs</label>
    <nameField>
        <label>UserInfo_Change_Logs Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UserInfo_Change_Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UserInfo_Change_Logs__c/fields/ChangedById__c.field-meta.xml
<CustomField>
    <fullName>ChangedById__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ChangedById</label>
    <referenceTo>User</referenceTo>
    <relationshipName>UserInfo_Change_Logs1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UserInfo_Change_Logs__c/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>UserId</label>
    <referenceTo>User</referenceTo>
    <relationshipName>UserInfo_Change_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UserInfo_Change_Logs__c/fields/UserProfile__c.field-meta.xml
<CustomField>
    <fullName>UserProfile__c</fullName>
    <label>UserProfile</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UserInfo_Change_Logs__c/fields/UserRole__c.field-meta.xml
<CustomField>
    <fullName>UserRole__c</fullName>
    <label>UserRole</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UserActiveLogInsertion.cls
/**
* @description       : This class is used to insert UserActive(UserActive_Logs__c) records whenever a user records is inserted or active status is updated
* @author            : Kajal.c@samsung.com
* @group             : 
* @last modified on  : 2023-02-06 
* @last modified by  : Kajal.c@samsung.com
* Modifications Log 
* Ver   Date         Author                           Modification
* 1.0   08-31-2022   rakshit.s@samsung.com           Initial Version
* 1.1   2023-02-06   Kajal.c@samsung.com             Added functionality related to MySales-123.
**/
public with sharing class UserActiveLogInsertion {
    
    @future
    public static void insertUserActiveLog(List<Id> userRecId){
        List<UserActive_Logs__c> userActiverecInsertionList = new list<UserActive_Logs__c>();
        List<Id> idList = new list<id>();
        List<User> userRec = new List<User>();
        userRec = [Select id, isActive,CompanyCode__c,Name,Email,Username,CreatedDate,CreatedById,LastModifiedDate from User where Id IN: userRecId];
        for(User uu : userRec){
            UserActive_Logs__c rec = new UserActive_Logs__c();
            // rec.Active__c = userRec.IsActive;
            rec.ChangedById__c = userinfo.getUserId();
            rec.Changeddate__c = uu.LastModifiedDate;
            rec.CompanyCode__c = uu.CompanyCode__c;
            rec.UserId__c = uu.Id;
            rec.Name__c = uu.Name;
            rec.Email__c = uu.Email;
            rec.UserName__c = uu.Username;
            rec.UserCreatedDate__c = uu.CreatedDate;
            rec.UserCreatedById__c = uu.CreatedById;
            rec.Active__c = uu.IsActive;
            userActiverecInsertionList.add(rec);
        }
        if(userActiverecInsertionList.size()>0){
            try{
                insert userActiverecInsertionList;
            }
            catch(DmlException e){
                System.debug('The following exception has occurred: ' + e.getMessage());
            }
        }
    }
    
    /** START -- V1.1 MySales1-123 Added by Kajal  **/
    @future
    public static void insertUserActiveLogOnUpdate(List<Id> userRecId){
        List<UserInfo_Change_Logs__c> userActiverecUpdationList = new list<UserInfo_Change_Logs__c>();
        List<Id> idList = new list<id>();
        System.debug('ID List is' +userRecId);
        List<User> userInfoRec = new List<User>();
        userInfoRec = [Select id, isActive,CompanyCode__c,Name,Email,Username,UserRole.Name,Profile.Name,CreatedDate,CreatedById,LastModifiedDate from User where Id IN: userRecId];
         System.debug('User info List is' +userInfoRec);
         for(User uu : userInfoRec){
            UserInfo_Change_Logs__c rec = new UserInfo_Change_Logs__c();
            rec.UserId__c = uu.Id;
            rec.Name__c = uu.Name; 
            rec.CompanyCode__c = uu.CompanyCode__c; 
            rec.Email__c =  uu.Email; 
            rec.Username__c = uu.Username;
            rec.UserProfile__c = uu.Profile.Name;
            rec.UserRole__c    = uu.UserRole.Name;
            rec.ChangedById__c = userinfo.getUserId();
            rec.Changeddate__c = uu.LastModifiedDate;
            rec.Active__c = uu.IsActive;
            userActiverecUpdationList.add(rec);
        }
        if(userActiverecUpdationList.size()>0){
            try{
                System.debug('Active log list' +userActiverecUpdationList);
                insert userActiverecUpdationList;
            }
            catch(DmlException e){
                System.debug('The following exception has occurred: ' + e.getMessage());
            }
        }
    }
     /** END -- V1.1 MySales-123 Added by Kajal  **/
}