force-app/main/default/objects/MSP_Project__c/MSP_Project__c.object-meta.xml
<CustomObject>
    <label>SCP Project</label>
    <nameField>
        <label>Project ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SCP Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MSP_Project__c/fields/Approve__c.field-meta.xml
<CustomField>
    <fullName>Approve__c</fullName>
    <label>Approve</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>N</fullName>
                <default>true</default>
                <label>N</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MSP_Project__c/fields/Contract_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Start_Date__c</fullName>
    <formula>SCP_Account_ID__r.Contract_Start_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contract Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/MSP_Project__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <formula>HYPERLINK( SCP_Account_ID__r.Customer__r.Id , SCP_Account_ID__r.Customer__r.Name , &quot;_self&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MSP_Project__c/fields/Estimated_Monthly_Fee_Won__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Monthly_Fee_Won__c</fullName>
    <label>Estimated Monthly Fee</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/MSP_Project__c/fields/Incentive__c.field-meta.xml
<CustomField>
    <fullName>Incentive__c</fullName>
    <formula>TEXT( SCP_Account_ID__r.Incentive__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Incentive</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MSP_Project__c/fields/New_Business__c.field-meta.xml
<CustomField>
    <fullName>New_Business__c</fullName>
    <label>New Business</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
                <default>true</default>
                <label>N/A</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MSP_Project__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <formula>HYPERLINK( SCP_Account_ID__r.Partner__r.Id , SCP_Account_ID__r.Partner__r.Name , &quot;_self&quot; )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Partner</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MSP_Project__c/fields/Partner_AM__c.field-meta.xml
<CustomField>
    <fullName>Partner_AM__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Partner AM</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipName>MSP_Projects</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MSP_Project__c/fields/Partner_PM__c.field-meta.xml
<CustomField>
    <fullName>Partner_PM__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Partner PM</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipName>MSP_Projects1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MSP_Project__c/fields/Project_Summary__c.field-meta.xml
<CustomField>
    <fullName>Project_Summary__c</fullName>
    <label>Project Summary</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/MSP_Project__c/fields/SCP_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>SCP_Account_ID__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>SCP Account ID</label>
    <referenceTo>SCP_Account__c</referenceTo>
    <relationshipName>MSP_Projects</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MSP_Project__c/fields/SDS_AM__c.field-meta.xml
<CustomField>
    <fullName>SDS_AM__c</fullName>
    <formula>HYPERLINK( SCP_Account_ID__r.SDS_AM__c , SCP_Account_ID__r.SDS_AM__r.EvHName__c , &quot;_self&quot; )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SDS AM</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MSP_Project__c/fields/SDS_PDM__c.field-meta.xml
<CustomField>
    <fullName>SDS_PDM__c</fullName>
    <formula>HYPERLINK( SCP_Account_ID__r.SDS_PDM__c , SCP_Account_ID__r.SDS_PDM__r.EvHName__c , &quot;_self&quot; )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SDS PDM</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SCP_Account__c/SCP_Account__c.object-meta.xml
<CustomObject>
    <label>SCP Account</label>
    <nameField>
        <label>SCP Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SCP Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SCP_Account__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Customer</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>MDG check must equal true</errorMessage>
        <filterItems>
            <field>Account.MDGCheck__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SCP Accounts</relationshipLabel>
    <relationshipName>SCP_Accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SCP_Account__c/fields/Incentive__c.field-meta.xml
<CustomField>
    <fullName>Incentive__c</fullName>
    <label>Incentive</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SCP_Account__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SCP Accounts (Partner)</relationshipLabel>
    <relationshipName>SCP_Accounts1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SCP_Account__c/fields/SCP_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>SCP_Account_ID__c</fullName>
    <label>SCP Account ID</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SCP_Account__c/fields/SDS_AM__c.field-meta.xml
<CustomField>
    <fullName>SDS_AM__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>SDS AM</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>SCP Accounts</relationshipLabel>
    <relationshipName>SCP_Accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SCP_Account__c/fields/SDS_PDM__c.field-meta.xml
<CustomField>
    <fullName>SDS_PDM__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>SDS PDM</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>SCP Accounts (SDS PDM)</relationshipLabel>
    <relationshipName>SCP_Accounts1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CustomRelatedListController.cls
/**
 * @description       : Custom Related List Component (SCP Account)
 * @author            : gitesh.s@samsung.com
 * @group             : 
 * @last modified on  : 20-12-2022
 * @last modified by  : gitesh.s@smsung.com
 * Modifications Log 
 * Ver   Date         Author                 Modification
 * 1.0   20-12-2022   gitesh.s@samsung.com   Initial Version
**/
public class CustomRelatedListController {
    @AuraEnabled
    public static String getObjectName(Id recordId) {
        return recordId.getSObjectType().getDescribe().getName();
    }

    @AuraEnabled
    public static List<SCP_Account__c> getCurrentRecord(Id recordId) {
        return [SELECT Name, Contract_Start_Date__c, Customer__c, Incentive__c, Partner__c, SCP_Account_ID__c, SDS_AM__c, SDS_PDM__c FROM SCP_Account__c WHERE Id =: recordId];
    }

    @AuraEnabled
    public static List<MSP_Project__c> getRelatedRecords(Id recordId) {
        return [SELECT Id, Name, Project_Name__c, Estimated_Monthly_Fee_Won__c, New_Business__c, Approve__c FROM MSP_Project__c WHERE SCP_Account_ID__c =: recordId LIMIT 6];
    }

    @AuraEnabled
    public static List<MSP_Project__c> getMSPRecord(Id recordId) {
        return [SELECT Id, Name, Project_Name__c, Project_Summary__c, Partner_AM__c, Partner_PM__c, Estimated_Monthly_Fee_Won__c, New_Business__c FROM MSP_Project__c WHERE Id =: recordId];
    }

    @AuraEnabled
    public static void deleteMSPRecord(Id recordId) {
        List<MSP_Project__c> record = [SELECT Id FROM MSP_Project__c WHERE Id =: recordId];
        delete record;
    }

    @AuraEnabled
    public static Boolean checkApprovalStatus(Id recordId) {
        return Approval.isLocked(recordId);
    }

    @AuraEnabled
    public static Profile getProfileInfo() {
        String profileId = UserInfo.getProfileId();
        Profile profile = [SELECT Id, Name FROM Profile WHERE Id =:profileId];
        return profile;
    }
}