force-app/main/default/objects/KnoxApproval__c/KnoxApproval__c.object-meta.xml
<CustomObject>
    <label>Knox Approval</label>
    <nameField>
        <label>Knox Approval Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Knox Approval</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KnoxApproval__c/fields/MISID__c.field-meta.xml
<CustomField>
    <fullName>MISID__c</fullName>
    <description>Interface : ExternalKey 옵션 지정</description>
    <externalId>true</externalId>
    <label>MISID</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KnoxApproval__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Knox Approval</relationshipLabel>
    <relationshipName>Knox_Approval</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KnoxEmail__c/KnoxEmail__c.object-meta.xml
<CustomObject>
    <label>Knox Email</label>
    <nameField>
        <label>Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>KnoxEmail</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KnoxEmail__c/fields/HtmlBody__c.field-meta.xml
<CustomField>
    <fullName>HtmlBody__c</fullName>
    <label>HtmlBody</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/KnoxEmail__c/fields/MailId__c.field-meta.xml
<CustomField>
    <fullName>MailId__c</fullName>
    <label>Mail Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KnoxEmail__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Knox Email</relationshipLabel>
    <relationshipName>KnoxEmail</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KnoxEmail__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Send</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KnoxEmail__c/fields/ToAddress__c.field-meta.xml
<CustomField>
    <fullName>ToAddress__c</fullName>
    <label>To Address</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/SendActCompleteEmail.cls
/**
 * @description       : 
 * @author            : seonju.jin@dkbmc.com
 * @group             : 
 * @last modified on  : 2022-02-18
 * @last modified by  : seonju.jin@dkbmc.com
**/
public without sharing class SendActCompleteEmail {

    @future(callout=true)
    public static void sendKnoxMail(Set<Id> idSet){
        System.debug('future sendKnoxMail');
        Organization org = [ SELECT Id, IsSandBox FROM Organization];

        List<Object> logObjList = new List<Object>();
        List<KnoxApproval__c> approvalList = [SELECT Id, Name, Opportunity__c, Opportunity__r.OpportunityCode__c, MISID__c, CreatedById FROM KnoxApproval__c WHERE Id IN :idSet];
        List<String> toList = new List<String>();

        String toListStr = System.Label.MISID_EMAIL_TOLIST;
        toList = toListStr.split(',');      //수신자설정
        List<KnoxEmail__c> knoxEmailList = new List<KnoxEmail__c>();
        for(KnoxApproval__c knox : approvalList){
            try{

                List<Object> paramters = new List<Object>{knox.Opportunity__c, knox.Opportunity__r.OpportunityCode__c, knox.MISID__c};
                String emailcontent = '';
                try{
                    emailcontent = String.format(System.Label.MISID_EMAIL_CONTENT, paramters);
                }catch(Exception e){
                    System.debug(e.getMessage());
                    System.debug(e.getStackTraceString());
                    emailcontent = System.Label.MISID_EMAIL_CONTENT + '\r\n' + paramters.toString();
                }

                IF_KnoxEmailSendController.InputClass bodyMap = new IF_KnoxEmailSendController.InputClass();
                bodyMap.isMulti = true;
                bodyMap.subject = System.Label.MISID_EMAIL_SUBJECT;
                bodyMap.contents = emailcontent;
                bodyMap.contentType = 'TEXT';   // contentType : 1) TEXT : 텍스트, 2) MIME : 마임, 3) HTML : HTML
                bodyMap.docSecuType = 'PERSONAL';
                bodyMap.sfdcId = knox.Id;
                IF_KnoxEmailSendController.Sender sender;

                //보내는 사람 설정
                String senderAddress = System.Label.MISID_EMAIL_SENDER;
                sender = new IF_KnoxEmailSendController.Sender(senderAddress.split('@')[0], senderAddress);
                bodyMap.sender = sender;
        
                // recipientType : 1) 수신 : TO, 2) 참조 : CC, 3) 비밀참조 : BCC
                List<IF_KnoxEmailSendController.Recipients> recipientsList = new List<IF_KnoxEmailSendController.Recipients>();
                for(String t : toList){
                    IF_KnoxEmailSendController.Recipients r = new IF_KnoxEmailSendController.Recipients(t, 'TO');
                    recipientsList.add(r);
                }
        
                bodyMap.recipients = recipientsList;
                bodyMap.attachments = new List<IF_KnoxEmailSendController.Attachments>();
                Map<String,Object> response = new Map<String, Object>();
                if(!Test.isRunningTest()){
                    response = IF_KnoxEmailSendController.send(bodyMap);
                } else {
                    response.put('result', 'success');
                    response.put('mailId', 'testMailId');
                }
                logObjList.add(response.get('INTERFACE_LOG'));
        
                String responseResult = String.valueOf(response.get('result'));
                if(responseResult == 'success'){
                    String knoxEmailId = String.valueOf(response.get('mailId'));
                    KnoxEmail__c knoxEmail = new KnoxEmail__c(
                        RecordId__c = knox.Id
                        , ToAddress__c = String.join(toList, ',')
                        , Name = System.Label.MISID_EMAIL_SUBJECT
                        , HtmlBody__c = emailcontent
                        , MailId__c = knoxEmailId
                        , Status__c = 'Send'
                    );
                    knoxEmailList.add(knoxEmail);
                }
            }catch(Exception e){
                System.debug(e.getMessage());
                System.debug(e.getStackTraceString());
            }
        }

        if(logObjList.size() > 0) createInterfaceLog(logObjList);
        if(knoxEmailList.size() > 0) insert knoxEmailList;
    }


    public static void createInterfaceLog(List<Object> objList){
        for(Object logObj : objList){
            try{
                IF_Log log = new IF_Log();
                if(logObj != null){
                    IF_Log.InterfaceLog iflog_interfaceLog = (IF_Log.InterfaceLog)logObj;
                    log.createLog(iflog_interfaceLog);
                } 
            }catch(Exception e){
                System.debug(LoggingLevel.ERROR, e.getStackTraceString());
            }
        }
    }
}