force-app/main/default/objects/KnoxApproval__c/KnoxApproval__c.object-meta.xml
<CustomObject>
    <label>Knox Approval</label>
    <nameField>
        <label>Knox Approval Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Knox Approval</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KnoxApproval__c/fields/HTML__c.field-meta.xml
<CustomField>
    <fullName>HTML__c</fullName>
    <label>HTML</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/KnoxApprovalHTMLController.cls
/**
 * @description       : 
 * @author            : dongyoung.kim@dkbmc.com
 * @group             : 
 * @last modified on  : 2021-01-18
 * @last modified by  : dongyoung.kim@dkbmc.com
 * Modifications Log 
 * Ver   Date         Author                    Modification
 * 1.0   2021-01-18   dongyoung.kim@dkbmc.com   Initial Version
**/
public class KnoxApprovalHTMLController {
    @AuraEnabled
    public static List<KnoxApproval__c> getKnoxAppInfo(Id recordId){
        List<KnoxApproval__c> getKnoxAppInfo = [SELECT id, HTML__C
                                                FROM KnoxApproval__c 
                                                WHERE id =: recordId];
        return getKnoxAppInfo;
    }
}