force-app/main/default/objects/Department__c/Department__c.object-meta.xml
<CustomObject>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Department</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Lead__c/Sales_Lead__c.object-meta.xml
<CustomObject>
    <label>Sales Lead</label>
    <nameField>
        <label>Sales Lead Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Leads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Lead__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Contract Account</description>
    <inlineHelpText>Required Information only for HQ users when creating IT Sales Lead / Required information when converting</inlineHelpText>
    <label>Account(*)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Leads</relationshipLabel>
    <relationshipName>Sales_Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WeeklyReport__c/WeeklyReport__c.object-meta.xml
<CustomObject>
    <label>Weekly Report</label>
    <nameField>
        <label>Reporting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Weekly Report</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/WeeklyReport__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Weekly Report</relationshipLabel>
    <relationshipName>AccountWeeklyReports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WeeklyReport__c/fields/Contents__c.field-meta.xml
<CustomField>
    <fullName>Contents__c</fullName>
    <label>Contents</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/WeeklyReport__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <formula>Owner:User.Department</formula>
    <label>Department</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WeeklyReport__c/fields/DisplayOrder__c.field-meta.xml
<CustomField>
    <fullName>DisplayOrder__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Display Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WeeklyReport__c/fields/IssueDescription__c.field-meta.xml
<CustomField>
    <fullName>IssueDescription__c</fullName>
    <label>Issue Description</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/WeeklyReport__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Weekly Report</relationshipLabel>
    <relationshipName>Weekly_Report</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WeeklyReport__c/fields/ReportingDate__c.field-meta.xml
<CustomField>
    <fullName>ReportingDate__c</fullName>
    <label>Reporting Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/WeeklyReport__c/fields/SalesLead__c.field-meta.xml
<CustomField>
    <fullName>SalesLead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Lead</label>
    <referenceTo>Sales_Lead__c</referenceTo>
    <relationshipLabel>Weekly Report</relationshipLabel>
    <relationshipName>Weekly_Report</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/WeeklyReportHandlerController.cls
/**
 * @description       : 
 * @author            : gitesh.s@samsung.com
 * @group             : 
 * @last modified on  : 15-03-2023
 * @last modified by  : gitesh.s@smsung.com
 * Modifications Log 
 * Ver   Date         Author                 Modification
 * 1.0   15-03-2023   gitesh.s@samsung.com   Initial Version
**/
public class WeeklyReportHandlerController {
    @AuraEnabled
    public static List<WeeklyReport__c> getWeeklyIssueReports(string weeklyReportIds) {
        List<String> weeklyReports;
        String weeklyReportId;

        if(weeklyReportIds.contains('-')) {  
            weeklyReports = weeklyReportIds.split('-');
            weeklyReportId = String.join(weeklyReports,'\',\'');
        }
        else {
            weeklyReportId = weeklyReportIds;
        }
        String queryString = 'SELECT Id, Name, OwnerId, Owner.Alias, Owner.Name, Department__c, Opportunity__c, Opportunity__r.Name, Opportunity__r.AccountId, Opportunity__r.Account.Name, SalesLead__c, SalesLead__r.Name, SalesLead__r.AccountId__c, SalesLead__r.AccountId__r.Name, DisplayOrder__c, Contents__c, IssueDescription__c, ReportingDate__c FROM WeeklyReport__c WHERE Id IN (\''+weeklyReportId+'\') ORDER BY ReportingDate__c DESC';
        return Database.query(queryString);
    }

    @AuraEnabled
    public static List<WeeklyReport__c> getRelatedWeeklyReports(String recordId) {
        String queryString = 'SELECT Id, Name, Account__r.Name FROM WeeklyReport__c WHERE Account__c IN (\''+recordId+'\')';
        return Database.query(queryString);
    }

    @AuraEnabled
    public static List<Account> getAccountName(String recordId){
        String queryString = 'SELECT Id, Name FROM Account WHERE Id IN (\''+recordId+'\')';
        return Database.query(queryString);
    }
}