force-app/main/default/objects/Partner_Business_Management__c/Partner_Business_Management__c.object-meta.xml
<CustomObject>
    <label>Partner Business Management</label>
    <nameField>
        <displayFormat>B-{yy}{mm}{dd}{000}</displayFormat>
        <label>Business Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Business Managements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner_Business_Management__c/fields/Partner_Account__c.field-meta.xml
<CustomField>
    <fullName>Partner_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Partner Account</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Account.Partner_Type__c</field>
            <operation>equals</operation>
            <value>Reseller</value>
        </filterItems>
        <filterItems>
            <field>Account.Partner_Type__c</field>
            <operation>equals</operation>
            <value>Managed Service Provider</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner Business Managements</relationshipLabel>
    <relationshipName>Partner_Business_Opportunities</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partner_Business_Management__c/fields/Partner_Sales__c.field-meta.xml
<CustomField>
    <fullName>Partner_Sales__c</fullName>
    <label>Partner Sales</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partner_Business_Management__c/fields/Scheduled_Service_Opening_Date__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Service_Opening_Date__c</fullName>
    <label>Scheduled Service Opening Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/PartnerBusinessListController.cls
/**
 * @description       : 
 * @author            : zenith21c@test.com
 * @group             : 
 * @last modified on  : 03-22-2022
 * @last modified by  : zenith21c@test.com
**/
public with sharing class PartnerBusinessListController {
    @AuraEnabled(cacheable=true)
    public static List<Partner_Business_Management__c> getPartnerBusinessList() {
        return [select Id
                    , Project_Name__c
                    , Name
                    , Partner_Sales__c
                    , Scheduled_Service_Opening_Date__c
                    , Partner_Account__c
                from Partner_Business_Management__c
                order by Scheduled_Service_Opening_Date__c desc
                limit 3];
    }
}