force-app/main/default/objects/Partner_Business_Management__c/Partner_Business_Management__c.object-meta.xml
<CustomObject>
    <label>Partner Business Management</label>
    <nameField>
        <displayFormat>B-{yy}{mm}{dd}{000}</displayFormat>
        <label>Business Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Business Managements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner_Business_Management__c/fields/Contract_No__c.field-meta.xml
<CustomField>
    <fullName>Contract_No__c</fullName>
    <label>Contract No</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partner_Business_Management__c/fields/Discount_Rate__c.field-meta.xml
<CustomField>
    <fullName>Discount_Rate__c</fullName>
    <label>Discount Rate</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partner_Business_Management__c/fields/mBizTypeL1Code__c.field-meta.xml
<CustomField>
    <fullName>mBizTypeL1Code__c</fullName>
    <label>Type of Business L1</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>L100</fullName>
                <label>The Public</label>
            </value>
            <value>
                <fullName>L200</fullName>
                <label>Finance</label>
            </value>
            <value>
                <fullName>L300</fullName>
                <label>Service</label>
            </value>
            <value>
                <fullName>L400</fullName>
                <label>Manufacturing(Discrete)</label>
            </value>
            <value>
                <fullName>L500</fullName>
                <label>Manufacturing(Process)</label>
            </value>
            <value>
                <fullName>L600</fullName>
                <label>Manufacturing(CPG)</label>
            </value>
            <value>
                <fullName>L700</fullName>
                <label>Logistics</label>
            </value>
            <value>
                <fullName>L800</fullName>
                <label>Other</label>
            </value>
            <value>
                <fullName>콘도미니</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partner_Business_Management__c/fields/Partner_Account__c.field-meta.xml
<CustomField>
    <fullName>Partner_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Partner Account</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Account.Partner_Type__c</field>
            <operation>equals</operation>
            <value>Reseller</value>
        </filterItems>
        <filterItems>
            <field>Account.Partner_Type__c</field>
            <operation>equals</operation>
            <value>Managed Service Provider</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner Business Managements</relationshipLabel>
    <relationshipName>Partner_Business_Opportunities</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partner_Business_Management__c/fields/SDS_Sales__c.field-meta.xml
<CustomField>
    <fullName>SDS_Sales__c</fullName>
    <label>SDS Sales</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partner_Business_Management__c/fields/SDS_Sales_Email__c.field-meta.xml
<CustomField>
    <fullName>SDS_Sales_Email__c</fullName>
    <label>SDS Sales Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Partner_Business_Management__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Temporary(T)</fullName>
            </value>
            <value>
                <fullName>Submitted(S)</fullName>
            </value>
            <value>
                <fullName>Reviewing(R)</fullName>
            </value>
            <value>
                <fullName>Approved(A)</fullName>
            </value>
            <value>
                <fullName>Rejected(V)</fullName>
            </value>
            <value>
                <fullName>Closed(C)</fullName>
            </value>
            <value>
                <fullName>Rejected(R)</fullName>
                <isActive>false</isActive>
                <label>Rejected(R)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partner_ReAuth_Requirement__c/Partner_ReAuth_Requirement__c.object-meta.xml
<CustomObject>
    <label>Partner ReAuth Requirement</label>
    <nameField>
        <displayFormat>prar-{0000000}</displayFormat>
        <label>Partner ReAuth Requirement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner ReAuth Requirements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Partnership_Info__c/Partnership_Info__c.object-meta.xml
<CustomObject>
    <description>MSP Accout 하위의 파트너십 현황 정보</description>
    <label>Partnership Info</label>
    <nameField>
        <displayFormat>PI-{0000}</displayFormat>
        <label>Partnership Info Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partnership Infos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Partnership_Info__c/fields/Contract_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_End_Date__c</fullName>
    <description>계약 만료일(Date)</description>
    <label>Contract End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Partnership_Info__c/fields/Contract_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Start_Date__c</fullName>
    <description>계약 시작일(Date)</description>
    <label>Contract Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/PartnerProfileOverviewController_Test.cls
/**
 * @description       : 
 * @author            : ukhyeon.lee@samsung.com
 * @group             : 
 * @last modified on  : 08-30-2022
 * @last modified by  : ukhyeon.lee@samsung.com
**/
@isTest(SeeAllData=true)
private class PartnerProfileOverviewController_Test {
    static User partner;
    static {
        partner = [Select Id, AccountId From User Where UserType='PowerPartner' and isActive=true AND Account.isPartner=true Limit 1];
        List<Partner_ReAuth_Requirement__c> prrList = new List<Partner_ReAuth_Requirement__c>();
        

        Partner_Business_Management__c pbm = new Partner_Business_Management__c(
            Project_Name__c = 'test',
            Partner_Account__c = partner.AccountId,
            Amount__c=5000,
            SDS_Sales_Email__c = 'test@test.com' ,
            SDS_Sales__c = 'test',
            mBizTypeL1Code__c = 'L100',
            Discount_Rate__c = '5',
            Contract_No__c = 'A123123'
        );
        insert pbm;

        Partnership_Info__c pi = new Partnership_Info__c(
            Contract_Start_Date__C = Date.newInstance(2022, 1, 1),
            Contract_End_Date__C = Date.newInstance(2022, 2, 17)
        );
        insert pi;

        PartnerMarketingBudget pmb = new PartnerMarketingBudget(
            Title = 'Test',
            Amount = 100,
            Type = 'Marketing Funds'
        );
        insert pmb;

        PartnerFundAllocation pfa = new PartnerFundAllocation(
            Title = 'Test',
            Amount = 10,
            ChannelPartnerId = partner.AccountId,
            budgetId = pmb.Id
        );
        insert pfa;

        PartnerFundRequest pfrApproved = new PartnerFundRequest(
            AllocationId = pfa.Id,
            ChannelPartnerId =partner.AccountId,
            Title = 'Test',
            Amount = 10,
            RequestedAmount = 2,
            Status = 'Approved',
            OwnerId = partner.Id
        );
        insert pfrApproved;

        PartnerFundClaim pfcPaid = new PartnerFundClaim(
            requestId = pfrApproved.Id,
            Title = 'Test',
            Amount = 10,
            Status = 'Draft',
            Status__c = 'Paid',
            OwnerId = partner.Id
        );
        insert pfcPaid;        
    }
    


    @isTest 
    static void PartnerProfileOverviewController_Test() {
        Test.startTest();
        PartnerProfileOverviewController.partnerProfileOverview(partner.AccountId);
		Test.stopTest();
    }
}