force-app/main/default/objects/CostCenter__c/CostCenter__c.object-meta.xml
<CustomObject>
    <label>Cost Center</label>
    <nameField>
        <label>Cost Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cost Center</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CostCenter__c/fields/CostCenter__c.field-meta.xml
<CustomField>
    <fullName>CostCenter__c</fullName>
    <externalId>true</externalId>
    <label>Cost Center</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CostCenter__c/fields/CostCenterName__c.field-meta.xml
<CustomField>
    <fullName>CostCenterName__c</fullName>
    <label>Cost Center Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/EvMailAddr__c.field-meta.xml
<CustomField>
    <fullName>EvMailAddr__c</fullName>
    <label>Email</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/EvUniqID__c.field-meta.xml
<CustomField>
    <fullName>EvUniqID__c</fullName>
    <externalId>true</externalId>
    <label>EP ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MasterActivity__c/MasterActivity__c.object-meta.xml
<CustomObject>
    <label>Master Activity</label>
    <nameField>
        <displayFormat>MA-{000000}</displayFormat>
        <label>Seq. No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Master Activities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/MasterActivity__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cold</fullName>
            </value>
            <value>
                <fullName>Warm</fullName>
            </value>
            <value>
                <fullName>Hot</fullName>
            </value>
            <value>
                <fullName>Z01</fullName>
                <label>Idendified</label>
            </value>
            <value>
                <fullName>Z02</fullName>
                <label>Validated</label>
            </value>
            <value>
                <fullName>Z03</fullName>
                <label>Qualified</label>
            </value>
            <value>
                <fullName>Z04</fullName>
                <label>Solutioned</label>
            </value>
            <value>
                <fullName>Z05</fullName>
                <label>Won</label>
            </value>
            <value>
                <fullName>Z06</fullName>
                <label>Failed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpptyCodeSetting__c/OpptyCodeSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Opportunity Code 생성 제어</description>
    <label>Oppty Code Setting</label>
</CustomObject>

force-app/main/default/objects/OpptyCodeSetting__c/fields/CodeSetting__c.field-meta.xml
<CustomField>
    <fullName>CodeSetting__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Code Setting 필드가 true인 경우 Opportunity Code를 채번</description>
    <label>Code Setting</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sales_Lead__c/Sales_Lead__c.object-meta.xml
<CustomObject>
    <label>Sales Lead</label>
    <nameField>
        <label>Sales Lead Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Leads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Lead__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Contract Account</description>
    <inlineHelpText>Required Information only for HQ users when creating IT Sales Lead / Required information when converting</inlineHelpText>
    <label>Account(*)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Leads</relationshipLabel>
    <relationshipName>Sales_Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Lead__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>예상금액</description>
    <inlineHelpText>Required Information only for HQ users when creating IT Sales Lead / Required information when converting</inlineHelpText>
    <label>Amount(*)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sales_Lead__c/fields/Authority__c.field-meta.xml
<CustomField>
    <fullName>Authority__c</fullName>
    <defaultValue>false</defaultValue>
    <description>권한</description>
    <inlineHelpText>Whether the customer in charge has obtained the right to perform the business (change the stage to Hot when satisfying two or more BANTs)</inlineHelpText>
    <label>Authority</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sales_Lead__c/fields/Budget__c.field-meta.xml
<CustomField>
    <fullName>Budget__c</fullName>
    <defaultValue>false</defaultValue>
    <description>예산확보 여부</description>
    <inlineHelpText>Whether to have a customer budget (change the stage to Hot when satisfying two or more BANTs)</inlineHelpText>
    <label>Budget</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sales_Lead__c/fields/CloseDate__c.field-meta.xml
<CustomField>
    <fullName>CloseDate__c</fullName>
    <description>예상수주일자</description>
    <label>Close Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Sales_Lead__c/fields/CustomerContactDate__c.field-meta.xml
<CustomField>
    <fullName>CustomerContactDate__c</fullName>
    <label>Customer Contact Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Sales_Lead__c/fields/Internal_External__c.field-meta.xml
<CustomField>
    <fullName>Internal_External__c</fullName>
    <inlineHelpText>Required Information only for HQ users when creating IT Sales Lead  / Required information when converting</inlineHelpText>
    <label>Internal/External(*)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Internal</fullName>
            </value>
            <value>
                <fullName>External</fullName>
            </value>
            <value>
                <fullName>Undefined</fullName>
                <default>true</default>
                <label>Undefined</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Lead__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lead ID</description>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipName>BO_Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Lead__c/fields/LeadChannel__c.field-meta.xml
<CustomField>
    <fullName>LeadChannel__c</fullName>
    <label>Lead Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Direct Registration</fullName>
            </value>
            <value>
                <fullName>Marketing Lead Converted</fullName>
            </value>
            <value>
                <fullName>Demand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Lead__c/fields/LeadStage__c.field-meta.xml
<CustomField>
    <fullName>LeadStage__c</fullName>
    <description>Lead Stage</description>
    <label>Lead Stage</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cold</fullName>
                <color>#33CCFF</color>
                <label>Cold</label>
            </value>
            <value>
                <fullName>Warm</fullName>
                <color>#FF9900</color>
                <label>Warm</label>
            </value>
            <value>
                <fullName>Hot</fullName>
                <color>#FF0000</color>
                <label>Hot</label>
            </value>
            <value>
                <fullName>Converted</fullName>
                <color>#BBBBBB</color>
                <label>Converted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Lead__c/fields/LeadStatus__c.field-meta.xml
<CustomField>
    <fullName>LeadStatus__c</fullName>
    <description>Sales Lead Status</description>
    <inlineHelpText>Sales Lead Status</inlineHelpText>
    <label>Lead Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Process</fullName>
                <default>true</default>
                <label>In Process</label>
            </value>
            <value>
                <fullName>Close</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Lead__c/fields/PersonalInfoAgreement__c.field-meta.xml
<CustomField>
    <fullName>PersonalInfoAgreement__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Personal Info. Agreement</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sales_Lead__c/fields/PersonalInfoAgreementExpireDate__c.field-meta.xml
<CustomField>
    <fullName>PersonalInfoAgreementExpireDate__c</fullName>
    <label>Personal Info. Agreement Expire Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Sales_Lead__c/fields/RevenueEndDate__c.field-meta.xml
<CustomField>
    <fullName>RevenueEndDate__c</fullName>
    <description>(계약) 매출 종료일</description>
    <label>Contract End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Sales_Lead__c/fields/RevenueStartDate__c.field-meta.xml
<CustomField>
    <fullName>RevenueStartDate__c</fullName>
    <description>(계약) 매출 시작일</description>
    <label>Contract Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Sales_Lead__c/fields/SalesDepartment__c.field-meta.xml
<CustomField>
    <fullName>SalesDepartment__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Required Information only for HQ users when creating IT Sales Lead / Required information when converting</inlineHelpText>
    <label>Sales Dept. 3(*)</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR (2 AND 3 AND 4)</booleanFilter>
        <errorMessage>Closed departments cannot be selected.</errorMessage>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>Custom System Administrator, System Administrator</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>notEqual</operation>
            <value>Custom System Administrator, System Administrator</value>
        </filterItems>
        <filterItems>
            <field>CostCenter__c.Closed__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$User.CompanyCode__c</field>
            <operation>equals</operation>
            <valueField>CostCenter__c.CompanyCode__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CostCenter__c</referenceTo>
    <relationshipLabel>Sales Leads</relationshipLabel>
    <relationshipName>Sales_Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Lead__c/recordTypes/Logistics.recordType-meta.xml
<RecordType>
    <fullName>Logistics</fullName>
    <active>true</active>
    <label>Logistics</label>
</RecordType>

force-app/main/default/classes/SalesLeadToOppModalController_Test.cls
/**
 * @description       : 
 * @author            : Junghwa.Kim@dkbmc.com
 * @group             : 
 * @last modified on  : 2021-10-18
 * @last modified by  : younghoon.kim@dkbmc.com
 * Modifications Log 
 * Ver   Date         Author                  Modification
 * 1.0   11-11-2020   Junghwa.Kim@dkbmc.com   Initial Version
**/
@isTest(SeeAllData = false)
public with sharing class SalesLeadToOppModalController_Test {
    static Lead l;
   	static Sales_Lead__c sl;
   	static Sales_Lead__c sl2;
   	static Sales_Lead__c sl3;
    static Account acc;
    static Employee__c emp;
    static User adminUser;
    static User logiUser;
    static Profile adminpf;
    static Profile logipf;
    static MasterActivity__c ma;
    static OpptyCodeSetting__c ocs;
    static CostCenter__c costCenter;
    static {
        adminpf =  [SELECT Id FROM Profile WHERE Name = 'System Administrator' OR Name = '시스템 관리자' limit 1];
        logipf = [SELECT Id FROM Profile WHERE Name Like '%Logi%' LIMIT 1];   
        
        adminUser = new User(
            Alias = 'testUser'
            , Email = 'admin11User@test.com.test'
            , EmailEncodingKey = 'UTF-8'
            , LastName = 'Testing'
            , LanguageLocaleKey = 'en_US'
            , LocaleSidKey = 'en_US'
            , EmployeeNumber = 'AC100000'
            , TimeZoneSidKey = 'Asia/Seoul'
            , ProfileId = adminpf.Id
            , UserName = 'admin11User@test.com.test'
            , FederationIdentifier = 'epId1'
        );
                                
        insert adminUser;
        logiUser = new User(
            Alias = 'testUser'
            , Email = 'logi12User@test.com.test'
            , EmailEncodingKey = 'UTF-8'
            , LastName = 'Testing'
            , LanguageLocaleKey = 'en_US'
            , LocaleSidKey = 'en_US'
            , EmployeeNumber = 'AC100000'
            , TimeZoneSidKey = 'Asia/Seoul'
            , ProfileId = adminpf.Id
            , UserName = 'logi12User@test.com.test'
            , FederationIdentifier = 'epId2'
        );
                                
        insert logiUser;

        emp = new Employee__c(
            Name = 'logi12User',
            EvMailAddr__c = 'logi12User' + '@samsung.com',
            EvUniqID__c = 'epId2'            
        );
        insert emp;

        acc = new Account(
            Name = 'testAccount',
            MDGCheck__c = true
        );
        
        insert acc;
        
    	l = new Lead(LastName = 'TestLead', 
                     PersonalInfoAgreementExpireDate__c = Date.today(), 
                     PersonalInfoAgreement__c = true, 
                     Company='TestCompany');
        insert l;
        costCenter = new CostCenter__c(CostCenterName__c = 'Test1', Name ='Test1');
        insert costCenter;
        
        List<Sales_Lead__c> slList = new List<Sales_Lead__c>();
        sl = new Sales_Lead__c(
            Name = 'TestSalesLead', 
            LeadStage__c = 'Hot',
            LeadStatus__c = 'In Process',
            Lead__c = L.Id, 
            Amount__c = 5000, 
            CloseDate__c = Date.today().addDays(1),  
            RevenueEndDate__c = Date.today().addDays(3), 
            RevenueStartDate__c = Date.today().addDays(2),
            Budget__c = true,
            Authority__c = true,
            LeadChannel__c = 'Marketing Lead Converted',
            Internal_External__c = 'Internal',
            SalesDepartment__c = costCenter.Id,
            CustomerContactDate__c = DateTime.now()
        );
        insert sl;

        sl2 = new Sales_Lead__c(
            Name = 'TestSalesLead', 
            LeadStage__c = 'Warm',
            LeadStatus__c = 'In Process',
            Amount__c = 5000,
            Lead__c = L.Id, 
            RevenueEndDate__c = Date.today().addDays(3), 
            RevenueStartDate__c = Date.today().addDays(2),
            LeadChannel__c = 'Marketing Lead Converted',
            Internal_External__c = 'Internal'
        );
        insert sl2;

        sl3 = new Sales_Lead__c(
            Name = 'TestSalesLead', 
            LeadStage__c = 'Hot',
            LeadStatus__c = 'In Process',
            Amount__c = 5000, 
            AccountId__c = acc.Id,
            CloseDate__c = Date.today().addDays(1),  
            RevenueEndDate__c = Date.today().addDays(3), 
            RevenueStartDate__c = Date.today().addDays(2),
            Budget__c = true,
            Authority__c = true,
            Internal_External__c = 'Internal',
            SalesDepartment__c = costCenter.Id
        );
        insert sl3;
        //insert slList;

        L.SalesLeadID__c = sl.Id;
        update L;
        
        ma = new MasterActivity__c(TransactionName__c = Utils.getPicklistOptionType('Opportunity_Activity__c','TransactionName__c')[0].get('value'), Stage__c = 'Z01');
        insert ma;

        ocs = new OpptyCodeSetting__c(Name = 'test', CodeSetting__c  = false);
        insert ocs;
    }
    @isTest
    public static void SalesLeadToOppModalController_Test() {
        try{
            SalesLeadToOppModalController.ReturnWrapper rw = SalesLeadToOppModalController.getOppLabel(String.valueOf(sl.Id));
            //String recordId, List<Map<String, String>> opplist
            List<Map<String, String>> opplist1 = new List<Map<String, String>>();
            List<Map<String, String>> opplist2 = new List<Map<String, String>>();
            RecordType rtlist = [SELECT Id,Name, DeveloperName FROM RecordType WHERE sObjectType='Opportunity' AND DeveloperName = 'Logistics' LIMIT 1];
            for(Map<String, String> r : rw.sflist){
                Map<String, String> maps = new Map<String, String>();
                maps.put('Api', r.get('oppApi'));
                maps.put('Value', r.get('oppValue'));
                opplist1.add(maps);
                opplist2.add(maps);
            }
            Map<String, String> recordtype = new Map<String, String>();
            recordtype.put('Api', 'RecordTypeId');
            recordtype.put('Value', String.valueOf(rtlist.Id));
            
            Map<String, String> OwnerMap1 = new Map<String, String>();
            Map<String, String> OwnerMap2 = new Map<String, String>();
            OwnerMap1.put('Api', 'OwnerId');
            OwnerMap1.put('Value', String.valueOf(logiUser.Id));
            opplist1.add(OwnerMap1);
            System.debug('convertOpp 1 ');
            SalesLeadToOppModalController.convertOpp(String.valueOf(sl.Id), opplist1);
            SalesLeadToOppModalController.convertOpp(String.valueOf(sl3.Id), opplist1);
            OwnerMap2.put('Api', 'OwnerId');
            OwnerMap2.put('Value', String.valueOf(adminUser.Id));
            opplist2.add(OwnerMap2);
            System.debug('convertOpp 2 ');
            SalesLeadToOppModalController.convertOpp(String.valueOf(sl.Id), opplist2);
        } catch(Exception e){
            System.debug(e);
        }
        SalesLeadToOppModalController.getRecordType(logipf.Id, logiUser.Id);
        SalesLeadToOppModalController.isConverted(String.valueOf(sl.Id));	
        SalesLeadToOppModalController.isConverted(String.valueOf(sl2.Id));	
    }
}