force-app/main/default/objects/CostCenter__c/CostCenter__c.object-meta.xml
<CustomObject>
    <label>Cost Center</label>
    <nameField>
        <label>Cost Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cost Center</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CostCenter__c/fields/CompanyCode__c.field-meta.xml
<CustomField>
    <fullName>CompanyCode__c</fullName>
    <label>Company Code</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CostCenter__c/fields/CostCenter__c.field-meta.xml
<CustomField>
    <fullName>CostCenter__c</fullName>
    <externalId>true</externalId>
    <label>Cost Center</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CostCenter__c/fields/ZZCheck__c.field-meta.xml
<CustomField>
    <fullName>ZZCheck__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ZZCheck</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/EvKostl__c.field-meta.xml
<CustomField>
    <fullName>EvKostl__c</fullName>
    <label>Cost Center</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/EvSapBukrs__c.field-meta.xml
<CustomField>
    <fullName>EvSapBukrs__c</fullName>
    <label>Company Code</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/EvUniqID__c.field-meta.xml
<CustomField>
    <fullName>EvUniqID__c</fullName>
    <externalId>true</externalId>
    <label>EP ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LeadToSalesLeadsModalController_Test.cls
/**
 * @description       : 
 * @author            : Junghwa.Kim@dkbmc.com
 * @group             : 
 * @last modified on  : 2021-10-05
 * @last modified by  : younghoon.kim@dkbmc.com
 * Modifications Log 
 * Ver   Date         Author                  Modification
 * 1.0   11-11-2020   Junghwa.Kim@dkbmc.com   Initial Version
**/
@isTest
public class LeadToSalesLeadsModalController_Test {
    static User admin;
    static User salesRep;
    static Employee__c emp;
    static CostCenter__c costCenter;
    static Lead lead;

    static{
        Profile profile_Admin =  [SELECT Id FROM Profile WHERE Name = 'System Administrator' OR Name = '시스템 관리자' limit 1];
        admin = new User(
            Alias = 'Admin'
            , Email = 'Admin@leadconvert.com'
            , EmailEncodingKey = 'UTF-8'
            , LastName = 'Admin'
            , LanguageLocaleKey = 'en_US'
            , LocaleSidKey = 'en_US'
            , TimeZoneSidKey = 'Asia/Seoul'
            , ProfileId = profile_Admin.Id
            , UserName = 'Admin@leadconvert.com'
            , FederationIdentifier = 'Admin_EPID_1'
        );
        insert admin;

        Profile profile_SalesRep =  [SELECT Id FROM Profile WHERE Name = 'Sales Rep.(HQ)' limit 1];
        salesRep = new User(
            Alias = 'SalesRep'
            , Email = 'SalesRep@leadconvert.com'
            , EmailEncodingKey = 'UTF-8'
            , LastName = 'SalesRep'
            , LanguageLocaleKey = 'en_US'
            , LocaleSidKey = 'en_US'
            , TimeZoneSidKey = 'Asia/Seoul'
            , ProfileId = profile_SalesRep.Id
            , UserName = 'SalesRep@leadconvert.com'
            , FederationIdentifier = 'SalesRep_EPID_1'
        );
        insert salesRep;

        emp = new Employee__c(
            Name = 'SalesRep'
            , EvKostl__c = 'T100-12345'
            , EvUniqID__c = 'SalesRep_EPID_1'
            , EvSapBukrs__c = 'T100'
        );
        insert emp;

        costCenter = new CostCenter__c(
            CompanyCode__c = 'T100'
            , CostCenter__c = 'T100-12345'
            , ZZCheck__c = true
        );
        insert costCenter;

        lead = new Lead(
            FirstName = 'Fitst Name'
            , LastName = 'Last Name'
            , Status = 'In Process'
            , LeadType__c = '01'
            , Company = 'Test Company'
        );
        insert lead;
    }

    @isTest
    public static void leadCheck_Test_1() {
        System.runAs(admin){
            LeadToSalesLeadsModalController.leadCheck(lead.Id);
        }
    }

    @isTest
    public static void getFieldLabel_Test_1() {
        System.runAs(admin){
            LeadToSalesLeadsModalController.getFieldLabel(lead.Id);
        }
    }

    @isTest
    public static void convertLead_Test_1() {
        System.runAs(admin){
            LeadToSalesLeadsModalController.convertLead(lead.Id, salesRep.Id);
        }
    }
}