force-app/main/default/objects/CostCenter__c/CostCenter__c.object-meta.xml
<CustomObject>
    <label>Cost Center</label>
    <nameField>
        <label>Cost Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cost Center</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CostCenter__c/fields/CostCenter__c.field-meta.xml
<CustomField>
    <fullName>CostCenter__c</fullName>
    <externalId>true</externalId>
    <label>Cost Center</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/EvKostl__c.field-meta.xml
<CustomField>
    <fullName>EvKostl__c</fullName>
    <label>Cost Center</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/EvUniqID__c.field-meta.xml
<CustomField>
    <fullName>EvUniqID__c</fullName>
    <externalId>true</externalId>
    <label>EP ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Lead__c/Sales_Lead__c.object-meta.xml
<CustomObject>
    <label>Sales Lead</label>
    <nameField>
        <label>Sales Lead Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Leads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Lead__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Contract Account</description>
    <inlineHelpText>Required Information only for HQ users when creating IT Sales Lead / Required information when converting</inlineHelpText>
    <label>Account(*)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Leads</relationshipLabel>
    <relationshipName>Sales_Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Lead__c/fields/Demand_Owner_ID__c.field-meta.xml
<CustomField>
    <fullName>Demand_Owner_ID__c</fullName>
    <label>Demand Owner ID</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Lead__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Sales Lead 개요</description>
    <label>Description</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Sales_Lead__c/fields/LeadChannel__c.field-meta.xml
<CustomField>
    <fullName>LeadChannel__c</fullName>
    <label>Lead Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Direct Registration</fullName>
            </value>
            <value>
                <fullName>Marketing Lead Converted</fullName>
            </value>
            <value>
                <fullName>Demand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Lead__c/fields/LeadStage__c.field-meta.xml
<CustomField>
    <fullName>LeadStage__c</fullName>
    <description>Lead Stage</description>
    <label>Lead Stage</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cold</fullName>
                <color>#33CCFF</color>
                <label>Cold</label>
            </value>
            <value>
                <fullName>Warm</fullName>
                <color>#FF9900</color>
                <label>Warm</label>
            </value>
            <value>
                <fullName>Hot</fullName>
                <color>#FF0000</color>
                <label>Hot</label>
            </value>
            <value>
                <fullName>Converted</fullName>
                <color>#BBBBBB</color>
                <label>Converted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Lead__c/fields/LeadStatus__c.field-meta.xml
<CustomField>
    <fullName>LeadStatus__c</fullName>
    <description>Sales Lead Status</description>
    <inlineHelpText>Sales Lead Status</inlineHelpText>
    <label>Lead Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Process</fullName>
                <default>true</default>
                <label>In Process</label>
            </value>
            <value>
                <fullName>Close</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Lead__c/fields/LeadType__c.field-meta.xml
<CustomField>
    <fullName>LeadType__c</fullName>
    <description>Sales Lead Type</description>
    <inlineHelpText>Sales Lead Type</inlineHelpText>
    <label>Lead Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>LeadChannel__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>Business</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>Technical Support</label>
            </value>
            <value>
                <fullName>09</fullName>
                <label>Others</label>
            </value>
            <value>
                <fullName>31</fullName>
                <label>System Enhancement</label>
            </value>
            <value>
                <fullName>32</fullName>
                <label>New System</label>
            </value>
            <value>
                <fullName>33</fullName>
                <label>Solution/Service</label>
            </value>
            <value>
                <fullName>34</fullName>
                <label>Consulting</label>
            </value>
            <value>
                <fullName>35</fullName>
                <label>Seminar</label>
            </value>
            <value>
                <fullName>36</fullName>
                <label>IT Trend / Research</label>
            </value>
            <value>
                <fullName>37</fullName>
                <label>Benchmarking</label>
            </value>
            <value>
                <fullName>39</fullName>
                <label>Etc</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Lead__c/fields/Requester_ID__c.field-meta.xml
<CustomField>
    <fullName>Requester_ID__c</fullName>
    <label>Requester ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Lead__c/fields/Requester_Name__c.field-meta.xml
<CustomField>
    <fullName>Requester_Name__c</fullName>
    <label>Requester Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Lead__c/fields/SalesDepartment__c.field-meta.xml
<CustomField>
    <fullName>SalesDepartment__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Required Information only for HQ users when creating IT Sales Lead / Required information when converting</inlineHelpText>
    <label>Sales Dept. 3(*)</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR (2 AND 3 AND 4)</booleanFilter>
        <errorMessage>Closed departments cannot be selected.</errorMessage>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>Custom System Administrator, System Administrator</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>notEqual</operation>
            <value>Custom System Administrator, System Administrator</value>
        </filterItems>
        <filterItems>
            <field>CostCenter__c.Closed__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$User.CompanyCode__c</field>
            <operation>equals</operation>
            <valueField>CostCenter__c.CompanyCode__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CostCenter__c</referenceTo>
    <relationshipLabel>Sales Leads</relationshipLabel>
    <relationshipName>Sales_Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Lead__c/recordTypes/HQ.recordType-meta.xml
<RecordType>
    <fullName>HQ</fullName>
    <active>true</active>
    <label>HQ</label>
</RecordType>

force-app/main/default/classes/test11.cls
public class test11 {
    //Akash test
  
    public class OtherException extends Exception {}
    
    public static void testExtendedException() {
        
        
        
        
        try{
            String leadName = 'Testing 3 create';
            String leadType = '31';
            String account = '';
            String owner = 'seonju.jin';
            String description = 'Test Desc';
            String reqName = 'sm2528 hong';
            String reqId = 'sm2528.hong';
            system.debug('leadName**=' + leadName + 'leadType**=' + leadType + 'account**=' + account + 'owner**=' + owner +
                         'description**=' + description + 'reqName**=' + reqName + 'reqId**=' + reqId);
            String leadRecordTypeID = Schema.SObjectType.Sales_Lead__c.getRecordTypeInfosByDeveloperName().get('HQ').getRecordTypeId();
            system.debug('leadRecordTypeID&&' + leadRecordTypeID);
            Sales_Lead__c slLead = new Sales_Lead__c();
            if(leadRecordTypeID != null)
                slLead.RecordTypeId = leadRecordTypeID;
            slLead.Name = leadName;
            slLead.LeadType__c = leadType;
            slLead.Description__c = description;
            slLead.Requester_Name__c = reqName;
            slLead.Requester_ID__c = reqId;
            slLead.LeadChannel__c = 'Demand' ;
            slLead.LeadStage__c = 'Cold';
            slLead.LeadStatus__c = 'In Process';
            if(account != null && account != ''){
                String accID;
                Account acc = [select id from account where AccountNumber =: account Limit 1];
                system.debug('acc @@' + acc);
                if(acc != null){
                    accID = acc.ID;
                    system.debug('accID@@' + accID);
                    slLead.AccountId__c = accID;
                }
            }
            
            if(owner != null && owner != ''){
                String ownerKnoxID = owner + '@%';
                ID uID;
                String EvUniqueID;
                String costCentreCode;
                List<User> userList = [Select id,FederationIdentifier,DefaultCurrencyIsoCode from user where IsActive = true And email Like : ownerKnoxID Limit 1];
                system.debug('userList Size @@' + userList.size());
                if(userList.size()== 1){
                    uID = userList[0].ID;
                    slLead.Demand_Owner_ID__c = uID;
                    slLead.CurrencyIsoCode = userList[0].DefaultCurrencyIsoCode;
                    EvUniqueID = userList[0].FederationIdentifier;
                    system.debug('uID@@' + uID);
                    system.debug('EvUniqueID@@' + EvUniqueID);
                    List<Employee__c> empList= [select EvKostl__c from Employee__c where EvUniqID__c =: EvUniqueID Limit 1];
                    system.debug('empList size@@' + empList.size());
                    if(empList.size() == 1 && empList[0].EvKostl__c != null){
                        costCentreCode = empList[0].EvKostl__c;
                        system.debug('CostCentreCode@@' + costCentreCode);
                        List<CostCenter__c> ccList = [select id from CostCenter__c where CostCenter__c =: costCentreCode Limit 1];
                        if(ccList.size() == 1 ){
                            slLead.SalesDepartment__c = ccList[0].ID;
                        }
                    }
                }else{
                    throw new OtherException(System.Label.User_Register_Demand_System);
                }
            }
            Insert slLead;
	    system.debug('slLead ID=' + slLead.ID);
                   
        }catch(Exception e){
            
            system.debug('Exeption detail=' + e.getCause()+e.getMessage()+e.getTypeName()+e.getLineNumber());
         
        }
        
       
    }
    
}