force-app/main/default/objects/CostCenter__c/CostCenter__c.object-meta.xml
<CustomObject>
    <label>Cost Center</label>
    <nameField>
        <label>Cost Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cost Center</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CostCenter__c/fields/CostCenter__c.field-meta.xml
<CustomField>
    <fullName>CostCenter__c</fullName>
    <externalId>true</externalId>
    <label>Cost Center</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity_Activity__c/Opportunity_Activity__c.object-meta.xml
<CustomObject>
    <label>Opportunity Activity</label>
    <nameField>
        <displayFormat>OA-{yymmdd}-{00000}</displayFormat>
        <label>Opportunity Activity No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Activity__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <label>Canceled</label>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Activity__c/fields/TransactionName__c.field-meta.xml
<CustomField>
    <fullName>TransactionName__c</fullName>
    <label>Opportunity Activity Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>XP11</fullName>
                <label>Register BO</label>
            </value>
            <value>
                <fullName>ZP21</fullName>
                <label>Review BO</label>
            </value>
            <value>
                <fullName>ZP32</fullName>
                <label>Request Resources</label>
            </value>
            <value>
                <fullName>XP31</fullName>
                <label>Receive RFP</label>
            </value>
            <value>
                <fullName>ZP31</fullName>
                <label>Request Strategy Committee</label>
            </value>
            <value>
                <fullName>XP32</fullName>
                <label>Strategy Committee Cost Plan Completion</label>
            </value>
            <value>
                <fullName>ZP62</fullName>
                <label>Request Committee Approval</label>
            </value>
            <value>
                <fullName>ZPZ3</fullName>
                <label>Agency Contract Exception</label>
            </value>
            <value>
                <fullName>ZP61</fullName>
                <label>Submit Proposal</label>
            </value>
            <value>
                <fullName>XP41</fullName>
                <label>Presentation</label>
            </value>
            <value>
                <fullName>XP42</fullName>
                <label>Preferred Bidder</label>
            </value>
            <value>
                <fullName>XP43</fullName>
                <label>Customer Approval</label>
            </value>
            <value>
                <fullName>XP44</fullName>
                <label>Negotiation</label>
            </value>
            <value>
                <fullName>XP51</fullName>
                <label>Contract P&amp;L</label>
            </value>
            <value>
                <fullName>XP52</fullName>
                <label>Legal Review</label>
            </value>
            <value>
                <fullName>ZP82</fullName>
                <label>Contract Approval</label>
            </value>
            <value>
                <fullName>XP57</fullName>
                <label>Closing</label>
            </value>
            <value>
                <fullName>ZPZ2</fullName>
                <label>Drop Opportunity</label>
            </value>
            <value>
                <fullName>XPX1</fullName>
                <label>Abort Opportunity</label>
            </value>
            <value>
                <fullName>ZAC1</fullName>
                <label>Hold Opportunity</label>
            </value>
            <value>
                <fullName>ZPZ1</fullName>
                <label>Lost Opportunity</label>
            </value>
            <value>
                <fullName>ZAC4</fullName>
                <label>Unhold Opportunity</label>
            </value>
            <value>
                <fullName>ZPG1</fullName>
                <label>Change Approval Request</label>
            </value>
            <value>
                <fullName>2.2.1.</fullName>
                <label>Credit Assessment</label>
            </value>
            <value>
                <fullName>2.2.2.</fullName>
                <label>Request AP(APS)</label>
            </value>
            <value>
                <fullName>2.3.2.</fullName>
                <label>Bidding LBS</label>
            </value>
            <value>
                <fullName>2.3.3.</fullName>
                <label>Test Shipment</label>
            </value>
            <value>
                <fullName>2.4.5.</fullName>
                <label>Final LBS</label>
            </value>
            <value>
                <fullName>2.5.1.</fullName>
                <label>Receive Contract</label>
            </value>
            <value>
                <fullName>2.5.3.</fullName>
                <label>Rate Change LBS</label>
            </value>
            <value>
                <fullName>XP61</fullName>
                <label>Request participation committee</label>
            </value>
            <value>
                <fullName>XP62</fullName>
                <label>Participation committee P&amp;L</label>
            </value>
            <value>
                <fullName>XP63</fullName>
                <label>Participation committee approval</label>
            </value>
            <value>
                <fullName>XP71</fullName>
                <label>Request decision committee</label>
            </value>
            <value>
                <fullName>XP72</fullName>
                <label>Decision committee P&amp;L</label>
            </value>
            <value>
                <fullName>XP73</fullName>
                <label>Decision committee approval</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Activity__c/fields/WhatId__c.field-meta.xml
<CustomField>
    <fullName>WhatId__c</fullName>
    <description>Opportunity</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Activity</relationshipLabel>
    <relationshipName>BO_Activity</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Organization__c/Organization__c.object-meta.xml
<CustomObject>
    <label>Organization</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organizations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/IF_OpportunityActivityInfoCallOutTest.cls
/**
* @description       : 
* @author            : Kajal.c@samsung.com
* @group             : 
* @last modified on  : 2023-03-09
* @last modified by  : Kajal.c@samsung.com
* Modifications Log 
* Ver   Date         Author                    Modification
* 1.0   2023-03-09   Kajal.c@samsung.com     Initial Version 
**/
@isTest
public class IF_OpportunityActivityInfoCallOutTest {

      final static String REQUEST_URL = '/services/apexrest/WebService/IF180';
      Set<Opportunity> oppty = new Set<Opportunity>();
      public static Opportunity HQOpportunity;
      public static CostCenter__c CostCenter;
      public static Opportunity_Activity__c OpAct;
      public static Opportunity_Activity__c OpAct1;
     @isTest
      static void setData(){
        Account acc = Utils_TestDataFactory.createAccount('TestAcc');
        acc.MDGCheck__c = true;
        update acc;
         
        Organization__c org = new Organization__c();
        insert org;
        HQOpportunity = new Opportunity(
            Name = 'MySales01',
            CurrencyIsoCode='EUR',
            OpportunityCode__c='SDS-22131801',
            CloseDate = System.today() + 30,
            StageName= 'Z01',
            Amount = 78,
            AccountId = acc.id,
            cOriginAcc__c = acc.id,
            CspMspType__c = 'N/A'
        );
        
        insert HQOpportunity;
      
        //Opportunity_Activity__c act1 = new Opportunity_Activity__c(WhatId__c  = HQOpportunity.Id, TransactionName__c = 'XP99', Status__c = 'Completed', EndDate__c = Date.today());
        Opportunity_Activity__c act2 = new Opportunity_Activity__c(WhatId__c  = HQOpportunity.Id, TransactionName__c = 'ZP21', Status__c = 'Completed', EndDate__c = Date.today());
        Opportunity_Activity__c act3 = new Opportunity_Activity__c(WhatId__c  = HQOpportunity.Id, TransactionName__c = 'XP61', Status__c = 'Completed', EndDate__c = Date.today());
        Opportunity_Activity__c act4 = new Opportunity_Activity__c(WhatId__c  = HQOpportunity.Id, TransactionName__c = 'XP62', Status__c = 'Completed', EndDate__c = Date.today());
        Opportunity_Activity__c act5 = new Opportunity_Activity__c(WhatId__c  = HQOpportunity.Id, TransactionName__c = 'XP63', Status__c = 'Completed', EndDate__c = Date.today());
        Opportunity_Activity__c act6 = new Opportunity_Activity__c(WhatId__c  = HQOpportunity.Id, TransactionName__c = 'XP71', Status__c = 'Completed', EndDate__c = Date.today());
        Opportunity_Activity__c act7 = new Opportunity_Activity__c(WhatId__c  = HQOpportunity.Id, TransactionName__c = 'XP72', Status__c = 'Completed', EndDate__c = Date.today());
        Opportunity_Activity__c act8 = new Opportunity_Activity__c(WhatId__c  = HQOpportunity.Id, TransactionName__c = 'XP73', Status__c = 'Completed', EndDate__c = Date.today());
        Opportunity_Activity__c act9 = new Opportunity_Activity__c(WhatId__c  = HQOpportunity.Id, TransactionName__c = 'ZP32', Status__c = 'Completed', EndDate__c = Date.today());
        Opportunity_Activity__c act10 = new Opportunity_Activity__c(WhatId__c  = HQOpportunity.Id, TransactionName__c = 'XP31', Status__c = 'Completed', EndDate__c = Date.today());
        Opportunity_Activity__c act11 = new Opportunity_Activity__c(WhatId__c  = HQOpportunity.Id, TransactionName__c = 'ZP61', Status__c = 'Completed', EndDate__c = Date.today());
        Opportunity_Activity__c act12 = new Opportunity_Activity__c(WhatId__c  = HQOpportunity.Id, TransactionName__c = 'XP41', Status__c = 'Completed', EndDate__c = Date.today());
        Opportunity_Activity__c act13 = new Opportunity_Activity__c(WhatId__c  = HQOpportunity.Id, TransactionName__c = 'XP42', Status__c = 'Completed', EndDate__c = Date.today());
        Opportunity_Activity__c act14 = new Opportunity_Activity__c(WhatId__c  = HQOpportunity.Id, TransactionName__c = 'XP43', Status__c = 'Completed', EndDate__c = Date.today());
        Opportunity_Activity__c act15 = new Opportunity_Activity__c(WhatId__c  = HQOpportunity.Id, TransactionName__c = 'XP44', Status__c = 'Completed', EndDate__c = Date.today());
        Opportunity_Activity__c act16 = new Opportunity_Activity__c(WhatId__c  = HQOpportunity.Id, TransactionName__c = 'XP51', Status__c = 'Completed', EndDate__c = Date.today());
        Opportunity_Activity__c act17 = new Opportunity_Activity__c(WhatId__c  = HQOpportunity.Id, TransactionName__c = 'XP52', Status__c = 'Completed', EndDate__c = Date.today());
        Opportunity_Activity__c act18 = new Opportunity_Activity__c(WhatId__c  = HQOpportunity.Id, TransactionName__c = 'ZP82', Status__c = 'Completed', EndDate__c = Date.today());
        //Opportunity_Activity__c act19 = new Opportunity_Activity__c(WhatId__c  = HQOpportunity.Id, TransactionName__c = '2.5.1', Status__c = 'Completed', EndDate__c = Date.today());
        Opportunity_Activity__c act20 = new Opportunity_Activity__c(WhatId__c  = HQOpportunity.Id, TransactionName__c = 'ZPZ3', Status__c = 'Completed', EndDate__c = Date.today());
        insert new List<Opportunity_Activity__c>{act2, act3, act4, act5, act6, act7,act8, act9, act10, act11, act12, act13,act14, act15, act16, act17, act18,act20};
        
       Test.startTest();
       Set<ID> idSet = new Set<ID>();
       List<Opportunity> oppIDList = [Select id from Opportunity];
       for(Opportunity opp : oppIDList){
       idSet.add(opp.ID);
       }
        IF_OpportunityActivityInfoCallOut If180callout = new IF_OpportunityActivityInfoCallOut();
        IF_OpportunityActivityInfoCallOut.doCalloutSendingOpportunityActivityInfo(idSet);
        Test.stopTest();
      }

}