force-app/main/default/objects/CostCenter__c/CostCenter__c.object-meta.xml
<CustomObject>
    <label>Cost Center</label>
    <nameField>
        <label>Cost Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cost Center</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CostCenter__c/fields/CostCenter__c.field-meta.xml
<CustomField>
    <fullName>CostCenter__c</fullName>
    <externalId>true</externalId>
    <label>Cost Center</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Role_CostCenter__c/Role_CostCenter__c.object-meta.xml
<CustomObject>
    <label>Role CostCenter</label>
    <nameField>
        <label>Role</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Role CostCenter</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Role_CostCenter__c/fields/CostCenter__c.field-meta.xml
<CustomField>
    <fullName>CostCenter__c</fullName>
    <label>Cost Center</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Batch_EccEmployeeController_Test.cls
/**
 * @description       : 
 * @author            : raeganja@partner.samsung.com
 * @group             : 
 * @last modified on  : 2021-05-04
 * @last modified by  : raeganja@partner.samsung.com
 * Modifications Log 
 * Ver   Date         Author                         Modification
 * 1.0   2021-03-22   raeganja@partner.samsung.com   Initial Version
**/
@isTest
public class Batch_EccEmployeeController_Test {
    public Batch_EccEmployeeController_Test() {

    }

    @TestSetup
    static void setup(){
        
        List<User> uList = [SELECT Id, UserRole.DeveloperName FROM User WHERE Id = :UserInfo.getUserId()];

        Role_CostCenter__c rc = new Role_CostCenter__c();
        rc.Name = uList.get( 0).UserRole.DeveloperName;
        rc.CostCenter__c = 'T100-12345';
        insert rc;
    }

    static testMethod  void testBatch1() {

        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new IF_Callout_TestMock(200));
        Test.stopTest();

        Id batchJobId = Database.executeBatch(new Batch_EccEmployeeController(), 1);
    }


    static testMethod  void testBatch2() {

        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new IF_Callout_TestMock(202));
        Test.stopTest();

        Id batchJobId = Database.executeBatch(new Batch_EccEmployeeController(), 1);
    }
    

    static testMethod  void testBatch3() {

        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new IF_Callout_TestMock(400));
        Test.stopTest();

        Id batchJobId = Database.executeBatch(new Batch_EccEmployeeController(), 1);
    }    

    private static testMethod void testSchedule(){

        Test.startTest();     
        Test.setMock(HttpCalloutMock.class, new IF_Callout_TestMock(202));

        String sch = '0 0 23 * * ?';
        String jobId = System.schedule('Batch_EccEmployeeController_Test', sch, new Batch_EccEmployeeController());         
        Test.stopTest();
    }
}