force-app/main/default/objects/OpportunityReviewSession__c/OpportunityReviewSession__c.object-meta.xml
<CustomObject>
    <label>Opportunity Review Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Review Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OpportunityReviewSession__c/fields/Note__c.field-meta.xml
<CustomField>
    <fullName>Note__c</fullName>
    <label>Note</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/OpportunityReviewSession__c/fields/Session_Date__c.field-meta.xml
<CustomField>
    <fullName>Session_Date__c</fullName>
    <label>Session Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OpportunityReviewSession__c/fields/Session_Result__c.field-meta.xml
<CustomField>
    <fullName>Session_Result__c</fullName>
    <label>Session Result</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/OpportunityReviewTarget__c/OpportunityReviewTarget__c.object-meta.xml
<CustomObject>
    <label>Review Target Opportunity</label>
    <nameField>
        <label>Review Target Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OpportunityReviewTargets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OpportunityReviewTarget__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>OpportunityReviewTargets</relationshipLabel>
    <relationshipName>OpportunityReviewTargets</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityReviewTarget__c/fields/Opportunity_Review_Session__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Review_Session__c</fullName>
    <label>Opportunity Review Session</label>
    <referenceTo>OpportunityReviewSession__c</referenceTo>
    <relationshipLabel>OpportunityReviewTargets</relationshipLabel>
    <relationshipName>OpportunityReviewTargets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OpportunityReviewTarget__c/fields/Today_Review_Target__c.field-meta.xml
<CustomField>
    <fullName>Today_Review_Target__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Today Review Target</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/OpportunityReviewSessionOverride.cls
public class OpportunityReviewSessionOverride {
    @AuraEnabled
    public static String createOpportunityReviewSessionRecord(String sessionName,Date sessionDate, String Note,String sessionResult,String BotargetList){
        system.debug('Akash1' + BotargetList);
            List<targetBo> incomingBo = (List<targetBo>)JSON.deserialize(BotargetList, List<targetBo>.class);
            system.debug('Akash3' + incomingBo);
            OpportunityReviewSession__c oppReview = new OpportunityReviewSession__c();
            oppReview.Name = sessionName;
            oppReview.Session_Date__c = sessionDate;
            oppReview.Session_Result__c = sessionResult;
            oppReview.Note__c = Note;
            
            insert oppReview;
            List<OpportunityReviewTarget__c> targetList = new List<OpportunityReviewTarget__c>();
            
            for(targetBo opp : incomingBo){
                OpportunityReviewTarget__c target = new OpportunityReviewTarget__c();
                target.Opportunity__c = opp.BoId;
                target.Opportunity_Review_Session__c = oppReview.Id;
                target.Today_Review_Target__c = opp.Checked;
                targetList.add(target);
            }
            insert targetList;
            return 'Success'; 
        
      
        
    }
    @AuraEnabled
    public static listView getListViews(){
        system.debug('Akash1');
        List<listView> listViews = [select id,name from ListView where SobjectType = 'OpportunityReviewSession__c' Limit 1];
        return listViews[0];
    }
    @AuraEnabled
    public static OpportunityReviewSession__c getExistingReviewSession(Id recordId){
      List<OpportunityReviewSession__c> reviewList =   [Select id,Name,Session_Date__c,Session_Result__c,Note__c from OpportunityReviewSession__c where Id=: recordId limit 1];
        system.debug('Akash0' + reviewList);
       return reviewList[0];
    }
    @AuraEnabled
    public static List<OpportunityReviewTarget__c> getOpportunityReviewTarget(Id recordId){
      List<OpportunityReviewTarget__c> reviewList =   [Select id,Name,Opportunity__c,Opportunity__r.Name,Opportunity__r.OpportunityCode__c,Opportunity__r.Account.AccountNumber,Opportunity__r.Account.Name,Opportunity__r.Amount,Opportunity__r.CloseDate,Opportunity_Review_Session__c,Today_Review_Target__c from OpportunityReviewTarget__c where Opportunity_Review_Session__c=: recordId];
        system.debug('Akash0' + reviewList);
       return reviewList;
    }
    public class targetBo{
        public string BoId;
        public Boolean Checked;
    }
    
}