force-app/main/default/objects/Partner_Privacy_Policy_Master__c/Partner_Privacy_Policy_Master__c.object-meta.xml
<CustomObject>
    <label>Partner Privacy Policy Master</label>
    <nameField>
        <displayFormat>P-{YY}{MM}{DD}{000}</displayFormat>
        <label>T&amp;C Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Privacy Policy Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner_Privacy_Policy_Master__c/fields/Apply_Date__c.field-meta.xml
<CustomField>
    <fullName>Apply_Date__c</fullName>
    <label>Apply Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Partner_Privacy_Policy_Master__c/fields/T_C_Detail__c.field-meta.xml
<CustomField>
    <fullName>T_C_Detail__c</fullName>
    <label>T&amp;C Detail</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Partner_Privacy_Policy_Master__c/fields/T_C_Type__c.field-meta.xml
<CustomField>
    <fullName>T_C_Type__c</fullName>
    <label>T&amp;C Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Privacy Policy</fullName>
            </value>
            <value>
                <fullName>Terms of Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PartnerPrivacyPolicyController.cls
/**
 * @description       : 
 * @author            : chae_ho.yang@samsung.com
 * @group             : 
 * @last modified on  : 12-14-2022
 * @last modified by  : chae_ho.yang@samsung.com
**/
public with sharing class PartnerPrivacyPolicyController {
    @AuraEnabled(cacheable=true)
    public static List<Partner_Privacy_Policy_Master__c> getPartnerPrivacyPolicyVersion() {
        return [SELECT Id, Version__c, T_C_Detail__c FROM Partner_Privacy_Policy_Master__c WHERE T_C_Type__c = 'Privacy Policy' ORDER BY Apply_Date__c DESC];
    }

    @AuraEnabled(cacheable=true)
    public static List<Partner_Privacy_Policy_Master__c> getTermsOfServiceVersion() {
        return [SELECT Id, Version__c, T_C_Detail__c FROM Partner_Privacy_Policy_Master__c WHERE T_C_Type__c = 'Terms of Service' ORDER BY Apply_Date__c ASC];
    }
}