force-app/main/default/objects/LBS__c/LBS__c.object-meta.xml
<CustomObject>
    <label>LBS</label>
    <nameField>
        <label>LBS ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LBS</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LBS__c/fields/LBSStatus__c.field-meta.xml
<CustomField>
    <fullName>LBSStatus__c</fullName>
    <description>LBS Status</description>
    <label>LBS Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>REQ</fullName>
                <label>(Bidding) Requested</label>
            </value>
            <value>
                <fullName>ONGO</fullName>
                <label>(Bidding) Ongoing</label>
            </value>
            <value>
                <fullName>PASS</fullName>
                <label>(Bidding) Passed</label>
            </value>
            <value>
                <fullName>BREJ</fullName>
                <label>(Bidding) Rejected</label>
            </value>
            <value>
                <fullName>BREG</fullName>
                <label>(Bidding) Saved</label>
            </value>
            <value>
                <fullName>BRJQ</fullName>
                <label>(Bidding) Modify Request</label>
            </value>
            <value>
                <fullName>FREQ</fullName>
                <label>(Final) Requested</label>
            </value>
            <value>
                <fullName>FCHK</fullName>
                <label>(Final) Checking</label>
            </value>
            <value>
                <fullName>CMPT</fullName>
                <label>(Final) Completed</label>
            </value>
            <value>
                <fullName>FREJ</fullName>
                <label>(Final) Rejected</label>
            </value>
            <value>
                <fullName>FREG</fullName>
                <label>(Final) Saved</label>
            </value>
            <value>
                <fullName>FRJQ</fullName>
                <label>(Final) Modify Request</label>
            </value>
            <value>
                <fullName>DEL</fullName>
                <label>Deleted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Activity__c/Opportunity_Activity__c.object-meta.xml
<CustomObject>
    <label>Opportunity Activity</label>
    <nameField>
        <displayFormat>OA-{yymmdd}-{00000}</displayFormat>
        <label>Opportunity Activity No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Activity__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <label>Canceled</label>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Activity__c/fields/TransactionName__c.field-meta.xml
<CustomField>
    <fullName>TransactionName__c</fullName>
    <label>Opportunity Activity Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>XP11</fullName>
                <label>Register BO</label>
            </value>
            <value>
                <fullName>ZP21</fullName>
                <label>Review BO</label>
            </value>
            <value>
                <fullName>ZP32</fullName>
                <label>Request Resources</label>
            </value>
            <value>
                <fullName>XP31</fullName>
                <label>Receive RFP</label>
            </value>
            <value>
                <fullName>ZP31</fullName>
                <label>Request Strategy Committee</label>
            </value>
            <value>
                <fullName>XP32</fullName>
                <label>Strategy Committee Cost Plan Completion</label>
            </value>
            <value>
                <fullName>ZP62</fullName>
                <label>Request Committee Approval</label>
            </value>
            <value>
                <fullName>ZPZ3</fullName>
                <label>Agency Contract Exception</label>
            </value>
            <value>
                <fullName>ZP61</fullName>
                <label>Submit Proposal</label>
            </value>
            <value>
                <fullName>XP41</fullName>
                <label>Presentation</label>
            </value>
            <value>
                <fullName>XP42</fullName>
                <label>Preferred Bidder</label>
            </value>
            <value>
                <fullName>XP43</fullName>
                <label>Customer Approval</label>
            </value>
            <value>
                <fullName>XP44</fullName>
                <label>Negotiation</label>
            </value>
            <value>
                <fullName>XP51</fullName>
                <label>Contract P&amp;L</label>
            </value>
            <value>
                <fullName>XP52</fullName>
                <label>Legal Review</label>
            </value>
            <value>
                <fullName>ZP82</fullName>
                <label>Contract Approval</label>
            </value>
            <value>
                <fullName>XP57</fullName>
                <label>Closing</label>
            </value>
            <value>
                <fullName>ZPZ2</fullName>
                <label>Drop Opportunity</label>
            </value>
            <value>
                <fullName>XPX1</fullName>
                <label>Abort Opportunity</label>
            </value>
            <value>
                <fullName>ZAC1</fullName>
                <label>Hold Opportunity</label>
            </value>
            <value>
                <fullName>ZPZ1</fullName>
                <label>Lost Opportunity</label>
            </value>
            <value>
                <fullName>ZAC4</fullName>
                <label>Unhold Opportunity</label>
            </value>
            <value>
                <fullName>ZPG1</fullName>
                <label>Change Approval Request</label>
            </value>
            <value>
                <fullName>2.2.1.</fullName>
                <label>Credit Assessment</label>
            </value>
            <value>
                <fullName>2.2.2.</fullName>
                <label>Request AP(APS)</label>
            </value>
            <value>
                <fullName>2.3.2.</fullName>
                <label>Bidding LBS</label>
            </value>
            <value>
                <fullName>2.3.3.</fullName>
                <label>Test Shipment</label>
            </value>
            <value>
                <fullName>2.4.5.</fullName>
                <label>Final LBS</label>
            </value>
            <value>
                <fullName>2.5.1.</fullName>
                <label>Receive Contract</label>
            </value>
            <value>
                <fullName>2.5.3.</fullName>
                <label>Rate Change LBS</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Activity__c/fields/WhatId__c.field-meta.xml
<CustomField>
    <fullName>WhatId__c</fullName>
    <description>Opportunity</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Activity</relationshipLabel>
    <relationshipName>BO_Activity</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/classes/IF_CelloLbsStatusController_Test.cls
/**
 * @description       : 
 * @author            : raeganja@partner.samsung.com
 * @group             : 
 * @last modified on  : 2021-10-20
 * @last modified by  : seonju.jin@dkbmc.com
 * Modifications Log 
 * Ver   Date         Author                         Modification
 * 1.0   2020-12-31   raeganja@partner.samsung.com   Initial Version
**/
@isTest

public class IF_CelloLbsStatusController_Test {
    //IF-069
    final static String REQUEST_URL = '/services/apexrest/WebService/IF069';
    static Account acc = Utils_TestDataFactory.createAccount('TestAcc');
    static Opportunity_Activity__c opptyAct1;
    static Opportunity_Activity__c opptyAct2;

    static Opportunity  oppty;
    static{
        
        acc.MDGCheck__c = true;
        update acc;
        oppty = Utils_TestDataFactory.createOpportunity('TestOppty', acc.id);

        opptyAct1 = new Opportunity_Activity__c(
                WhatId__c = oppty.Id
                , TransactionName__c = OpportunityActivityHelper.ACT_CODE_BIDDING_LBS
                , Status__c = 'In Progress'
            );
        insert opptyAct1;
        opptyAct2 = new Opportunity_Activity__c(
                    WhatId__c = oppty.Id
                    , TransactionName__c = OpportunityActivityHelper.ACT_CODE_FINAL_LBS
                    , Status__c = 'In Progress'
                );
        insert opptyAct2;
    }
    static LBS__c lbs = Utils_TestDataFactory.createLBS('RL20082103599', oppty.id);
    

    @TestSetup
    private static void setData(){
        
    }

    @isTest 
    static void restServiceTest() {
        Test.startTest();

        RestRequest request = new RestRequest();
        RestResponse response = new RestResponse();
        request.requestURI = REQUEST_URL;        
        request.httpMethod = 'POST';

        String reqeustBody = 
        '{ ' +
        '   "DATA": [ ' +
        '       { ' +
        '           "Opportunity": [ ' +
        '               { ' +
        '                   "Id": "'+oppty.id+'", ' +
        '                   "BizDevelopmentType": "02", ' +
        '                   "Name": "중남미 포워딩사업 test2", ' +
        '                   "LogisticsBizType": "01,02", ' +
        '                   "OwnerID": "M160205072003C603452", ' +
        '                   "SalesRegionalHQ": "C", ' +
        '                   "SalesBranch": "T611", ' +
        '                   "DeliveryRegionalHQ": "C", ' +
        '                   "DeliveryBranch": "T611" ' +
        '               } ' +
        '           ], ' +
        '           "LBS": [ ' +
        '               { ' +
        '                   "OpportunityId": "'+oppty.id+'", ' +
        '                   "LBSID": "RL20082103599", ' +
        '                   "LogisticsServiceType": "01", ' +
        '                   "BiddingDeadline": "2020-10-01", ' +
        '                   "CloseDate": "2020-10-06", ' +
        '                   "cRevenueStartDate": "2020-12-10", ' +
        '                   "cRevenueEndDate": "2020-12-31", ' +
        '                   "Type": "01", ' +
        '                   "LBSStatus": "CMPT", ' +
        '                   "Amount": "0.0", ' +
        '                   "LEGAL_SYS_CNTRT_NO": "OA2018094379" ' +
        '               } ' +
        '           ] ' +
        '       } ' +
        '   ] ' +
        '}';

        request.requestBody = Blob.valueOf(reqeustBody);
        RestContext.request  = request;
        RestContext.response = response;

        try {

            IF_CelloLbsStatusController.saveData();

        } catch (Exception e) {
            system.debug(e);
        }        

        Test.stopTest();
    }

    @isTest 
    static void restServiceTest2() {
        Test.startTest();

        RestRequest request = new RestRequest();
        RestResponse response = new RestResponse();
        request.requestURI = REQUEST_URL;        
        request.httpMethod = 'POST';

        String reqeustBody = 
        '{ ' +
        '   "DATA": [ ' +
        '       { ' +
        '           "Opportunity": [ ' +
        '               { ' +
        '                   "Id": "'+oppty.id+'", ' +
        '                   "BizDevelopmentType": "02", ' +
        '                   "Name": "중남미 포워딩사업 test2", ' +
        '                   "LogisticsBizType": "01,02", ' +
        '                   "OwnerID": "M160205072003C603452", ' +
        '                   "SalesRegionalHQ": "C", ' +
        '                   "SalesBranch": "T611", ' +
        '                   "DeliveryRegionalHQ": "C", ' +
        '                   "DeliveryBranch": "T611" ' +
        '               } ' +
        '           ], ' +
        '           "LBS": [ ' +
        '               { ' +
        '                   "OpportunityId": "'+oppty.id+'", ' +
        '                   "LBSID": "RL20082103599", ' +
        '                   "LogisticsServiceType": "01", ' +
        '                   "BiddingDeadline": "2020-10-01", ' +
        '                   "CloseDate": "2020-10-06", ' +
        '                   "cRevenueStartDate": "2020-12-10", ' +
        '                   "cRevenueEndDate": "2020-12-31", ' +
        '                   "Type": "01", ' +
        '                   "LBSStatus": "PASS", ' +
        '                   "Amount": "0.0", ' +
        '                   "LEGAL_SYS_CNTRT_NO": "OA2018094379" ' +
        '               } ' +
        '           ] ' +
        '       } ' +
        '   ] ' +
        '}';

        request.requestBody = Blob.valueOf(reqeustBody);
        RestContext.request  = request;
        RestContext.response = response;

        try {

            IF_CelloLbsStatusController.saveData();

        } catch (Exception e) {
            system.debug(e);
        }        

        Test.stopTest();
    }

    @isTest 
    static void restServiceTest3() {
        Test.startTest();

        RestRequest request = new RestRequest();
        RestResponse response = new RestResponse();
        request.requestURI = REQUEST_URL;        
        request.httpMethod = 'POST';

        lbs.LBSStatus__c   = 'REG';
        String reqeustBody = 
        '{ ' +
        '   "DATA": [ ' +
        '       { ' +
        '           "Opportunity": [ ' +
        '               { ' +
        '                   "Id": "'+oppty.id+'", ' +
        '                   "BizDevelopmentType": "02", ' +
        '                   "Name": "중남미 포워딩사업 test2", ' +
        '                   "LogisticsBizType": "01,02", ' +
        '                   "OwnerID": "M160205072003C603452", ' +
        '                   "SalesRegionalHQ": "C", ' +
        '                   "SalesBranch": "T611", ' +
        '                   "DeliveryRegionalHQ": "C", ' +
        '                   "DeliveryBranch": "T611" ' +
        '               } ' +
        '           ], ' +
        '           "LBS": [ ' +
        '               { ' +
        '                   "OpportunityId": "'+oppty.id+'", ' +
        '                   "LBSID": "RL20082103599", ' +
        '                   "LogisticsServiceType": "01", ' +
        '                   "BiddingDeadline": "2020-10-01", ' +
        '                   "CloseDate": "2020-10-06", ' +
        '                   "cRevenueStartDate": "2020-12-10", ' +
        '                   "cRevenueEndDate": "2020-12-31", ' +
        '                   "Type": "01", ' +
        '                   "LBSStatus": "DEL", ' +
        '                   "Amount": "0.0", ' +
        '                   "LEGAL_SYS_CNTRT_NO": "OA2018094379" ' +
        '               } ' +
        '           ] ' +
        '       } ' +
        '   ] ' +
        '}';

        request.requestBody = Blob.valueOf(reqeustBody);
        RestContext.request  = request;
        RestContext.response = response;

        try {

            IF_CelloLbsStatusController.saveData();

        } catch (Exception e) {
            system.debug(e);
        }        

        Test.stopTest();
    }

    @isTest 
    static void restServiceTest_DATA_NULL() {
        Test.startTest();

        RestRequest request = new RestRequest();
        RestResponse response = new RestResponse();
        request.requestURI = REQUEST_URL;        
        request.httpMethod = 'POST';

        String reqeustBody = 
        '{ ' +
        '}';

        request.requestBody = Blob.valueOf(reqeustBody);
        RestContext.request  = request;
        RestContext.response = response;

        try {

            IF_CelloLbsStatusController.saveData();

        } catch (Exception e) {
            system.debug(e);
        }        

        Test.stopTest();
    }

    @isTest 
    static void restServiceTest_Exception() {
        Test.startTest();

        RestRequest request = new RestRequest();
        RestResponse response = new RestResponse();
        request.requestURI = REQUEST_URL;        
        request.httpMethod = 'POST';

        String reqeustBody = 
        '{ ' +
        '   "DATA_Exception": [ ' +
        '       { ' +
        '           "Opportunity": [ ' +
        '               { ' +
        '                   "Id": "'+oppty.id+'", ' +
        '                   "BizDevelopmentType": "02", ' +
        '                   "Name": "중남미 포워딩사업 test2", ' +
        '                   "LogisticsBizType": "01,02", ' +
        '                   "OwnerID": "M160205072003C603452", ' +
        '                   "SalesRegionalHQ": "C", ' +
        '                   "SalesBranch": "T611", ' +
        '                   "DeliveryRegionalHQ": "C", ' +
        '                   "DeliveryBranch": "T611" ' +
        '               } ' +
        '           ], ' +
        '           "LBS": [ ' +
        '               { ' +
        '                   "OpportunityId": "'+oppty.id+'", ' +
        '                   "LBSID": "RL20082103599", ' +
        '                   "LogisticsServiceType": "01", ' +
        '                   "BiddingDeadline": "2020-10-01", ' +
        '                   "CloseDate": "2020-10-06", ' +
        '                   "cRevenueStartDate": "2020-12-10", ' +
        '                   "cRevenueEndDate": "2020-12-31", ' +
        '                   "Type": "01", ' +
        '                   "LBSStatus": "CMPT", ' +
        '                   "Amount": "0.0", ' +
        '                   "LEGAL_SYS_CNTRT_NO": "OA2018094379" ' +
        '               } ' +
        '           ] ' +
        '       } ' +
        '   ] ' +
        '}';

        request.requestBody = Blob.valueOf(reqeustBody);
        RestContext.request  = request;
        RestContext.response = response;

        try {

            IF_CelloLbsStatusController.saveData();

        } catch (Exception e) {
            system.debug(e);
        }        

        Test.stopTest();
    }

    
    @isTest 
    static void restServiceTes_DEL() {
        Test.startTest();

        RestRequest request = new RestRequest();
        RestResponse response = new RestResponse();
        request.requestURI = REQUEST_URL;        
        request.httpMethod = 'POST';

        String reqeustBody = 
        '{ ' +
        '   "DATA": [ ' +
        '       { ' +
        '           "Opportunity": [ ' +
        '               { ' +
        '                   "Id": "'+oppty.id+'", ' +
        '                   "BizDevelopmentType": "02", ' +
        '                   "Name": "중남미 포워딩사업 test2", ' +
        '                   "LogisticsBizType": "01,02", ' +
        '                   "OwnerID": "M160205072003C603452", ' +
        '                   "SalesRegionalHQ": "C", ' +
        '                   "SalesBranch": "T611", ' +
        '                   "DeliveryRegionalHQ": "C", ' +
        '                   "DeliveryBranch": "T611" ' +
        '               } ' +
        '           ], ' +
        '           "LBS": [ ' +
        '               { ' +
        '                   "OpportunityId": "'+oppty.id+'", ' +
        '                   "LBSID": "RL20082103599", ' +
        '                   "LogisticsServiceType": "01", ' +
        '                   "BiddingDeadline": "2020-10-01", ' +
        '                   "CloseDate": "2020-10-06", ' +
        '                   "cRevenueStartDate": "2020-12-10", ' +
        '                   "cRevenueEndDate": "2020-12-31", ' +
        '                   "Type": "01", ' +
        '                   "LBSStatus": "DEL", ' +
        '                   "Amount": "0.0", ' +
        '                   "LEGAL_SYS_CNTRT_NO": "OA2018094379" ' +
        '               } ' +
        '           ] ' +
        '       } ' +
        '   ] ' +
        '}';

        request.requestBody = Blob.valueOf(reqeustBody);
        RestContext.request  = request;
        RestContext.response = response;

        try {

            IF_CelloLbsStatusController.saveData();
            system.debug('opptyAct1:' + [SELECT Id, Name, Status__c, TransactionName__c FROM Opportunity_Activity__c WHERE WhatId__c =: oppty.Id]);

        } catch (Exception e) {
            system.debug(e);
        }        

        Test.stopTest();
    }
}