force-app/main/default/objects/AccountSalesArea__c/AccountSalesArea__c.object-meta.xml
<CustomObject>
    <label>Account Sales Area</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Sales Area</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountSalesArea__c/fields/ANTLF__c.field-meta.xml
<CustomField>
    <fullName>ANTLF__c</fullName>
    <label>Max.Part.Deliveries</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AccountSalesArea__c/fields/AUFSD__c.field-meta.xml
<CustomField>
    <fullName>AUFSD__c</fullName>
    <description>Central order block</description>
    <label>Central order block</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountSalesArea__c/fields/AWAHR__c.field-meta.xml
<CustomField>
    <fullName>AWAHR__c</fullName>
    <description>오더확률</description>
    <label>Order probability</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AccountSalesArea__c/fields/BZIRK__c.field-meta.xml
<CustomField>
    <fullName>BZIRK__c</fullName>
    <label>Sales district</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountSalesArea__c/fields/FAKSD__c.field-meta.xml
<CustomField>
    <fullName>FAKSD__c</fullName>
    <description>Billing block for sales area</description>
    <label>Billing block for sales area</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountSalesArea__c/fields/INCO1__c.field-meta.xml
<CustomField>
    <fullName>INCO1__c</fullName>
    <label>Incoterms</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountSalesArea__c/fields/INCO2__c.field-meta.xml
<CustomField>
    <fullName>INCO2__c</fullName>
    <description>인도 조건 2</description>
    <label>Incoterms (Part 2)</label>
    <length>28</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountSalesArea__c/fields/KALKS__c.field-meta.xml
<CustomField>
    <fullName>KALKS__c</fullName>
    <description>고객가격절차</description>
    <label>Cust.pric.procedure</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountSalesArea__c/fields/KDGRP__c.field-meta.xml
<CustomField>
    <fullName>KDGRP__c</fullName>
    <description>Customer group</description>
    <label>Customer group</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountSalesArea__c/fields/KONDA__c.field-meta.xml
<CustomField>
    <fullName>KONDA__c</fullName>
    <description>가격 그룹</description>
    <label>Price group (customer)</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountSalesArea__c/fields/KTGRD__c.field-meta.xml
<CustomField>
    <fullName>KTGRD__c</fullName>
    <description>계정지정그룹</description>
    <label>AcctAssgGr</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountSalesArea__c/fields/KURST__c.field-meta.xml
<CustomField>
    <fullName>KURST__c</fullName>
    <description>환율 유형</description>
    <label>Exchange Rate Type</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountSalesArea__c/fields/KZAZU__c.field-meta.xml
<CustomField>
    <fullName>KZAZU__c</fullName>
    <label>Order Combination</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountSalesArea__c/fields/LIFSD__c.field-meta.xml
<CustomField>
    <fullName>LIFSD__c</fullName>
    <description>Delivery block for sales area</description>
    <label>Delivery block for sales area</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountSalesArea__c/fields/LOEVM__c.field-meta.xml
<CustomField>
    <fullName>LOEVM__c</fullName>
    <description>삭제지시자</description>
    <label>Del. indicator for sales area</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountSalesArea__c/fields/LPRIO__c.field-meta.xml
<CustomField>
    <fullName>LPRIO__c</fullName>
    <description>납품 우선순위</description>
    <label>Delivery Priority</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AccountSalesArea__c/fields/PLTYP__c.field-meta.xml
<CustomField>
    <fullName>PLTYP__c</fullName>
    <description>가격 리스트</description>
    <label>Price List</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountSalesArea__c/fields/SPART__c.field-meta.xml
<CustomField>
    <fullName>SPART__c</fullName>
    <description>제품군</description>
    <label>Division</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountSalesArea__c/fields/VKBUR__c.field-meta.xml
<CustomField>
    <fullName>VKBUR__c</fullName>
    <label>Sales Office</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountSalesArea__c/fields/VKORG__c.field-meta.xml
<CustomField>
    <fullName>VKORG__c</fullName>
    <label>Sales Organization</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountSalesArea__c/fields/VSBED__c.field-meta.xml
<CustomField>
    <fullName>VSBED__c</fullName>
    <label>Shipping Conditions</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountSalesArea__c/fields/VTWEG__c.field-meta.xml
<CustomField>
    <fullName>VTWEG__c</fullName>
    <description>유통 경로</description>
    <label>Distribution Channel</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountSalesArea__c/fields/WAERS__c.field-meta.xml
<CustomField>
    <fullName>WAERS__c</fullName>
    <description>통화</description>
    <label>Currency</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountSalesArea__c/fields/ZTERM__c.field-meta.xml
<CustomField>
    <fullName>ZTERM__c</fullName>
    <description>지급 조건</description>
    <label>Terms of Payment</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/MDGAccount__c.object-meta.xml
<CustomObject>
    <label>MDG Account</label>
    <nameField>
        <label>Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MDG Account</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/MDGAccount__c/fields/ANTLF__c.field-meta.xml
<CustomField>
    <fullName>ANTLF__c</fullName>
    <label>ANTLF</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/AUFSD__c.field-meta.xml
<CustomField>
    <fullName>AUFSD__c</fullName>
    <label>AUFSD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/AWAHR__c.field-meta.xml
<CustomField>
    <fullName>AWAHR__c</fullName>
    <label>AWAHR</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/BP_HEADER__c.field-meta.xml
<CustomField>
    <fullName>BP_HEADER__c</fullName>
    <label>BP_HEADER</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/BZIRK__c.field-meta.xml
<CustomField>
    <fullName>BZIRK__c</fullName>
    <label>BZIRK</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/CITY1__c.field-meta.xml
<CustomField>
    <fullName>CITY1__c</fullName>
    <label>CITY1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/CITY2__c.field-meta.xml
<CustomField>
    <fullName>CITY2__c</fullName>
    <label>CITY2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/COUNTRY__c.field-meta.xml
<CustomField>
    <fullName>COUNTRY__c</fullName>
    <label>COUNTRY</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/FAKSD__c.field-meta.xml
<CustomField>
    <fullName>FAKSD__c</fullName>
    <label>FAKSD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/FAX_NUMBER__c.field-meta.xml
<CustomField>
    <fullName>FAX_NUMBER__c</fullName>
    <label>FAX_NUMBER</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/INCO1__c.field-meta.xml
<CustomField>
    <fullName>INCO1__c</fullName>
    <label>INCO1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/INCO2__c.field-meta.xml
<CustomField>
    <fullName>INCO2__c</fullName>
    <label>INCO2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/KALKS__c.field-meta.xml
<CustomField>
    <fullName>KALKS__c</fullName>
    <label>KALKS</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/KDGRP__c.field-meta.xml
<CustomField>
    <fullName>KDGRP__c</fullName>
    <label>KDGRP</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/KONDA__c.field-meta.xml
<CustomField>
    <fullName>KONDA__c</fullName>
    <label>KONDA</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/KTGRD__c.field-meta.xml
<CustomField>
    <fullName>KTGRD__c</fullName>
    <label>KTGRD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/KUNNR__c.field-meta.xml
<CustomField>
    <fullName>KUNNR__c</fullName>
    <label>KUNNR</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/KURST__c.field-meta.xml
<CustomField>
    <fullName>KURST__c</fullName>
    <label>KURST</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/KZAZU__c.field-meta.xml
<CustomField>
    <fullName>KZAZU__c</fullName>
    <label>KZAZU</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/LAND1__c.field-meta.xml
<CustomField>
    <fullName>LAND1__c</fullName>
    <label>LAND1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/LIFSD__c.field-meta.xml
<CustomField>
    <fullName>LIFSD__c</fullName>
    <label>LIFSD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/LOEVM__c.field-meta.xml
<CustomField>
    <fullName>LOEVM__c</fullName>
    <label>LOEVM</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/LPRIO__c.field-meta.xml
<CustomField>
    <fullName>LPRIO__c</fullName>
    <label>LPRIO</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/NAME1__c.field-meta.xml
<CustomField>
    <fullName>NAME1__c</fullName>
    <label>NAME1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/NAME2__c.field-meta.xml
<CustomField>
    <fullName>NAME2__c</fullName>
    <label>NAME2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/PLTYP__c.field-meta.xml
<CustomField>
    <fullName>PLTYP__c</fullName>
    <label>PLTYP</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/POST_CODE1__c.field-meta.xml
<CustomField>
    <fullName>POST_CODE1__c</fullName>
    <label>POST_CODE1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/REGION__c.field-meta.xml
<CustomField>
    <fullName>REGION__c</fullName>
    <label>REGION</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/SPART__c.field-meta.xml
<CustomField>
    <fullName>SPART__c</fullName>
    <label>SPART</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/STCD1__c.field-meta.xml
<CustomField>
    <fullName>STCD1__c</fullName>
    <label>STCD1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/STCD2__c.field-meta.xml
<CustomField>
    <fullName>STCD2__c</fullName>
    <label>STCD2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/STCD3__c.field-meta.xml
<CustomField>
    <fullName>STCD3__c</fullName>
    <label>STCD3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/STCD4__c.field-meta.xml
<CustomField>
    <fullName>STCD4__c</fullName>
    <label>STCD4</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/TEL_NUMBER__c.field-meta.xml
<CustomField>
    <fullName>TEL_NUMBER__c</fullName>
    <label>TEL_NUMBER</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/URI_ADDR__c.field-meta.xml
<CustomField>
    <fullName>URI_ADDR__c</fullName>
    <label>URI_ADDR</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/VKBUR__c.field-meta.xml
<CustomField>
    <fullName>VKBUR__c</fullName>
    <label>VKBUR</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/VKORG__c.field-meta.xml
<CustomField>
    <fullName>VKORG__c</fullName>
    <label>VKORG</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/VSBED__c.field-meta.xml
<CustomField>
    <fullName>VSBED__c</fullName>
    <label>VSBED</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/VTWEG__c.field-meta.xml
<CustomField>
    <fullName>VTWEG__c</fullName>
    <label>VTWEG</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/WAERS__c.field-meta.xml
<CustomField>
    <fullName>WAERS__c</fullName>
    <label>WAERS</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MDGAccount__c/fields/ZTERM__c.field-meta.xml
<CustomField>
    <fullName>ZTERM__c</fullName>
    <label>ZTERM</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Batch_AccountSalesAreaController.cls
/**
 * @description       : MDGAccount__c(Dummy Object) 에서 AccountSalesArea__c 정보를 Upsert
 * @author            : soohong0.kim@partner.samsung.com
 * @group             : 
 * @last modified on  : 02-25-2021
 * @last modified by  : soohong0.kim@partner.samsung.com
 * Modifications Log 
 * Ver   Date         Author                             Modification
 * 1.0   11-18-2020   soohong0.kim@partner.samsung.com   Initial Version
**/

//Test Class -> Batch_AccountMdgController_Test
global class Batch_AccountSalesAreaController implements Database.StateFul, Database.Batchable<sObject>, Database.AllowsCallouts, Schedulable {
    private final String APEX_CLASS      = 'Batch_AccountSalesAreaController';
    private IF_Log.BatchLog batchLog     = null;
    private List<IF_Log.BatchLog> batchLogList = new List<IF_Log.BatchLog>();
    private List<AccountSalesArea__c> uSalesList = new List<AccountSalesArea__c>();
    private List<MDGAccount__c> uMdgList = new List<MDGAccount__c>();
    private IF_Log ifLog = new IF_Log();
    global Database.QueryLocator start(Database.BatchableContext bc) {
        String query = 'SELECT Id, OwnerId, IsDeleted, Name, CurrencyIsoCode, CreatedDate, CreatedById, LastModifiedDate, LastModifiedById, ';
        query+='SystemModstamp, LastActivityDate, ANTLF__c, AUFSD__c, AWAHR__c, BP_HEADER__c, BZIRK__c, CITY1__c, CITY2__c, COUNTRY__c, FAKSD__c, ';
        query+='FAX_NUMBER__c, INCO1__c, INCO2__c, KALKS__c, KDGRP__c, KONDA__c, KTGRD__c, KUNNR__c, KURST__c, KZAZU__c, LAND1__c, LIFSD__c, LOEVM__c, ';
        query+='LPRIO__c, NAME1__c, NAME2__c, PLTYP__c, POST_CODE1__c, REGION__c, SPART__c, STCD1__c, STCD2__c, STCD3__c, STCD4__c, STREET__c, TEL_NUMBER__c, ';
        query+='URI_ADDR__c, VKBUR__c, VKORG__c, VSBED__c, VTWEG__c, WAERS__c, ZTERM__c, ZZJ_1KFRE__c, ZZKDGRP_C__c, ZZNSTKUNL1_T__c, ZZNSTKUNL1__c, ';
        query+='ZZNSTKUNL2_T__c, ZZNSTKUNL2__c, ZZNSTKUNL3_T__c, ZZNSTKUNL3__c, ZZSHIPPER__c,';
        query+=' mLOEVM__c, ExternalId__c, Type__c, isBatch__c ';
        query+=' FROM MDGAccount__c ';
        query+=' WHERE Type__c = \'S\' ';
        
        
        return Database.getQueryLocator(query);
    }
    global void execute(Database.BatchableContext bc, List<MDGAccount__c> objList) {

        system.debug('raw data size : '+objList.size());
        Map<String,String> keyMap = new Map<String,String>();
        List<AccountSalesArea__c> salesList = new List<AccountSalesArea__c>();
        String guId     = IF_Util.generateGuid();
        SavePoint sp = DataBase.setSavePoint();
        try{

            Set<String> accNo = new Set<String>();
            for(MDGAccount__c obj : objList){
                accNo.add(obj.BP_HEADER__c);
            }

            List<Account> accList = [select id, AccountNumber from account where AccountNumber in: accNo];
            for(Account obj : accList){
                keyMap.put(obj.AccountNumber,obj.id);
            }

            List<MDGAccount__c> mdgAcctList = new List<MDGAccount__c>();
            for(MDGAccount__c obj : objList){
                AccountSalesArea__c sales = new AccountSalesArea__c();
                sales.Name = obj.VKORG__c+obj.SPART__c+obj.VTWEG__c;
                sales.VKORG__c = obj.VKORG__c;
                sales.VTWEG__c = obj.VTWEG__c;
                sales.SPART__c = obj.SPART__c;
                sales.AWAHR__c = Decimal.valueOf(obj.AWAHR__c);
                sales.BZIRK__c = obj.BZIRK__c;
                sales.AUFSD__c = obj.AUFSD__c;
                sales.FAKSD__c = obj.FAKSD__c;
                sales.INCO1__c = obj.INCO1__c;
                sales.INCO2__c = obj.INCO2__c;
                sales.LIFSD__c = obj.LIFSD__c;
                sales.LOEVM__c = obj.LOEVM__c;
                sales.WAERS__c = obj.WAERS__c;
                sales.ZTERM__c = obj.ZTERM__c;
                sales.KALKS__c = obj.KALKS__c;
                sales.KDGRP__c = obj.KDGRP__c;
                sales.KTGRD__c = obj.KTGRD__c;
                sales.KURST__c = obj.KURST__c;
                sales.VKBUR__c = obj.VKBUR__c;
                sales.ANTLF__c = Decimal.valueOf(obj.ANTLF__c);
                sales.VSBED__c = obj.VSBED__c;
                sales.KZAZU__c = obj.KZAZU__c;
                sales.LPRIO__c = Decimal.valueOf(obj.LPRIO__c);
                sales.PLTYP__c = obj.PLTYP__c;
                sales.KONDA__c = obj.KONDA__c;
                sales.ExternalId__c = obj.ExternalId__c;
                sales.AccountId__c = keyMap.get(obj.BP_HEADER__c);
                
                //MDGAccount 오브젝트 레코드에 Batch 완료 Flag Update 처리
                obj.isBatch__c = 'Y';

                uSalesList.add(sales);
                uMdgList.add(obj);
            }
            
            
            
            batchLog = new IF_Log.BatchLog('', guId, APEX_CLASS, 'Batch Excute', salesList.size());
        }catch(Exception e){
            batchLog = new IF_Log.BatchLog('', guId, APEX_CLASS, 'Batch Excute', 0, 0, e);    
            DataBase.rollback(sp);
        }
        batchLogList.add(batchLog);
    }

    global void finish(Database.BatchableContext bc) {
        //Log생성
        for(IF_Log.BatchLog obj :batchLogList){
            obj.ApexMethod = 'execute';
            ifLog.createLog( obj );
        }
        upsert uSalesList ExternalId__c;
        update uMdgList;
    }

    global void execute(SchedulableContext sc) {
        database.executebatch(new Batch_AccountSalesAreaController(), 100);
    }

}