force-app/main/default/objects/BO_Matrix_cnt__c/BO_Matrix_cnt__c.object-meta.xml
<CustomObject>
    <label>BO Matrix Count</label>
    <nameField>
        <displayFormat>BO Matrix-{000}</displayFormat>
        <label>Logistic Oppty Count Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BO Matrix Counts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BO_Matrix_cnt__c/fields/Count__c.field-meta.xml
<CustomField>
    <fullName>Count__c</fullName>
    <description>레코드 개수</description>
    <label>Record Count</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BO_Matrix_cnt__c/fields/From_RHQ__c.field-meta.xml
<CustomField>
    <fullName>From_RHQ__c</fullName>
    <description>출발 권역
From RHQ</description>
    <label>From RHQ</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CHINA</fullName>
            </value>
            <value>
                <fullName>KOREA</fullName>
            </value>
            <value>
                <fullName>EUROPE/CIS</fullName>
            </value>
            <value>
                <fullName>LATIN AMERICA</fullName>
            </value>
            <value>
                <fullName>MEIA</fullName>
            </value>
            <value>
                <fullName>NORTH AMERICA</fullName>
            </value>
            <value>
                <fullName>PACIFIC</fullName>
            </value>
            <value>
                <fullName>CHINA_TO_SUM</fullName>
            </value>
            <value>
                <fullName>KOREA_TO_SUM</fullName>
            </value>
            <value>
                <fullName>EUROPE_TO_SUM</fullName>
            </value>
            <value>
                <fullName>LATIN_AMERICA_TO_SUM</fullName>
            </value>
            <value>
                <fullName>MEIA_TO_SUM</fullName>
            </value>
            <value>
                <fullName>NORTH_AMERICA_TO_SUM</fullName>
            </value>
            <value>
                <fullName>PACIFIC_TO_SUM</fullName>
            </value>
            <value>
                <fullName>TOTAL_FROM_TO_SUM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BO_Matrix_cnt__c/fields/To_RHQ__c.field-meta.xml
<CustomField>
    <fullName>To_RHQ__c</fullName>
    <description>도착 권역
To RHQ</description>
    <label>To RHQ</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CHINA</fullName>
            </value>
            <value>
                <fullName>KOREA</fullName>
            </value>
            <value>
                <fullName>EUROPE/CIS</fullName>
            </value>
            <value>
                <fullName>LATIN AMERICA</fullName>
            </value>
            <value>
                <fullName>MEIA</fullName>
            </value>
            <value>
                <fullName>NORTH AMERICA</fullName>
            </value>
            <value>
                <fullName>PACIFIC</fullName>
            </value>
            <value>
                <fullName>CHINA_FROM_SUM</fullName>
            </value>
            <value>
                <fullName>KOREA_FROM_SUM</fullName>
            </value>
            <value>
                <fullName>EUROPE_FROM_SUM</fullName>
            </value>
            <value>
                <fullName>LATIN_AMERICA_FROM_SUM</fullName>
            </value>
            <value>
                <fullName>MEIA_FROM_SUM</fullName>
            </value>
            <value>
                <fullName>NORTH_AMERICA_FROM_SUM</fullName>
            </value>
            <value>
                <fullName>PACIFIC_FROM_SUM</fullName>
            </value>
            <value>
                <fullName>TOTAL_FROM_TO_SUM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/logisticOpportunityCountSchedulable_Test.cls
/**
 * @description       : Test class of logisticOpportunityCountSchedulable 
 * @author            : d.ashish@samsung.com
 * @group             : 
 * @last modified on  : 2023-06-07
 * @last modified by  : d.ashish@samsung.com
 * Modifications Log 
 * Ver   Date         Author                   Modification
 * 1.0   2023-06-07   d.ashish@samsung.com   Initial Version
**/
@isTest
public class logisticOpportunityCountSchedulable_Test {
    @testsetup
    static void createBoMatrix(){
        //SJOSHI start: Updated below 1 line, changed EUROPE to EUROPE/CIS as per requirement
        List<String> clist = new List<String>{'CHINA','EUROPE/CIS','KOREA','LATIN AMERICA','MEIA','NORTH AMERICA','PACIFIC'};
        //SJOSHI end
            List<BO_Matrix_cnt__c> mylist = new list<BO_Matrix_cnt__c>();
        for(integer i=0; i<7;i++){
            for(integer j=0;j<7;j++){
                mylist.add(new BO_Matrix_cnt__c(From_RHQ__c=clist[i], To_RHQ__c =clist[j], Count__c=0)); 
            }
        }
        insert mylist;
    }
    
    @isTest
    public static void testlogisticOpportunityCountSchedulable(){
        String schedmon5am = '0 00 05 ? * 2';  //Every Monday, 5AM
        logisticOpportunityCountSchedulable SC = new logisticOpportunityCountSchedulable(); 
        System.schedule('Schedule logisticOpportunityCountSchedulable - Monday 5AM', schedmon5am, SC);
    }
}